### ISSUE TITLE
Add monitoring indicators for the number of watches 

### ISSUE THREAD

**Issue by lambdaxs** [hashicorp/consul#10061]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Add monitoring indicators for the number of watches in metrics api. Then We can understand clearly 
 the number of watches .thk~

#### Use Case(s)

e.g.
consul_watch_count 22

**Comment by jsosulska** [comment]
Hi @lambdaxs ,

Thanks for posting, and welcome to the Consul repo 😄  You can monitor `consul.rpc.queries_blocking` to get a number pretty close to your total watches. This number may actually be slightly higher because `watches` are just a specific type of `blocking_query`.

Trying to separate out watches-only is currently not supported. To differentiate and report on only watches requires substantially more plumbing to make work. I would love to hear any ideas you may have around how this could be implemented 🤔 

I hope that the metric I pointed to helps out. Feel free to add any comments or context if you have any ideas for an easy solution :) In the meantime, I will be closing this out.

**Comment by lambdaxs** [comment]
thanks very much~

**Comment by lambdaxs** [comment]
when I watch a key, the `consul_rpc_queries_blocking` value will +1.
but when I use `Ctrl+c` to cancel the watch, the `consul_rpc_queries_blocking` not -1.
So, Is there a delay in the statistics of this indicator ？

![image](https://user-images.githubusercontent.com/12015791/116227738-0b7b8500-a787-11eb-878b-46cef29a9b7f.png)
