### ISSUE TITLE
"consul acl token create" does not respect environment variables

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul#10092]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I have a cluster set up using TLS on port 8501 which is working fine.  However I find that 

$ consul acl token create

 is not picking up any environment variables

The command works fine when the options are specified as part of the command

#### Reproduction Steps

$ export CONSUL_HTTP_ADDR=https://127.0.0.1:8501
$ export CONSUL_HTTP_TOKEN=sdfsdfsfs
$ consul acl token create -node-identity=y:dc1

yields

Put "http://127.0.0.1:8500/v1/acl/token": dial tcp 127.0.0.1:8500: connect: connection refused

### Consul info for both Client and Server

version 1.9.4

### Operating system and Environment details

ubuntu 18/04 /  aws / x64
nothing else installed/running on it

**Comment by ChipV223** [comment]
Hi @mr-miles !

Looking at the `Put "http://127.0.0.1:8500/v1/acl/token": dial tcp 127.0.0.1:8500: connect: connection refused`, I believe you would need to additional environment variables in order to run the Consul CLI commands.

Can you try setting the following and then re-running `consul acl token create -node-identity=y:dc1` again:

* [CONSUL_HTTP_SSL](https://www.consul.io/commands#consul_http_ssl)

* [CONSUL_CACERT](https://www.consul.io/commands#consul_cacert) or [CONSUL_CAPATH](https://www.consul.io/commands#consul_capath)

* [CONSUL_CLIENT_CERT](https://www.consul.io/commands#consul_client_cert)

* [CONSUL_CLIENT_KEY](https://www.consul.io/commands#consul_client_key)

**Comment by mr-miles** [comment]
Sorry, this turned out to be down to my bash knowledge.  With sudo, environment variables are not retained by default even if they are set to be created in the default user profile.
