### ISSUE TITLE
Failed to write NodeID to disk on Minikube on MacOS

### ISSUE THREAD

**Issue by braghettos** [hashicorp/consul#10096]
#### Overview of the Issue

I'm trying to setup Consul on my local minikube but the installation fails because the pods 'consul-server-0' goes in CrashLoopBackOff with the following error:

`==> failed to setup node ID: failed to write NodeID to disk: open /consul/data/node-id: permission denied`

#### Reproduction Steps

Start a local Kubernetes cluster with minikube:

`minikube start --nodes 3 -p multinode-demo --driver=virtualbox --disk-size=50g --network-plugin=cni --cni=flannel --kubernetes-version=v1.18.18`

Install consul via official helm chart:

`helm install consul hashicorp/consul`

### Consul info for both Client and Server

Unable to install Consul, helm chart version is 0.31.1

### Operating system and Environment details

MacOS Big Sure, Docker engine 20.10.5, Helm 3

### Log Fragments

```
kubectl logs consul-server-0
==> failed to setup node ID: failed to write NodeID to disk: open /consul/data/node-id: permission denied
```

**Comment by jsosulska** [comment]
Hi @braghettos 

Thanks for submitting this request. I was able to replicate the issue with my local minikube based on their reproduction steps. I attempted to remove some of the variables and launching this on Minikube 3 node cluster on docker. For both docker and VBOX, I got the same issue. It seems like the Consul user can't write to the data volume, even though the PVC's are mounted to the correct pods.

For questions specifically around the helm chart functionality, those are posted to the [consul-helm](https://github.com/hashicorp/consul-helm/issues/) for most instances. I do see that a [recent commit](https://github.com/hashicorp/consul-helm/pull/901) went through and affected the `disable-node-id` settings.

Can you try installing the helm chart from master and confirming this functionality? If this is fixed in master, we'll close. If the issue still persists, I'll transfer over the issue :)

Please let me know your results, @braghettos

**Comment by braghettos** [comment]
Hi @jsosulska, I tried also the disable-node-id setting, but that's not working. I'll try using directly the chart in the main repo and I'll let you know.

**Comment by david-yu** [comment]
Hi @braghettos! It seems that minikube prevents a non-root container to write to a volume that is mounted using host paths, it sounds like there may be a way to overcome this with the `minikube mount` command as described in a similar StackOverflow [thread](https://stackoverflow.com/questions/60479594/minikube-volume-write-permissions/60498848#60498848). However if you are comfortable with running as root in your dev environment that may also address the problem:

```
securityContext:   
  runAsNonRoot: false    
  runAsGroup: 0    
  runAsUser: 0    
  fsGroup: 0
```

**Comment by david-yu** [comment]
Closing as this is now also reflected in https://learn.hashicorp.com/tutorials/consul/kubernetes-minikube?in=consul/kubernetes-deploy, using root however is not enabled in the Helm chart by default but it makes sense in this case for development purposes.

**Comment by holstvoogd** [comment]
That link is dead now, issue still persists.
