### ISSUE TITLE
Should consul allow a service name with a '.' character?

### ISSUE THREAD

**Issue by stevendborrelli** [hashicorp/consul#1010]
Consul version: 0.5.2

Recently we had a `invalid health service dependency format` failure in consul-template. After tracking down the issue, we found that a service had been registered with a '.' in the service name.

**Comment by ryanuber** [comment]
@stevendborrelli it would be nice to not allow it. Consul will actually log a warning message if a service is registered with a `.` in the name, since it makes other parts of Consul non-functional (like querying DNS for the service due to the convention we use for tags). Unfortunately though, there are quite a few users who rely on dots being allowed in service names, so for now we can't expressly disallow that for now.
