### ISSUE TITLE
Token encryption

### ISSUE THREAD

**Issue by CherleX** [hashicorp/consul#10150]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description
If you want to enable ACL authentication, you need to fill in the configuration file with tokens in plain text. For example：
```bash
"primary_datacenter": "global",
  "acl_datacenter": "global",
  "acl_default_policy": "deny",
  "acl_down_policy": "extend-cache",
  "acl_ttl": "360m",
  "acl_token": "test_token"
```
The plaintext token placed in the configuration file is at risk of being leaked. Should we consider supporting token encryption?

#### Use Case(s)

Use the ciphertext token in the configuration file.

**Comment by dnephin** [comment]
Thank you for raising this issue! The [Consul security model](https://www.consul.io/docs/security/security-models/core#threat-model) does state that "Access (read or write) to the Consul configuration directory" is considered privileged access and not part of the threat model. So it is expected that someone who can read the config is able to view these tokens.

However we do understand the concern of keeping secrets in plain text on disk. Encrypting the tokens seems like it doesn't solve the problem, because you would still need to specify the encryption key, which itself would end up in the configuration file.

There is one workaround that can be used today, to avoid writing tokens to the configuration file.  With [`acl.enable_token_persistence`](https://www.consul.io/docs/agent/options#acl_enable_token_persistence) enabled, you can write the tokens to a running agent with either the [`consul acl set-agent-token`](https://www.consul.io/commands/acl/set-agent-token) CLI command, or the [`/v1/agent/token`](https://www.consul.io/api-docs/agent#update-acl-tokens) API endpoint. Those tokens will be persisted in the data directory, so that when the agent restarts they will be available again. However this does still write the tokens to disk unencrypted.

One option which may resolve this concern would be to support specifying the token configuration from environment variables. So instead of putting the token value into the configuration file, the environment variable `CONSUL_CONFIG_ACL_TOKENS_DEFAULT` could be set to the value, and Consul could read that. 


I created #10249 to track allowing these values to be specified via environment variables. #8306 seems like it is a related and suggests another approach. If one of these options seems like it could work for you, I think we should close this issue.

**Comment by jkirschner-hashicorp** [comment]
Hi @CherleX,

Thanks for starting this conversation with us.

@dnephin outlined two potential approaches that might work for you (#10249 and #8306). Because we haven't heard from you in a few months, I'm closing this issue. However, of one of the referenced issues doesn't meet your needs, please comment here and reopen.
