### ISSUE TITLE
DNS lookup fail when client agent down

### ISSUE THREAD

**Issue by feiyang21687** [hashicorp/consul#1019]
when the agent which handle `/v1/agent/service/register` is down, dns can't work 

We run 3 consul server agent and 2 client agent, like below:

```
server1: 10.0.0.1
server1: 10.0.0.2
server1: 10.0.0.3
client1: 10.0.0.4
client2: 10.0.0.4
```

Then use `gliderlabs/registrator` to register local container to consul client, for example, register master.redis.service.consul to client1 agent 10.0.0.4.

config three server agent as `nameserver` in /etc/resolv.conf, like below:

```
nameserver 10.0.0.1
nameserver 10.0.0.2
nameserver 10.0.0.3
```

Then shutdown client1 10.0.0.4, `ping master.redis.service.consul` will return unknown host error.

**Comment by ryanuber** [comment]
Hi @feiyang21687, Consul uses health checking information to enhance the DNS interface. Basically what this means is that if a node is unhealthy (in your case you shut the node down, so the basic internal ping tests are failing), it will not be returned in DNS responses. Since you have no other nodes which can provide the "master.redis.service.consul" service, the DNS response comes back empty. If you have two or more instances of the service, then the DNS interface provides an easy way of always returning a healthy, working node to connect to. You can read more about the DNS interface [here](https://consul.io/docs/agent/dns.html).

Hope that helps!

**Comment by feiyang21687** [comment]
Hi @ryanuber , thank you for your reply.

But I mean how could I create a `HA` consul cluster. The `HA` means services dns lookup will not be affected by whichever consul agent down.

For example:

I registry a service through any one of the consul agent, like below:

`curl -X POST -d service.json 10.0.0.4/v1/agent/service/register`

Expect:

I could nslookup through other consul agent when `10.0.0.4` is down.

Actual:

I couldn't nslookup through any of other consul agent.

BTW, I checked the API doc, and I found `/v1/catalog/register` could work like what we expect. But in the doc, it recommends to use `/v1/agent/service/register`. But `/v1/agent/service/register` says Registers a new **local** service. local??? I'm confused, why it is local? How to register a distributed service?

> Note: it is usually preferrable instead to use the agent endpoints for registration as they are simpler and perform anti-entropy.

The service configuration which register by `/v1/agent/service/register` is sync by serf protocol. So why not other node handle over the services dns when the agent which handle `/v1/agent/service/register` is down?

**Comment by ryanuber** [comment]
@feiyang21687 sorry, let me explain a bit more.

High availability in Consul refers to our ability to service a request, not only resolving DNS names. The health checking system is integrated with the service discovery mechanisms, and DNS service discovery will only return nodes with no failing health checks. This is by design, and allows clients to easily tolerate partial service interruptions without tight coupling by simply routing requests using Consul's DNS server.

WRT "local" services, consul has two different types of registrations:

* The "local" registration, which means a service on node A is registered to the consul agent running on the same node.
* The global service catalog, which is maintained by the server nodes using the replicated log, and accessible via the `/v1/catalog` and `/v1/health` endpoints. The local registrations from each agent sync in to the catalog periodically. The catalog then provides a consistent view of the available services and their health status on all nodes to the rest of the cluster.

It is possible to register a service directly into the global service catalog using the `/v1/catalog/register` API's, however that class of registration is limited in that they are not updated by an agent's health status updates.

Hope this helps!

**Comment by feiyang21687** [comment]
@ryanuber Thank you very much.

So what's the best practice to deploy that consul cluster? Run client agent on every **service** machine, is that right?

But I have some worries:

A: DNS lookup performance. I check the code, dns lookup request will be hand over to the client which hold the service. If there are many client agent, like thousands, will dns lookup performance be affected?

B: Server agent workload. If there are many client agent, will server agent sync heavily?

**Comment by ryanuber** [comment]
@feiyang21687 the most typical deployment case has an agent installed on each node, that is correct. Most of these agents can be run in client mode, which has a very light workload compared to the server nodes.

When you make a DNS query for a service in Consul, internally the query is forwarded to a server node to handle the request. The servers maintain the global catalog, so it would not be necessary to reach out to each client to get the result. DNS performance should not be affected by the number of connected clients.

As more clients are added, the workload on the servers does increase, yes. However, to mitigate this, each client uses a random stagger interval to avoid a thundering herd of updates. Also, once your cluster size grows beyond certain bounds, the anti-entropy sync delay is increased so that the server nodes do not become overwhelmed. You can see the sync interval and how it is affected by cluster size on the [anti-entropy documentation](https://consul.io/docs/internals/anti-entropy.html) page, specifically the "Periodic Synchronization" paragraph.

**Comment by feiyang21687** [comment]
@ryanbreen Thank you very much. I get it.
