### ISSUE TITLE
springcloud + consul + dubbo2.7.4.1  No provider available

### ISSUE THREAD

**Issue by LiPeng960419** [hashicorp/consul#10242]
Use the consul registration center to find the service to automatically go offline after a period of time
springboot 2.2.12.RELEASE
spring-cloud-starter-dubbo 2.2.0.RELEASE
springcloud Hoxton.RELEASE

org.apache.dubbo.registry.consul.ConsulRegistry|| [DUBBO] fail to check pass for url
No provider available in [invoker :interface 
most of service downed

**Comment by jsosulska** [comment]
Hello @LiPeng960419 

Welcome to the Consul repository. At this point in time the Spring Cloud integration is a community driven integration. If you are looking for additional support, please open an issue with the [spring-cloud-consul](https://github.com/spring-cloud/spring-cloud-consul) repository.

There is also an open issue for [Consul to support Dubbo](https://github.com/hashicorp/consul/issues/9583). Please add a +1 on the issue, as well as describe your usecase and workload in a comment. If this issue is prioritized to be worked on, a larger Dubbo compliant solution would be implemented.

Happy Coding!
