### ISSUE TITLE
Leader Status Check, HTTP status

### ISSUE THREAD

**Issue by robrankin** [hashicorp/consul#1025]
Currently if the cluster has no leader, the `/v1/status/leader` endpoint returns HTTP 200.  Should this be changed to be an HTTP 5xx status?

The `/v1/health/service/consul` endpoint returns a 5xx status when the cluster is without a leader, seems to make sense the `/v1/status/leader` endpoint should too?

**Comment by blalor** [comment]
I think this is inconsistent, actually. I've seen different behaviors. I believe clients return 500, while servers return 200. It should probably be 200 with an empty string indicating no leader; asking for the leader when there isn't one isn't really a failure…

**Comment by robrankin** [comment]
I'm a fan of returning something like an HTTP 5xx status, as it doesn't require parsing the response to determine that there's something terribly wrong.

Either way, if it was consistent across the endpoints and across server v. client that would be fantastic.

**Comment by blalor** [comment]
I believe in HTTP status codes.  They're the One True Way™.  In most cases, not having a leader is "terribly wrong", but if the agent's not joined to a cluster, yet, an empty response is valid.  I guess it boils down to "what question is being asked"?

**Comment by robrankin** [comment]
Good point.  The question I was asking was:

1.) Directed to the consul servers, not agents
2.) "Do you have a leader"?

Basically setting up some monitoring to query the Consul servers.

**Comment by ryanuber** [comment]
Hmm, I'm on the fence about this. Usually the 500 error on a client means it was unable to do leader forwarding, so that would probably explain the different status codes when asking a client vs. a server node for the leader. They are different failures though, for example a client which gets partitioned from the servers should return a 500 if asked for the leader since it can't know at that point. Making the servers return a 500 when there is no leader masks the fact that the server actually did determine that there is currently no leader.

**Comment by highlyunavailable** [comment]
I would say that if there is no leader the response should be emptystring rather than 500 since the leader was successfully determined but there is no leader.

**Comment by ryanuber** [comment]
I think keeping the 500's for internal or communication errors is the right thing for now, and 200's for successful queries. The response payload will then give you the indication of leader presence. Let me know if I missed anything!
