### ISSUE TITLE
Vunerability CVE-2016-4074 on jq

### ISSUE THREAD

**Issue by lchiron** [hashicorp/consul#10263]
#### Overview of the Issue

Security tool scanned the hashicorp/consul:1.10.0-beta2 docker image and found the following CVE: 
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2016-4074

#### Reproduction Steps

Steps to reproduce this issue

1. Get lastest hashicorp/consul:1.10.0-beta2 docker image (we testes both latest and 1.9.5)
2. Use a security tool to scan for CVEs

#### Environment

Kubernetes version: AKS v1.18.14
consul version: 1.10.0-beta2 and 1.9.5

#### Security scan result

Fixable CVE-2016-4074 (CVSS 7.5) found in component 'jq' (version 1.6-r0) in container 'consul', resolved by version 1.6_rc1-r0

**Comment by mikemorris** [comment]
This vulnerability appears to be fixed in the version of `jq` (1.6-r0) we're bundling with the Consul Docker image at https://github.com/hashicorp/docker-consul/blob/master/0.X/Dockerfile#L19, but looks like it's being improperly flagged by some scanning tools still (see https://github.com/stedolan/jq/issues/1136#issuecomment-780037325).
