### ISSUE TITLE
consul agent should be a better unix service citizen

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#104]
`consul agent` should have options to properly daemonize itself, write its pid to a file, and output logs to a file in a structured format.  The pid file and daemonization can be worked around in a bash startup script.  The log output is much more geared toward humans, however; specifically the leading whitespace, the `==>` lines, and the summary info output when the agent starts up.

```
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
    Join completed. Synced with 1 initial agents
==> Consul agent running!
       Node name: 'server-3'
      Datacenter: 'dc1'
          Server: true (bootstrap: false)
     Client Addr: 127.0.0.1 (HTTP: 8500, DNS: 8600, RPC: 8400)
    Cluster Addr: 172.17.0.4 (LAN: 8301, WAN: 8302)

==> Log data will now stream in as it occurs:

    2014/05/02 02:36:07 [INFO] serf: EventMemberJoin: server-3 172.17.0.4
    2014/05/02 02:36:07 [INFO] serf: EventMemberJoin: server-3 172.17.0.4
```

**Comment by jorgemarey** [comment]
Hi, I was wondering if there is any easy way to know when consul has finished bootstrapping. I explain my case:

I have a systemd service that launches consul at boot. I have other services that dependes of consul, so they should start when consul has finished starting. The problem is that with systemd files, the service is considered active at the moment the command is executed. (this happends when de _Type_ is set to default, but I didn't find any other Type useful to this case). So the next services start when consul hasn't finished bootstraping, resulting on several problems. 

I thought that maybe it was a good idea to modify consul and set somethig like docker has to notify when it has finished bootstraping: [docker-systemd-notify](https://github.com/docker/docker/blob/master/cmd/dockerd/daemon_linux.go), but I guess that this contradicts what @mitchellh said of leaving daemonization to a higher level.

So I thought about wrapping the consul service with something that checks that consul has finished and make the nofity. In this case, my initial idea was to make request to `/v1/status/leader` every second and when the request's reponse was ok, then notify. But I don't know if there's a better way of doing this.

Thanks!

**Comment by jniesen** [comment]
@jorgemarey Where did you end up with your startup issues? I've been debugging a dependency issue for about an hour that sounds like yours. I have a Systemd Unit for consul-template:

```
[Unit]
Description=Consul-Template
Requires=consul-agent.service cloud-final.service
After=consul-agent.service cloud-final.service
[Service]
Environment="CONSUL_HOST=localhost:8500" "CONFIG_DIR=/etc/consul-template.d"
EnvironmentFile=/etc/sysconfig/consul-template
ExecStart=/usr/bin/consul-template -consul $CONSUL_HOST -config $CONFIG_DIR
Restart=on-failure
RestartSec=5s
StartLimitInterval=0
[Install]
WantedBy=multi-user.target
```

It depends on the local Consul agent (managed via SystemD with consul-agent.service). The problem is, as you said, that the consul-template service starts before the Consul agent has finished bootstrapping, so I get a failed request from consul-template, which causes downstream issues for the service that consul-template is configured to restart on template renders.

```
Nov 28 19:45:23 systemd: Started Consul Agent.
Nov 28 19:45:23 systemd: Starting Consul Agent...
Nov 28 19:45:23 systemd: Started Consul-Template.
Nov 28 19:45:23 systemd: Starting Consul-Template...
Nov 28 19:45:31 consul-template: 2016/11/28 19:45:31 [ERR] (view) "key(*****)" store key: error fetching: Get http://localhost:8500/v1/kv/*****?stale=&wait=60000ms: dial tcp [::1]:8500: getsockopt: connection refused
Nov 28 19:45:31 ip-10-142-4-121 consul-template: 2016/11/28 19:45:31 [ERR] (runner) watcher reported error: store key: error fetching: Get http://localhost:8500/v1/kv/*****?stale=&wait=60000ms: dial tcp [::1]:8500: getsockopt: connection refused
Nov 28 19:45:32 consul: ==> Starting Consul agent...
Nov 28 19:45:32 consul: ==> Starting Consul agent RPC...
Nov 28 19:45:32 consul: ==> Joining cluster...
Nov 28 19:45:32 consul: Join completed. Synced with 1 initial agents
Nov 28 19:45:32 consul: ==> Consul agent running!
```

**Comment by jorgemarey** [comment]
Hi @jniesen! I didn't find a "nice" way to do this. The choices that you have (from what I could see) are: made the service that will use consul (in this case) use some kind of retries or make some service that, based on some polling, waits for consul to be ready and then make consul-template wait on that service.

**Comment by jniesen** [comment]
@jorgemarey thanks for the input. I went with your suggestion.

```
# consul-ready.service
[Unit]
Description=Consul-Agent-Watcher
Requires=consul-agent.service cloud-final.service
After=consul-agent.service cloud-final.service
[Service]
Type=notify
ExecStart=/usr/bin/consul-ready
[Install]
WantedBy=multi-user.target
```

```
# /usr/bin/consul-ready
#!/usr/bin/env bash

consulReady() {
  curl --fail --silent http://localhost:8500/v1/status/leader > /dev/null
  [[ $? == 0 ]]
}

main() {
  until $(consulReady)
  do
    echo 'Waiting on Consul'
    sleep 5
  done

  echo 'Consul is Ready'
  /bin/systemd-notify --ready
}

main
```

The consul-template.service now depends on consul-ready.service and things are working nicely.
