### ISSUE TITLE
Can't get rid of a service from UI

### ISSUE THREAD

**Issue by lukyanov** [hashicorp/consul#10421]
#### Overview of the Issue

I can't deregister a service so that it would disappear from the UI. Actual deregistration happens successfully.
I know this because I don't see the service in `curl localhost:8500/v1/agent/services` on any of my nodes. However, I can still see it here: `localhost:8500/v1/internal/ui/services` (and thus in the UI).

Tried everything:
- deregistration from CLI and API
- deregistration via catalog

`consul catalog services` also shows the service.

### Consul info for both Client and Server
<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 5
	services = 5
build:
	prerelease = 
	revision = a417fe51
	version = 1.9.0
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 62
	max_procs = 2
	os = linux
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 6269
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 843
	members = 6
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = a417fe51
	version = 1.9.0
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 172.31.59.204:8300
	server = true
raft:
	applied_index = 33006992
	commit_index = 33006992
	fsm_pending = 0
	last_contact = 7.431936ms
	last_log_index = 33006992
	last_log_term = 11213
	last_snapshot_index = 32993743
	last_snapshot_term = 11163
	latest_configuration = [{Suffrage:Voter ID:ec2ce283-5942-3596-6b31-abf83d41cc05 Address:172.31.59.203:8300} {Suffrage:Voter ID:ec2f7d84-4243-637d-b639-dbd27f8d60a6 Address:172.31.59.204:8300} {Suffrage:Voter ID:ec24f45c-8286-00bb-7360-e87a7156902d Address:172.31.59.202:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 11213
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 140
	max_procs = 1
	os = linux
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 6269
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 852
	members = 7
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 135
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 14.04.3 LTS

**Comment by dnephin** [comment]
Thank you for reporting this issue!

I don't think we've seen this issue before, so we may need some additional information to help debug the problem.

[Deregistering the service via the catalog](https://www.consul.io/api-docs/catalog#deregister-entity) should work to remove it. What happens when you attempt to deregister it with that API? Do you get any error?

How was the service registered originally? Was it done directly with the `/catalog/register`, or with `/agent/service/register` ?

Does the service have a node associated with it? That should tell you which node it came from, and it's possible the agent logs on that node have some warnings or errors that might provide more information about why it wasn't removed.

If you can share the name of the service, or even some of the output of the `/v1/internal/ui/services` response, that may also help give us some hint about what is happening.

**Comment by jkirschner-hashicorp** [comment]
Hi @lukyanov,

Just checking in again, do you have any updates on this?

**Comment by jkirschner-hashicorp** [comment]
Hi @lukyanov,

We don't have enough information at this time to take any further action and haven't heard any updates in a while, so I'm closing this for now.

If you are still experiencing this issue, please reopen and provide some of the additional information requested by @dnephin.

Thanks!
