### ISSUE TITLE
Services not appearing in UI with ACL turned on if not logged in, despite write policy allowing it

### ISSUE THREAD

**Issue by zupalex** [hashicorp/consul#10426]
#### Overview of the Issue

Hello, I'm facing an issue which looks kind of similar to [this one](https://github.com/hashicorp/consul/issues/701) which is quite old, but it's at the same time not the same scenario.
We had a set of 3 Consul server running without ACL for a while and it was working fine. In the UI we could see the services that got registered. However after recreating the cluster, turning on ACL, and edit the anonymous token to allow write for services resources with an empty prefix, we cannot see anymore the services in the UI when not logged in. Contacting any server `/catalog/services` endpoint via curl without providing any token returns properly the list of services though, so the edit of the anonymous token policies did work.

#### Reproduction Steps

- Create a 3 servers cluster
- Turn on ACL
- Try to query `catalog/services` anonymously and see it is refused as expected
- Edit the anonymous token with the following policy:
```
Posted to Consul as 'service-readwrite'
service_prefix "" {
  policy = "write"
}
-----------------
curl -X PUT --header "X-Consul-Token: $consul_token" "http://${consul_host}:${consul_port}/v1/acl/token/00000000-0000-0000-0000-000000000002" --data '{"Policies": [ { "Name": "service-readwrite" }]}'
```
- Register some services
- Query the `catalog/services` endpoint anonymously and see that we get the expected list of services
- Check the web UI services page, it returns nothing
- Log in with the management token, services show up

There was no errors in the web browser console.

### Consul info for both Client and Server

Consul servers running version 1.8.4

### Operating system and Environment details

Using the official Consul Docker image from Dockerhub

**Comment by johncowen** [comment]
Hi @zupalex 👋 

Thanks for submitting the report!

I'm guessing that using querying the `/v1/internal/ui/services?dc=your-dc` endpoint via curl also gives you an empty 200 response (`[]`)? Is that right?

Thanks!

**Comment by zupalex** [comment]
Hello. I just tried and indeed it does respond with an empty array and status code 200.

**Comment by zupalex** [comment]
It turns out that the anonymous token needs to also have read access to "node" and/or "agent". Should have been obvious that it needs it since it displays info about the nodes where the service is registered 🙄 
I think though that the UI should display the list of services with their tags. It should basically display what a query to `/catalog/services` shows.

**Comment by johncowen** [comment]
Hi @zupalex , thanks for the additional information.

We show a lot more information on the UI Service listing page than what is returned to us in `/catalog/services` which is why we have an additional API endpoint to provide the data for this page.

I can understand your thinking here, but I've reached out to our docs team to see if can make the ACL requirements of the UI clearer somewhere. Actually, I wonder if we could revisit the text we show there in UI itself if we can see that you are using the anonymous token and you get no services returned 🤔 

Maybe instead of:

"There don't seem to be any registered services, or you may not have access to view services yet."

We could use something like:

"There don't seem to be any registered services, or the token you are using doesn't have the required ACL rules to view services/nodes yet."

I know its not ideal and I think additional documentation would be best around this, but do you think that ^ may have helped in your case?

Lastly I'm guessing we can close this issue now? Let me know and I can close it if you think the same.

Thanks again for this issue and documenting your experience for us though 👍

**Comment by zupalex** [comment]
Thanks for the reply. It definitely would help if the documentation was clearer about which policies are required to view the services page in the UI. I dumbly assumed that since it's the services page it just needs service read, so if it mentioned that it might be missing "service and/or node" authorization, I would have realized immediately.
This issue can indeed be closed. Thanks.
