### ISSUE TITLE
Proxy upstream config need both local_bind_port and local_bind_socket_path

### ISSUE THREAD

**Issue by sw11517** [hashicorp/consul#10480]
#### Overview of the Issue

It does not work when you build a sidercar config by the tutorials. There is an error log of "upstream has no local_bind_port or local_bind_socket_path. " when you start the proxy.

We search this log in the source code(master), we found that(connect/proxy/proxy.go:106): 

```
if uc.LocalBindPort < 1 || uc.LocalBindSocketPath == "" {
	p.logger.Error("upstream has no local_bind_port or local_bind_socket_path. "+
		"Can't start upstream.", "upstream", uc.String())
	continue
}
```

It means we should set both local_bind_port and local_bind_socket_path, and it should be "and" logic instead of "or"

**Comment by rboyer** [comment]
Thanks for the feedback. The [built-in connect proxy](https://www.consul.io/docs/connect/proxies/built-in) doesn't have nearly the same degree of testing and this bug was unfortunately in an aspect that was not tested. The built-in proxy doesn't get as much hardening or field-testing mostly due to this call out on the above page:

> Note: The built-in proxy is not supported for production deployments. It does not support many of the Connect service mesh features, and is not under active development. The Envoy proxy should be used for production deployments.

That said, the bug has been patched on the `master` branch and backported to the `release/1.10.x` branch where it will be shipped in `1.10.1` when that is released.
