### ISSUE TITLE
Api Lock.isHeld is un enexported field

### ISSUE THREAD

**Issue by ThomasAlxDmy** [hashicorp/consul#1051]
Trying to play with lock in Consul and I'm runing into some trouble because isHeld is unexported. 
Could you change it to IsHeld?

**Comment by highlyunavailable** [comment]
This doesn't directly answer your request (I'll leave it up to the actual authors to do that of course), but is a viable workaround:

The idiom I've seen used mostly is not to check isHeld, but to store a reference to the `out chan struct{}` that `Lock` returns and test its second property to see if it is still open (e.g. `_, ok := (<-leaderCh)`). This is effectively the same thing as checking IsHeld, or since this is not a data channel, just monitor to see if you get anything over it - if you ever get data, it'll be because the channel is closed and the zero value is being returned.

**Comment by ThomasAlxDmy** [comment]
@highlyunavailable I'm confused on how I can use it that way. Isn't <-leaderCh going to block until the locks returns? What I really need to do is execute some operation while I'm holding the lock and then releasing it when I'm done.

**Comment by highlyunavailable** [comment]
A simple example looks like this:

```go
package main

import (
	"github.com/hashicorp/consul/api"
	"log"
	"time"
)

func main() {
	c, err := api.NewClient(api.DefaultConfig())
	l, err := c.LockKey("myLock")
	lockCh, err := l.Lock(nil)
	defer l.Unlock()
	if err != nil {
		log.Fatalf("Oh no, could not acquire lock: %v", err)
	}

	processNums := [10]int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

	go func(lock *api.Lock) {
		time.Sleep(time.Second * 5)
		lock.Unlock()
	}(l)

	for i := 0; i < len(processNums); i++ {
		time.Sleep(time.Second)
		select {
		case <-lockCh:
			log.Fatalln("Lock was lost, exiting")
		default:
			log.Printf("The number is: %d", processNums[i])
		}
	}
}
```

This program will always exit after 5 since the lock is lost then. A caveats to note: It's only checking per step (that is, every time it tries to print the number) so don't put a long-running statement inside the default case there because it will run through the function in there before checking again. `defer l.Unlock()` up top will unlock when all numbers are printed, if we didn't have that goroutine to unlock after 5 seconds.
