### ISSUE TITLE
Consul DNS interface usage without commandline?

### ISSUE THREAD

**Issue by VaradDeolankar** [hashicorp/consul#1056]
I want to use the DNS interface of consul since it provides load balancing. But, I want to implement making DNS queries programmatically, without using the command line tools such as dig. But, in my knowledge, there isn't much programmatic support for making DNS queries across all the languages( C/C++, C#, KDB, etc.). 

Is there any simple way to access the DNS entrypoint of consul without using third party APIs.?

Also, the HTTP API does not provide the load balancing feature. So, is it possible for consul's HTTP API to provide that feature instead. 
If not, could you also provide some more information on where the code change would be required in consul code if such a feature has to be implemented for the HTTP API? So that we can change it as per our need.

**Comment by ryanbreen** [comment]
Every language I know of has built-in support for DNS queries and additional libraries you can use if you want to do something fancy. I suggest you start by researching those options on your platform.

**Comment by VaradDeolankar** [comment]
Thanks for the reply. Could you also throw some light on the doubt about the HTTP API that I raised above?

**Comment by ryanbreen** [comment]
Sure.  The HTTP API will return the set of nodes currently reporting alive for a service.  To implement load balancing, just select a random entry from the list.  I'm not sure that's something that should be added to Consul proper: if you're consuming the HTTP API, you are already writing code to do so, so randomizing the order of returned services should be trivial.  Randomization in the DNS responses is more helpful because consumers of DNS responses typically use the first entry returned.

**Comment by VaradDeolankar** [comment]
But, Randomizing does not provide proper load balancing as Round robin does. And Round robin can't be implemented on client's side because obviously any client can't maintain the service instances in use. So is there a way in which that feature can be implemented in Consul's HTTP API?

**Comment by highlyunavailable** [comment]
Round robin does not provide "proper" load balancing either. Round robin could also be implemented on the client side, e.g. by the following (go) code (which is wildly inefficient and really should use a blocking query + cached slice of services - also probably wrong in a couple of places since I just free-wrote it):

```go
func roundRobin(serviceName string) *ServiceEntry {
	instanceMaxIndex := 0
	instanceNext := 0
	// Client is coming from somewhere outside
	instances, _, err := client.Health.Service(serviceName, nil, true, nil)
	if len(instances)-1 != instanceMaxIndex {
		instanceMaxIndex = len(instances)-1
		instanceNext = 0
	}
	if instanceNext >= instanceMaxIndex {
		instanceNext = 0
	}
	ins := instances[instanceNext]
	instanceNext++
	return ins
}
```

It's no worse doing round robin or random from the client than on some magical central server, as over time/enough requests they will both average out to a mostly even load across all instances of the service. If you want a real load balance that can do traffic-based load balancing, put one in front of your service. Neither round robin nor randomization is not a substitute for that.

**Comment by ryanbreen** [comment]
Agreed with @highlyunavailable.  I'm going to close this because I don't see a need to burden Consul with this, but I'm happy to be overridden if others disagree.
