### ISSUE TITLE
missing client token

### ISSUE THREAD

**Issue by j246he** [hashicorp/consul#10652]
Hi guys,
I do not know where to ask a question, so I ask here.
When I'm doing the bootstrap, it is already saying "missing client token.", through CLI and API.

>  vault secrets enable consul
Success! Enabled the consul secrets engine at: consul/
export CONSUL_HTTP_ADDR=https://vault.tools.sap
consul acl bootstrap
Failed ACL bootstrapping: Unexpected response code: 400 ({"errors":["missing client token"]})
curl --request PUT https://vault.tools.sap/v1/acl/bootstrap
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    36  100    36    0     0     48      0 --:--:-- --:--:-- --:--:--    48{"errors":["missing client token"]}

Can anyone tell me how to solve this issue? Thanks.

**Comment by jkirschner-hashicorp** [comment]
@j246he : can you double-check whether your `CONSUL_HTTP_ADDR` points to a Consul instance?

It seems like what might be happening is that instead of submitting a `PUT` request to `/v1/acl/bootstrap` on a Consul instance, that request is actually going to a Vault instance. We suspect this because:
- The "missing client token" error seems to be [generated by Vault](https://github.com/hashicorp/vault/blob/v1.7.3/vault/request_handling.go#L126)
- "https://vault.tools.sap" looks more like a Vault address than a Consul address

**Comment by jkirschner-hashicorp** [comment]
Hi @j246he,

Just checking in again, any updates on this?

**Comment by jkirschner-hashicorp** [comment]
Hi @j246he - closing this for now, but you are welcome to reply and reopen if needed.
