### ISSUE TITLE
how to protect UI  with https?

### ISSUE THREAD

**Issue by huaerfan** [hashicorp/consul#10721]
Since the token can be viewed through the UI, can I use HTTPS to protect the UI？

**Comment by jkirschner-hashicorp** [comment]
Hi @huaerfan,

Yes, the [UI can be configured for HTTPS access](https://learn.hashicorp.com/tutorials/consul/tls-encryption-openssl-secure#configure-the-consul-ui-for-https). There is also a [page with several recommendations to consider for securing UI access](https://www.consul.io/docs/security/security-models/core#recommendations). In addition to using HTTPS, you can consider using ACLs with a [default deny policy](https://learn.hashicorp.com/tutorials/consul/access-control-setup-production#enable-acls-on-the-agents) so that a [token (with flexible levels of access) is required to use the UI](https://learn.hashicorp.com/tutorials/consul/access-control-setup-production#consul-ui-token).

You can also post questions like this on the [Consul Discuss forum](https://discuss.hashicorp.com/c/consul/29), where other community members may be able to assist. [Here's a related thread](https://discuss.hashicorp.com/t/consul-web-ui-tls-enabled/24797/6).

Let me know if these help.

There may also be an opportunity to improve the documentation here. Can you let me know which Consul web page(s) you were looking at that prompted this question, but didn't seem to provide the information you were looking for?

**Comment by huaerfan** [comment]
Oh, thank you so much. I was careless and missed the tutorial, Thanks again!

**Comment by jkirschner-hashicorp** [comment]
No problem!

We want to make sure the right information is discoverable from the right places. If you did some looking, but didn't find this info on the pages you looked at, let me know if there's anywhere you think the tutorial should be linked from.

**Comment by jkirschner-hashicorp** [comment]
@huaerfan : PR #10834 improves the cross-referencing of documentation around configuring the UI with HTTPS. I've also added information about securing the UI with HTTPS to the [ACL tutorial's UI token section](https://learn.hashicorp.com/tutorials/consul/access-control-setup-production#consul-ui-token). Thank you for raising the question and helping to uncover an opportunity to improve the docs.
