### ISSUE TITLE
Creating a Session with the API does not allow LockDelay = 0

### ISSUE THREAD

**Issue by ChrisAubuchon** [hashicorp/consul#1077]
According to the Sessions internal page, the LockDelay for a Session can be between 0 and 60. Using the API in `api/session.go` does not allow a zero value

The block at https://github.com/hashicorp/consul/blob/master/api/session.go#L80-L82 only puts a value for LockDelay in the body if LockDelay != 0. When LockDelay == 0, no value is put in the request body and the default value of 15s is used instead.

**Comment by highlyunavailable** [comment]
That's a nasty one because the "zero value" of a time.Duration is `0`, so an unset value is indistinguishable from an actual value of 0. While this does look like a bug, as a workaround, you can use something like time.Nanosecond as your duration, which doesn't EXACTLY equal 0 but also doesn't completely disable LockDelay either technically.

**Comment by i0rek** [comment]
Lockdelay is now documented properly: https://www.consul.io/api/session.html#lockdelay.
