### ISSUE TITLE
Snapshot agent filename should include consul version (or at least allow for templating that does)

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul#10829]
#### Feature Description

Knowing which snapshot is compatible with which consul binary would be hugely useful, we can include that in the snapshot manual commands but the agent doesn't allow us to configure the name of the files.

Templating would be best so we can hook into other information such as `datacenter`

#### Use Case(s)

Restoring a snapshot and being sure I'm not restoring to a mismatching version to my consul binary, or to the wrong datacenter

**Comment by jkirschner-hashicorp** [comment]
Hi @chrisjohnson,

Thank you for raising this suggestion.

Making sure I understand, do you mean that the manual `consul snapshot` command allows specifying a filename, but that the automatic snapshot agent launched by `consul snapshot agent` provides no means to specify a filename?

I also have a few questions about how you'd prefer this would work:
- Would you prefer that the name is still automatically chosen for you, just that additional information be added to the name (like datacenter, version)? Or are there reasons you'd want more control (specifying a template)?
  - One consideration with the template filename option is that it would be harder to prevent name collisions. Currently, a UNIX timestamp with nanosecond resolution is automatically included in the name to mitigate name collisions. Maybe if the user doesn't include the timestamp in the template filename, the snapshot agent could append the timestamp to the end of the supplied template.
- Is there information beyond datacenter and version that might be important to you to include in the filename? If so, why?
- If you could only pick datacenter **or** version to include the filename, which would you pick and why?
  - I ask because one of them is much less simple to include than it appears, so I'm trying to understand relative importance.

**Comment by david-yu** [comment]
Closing as this is now addressed by https://github.com/hashicorp/consul/pull/18625
