### ISSUE TITLE
namespace default policies and roles are not reflected in the APIs

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul#10831]
#### Overview of the Issue

When adding a default policy or role to a namespace, when inspecting the tokens, I cannot reflect this information.

I'm totally unable to tell if default policies get applied retroactively (e.g. do they apply to tokens that already exist within a namespace?). If the API/UI reflected these defaults when inspecting tokens, it would be possible to answer this question.

#### Reproduction Steps

1. Create a namespace
2. Create some tokens
3. Update the namespace to set a default policy
4. Create another token
5. View a token in the UI or use `consul acl token read` to inspect it
6. Observe that the default policy you applied doesn't show up
7. Also inspect one of the tokens you created prior to setting the default. Does the default apply to them? Who knows?

### Consul info for both Client and Server

consul 1.9.7+ent

**Comment by jkirschner-hashicorp** [comment]
Thanks @chrisjohnson. I'll share some mockup options later this month for how we could show this additional info (i.e., namespace default policies and roles). It's helpful to have this example for thinking through options and creating more realistic mockups.

**Comment by jkirschner-hashicorp** [comment]
@chrisjohnson: this is a mock-up of a potential direction we could take to make this better. Because it hasn't been vetted by others yet (engineering, design), it may need to change. However, I wanted to share it in this early form to get feedback from you (and anyone else viewing this):
- How does this compare to what you were hoping for?
- What feels unnecessary or unhelpful?
- What feels like its missing or could be improved?

This just shows potential CLI changes. There would be corresponding HTTP API changes. And we'd also want to reflect this info on the GUI. Do you have a sense of how you'd prefer to explore such information, and why? (HTTP API, CLI, or GUI?)

# CLI: Token Read

## Current

```
$ consul acl token read -namespace=testing-rx3 -id=2b58e043-178d-8f43-fb74-4ef511f3c0ac
AccessorID:       2b58e043-178d-8f43-fb74-4ef511f3c0ac
SecretID:         xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Namespace:        testing-rx3
Description:      service.token -- mitrx3n1.cmmint.net
Local:            false
Create Time:      2021-10-07 10:35:40.125000128 -0400 -0400
Roles:
    df7397a4-4864-7efb-4cb2-a20a10216e1b - all-services
```

## Proposal (Rough Draft)

### Standard Read

#### v1
Include all policy sources in the output (appended to the end of the existing output), not just those directly attached to the token.

```
$ consul acl token read -namespace=testing-rx3 -id=2b58e043-178d-8f43-fb74-4ef511f3c0ac
AccessorID:       2b58e043-178d-8f43-fb74-4ef511f3c0ac
SecretID:         xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Namespace:        testing-rx3
Description:      service.token -- mitrx3n1.cmmint.net
Local:            false
Create Time:      2021-10-07 10:35:40.125000128 -0400 -0400
Roles:
    df7397a4-4864-7efb-4cb2-a20a10216e1b - all-services
Namespace Default Roles:
    0cc25c56-2020-cc13-c39e-16efdf741151 - global-namespace-default
Default Policy:   deny
```

#### v2
Same as v1, except the additional policy sources are more clearly defined as separate from the token itself:
```
$ consul acl token read -namespace=testing-rx3 -id=2b58e043-178d-8f43-fb74-4ef511f3c0ac
...
Roles:
  df7397a4-4864-7efb-4cb2-a20a10216e1b - all-services
Inherited:
  Namespace Default Roles:
    0cc25c56-2020-cc13-c39e-16efdf741151 - global-namespace-default
  Default Policy:   deny

```

### Expanded Read (shows all rules)

By including a flag (e.g., `-rules`), the output can include all the rules from the associated roles and policies.
```
$ consul acl token read -rules -namespace=testing-rx3 -id=2b58e043-178d-8f43-fb74-4ef511f3c0ac
AccessorID:       2b58e043-178d-8f43-fb74-4ef511f3c0ac
SecretID:         xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Namespace:        testing-rx3
Description:      service.token -- mitrx3n1.cmmint.net
Local:            false
Create Time:      2021-10-07 10:35:40.125000128 -0400 -0400
Roles:
  df7397a4-4864-7efb-4cb2-a20a10216e1b - all-services

    Rules:
      namespace_prefix "" {
        service_prefix "" {
          policy = "read"
        }
        node_prefix "" {
          policy = "read"
        }
      }

Namespace Default Roles:
  0cc25c56-2020-cc13-c39e-16efdf741151 - global-namespace-default

    Rules:
    namespace_prefix "" {
      # Give global read access to ACL tokens/roles/policies
      # *NOTE* This does not allow you to read a tokens SecretID
      acl = "read"

      # Give global read access to the service catalog
      service_prefix "" {
        policy = "read"
      }

      # Give global read access to the node catalog
      node_prefix "" {
        policy = "read"
      }
    }

    # Allow token to be used to issue commands like `consul info`
    agent_prefix "" {
      policy = "read"
    }

Default Policy:   deny
```

**Comment by jkirschner-hashicorp** [comment]
@chrisjohnson : I'm actually in the process of writing up a similar thing for #10830 (which will be longer) to share with you!

I worked on designs for both of these issues together because I know how important they are to improving Consul ACL UX. The next step will be talking with engineering about what's possible in what amount of time so we can prioritize accordingly!

**Comment by jkirschner-hashicorp** [comment]
@chrisjohnson : I thought you might be excited to see this PR :) https://github.com/hashicorp/consul/pull/12670

It adds token read CLI and API endpoint functionality for _expanding_ a token, both in terms of:

- Resolving policies, roles, etc all the way down to ACL rules
- Showing all access control info that applies to an ACL token, including those inherited from namespace and global defaults

**Comment by chrisjohnson** [comment]
Truly fantastic work, thanks so much for seeing this through everyone involved! This is a great improvement to the discoverability of consul ACLs

**Comment by jkirschner-hashicorp** [comment]
Associated docs PR now also merged: https://github.com/hashicorp/consul/pull/12677
