### ISSUE TITLE
CONSUL: [ERROR] agent: Check failed to invoke

### ISSUE THREAD

**Issue by Rakshithakrishna2** [hashicorp/consul#10852]
For building edgex-security with consul and the whole process is without docker, I am facing issue while running the consul server, 
![Screenshot from 2021-08-16 11-46-19](https://user-images.githubusercontent.com/88701371/129520058-7486db07-0685-4891-92c1-9208a082bf49.png)

Note: There are list of files in respective folder, as given below,
/edgeX/consul/config$ ls
00-consul.json  01-mongo.json  01-redis.json  02-kong-db.json  02-kong.json  02-kong-migrations.json  02-security-secretstore-setup.json
But still I am facing those errors,
please provide me the solution for the same.
Thank you

**Comment by jkirschner-hashicorp** [comment]
Hi @Rakshithakrishna2,

The best place to start is to check all the lines containing `[ERROR]`. It look the service checks are failing because consul is looking for them in `/consul/scripts`, but there is "no such file or directory". Can you check whether `/consul/scripts/kong-migrations-checker.sh` and `consul/scripts/kong-db-checker.sh` exist at those paths?

**Comment by Rakshithakrishna2** [comment]
thanks jkirschner-hashicorp!! that worked.

**Comment by jkirschner-hashicorp** [comment]
Glad to hear it!
