### ISSUE TITLE
Deadlock on CircleCI

### ISSUE THREAD

**Issue by lra** [hashicorp/consul#1095]
Hi,

We launch consul on [CircleCI](https://circleci.com/) and it usually works fine. But sometimes (like 1% of the times) consul randomly crashes triggering a failure for an unknown reason. It happens after a while and after consul already answered requests for 20 mins.

Here are the stdout and stderr:
- stdout: https://gist.github.com/lra/379648afdfde989731cc
- stderr: https://gist.github.com/lra/2bb2d1bea012a19e939d

We are launching consul with this config:
```json
{
    "bootstrap_expect": 1,
    "client_addr": "0.0.0.0",
    "data_dir": "/tmp/consul",
    "datacenter": "devolate",
    "encrypt": "SomeThing==",
    "server": true
}
```

It's hard to reproduce but it happens once in a while.

**Comment by ryanuber** [comment]
Hey @lra, This is an unfortunate panic. Consul internally checks for this potential deadlock scenario and bails in this way if a transaction can't be started. Usually this is because of a leaked transaction which will never close. The timeout is pretty conservative at 30 seconds, so you are definitely hitting this nasty little bug. I would expect that this could be worse on systems which perform poorly. Fortunately, we plan to mitigate this by moving the state store into a pure in-memory store for Consul 0.6, so this type of issue should be completely gone once that lands.

Thanks for the detailed report, and let me know if I missed anything.

**Comment by lra** [comment]
cool, will upgrade when released and let u know if it happens again.

**Comment by lra** [comment]
any new version planned soon? We hit this deadlock problem a lot as we scale and we run 0.5.2.

**Comment by ryanuber** [comment]
@lra yes, definitely soon, though there is not a firm date at this point. 0.6 aims to be a massive performance and stability improvement release. It is odd that you are hitting this deadlock so often, though, and we haven't heard many reports of it happening in the wild. Anything unusual about your setup(s)?

**Comment by lra** [comment]
Those are [CircleCI](https://circleci.com/) containers, we just run a lot of them in parallel (100+) that are constantly killed and created, so we launch a lot of independent consuls (1 for each) and sometimes one of them deadlock, which leads to a false positive.

I could maybe add a TCP check to see if consul is really running, but I try to avoid those kind of hacks and like to rely on the tools I'm using ;)
