### ISSUE TITLE
Issue in querying service name that contains forward slash using the HTTP api

### ISSUE THREAD

**Issue by ghost** [hashicorp/consul#1096]
I have a service registered with the id and name as '/service.v1'

I see it listed when i query for services using http://localhost:8500/v1/catalog/services
But how do i use the 
`http://localhost:8500/v1/catalog/service/<servicename>` api??

**Comment by tgwizard** [comment]
Does it work with just urlencoding it? 

```
http://localhost:8500/v1/catalog/service/%2fservice.v1
```

**Comment by avinashkolluru** [comment]
@tgwizard No it doesnt work

**Comment by ryanuber** [comment]
This is because of the way `net/http`'s `ServeMux` works. We've had similar issues come up before, and if I remember correctly, it would basically require changing the muxer to make the routes work. For the time being, we can only recommend starting a service name with a slash. We can probably add an additional check, since I can see how the service registration could become "stuck".

**Comment by sielaq** [comment]
try to deregister it not with URL but with JSON, like:
```
curl -s -X PUT -d '{"Node": "your_node", "ServiceID": "/service_with_slash"}' http://consul.service.consul:8500/v1/catalog/deregister
```

**Comment by timp87** [comment]
Turns out this is a big problem. Once you registered serviceID with slash there is not way to deregister.

**Comment by ChipV223** [comment]
Hi @sielaq and @timp87!

You can actually remove the service with the `/` in the serviceID by using the [Catalog Deregister Entity API](https://www.consul.io/api-docs/catalog#deregister-entity)

Closing this case given the aforementioned solution, but feel free to respond if you have any additional questions!
