### ISSUE TITLE
Service weights have no effect on DNS returns

### ISSUE THREAD

**Issue by xiangma0510** [hashicorp/consul#10963]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I have registered three nodes in a database cluster to the same `postgresql` service. The primary node has a passing state and the secondary node has a warning state. I want to control the DNS resolution priority by using the weights :{"passing":1,"warning":5}. In my demand, I want the result of the dig postgresql.service.consul return only warning node's IP

#### Reproduction Steps

Steps to reproduce this issue, eg:
It looks like round-robin 
```
[root@g4-rails-01 consul]# ping postgresql.service.consul -c 1
PING postgresql.service.consul (10.8.0.26) 56(84) bytes of data.
64 bytes from g4-patroni-03.node.gitlab_consul.consul (10.8.0.26): icmp_seq=1 ttl=64 time=0.068 ms

--- postgresql.service.consul ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.068/0.068/0.068/0.000 ms
[root@g4-rails-01 consul]# ping postgresql.service.consul -c 1
PING postgresql.service.consul (10.8.0.24) 56(84) bytes of data.
64 bytes from g4-patroni-01.node.gitlab_consul.consul (10.8.0.24): icmp_seq=1 ttl=64 time=0.073 ms

--- postgresql.service.consul ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.073/0.073/0.073/0.000 ms
[root@g4-rails-01 consul]# ping postgresql.service.consul -c 1
PING postgresql.service.consul (10.8.0.25) 56(84) bytes of data.
64 bytes from g4-patroni-02.node.gitlab_consul.consul (10.8.0.25): icmp_seq=1 ttl=64 time=0.069 ms

--- postgresql.service.consul ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.069/0.069/0.069/0.000 ms
[root@g4-rails-01 consul]# ping postgresql.service.consul -c 1
PING postgresql.service.consul (10.8.0.26) 56(84) bytes of data.
64 bytes from g4-patroni-03.node.gitlab_consul.consul (10.8.0.26): icmp_seq=1 ttl=64 time=0.059 ms
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
$ /opt/gitlab/embedded/bin/consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 8
build:
	prerelease =
	revision = bbcbb733
	version = 1.9.6
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 6
	goroutines = 67
	max_procs = 6
	os = linux
	version = go1.16.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 10
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1802
	members = 10
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
$ /opt/gitlab/embedded/bin/consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = bbcbb733
	version = 1.9.6
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.8.0.22:8300
	server = true
raft:
	applied_index = 17809
	commit_index = 17809
	fsm_pending = 0
	last_contact = 20.093015ms
	last_log_index = 17809
	last_log_term = 12
	last_snapshot_index = 16385
	last_snapshot_term = 12
	latest_configuration = [{Suffrage:Voter ID:cf8d0f99-7779-9592-905b-3a05aaf0830e Address:10.8.0.22:8300} {Suffrage:Voter ID:3a3fccf7-c65e-26b2-ee4e-31ba13a0e07a Address:10.8.0.23:8300} {Suffrage:Voter ID:c27c8332-d27a-17dc-07a3-3ea50d8f8946 Address:10.8.0.21:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 12
runtime:
	arch = amd64
	cpu_count = 6
	goroutines = 107
	max_procs = 6
	os = linux
	version = go1.16.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 10
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1802
	members = 10
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 761
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

#### Service config 
```
{
	"service": {
		"name": "postgresql",
		"address": "",
		"port": 5432,
		"weights": {
			"passing": 1,
			"warning": 5
		},
		"checks": [{
			"id": "service:postgresql",
			"interval": "10s",
			"status": "failing",
			"args": ["/opt/gitlab/bin/gitlab-ctl", "patroni", "check-leader"]
		}]
	}
}
```

#### Server config
```
{
	"datacenter": "gitlab_consul",
	"disable_update_check": true,
	"enable_script_checks": true,
	"node_name": "g4-patroni-01",
	"rejoin_after_leave": true,
	"server": false,
	"retry_join": ["10.8.0.21", "10.8.0.22", "10.8.0.23"]
}
```

**Comment by xiangma0510** [comment]
```
# dig postgresql.service.consul

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.5 <<>> postgresql.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42486
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;postgresql.service.consul.	IN	A

;; ANSWER SECTION:
postgresql.service.consul. 0	IN	A	10.8.0.25
postgresql.service.consul. 0	IN	A	10.8.0.24
postgresql.service.consul. 0	IN	A	10.8.0.26

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 31 14:40:57 CST 2021
;; MSG SIZE  rcvd: 102

```

**Comment by blake** [comment]
Hi @xiangma0510, weights are returned as part of DNS SRV lookups. If you issue an SRV query, you should see different weight values returned in the response data based on the state of the service's health check.

```shell-session
$ dig -t SRV postgresql.service.consul
```

This Wikipedia article documents the format of an SRV response https://en.wikipedia.org/wiki/SRV_record.

**Comment by xiangma0510** [comment]
```
[root@g4-rails-01 consul]# dig postgresql.service.consul SRV

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.5 <<>> postgresql.service.consul SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64061
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 7
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;postgresql.service.consul.	IN	SRV

;; ANSWER SECTION:
postgresql.service.consul. 0	IN	SRV	1 5 5432 g4-patroni-03.node.gitlab_consul.consul.
postgresql.service.consul. 0	IN	SRV	1 5 5432 g4-patroni-02.node.gitlab_consul.consul.
postgresql.service.consul. 0	IN	SRV	1 1 5432 g4-patroni-01.node.gitlab_consul.consul.

;; ADDITIONAL SECTION:
g4-patroni-03.node.gitlab_consul.consul. 0 IN A	10.8.0.26
g4-patroni-03.node.gitlab_consul.consul. 0 IN TXT "consul-network-segment="
g4-patroni-02.node.gitlab_consul.consul. 0 IN A	10.8.0.25
g4-patroni-02.node.gitlab_consul.consul. 0 IN TXT "consul-network-segment="
g4-patroni-01.node.gitlab_consul.consul. 0 IN A	10.8.0.24
g4-patroni-01.node.gitlab_consul.consul. 0 IN TXT "consul-network-segment="

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 31 14:53:02 CST 2021
;; MSG SIZE  rcvd: 387
```

**Comment by xiangma0510** [comment]
A high weight means that it can be returned first, even if the status is warning. According to the return result of `dig`, it can be seen that the weight setting is correct, but the result of `ping` returns all

**Comment by xiangma0510** [comment]
My understanding is that when I ping, it should only return the high-weight IP, unless none of the high-weight IP exists

**Comment by blake** [comment]
SRV records an additional record type that may be provided by a DNS server. The DNS server does not perform any ordering or filtering of the response data based on the values in the resource records. It simply sends the relevant response to the client.

SRV records are designed to be used by clients. The clients evaluate the additional information from the SRV response and use parameters such as weight, priority, etc when deciding which server to connect to. From <https://en.wikipedia.org/wiki/SRV_record#Provisioning_for_high_service_availability>:

> Clients should use the SRV records with the lowest-numbered priority value first, and fall back to records of higher value if the connection fails. If a service has multiple SRV records with the same priority value, clients should load balance them in proportion to the values of their weight fields.

See the Usage Rules section of [RFC2782](https://datatracker.ietf.org/doc/html/rfc2782) for more info on how clients should interpret SRV response data when connecting to a server.

The reason you are seeing `ping` is returning all of the IPs is because ping does not use DNS SRV queries when resolving hostnames. It uses A or AAAA records.

You will need to issue the DNS query from a client application that understands SRV records in order for the application to evaluate the configured weights when connecting to the destination service.

**Comment by xiangma0510** [comment]
Isn't this service an SRV query issued from the client? The address that resolves this domain name is 127.0.0.1#53, which is listening on by consul

**Comment by xiangma0510** [comment]
Or is there another configuration that will do what I want?

**Comment by jkirschner-hashicorp** [comment]
> Isn't this service an SRV query issued from the client? The address that resolves this domain name is 127.0.0.1#53, which is listening on by consul

Unfortunately, "service/SRV query" and "client" are being used to refer to a few different things here.

Let's say you have a "client application" that wants to discover available `postgresql` service instances registered with Consul. The client application has the option of using the [DNS interface or HTTP interface](https://learn.hashicorp.com/tutorials/consul/get-started-service-discovery#query-services).

When you executed `ping postgresql.service.consul -c 1`:
- `ping` is your client application
- `ping` is using the DNS interface to perform a [Consul service lookup](https://www.consul.io/docs/discovery/dns#service-lookups). The Consul client agent on each node acts as a DNS server (in your case, listening on 127.0.0.1:53).

The Consul DNS server supports both DNS "A" and "SRV" record requests. Which type of record request occurs is controlled by the client application, in this case `ping`. Not all client applications will request or understand "SRV" records. `ping` does not request "SRV" records, only "A" records. This SRV record request can be called a "SRV query". The client application decides whether its "Consul service lookup" uses a "DNS A query" or a "DNS SRV query".

"SRV" records include weight information. "A" records do not. With both A and SRV queries, the client application will receive a response that contains a list of records (nodes hosting services registered with Consul's service catalog). The order of the list of records is randomized by Consul each time (and does not take into account weights). It's the responsibility of the client application to decide what to do with that list of records.

Because `ping` is not asking for "SRV" records, it has no access to weight information. It is just picking a record from the list to use.

If you are writing a client application (not using `ping`), that application can be written to use the weight information in the SRV query response (or, alternatively, [in the HTTP API response](https://www.consul.io/api-docs/catalog#list-nodes-for-service)) to select the appropriate service. [RFC2782](https://datatracker.ietf.org/doc/html/rfc2782) provides guidance for how a client application should use the weight field on page 3 in the "Weight" section. [Here's an example of someone implementing that algorithm in Python](https://github.com/RobertDeRose/python-robin-srv/blob/master/src/robin_srv/srv.py#L39) so that they can choose a SRV record from a DNS lookup based on weight.

**Comment by xiangma0510** [comment]
Got it, thanks, have a nice day

**Comment by jkirschner-hashicorp** [comment]
@xiangma0510 : were there specific Consul documentation pages or guides you were following? Are there parts that could have been clearer?

I'm wondering if there's an opportunity to improve the documentation. Thanks!

**Comment by xiangma0510** [comment]
I'm only looking at consul DNS configuration here, for my current request I'm using an alternative, registering a new service and specifying only_passing, which serves the same purpose

**Comment by jkirschner-hashicorp** [comment]
Hi @xiangma0510,

It sounds like you have a working alternative, but I'd still like to better understand your original goal to see if there's an improvement that can be made.

Regarding the context: you mentioned you have 3 nodes in a database cluster. Each node has a `postgresql` service. Do I understand correctly that you have 1 `postresql` service acting as the primary, and the other 2 are secondaries?

Regarding the use case: did you need a way to access the primary every time via DNS? Or was it something else you were trying to accomplish?

Thanks for your input!

**Comment by xiangma0510** [comment]
First of all, thank you for your patient help. The following is my request. I am using a patroni postgresql three-node (one active and two standby) postgresql high-availability cluster. All three nodes are registered to a service (postgresql), and the watch is registered. The status and name of each node in the service are different. Service changes will trigger the configuration modification of the postgresql connection pool. Currently, the application only uses the primary database, but in order to achieve load balancing, I need a link that only accesses the standby database.

**Comment by xiangma0510** [comment]
application node access the database through tcp connections, so SRV record weights does't work

**Comment by jkirschner-hashicorp** [comment]
Hi @xiangma0510,

It looks like patroni [has support for registering PostgreSQL instances into Consul](https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#consul).

> PATRONI_CONSUL_REGISTER_SERVICE: (optional) whether or not to register a service with the name defined by the scope parameter and the tag master, replica or standby-leader depending on the node’s role.

Try setting `PATRONI_CONSUL_REGISTER_SERVICE` to true. With this setting, it seems like patroni will update the `postgresql` service registration with tags to reflect the role (`master`, `replicate`, or `standby-leader`).

Consul DNS already supports [addressing services filtered by tag](https://www.consul.io/docs/discovery/dns#standard-lookup), such as `master.postgresql.service.consul` or `standby-leader.postgresql.service.consul`.

Does performing DNS lookups with these tags address your use case?

Thanks!

**Comment by xiangma0510** [comment]
Thank you for your reminding,in the previous test,I ignored the service register by patroni.
Now the cluster can run normally with minimal modification！
Consul is a good software!

Thanks again
