### ISSUE TITLE
consul crashed at 1 a.m. and 7 p.m. every day lead to check health failed

### ISSUE THREAD

**Issue by m12580** [hashicorp/consul#10982]
After the consul is restarted, it will break down in two stable periods every day, resulting in the timeout of all service health checks. After reading the official documents and forums, we still can't find a solution. I hope someone will give an answer. Thank you so much

`   2021/09/02 19:01:39 [WARN] agent: Check "***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:39 [WARN] agent: Check "service:***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "service:***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "service:***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "service:***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    2021/09/02 19:01:40 [WARN] agent: Check "service:***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by jkirschner-hashicorp** [comment]
Hi @m12580,

Thanks for reaching out. When you say that "Consul crashed", are you referring only to the warning messages above? Or were there other warning or error messages?

Messages like...
```
2021/09/02 19:01:40 [WARN] agent: Check "service:***********" HTTP request failed: Get http://***********/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

...are typically caused by network connectivity issues rather than by Consul. For example, [see this post](https://github.com/hashicorp/consul/issues/6781#issuecomment-556814918) from someone else with a similar error (who was coincidentally also using Spring Cloud's Consul integration).

It might be worth searching (such as on networking forums) for why a connection might be lost at a consistent time every day ([example](https://www.reddit.com/r/networking/comments/1x2lzi/works_internet_drops_at_the_same_time_every_day/)). That seems like a key clue.

**Comment by jkirschner-hashicorp** [comment]
Marking closed for now because we don't have enough information to take further action. You are welcome to reopen if you reply with the information requested above. Thanks!
