### ISSUE TITLE
Need longer TTL for sessions

### ISSUE THREAD

**Issue by omribahumi** [hashicorp/consul#1104]
The current maximum is 1h. Why was this limited?
For our use case (coreos/flannel#233) we need 24h, but is there a reason not to increase it to a much larger value, such as one or two weeks?

**Comment by ryanuber** [comment]
@omribahumi I think there may be a misunderstanding here. The cap is the maximum amount you may *extend* the life of a session at a time, and not the total time a session may be valid for. It is the responsibility of the client to "renew" the session before this time period expires using the [renew api](https://consul.io/docs/agent/http/session.html#session_renew). More info on session internals can be found [here](https://consul.io/docs/internals/sessions.html).

I *think* the 1h cap is in place to prevent dead client sessions from lingering around as a security practice. It seems reasonable to require clients to renew their session liveness each hour at least, but I'll let @armon comment here in case there are other reasons we cap it there.

**Comment by omribahumi** [comment]
@ryanuber I understood that. The thing is, because Consul will be used for address allocations, this limits the time the software (that is in charge of renewing the sessions every <1h) maintenance windows to a maximum of 1h.
Also, a good practice in address allocations is not to immediately re-use a recently freed subnet. This also limits the grace period to 1h.

I think this shouldn't be limited to such a small value, unless there's a performance reason for this.

**Comment by armon** [comment]
There are performance reasons for it as well, to limit the number of session TTLs Consul needs to manage. There are other implications caused by a leader failover, which can allow a doubling of that session time (read the Chubby paper for details). With a 24h session a cluster that is unstable (experiencing more than one election per day) would never be able to reap those sessions due to that effect. This is less likely to affect a short session. That said, we can increase the limit to say 24h and put a big warning that says use at your best judgement.

**Comment by omribahumi** [comment]
@armon any chance this could be in the next consul release?

**Comment by armon** [comment]
@omribahumi Yep! Easy enough!
