### ISSUE TITLE
Acl down_policy not work

### ISSUE THREAD

**Issue by Cloudnie** [hashicorp/consul#11148]
#### Overview of the Issue

Down_policy in "allow" mode, all actions should be permitted when primary datacenter is down，but it dose not work.

#### Reproduction Steps

1. Setup two datacenters and enable acl replication as below
![image](https://user-images.githubusercontent.com/38657873/134800963-1098ec47-af6d-4ca8-bf77-7f23cee2af06.png)
![image](https://user-images.githubusercontent.com/38657873/134801003-31a4e2f8-4793-432f-aee3-65c08bbdb0a9.png)
now verify acl replication ok.
2. Delete primary datacenter
3. Request 403 high probability
![image](https://user-images.githubusercontent.com/38657873/134801196-67d023b2-b363-4180-9c63-17c2f9df397c.png)

### Consul info for both Client and Server
consul verison 1.5.3
config of second dc:
![image](https://user-images.githubusercontent.com/38657873/134801449-c5791e6a-a18a-4c22-9189-98d5e3531409.png)

What's wrong?

**Comment by jkirschner-hashicorp** [comment]
Hi @Cloudnie,

**Q1:** Can you let us know whether the token you are using in the `consul kv get` command is a legacy token?

One way to do this is to list all tokens with [`consul acl token list`](https://www.consul.io/commands/acl/token/list#consul-acl-token-list), then check to see whether the "Legacy" field is `true`, e.g.,
```
$ consul acl token list

AccessorID:       dd40ea2f-ff15-e7cb-8249-5d5e95b7ee75
Description:      foo-service-token_1
Local:            false
Create Time:      0001-01-01 00:00:00 +0000 UTC
Legacy:           true
```

It is my understanding that `down_policy` is not supported with legacy ACL tokens. If you want to use `down_policy`, you will need to follow [this guide to migrate the legacy ACL tokens](https://learn.hashicorp.com/tutorials/consul/access-control-token-migration) to the new ACL system. Legacy ACL tokens were deprecated in Consul 1.4 and aren't supported by some 1.4+ enhancements (like `down_policy`), so we recommend migrating existing tokens to the new system.

**Q2:** I see in your screenshot that your `consul kv get` command returned "No key exists" once, then a 403 error every time after that. Do you ever receive a "No key exists" error after the 403 errors start? If so, the first success(es) may be caused by caching.

**Comment by Cloudnie** [comment]
> Hi @Cloudnie,
> 
> **Q1:** Can you let us know whether the token you are using in the `consul kv get` command is a legacy token?
> 
> One way to do this is to list all tokens with [`consul acl token list`](https://www.consul.io/commands/acl/token/list#consul-acl-token-list), then check to see whether the "Legacy" field is `true`, e.g.,
> 
> ```
> $ consul acl token list
> 
> AccessorID:       dd40ea2f-ff15-e7cb-8249-5d5e95b7ee75
> Description:      foo-service-token_1
> Local:            false
> Create Time:      0001-01-01 00:00:00 +0000 UTC
> Legacy:           true
> ```
> 
> It is my understanding that `down_policy` is not supported with legacy ACL tokens. If you want to use `down_policy`, you will need to follow [this guide to migrate the legacy ACL tokens](https://learn.hashicorp.com/tutorials/consul/access-control-token-migration) to the new ACL system. Legacy ACL tokens were deprecated in Consul 1.4 and aren't supported by some 1.4+ enhancements (like `down_policy`), so we recommend migrating existing tokens to the new system.
> 
> **Q2:** I see in your screenshot that your `consul kv get` command returned "No key exists" once, then a 403 error every time after that. Do you ever receive a "No key exists" error after the 403 errors start? If so, the first success(es) may be caused by caching.

**Comment by Cloudnie** [comment]
thank you for your reply @jkirschner-hashicorp

**Comment by jkirschner-hashicorp** [comment]
@Cloudnie : are you in a position where it's possible to test this with a newer version of Consul (1.8+) to see if the problem still exists in recent versions?

**Comment by Cloudnie** [comment]
@jkirschner-hashicorp I'll take the time to test it.The test results will reply to you.
