### ISSUE TITLE
consul_autopilot_healthy is reporting zero on the leader

### ISSUE THREAD

**Issue by arielazem** [hashicorp/consul#11152]
Overview of the Issue
With Consul v1.10.1 (Revision db839f18b), the metric consul_autopilot_healthy is zero for all the servers including the leader, even when autopilot reports the cluster is healthy

![Screen Shot 2021-09-27 at 11 36 42 AM](https://user-images.githubusercontent.com/33434607/134940067-5d469c9f-5743-43e6-b42d-5383f932fee2.png)

Zero on all the servers

![Screen Shot 2021-09-27 at 11 43 00 AM](https://user-images.githubusercontent.com/33434607/134941262-0bab0c66-4514-4c13-a794-f06e9b1e84fa.png)

The autopilot health endpoint reports the cluster is healthy.

![Screen Shot 2021-09-27 at 11 38 44 AM](https://user-images.githubusercontent.com/33434607/134940403-aa9f5e6f-d780-452a-852e-5ba26bf86f40.png)

Reproduction Steps
Steps to reproduce this issue, eg:

Run Consul v1.10.1
Go to /v1/agent/metrics?format=prometheus
Operating system and Environment details
Linux VM in GCP

**Comment by arielazem** [comment]
@mikemorris , #10730 is about all the followers reporting 0, while this other ticket #11152 is about leader reporting 0 as well

**Comment by FFMMM** [comment]
hey @arielazem thanks for opening this issue with us!


I actually do believe that the underlying cause is a change in one of our dependencies (go-metrics). The behavior gets manifested as metrics that were previously `NaN` (whether in a certain stage of leadership or not) showing up with a 0 value.

As the team works on a fix, we'll track progress on #10730  for now so I will close this issue as a duplicate. But please feel free to re-open as needed.

---

For anyone  that's coming after, I added some more descriptive steps on how to repro the problem with the metrics here:

https://github.com/hashicorp/consul/issues/10730#issuecomment-929844513
