### ISSUE TITLE
Insecure execution of consul shell commands

### ISSUE THREAD

**Issue by ask0n** [hashicorp/consul#1118]
Is it expected behavior that ANY local user able to execute "consul keyring -list" and view all encryption keys?
Also anyone able to put system in maintenance state with "consul maint".
I think it would be great to have configuration option named "consul_manager" with list of users, who is allowed to execute consul commands from shell. Default value of consul_manager should be root.

**Comment by ryanuber** [comment]
Hi @bancore,

Consul allows this because it exposes the toggles for various settings through its HTTP API or over the RPC interface, so naturally if a client can connect to those interfaces and there is no authentication or ACL's set up, then anyone can perform these actions. This is why Consul binds to the loopback interface by default.

Because Consul is compatible across a wide variety of platforms, we can't lean on UNIX users and groups to do this kind of authorization. I would suggest looking into using Consul's [ACL system](https://consul.io/docs/internals/acl.html) to secure different aspects of the server. Service registrations can already be locked down using the ACL's, which also covers the `maint` command, and the next release of Consul will introduce many enhancements to the ACL system, which includes the keyring commands (these changes are already in the master branch).

Hope that helps!

**Comment by slackpad** [comment]
Closing this out since keyring ACLs shipped in Consul 0.6.0.
