### ISSUE TITLE
When trying to delete a policy, the delete button disappears

### ISSUE THREAD

**Issue by vinayak03** [hashicorp/consul#11269]
#### Overview of the Issue

Delete button on policy edit page disappears if we try to delete the policy.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create policy (or use existing policy)
2. Go policy edit page and try to delete the policy

### Consul info for both Client and Server

Client is web browser. 

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = dev
	revision = 2d05164b
	version = 1.11.0
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 15
	commit_index = 15
	fsm_pending = 0
	last_contact = 0
	last_log_index = 15
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:6618fd78-fa31-d8e3-5bbb-91d0d31f3f79 Address:127.0.0.1:8300}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 12
	goroutines = 106
	max_procs = 12
	os = darwin
	version = go1.16.7
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

MacOS Big Sur 11.6, Chrome version Version 93.0.4577.82 

### Log Fragments

No logs in browser console,  able to delete the policy from the list view, it is only limited to frontend and edit policy section.

**Comment by vinayak03** [comment]
yes this is happening on the main branch..

**Comment by johncowen** [comment]
@vinayak03 feel free to pick this one up. TLDR; It's related to our modal component previously having an `@open=true` argument/state (I 'think' I remember it being named `open` you'll have to check) so we could make it be open as soon as its in the DOM (rather than waiting for a user interaction/click to open it). If you trace it back the history of the modal component that should give you some clues.

I can leave it for you to figure out how to put that functionality back (please follow the previous `@open` interface), or if you would like more direction then let me know and I can write it up a little better. It 'should' be just opening the modal on DOM insert if that `@open` argument is true.

Let me know if there is anything else you need to know 👍
