### ISSUE TITLE
Indicate when list in API endpoint response is filtered by ACLs

### ISSUE THREAD

**Issue by jkirschner-hashicorp** [hashicorp/consul#11276]
#### Feature Description

Endpoints that return list of items will typically enforce ACLs by filtering the result set, such as:
- Agent endpoints for local checks/services
- RPC endpoints for queries to Consul servers

However, Consul doesn't give any indication that the results were filtered by ACLs.

For a user looking at the list of results, it is unclear whether they are viewing the full list, or whether they are seeing a partial (or empty) list due to incorrect permissions.

This information could be exposed through returning a new header.

For the service mesh use case, we could log in the proxycfg package when a query is filtered by ACLs. This would help discover and troubleshoot ACL permissions issues.

A separate issue can be created in the future to consider propagating this information to the Consul GUI.

#### Use Case(s)

General discovery and troubleshooting of ACL issues via the API endpoints. Potentially enabling surfacing this information on the Consul GUI in the future.

**Comment by jkirschner-hashicorp** [comment]
Hi @OverDrone,

Can you tell me more about the difference for your use case between these two approaches?
- the approach in the issue description: return 200 OK with a Boolean to indicate whether some results were filtered due to ACLs
- the approach you suggested: opt-in to returning 403 if some results were filtered due to ACLs

Thanks for linking to your Discuss forum post for additional context!

**Comment by OverDrone** [comment]
the main difference is in how client app treats filtered response. In my case if anything was filtered means exception. Also for kv there is no fine tune of permissions, you filter all or you filter none by acl. So when server tells "you can't view this whole kv tree due to lacking permissions" that's the semantics of 403 http error.
If there are cases when you still has some nonfiltered data left and you need to use it somehow then http 200 with flag is more appropriate.
