### ISSUE TITLE
About whether consul configuration center supports c++ integration

### ISSUE THREAD

**Issue by zhangbing17** [hashicorp/consul#11615]
Excuse me,About whether consul configuration center supports c++ integration，and,If you can. So how c++ integration, in the official website did not find the relevant documents and supported language

**Comment by Amier3** [comment]
Hey @zhangbing17 

I see this is your first post so welcome to the hashicorp community! 

Are you asking about our C++ SDKs? We don't have any official C++ SDKs, but we can point you to [ppconsul](https://github.com/oliora/ppconsul) and [oatpp-consul](https://github.com/oatpp/oatpp-consul) if you're using Oat++ . These are actively-maintained community projects that aren't supported by us but may still help out! 

I'll also link our page on[ libraries and SDKs](https://www.consul.io/api-docs/libraries-and-sdks) if you wanted to explore some of our other integrations

**Comment by jkirschner-hashicorp** [comment]
> consul configuration center

To the best of my knowledge, there's nothing within HashiCorp Consul with the name "Consul configuration center". I believe this is something specific to Spring Cloud Consul? 

Spring Cloud is a different project, so you can probably get a better answer to your question [on that repo](https://github.com/spring-cloud/spring-cloud-consul).

----

In addition to trying to use a C++ SDK, you could instead use the [Consul HTTP API](https://www.consul.io/api-docs) directly from C++. For example, [by using libcurl](https://stackoverflow.com/a/1112084). That said, I don't know if this would help you because I'm unfamiliar with the Consul Configuration Center within Spring Cloud Consul.

**Comment by Amier3** [comment]
Closing this for now , feel free to re-open if these resources didn't help your use-case
