### ISSUE TITLE
consul not expanding '~' when doing CLI login

### ISSUE THREAD

**Issue by andreas-ahman** [hashicorp/consul#11648]
#### Overview of the Issue

When logging in using the CLI we need to use the absolute path to the file. Using '~' as a shortcut for home directory does not work.

#### Reproduction Steps

```
~ » ll '~'
ls: cannot access '~': No such file or directory

~ » consul login -method=auth0 -type=oidc -token-sink-file="~/consul.token"
Complete the login via your OIDC provider. Launching browser to:

    https://<redacted>

~ » ll '~'
total 8
drwxr-xr-x  2 xxxx   26 Nov 25 07:32 ./
drwx------ 47 xxxx 4096 Nov 25 07:32 ../
-rw-------  1 xxxx   36 Nov 25 07:32 consul.token
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
build:
	prerelease = 
	revision = cf701c09
	version = 1.9.7+ent
```

</details>

### Operating system and Environment details

Arch Linux, amd64, Consul 1.9.7+ent

**Comment by Amier3** [comment]
Hey @andreas-ahman 

Looks like this may be due to how the cli handles the equal operator followed by the quotations ( as a literal string ). I was able to get the following command to work with the `~` by removing the equal sign and adding the path after a space without the quotations: 

`consul login -method=auth0 -token-sink-file='~/consul.token' -type=oidc -bearer-token-file ~/consul.token
`

I'll close this for now, but feel free to re-open if this doesnt fix the issue.

**Comment by dnephin** [comment]
To add a little more detail, Consul does not handle the `~` at all. It is the shell that is responsible for expanding the tilde into the home directory.

I was not aware of this either, but the `~` must be the first character in the arg, or the first character after a `=`, also apparently it can't be quoted. From my testing these should work:
* `-token-sink-file ~/consul.token`
* `-token-sink-file =~/consul.token`

but these do not:
*  `-token-sink-file="~/consul.token"`
*  `-token-sink-file "~/consul.token"`

That behaviour is entirely up to the shell though, so not much we can do about it in Consul. I think we'd rather avoid handling the `~` character, because generally the shell should take care of it.

Did you find the command in any of our documentation? If any of our example docs are wrong, please let us know so we can update them!
