### ISSUE TITLE
[doc] difference between service with check and check tied to service

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#1196]
Hi @armon 

Assuming we have a Redis service defined as `redis.json` in consul directory:

```
{
  "service": {
    "name": "redis",
    "tags": ["prod"],
    "address": "127.0.0.1",
    "port": 6379,
    "checks": [
      {
        "script": "nc localhost 6379",
        "interval": "10s"
      }
    ]
  }
}
```

Now assuming there is a check `redis_check.json`:

```
{
  "check": {
    "id": "redis-check",
    "name": "check Redis port",
    "script": "nc localhost 6379",
    "interval": "10s",
    "service_id": "redis",
  }
}
```

This example does not make sense in itself, but it's just to clear up the doc.

What happen in that case in Consul ? Should checks be tied to services or vice versa (or doesn't really matter) ?

Thanks in advance!

**Comment by slackpad** [comment]
These two checks should be equivalent because the standalone check is bound to that service via the `service_id` - they should behave exactly the same.

One use for standalone checks is when you don't bind them to a specific service, in which case they will be used to determine the health of the node itself.

**Comment by scalp42** [comment]
Thanks for clearing this up (node health vs service health).
