### ISSUE TITLE
allow environment variable to set encrypt key

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/consul#1205]
I am not quite sure if this is already possible (if so, I don't think it's documented), but it would be nice if we could provide the `-encrypt` value using an environment variable.

**Comment by slackpad** [comment]
It's possible to set this using a configuration file if you'd like to avoid a command-line parameter, but it's not currently settable via environment variables.

**Comment by strarsis** [comment]
+1 for environment variable support for HCL/JSON files - or even better in HCL config parser itself.

**Comment by slackpad** [comment]
You can also manage keys via HTTP endpoints now - https://www.consul.io/api/operator/keyring.html. I think we will close this out for now since there's a way to avoid a CLI parameter now. A more general improvement to allow hooking config values from env vars is a larger discussion, but that would apply across multiple of our tools, so this specific issue probably isn't the best forum for that.
