### ISSUE TITLE
In GUI, unable to create keys within a KV folder (Consul 1.11.x)

### ISSUE THREAD

**Issue by jkirschner-hashicorp** [hashicorp/consul#12073]
#### Overview of the Issue

The Consul 1.11.x GUI doesn't allow creating keys properly from within a folder.

#### Reproduction Steps

Per @shantanugadgil (see [this comment](https://github.com/hashicorp/consul/issues/10906#issuecomment-1011138333)):

Use Consul version: 1.11.1

1. in the webui, go to Key/Value
2. create key named toplevel/ (with trailing slash)
3. click the new "folder" named "toplevel"
4. click the blue Create button.
5. I expect to see the combined boxes of Key or folder and Value, I see only the Value box. 😮 Add a value and click "Save".
6. Click the blue Create button again. Notice that the Value box contains the value you saved in step 5.
7. Return to Key/Value root, and create a key named toplevel/alpha with value aaa. This works as expected.

In step 3, Consul seems to be treating what I created in step 2 as a folder named "toplevel". However, in steps 5-6, it seems to be treating that same entity as a key named "toplevel/", which could explain why I can edit its value (like it's a key) but not create a new key within the folder (the "Key or folder" name input field is missing). Further evidence: In step 5, when I look at the network tab in Chrome dev tools, I see a put request to `http://localhost:8500/v1/kv/toplevel/?dc=dc1` with the test payload I entered (by clicking "Save") and receive a 200 OK response. 

### Consul info for both Client and Server

Reproduced in Consul 1.11.1.

Not reproduced in Consul 1.10.3+ent. We suspect this first appeared in 1.11.x.

**Comment by johncowen** [comment]
Fix for this in https://github.com/hashicorp/consul/pull/12081

Whilst not great, I noticed that this bug seems to manifest if you create a folder and then go to create something in that folder in one go i.e. without refreshing the page (an ember-data related cache bug). If you refresh the page at anytime after creating the folder, or the folder is a folder that has been created before you came to use the UI, then the bug doesn't seem to manifest. 

i.e. refreshing the page after clicking the create button (when you don't see the input field) makes the input field appear again

Hopefully this info may help any folks how are blocked by this before this goes into a release.

Thanks again for the report!
