### ISSUE TITLE
Compile UI assets into the Consul binary

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1220]
We can use (https://github.com/jteeuwen/go-bindata) to compile the UI assets into the binary. We should still support the `-ui-dir` option, but now we can just have a `-ui` flag to enable the compiled in version. This makes distributing even simpler.

**Comment by rgl** [comment]
I would like to get my feet wet on consul, and this seems like a good place to start. Any recommendation on how do you want this implemented?

The [current code](https://github.com/hashicorp/consul/blob/78aa6f1443ba506e8c9bc88b6f4448ad6fee325f/command/agent/http.go#L270) is using `http.FileServer` so its natural to use https://github.com/elazarl/go-bindata-assetfs (instead of directly using go-bindata) because it already provides an adapter for `http.FileServer`.

**Comment by rgl** [comment]
The PR is still missing the dependencies on https://github.com/jteeuwen/go-bindata and https://github.com/elazarl/go-bindata-assetfs; also, the travis build file needs to be changed to install the bundler gem and install the needed Web UI dependencies... I'm not really sure how to do these... so help me out!

**Comment by rgl** [comment]
The PR is now ready to merge, I think.

**Comment by slackpad** [comment]
This was done under #1543.
