### ISSUE TITLE
why service belongs to a node ?

### ISSUE THREAD

**Issue by lostz** [hashicorp/consul#1243]
I am very confused that ,why service belongs to a node.
I want to register a service, if it belongs to a node, the node shutdown, I lost the service.
But my service is ok.
I must get all nodes and register a service to all nodes.
Can I have a easy way ?

**Comment by mitchellh** [comment]
A service belongs to a node because a service is meant to run on some node. If the node shuts down, that specific service instance becomes unavailable (because it can no longer be reached). The service as a whole remains available as long as other instances are online. For example: `foo.service.consul` will still return results, just pointing to the healthy nodes.

If you're running a service that isn't tied to a specific node, then look at [External Services](https://consul.io/docs/guides/external.html), which aren't tied to a node.
