### ISSUE TITLE
Using Consul to simulate security groups

### ISSUE THREAD

**Issue by eirslett** [hashicorp/consul#1246]
Some cloud providers, like DigitalOcean, don't offer security-group-like functionality.
I've tried simulating it by running consul on every node, and using consul-template to generate iptables configuration on the fly.
It basically opens up for all communication internally between nodes in the cluster, and blocks all other incoming traffic. Outgoing traffic is open to anyone.
The challenge is to introduce new nodes into the cluster; they will not be able to `consul join` the existing nodes because of the firewall. To solve that problem, the consul ports 8300, 8301 and 8302 are open to the world, but with a rate limiting on how many TCP connections one can make per minute. When a new node has successfully joined, it becomes part of the simulated security group..

What I'm worried about is 2 things:
1) If attackers manage to coin the cluster, they will be part of the security group and have full access. How can that be prevented? 
2) Consul is a key part of the infrastructure; if a DDoS attack is targeted towards it, the whole datacenter might go down. Is it possible to prevent that?
3) Is this setup a good idea at all, or a recipe for disaster?

**Comment by highlyunavailable** [comment]
This is certainly a novel way to do things. I can't address whether it's a good idea or not (it seems like a hell of a hack but it SHOULD work) but I can address the concerns you asked somewhat given my own experience deploying and using Consul.

> 1) If attackers manage to coin the cluster, they will be part of the security group and have full access. How can that be prevented?

I assume you mean Join here but yes, if they join the cluster even as an agent they would have at least read permissions. However, the mitigating factors:
1. If you set a pre-shared [encryption key](https://www.consul.io/docs/agent/options.html#_encrypt) then unless the agent has that key it cannot even join the cluster as an agent. If your encryption key gets leaked you have larger problems, but you can rotate it regularly.
2. There are 3 "verify_*" options, including [verify_server_hostname](https://www.consul.io/docs/agent/options.html#verify_server_hostname) that can prevent MITM attacks on the HTTP API and further lock down Servers, but i haven't used them so I'm not sure how easy they are to set up/maintain.
3. You can use the [ACL system](https://www.consul.io/docs/internals/acl.html) to lock down permissions. However, ACLs do not support limiting reads of much of the data (e.g. nodes) - they only support Services and K/V pairs at this time.

> 2) Consul is a key part of the infrastructure; if a DDoS attack is targeted towards it, the whole datacenter might go down. Is it possible to prevent that?

You've answered your own question here - rate limit connections. Otherwise, you might want to look into [port knocking](https://www.digitalocean.com/community/tutorials/how-to-configure-port-knocking-using-only-iptables-on-an-ubuntu-vps) as a way to open up the ability to connect to 8300-8302. For example, as part of your "join" process you port knock to open up Serf and RPC to a server, then join the agent to the cluster. Once the agent is joined, it would be a normal member and the port knocking rules would not apply.

> 3) Is this setup a good idea at all, or a recipe for disaster?

It's actually not too different from some stuff I did with Salt and IPTables, but it definitely feels like a hack. I don't see a HUGE problem with it, though it does have all the problems of host-based firewalls (insofar that if a single host gets compromised, that host has no traffic controls).

**Comment by shakisha** [comment]
i have got the same identical issue.
has anyone any update on this?

**Comment by kasperisager** [comment]
The way I'm currently going about this is by using `consul watch -type nodes` and then a small (~40 lines) Go handler that parses the node list and configures iptables rules for these. Works a treat with minimal effort!

**Comment by AdrianCohea** [comment]
Hi all! Sorry to necro this issue, but I wanted to chime in on the answer to the first question. The way to prevent unauthorized nodes from joining your Consul cluster (or Nomad cluster for that matter), is to use pre-shared gossip keys and TLS mutual authentication. That way, although 8300, 8301, and 8302 are open to the world, we can't actually join without having a valid TLS certificate issued by the certificate authority that we control. You can use something like Cloudflare's SSL tool, cfssl. (Available on Ubuntu via the golang-cfssl package).

I too am interested in figuring out how to do a better job with something like security groups, because I just don't think enumerating nodes all the time and pushing out updates to everything through Ansible is going to be a very good idea at scale.

I would much rather have something like "flush everything but baseline rules, then for all of my MongoDB VMs, please allow 27017 for any private or public IPs belonging to my VMs with the role Nomad."

It seems like we could do something already with Consul Template in exec mode to accomplish this, right? Or is there a better approach someone became aware of?

**Comment by i0rek** [comment]
@ghost is right. In order to protect your services from unauthorized access, please use Connect. Closing this issue now. Thanks for reporting!
