### ISSUE TITLE
Consul UI always timeout on sending request to /v1/internal/ui/services

### ISSUE THREAD

**Issue by LDHo** [hashicorp/consul#12503]
Hello, I am one of the users of the HCP Consul. However, upon I tried to access the Consul-UI of my consul cluster, I discovered that there is a GET request to the endpoint `/v1/internal/ui/services` with query parameter `dc=<dc_name>&&index=1336704` will fail due to timeout issue. 

I have conducted some experiments on this endpoint. I tried to remove the `index` query parameter and found that without that the api did able to return me an empty []. I have also tried out to reduce the index value to 3 digit value and found that the api was still able to function properly. I was wondering whether this issue was caused from the large index number in the query parameters which probably caused the query taking too long to return the results? 

There are actually few of the endpoints calling from consul-ui having this issue
- /v1/internal/ui/services?dc=consul-cluster&index=1336704
- /v1/internal/ui/nodes?dc=consul-cluster&index=1336704

However, they did have one common point which is all of them having a large index number in their query parameter.

Actually I am not pretty sure whether this is consul issue or my site issue but I indeed discover this problem on my consul-ui. 
Hope anyone could give me some advice regarding this issue.

Thanks

**Comment by johncowen** [comment]
Hi @LDHo 👋

Thanks for the report!

Not sure how far I can help with this one myself, but could you let me know:

1. What's the timeout HTTP status code you get when it happens?
2. Does another HTTP request start up again after the timeout?

If you could let me know and I can see if I can help if not I can see if I can pass it on to someone who can.

Short term, I'm guessing you can turn off live updates in the Settings page of the UI (button in the top right to get to the Settings page), whilst this will turn off live-updates completely you'll no longer get any timeouts due to blocking query issues, although I'm not sure how far this helps if you want the UI to be auto updating, i.e. you'll have to manually refresh the page in order to get new data/updates.

Let me know on those above questions and I can see if I can help further!

**Comment by LDHo** [comment]
Hello @johncowen, thanks for your reply ya. 
For your first question, I don't think I received any status code from the endpoint ya with that big indexes.
All I can see from the network waterfall of Google Chrome is that the request was cancelled after a long time of awaiting the response while after that particular request called, the consul-ui will indeed re-request the same endpoint again with the same query params ya.

**Comment by LDHo** [comment]
Hello, @johncowen great answering. That did help me a lot. Thanks! I will hereby close this issue ya.

**Comment by raffig** [comment]
Documentation from @johncowen says that those long polling endpoints have `wait` parameter that may be set. That would be useful for cases when Consul UI is behind the proxy. Sometimes there is no control over proxy timeout or code returned. In my case proxy returns 504 after 10 seconds, which breaks UI. It would be great to configure Consul UI to use wait parameter e.g. `8s`. Is there any way to do this?
