### ISSUE TITLE
Raft's replication VS. anti-entropy

### ISSUE THREAD

**Issue by half-dead** [hashicorp/consul#1250]
I have a question that might be a little tricky:

Say we have a large cluster containing 3 server nodes that are up for a long time.
And if we add two new servers into the cluster, will "leader to follower raft's replication" and "client to server periodic synchronization(anti-entropy)" begin at the same time? will it cause inconsistency? will these two new servers be able to serve requests before they catch up?

**Comment by slackpad** [comment]
Hi @half-dead - the anti-entropy syncs will get routed through to the leader since they are writing to the data store, so if the newly-added servers handle an anti-entropy sync request from an agent they will just proxy it through.

For a read query, it would depend on the consistency mode selected in the request. (https://www.consul.io/docs/agent/http.html). For `default` or `consistent` you should generally be ok, but for `stale` you could definitely get back an inconsistent set of results as the server catches up.
