### ISSUE TITLE
Importance of persisting data on -data-dir

### ISSUE THREAD

**Issue by calvn** [hashicorp/consul#1254]
Ideally data on `-data-dir` is not all that important on a multi-tenant datacenter since nodes will automatically sync when they come back up, but I would assume that data would be unrecoverable if all node on the datacenter were gone at once (for example, someone accidentally terminates all server instances). 

So my question is, would persisting data in `-data-dir` buy us anything? If so, is there any reason why `/tmp/consul` was chosen as `-data-dir` on the docs (https://www.consul.io/intro/getting-started/agent.html)?

In the case of running consul on docker, for example, would it be recommended to mount `-data-dir` and/or `-config-dir`?

**Comment by highlyunavailable** [comment]
Any API-registered services and checks also get their configuration written into `data-dir` for persistence between agent restarts, so their configuration would be lost if this directory was lost between Consul restarts. This doesn't apply to services/checks created in the static configuration JSON files of course.

**Comment by cleung2010** [comment]
@highlyunavailable What would be the recommendation for persisting that data, and in the case of a cluster outrage what would be the recovery process? Would it be pointing the new server nodes' `-data-dir` to the old data directory that was backed up in one way or another (e.g. a persistent volume that was mounted to the old instance)?

**Comment by highlyunavailable** [comment]
I can't give any official recommendation but I would _not_ point a new server to an old server's data directory - the Raft log and peers list is in there, and the peers list contains server IPs so unless your new server is always at the exact same IP as the old server, Consul probably would not start or would cause some oddities without manually editing the peers.json file. In the vast majority of cases you do not want to persist your data-dir. When I ran a consul cluster I only persisted it at the machine level - that is, it lived in /var/lib/consul and would survive reboots but not removal of the machine.

**Comment by cleung2010** [comment]
@slackpad I brought this issue up to you during Hashiconf. Would love to hear your recommendation on this.

**Comment by djenriquez** [comment]
Interesting topic. We are currently backing up our dockerized Consul servers using [Convoy](https://github.com/rancher/convoy), but it appears that this will cause issues if we were to restore this data onto a new Consul server on a machine with a different IP address, as @highlyunavailable noted. We followed this as recommened by @armon in this [Google Group topic](https://groups.google.com/forum/#!msg/consul-tool/cbe_W_SClog/u3PhFlDlyaAJ).

We know that [Consulate](https://github.com/gmr/consulate) exists, but we are striving for a service-agnostic back up solution, which is why we settled with Convoy. 

Our main goal was to backup the K/V store. Is there a subdirectory we should be backing up instead of the `/data/` directory in its entirety?

**Comment by cleung2010** [comment]
@djenriquez Thanks for the link on that GG topic. We also use consul-replicate, but only clone out a specific subset of the KV's for each datacenter. 

So far all the KV data that we use is populated by [git2consul](https://github.com/Cimpress-MCP/git2consul) so there is no issue with repopulating that to an entire new cluster. 

We also wrote [consul-migrate](https://github.com/Cimpress-MCP/consul-migrate) for exporting and importing ACLs, and used it when we transferred `acl_datacenter` from one DC to another. That gem is not quite polished, but it got the job done.

**Comment by slackpad** [comment]
Sorry for the late reply on this one. The snapshots contained in the data-dir should be useful for providing you a good state checkpoint in the event of a disaster, but as @highlyunavailable noted, the peers list would probably need surgery and there's no consistency guarantees for the Raft log post-snapshot, so that data could be lost (if it was corrupted you'd probably have to delete it and/or zero it out). Also, the frequency of snapshots is hard to control so it's hard to control the amount of data that's exposed.

We are going to look into adding a new snapshot API and/or CLI that would let you kick out a snapshot so you could have a known restore point. The Raft log post-snapshot would always be at risk, but at least you could control when the snapshot occurs.

Not sure which release this would be targeted for, but will update this ticket once it's slotted on the roadmap.

**Comment by slackpad** [comment]
Wanted to drop a link to https://github.com/leprechau/consul-backinator on here as another possible solution for KV backups.

**Comment by leprechau** [comment]
Thank you, I've moved backinator to a slightly different place on github and made some small improvements to it's command line handling using the hashi cli structure.  New location below and please let me know how it works and/or you have any suggestions for improvement.

https://github.com/myENA/consul-backinator

**Comment by slackpad** [comment]
Closing this out now that 0.7.1 is released, which adds new [snapshot API](https://www.consul.io/docs/agent/http/snapshot.html) and [snapshot CLI](https://www.consul.io/docs/commands/snapshot.html) for disaster recovery.
