### ISSUE TITLE
Document which APIs a node will disappear from when put in maintenance mode

### ISSUE THREAD

**Issue by dellis23** [hashicorp/consul#1257]
The docs say this about maintenance mode:

> In this mode of operation [maintenance mode], the service or node will not appear in DNS query results, or API results.

Every query I am running in the API is still showing the node that's in maintenance mode, from `/v1/health` to `/v1/catalog/nodes`.  This makes it unclear as to how maintenance mode should be used in an application that's consuming consul information.  For instance, if I have a service on a node which is in maintenance mode, do I need to query for all healthy services and then iterate through the list of nodes and verify they do not have the `_node_maintenance` check present?

**Comment by highlyunavailable** [comment]
Putting a node or service instance into "maintenance mode" just makes a check that is unhealthy with a special name, so as a consumer all you have to do is only use "healthy" service instances/nodes, which is what you normally would do anyway. DNS only returns healthy service instances anyway.

If you want to find a list of nodes that are in maintenance mode, you would have to iterate over the full list of unhealthy services/nodes, though.

I agree though that "or API results." is particularly confusing since the API can be asked to return unhealthy instances as well.

**Comment by dellis23** [comment]
So any checks for available `foo` services also have to check for whether `_service_maintenance:foo` is defined and critical as well as whether `_node_maintenance` for the host is not defined and not `critical`?  That doesn't seem ideal, but I guess that's beyond the scope of this issue.  At the very least, some explanation of how maintenance mode is intended to be used would be good for the docs.

**Comment by slackpad** [comment]
Agree the docs are a little confusing on this one.

**Comment by i0rek** [comment]
We have better docs now https://www.consul.io/docs/commands/maint.html: 

> The maint command provides control of service maintenance mode. Using the command, it is possible to mark a service provided by a node or all the services on the node as a whole as "under maintenance". In this mode of operation, the service will not appear in DNS query results, or API results. This effectively takes the service out of the pool of available "healthy" nodes of a service.
> Under the hood, maintenance mode is activated by registering a health check in critical status against a service, and deactivated by deregistering the health check.
