### ISSUE TITLE
Support ephemeral keys 

### ISSUE THREAD

**Issue by rfyiamcool** [hashicorp/consul#1259]
consul support ephemeral keys ,same as zookeeper ...

**Comment by highlyunavailable** [comment]
@rfyiamcool This is already supported. See the [session](https://consul.io/docs/internals/sessions.html) documentation. What you need to do is [create a Session](https://consul.io/docs/agent/http/session.html#session_create) with the `delete` behavior and [acquire](https://consul.io/docs/agent/http/kv.html) the key with it, then when the Session expires or is destroyed the key will be deleted. One caveat: If you release the key, then destroy the session, the key will _not_ be deleted because the session is no longer associated with the key.

This also means that you can create one session, associate it with multiple keys, then when the single session is deleted, all the keys associated with it will be deleted.

**Comment by rfyiamcool** [comment]
Thanks U !
