### ISSUE TITLE
force-leave across datacenters

### ISSUE THREAD

**Issue by omribahumi** [hashicorp/consul#1264]
I couldn't any reference to this in the docs. If I understand correctly, force-leave can only happen in the same DC.

Is that correct?

**Comment by highlyunavailable** [comment]
If you want to get technical about it, force-leave can only happen from the same serf pool, so to force-leave from a LAN pool you would have to be in the same datacenter, since datacenter is what determines membership in the pool. This means force-leave from the WAN pool could happen from any WAN pool member but it wouldn't affect the LAN pool.

**Comment by omribahumi** [comment]
@highlyunavailable I think we should improve the documentation for `force-leave` then

**Comment by v6** [comment]
// , I think you should point out the possible failure modes resulting from this confusion, at least for those of us who aren't as familiar with Consul's WAN features. I think I may have found a bug.
