### ISSUE TITLE
Fix race conditions in tests

### ISSUE THREAD

**Issue by tiwilliam** [hashicorp/consul#131]
There are certainly several reasons for this, but tests are constantly failing on Travis CI and sometimes on my local machine.

**Comment by discordianfish** [comment]
How did you came up with those numbers? I'm spinning up new consul clusters pretty often these days because I like to depend on it heavily in the future but it *seems* to me like there are quite some race conditions when deploying (eg. #841). Now I saw this ticket and wondering: Maybe the timings in the tests just workaround race conditions that happen in real deployments as well?

**Comment by tiwilliam** [comment]
@discordianfish Which numbers are you referring to? We switched to a solution where we just wait for the leader until it is elected and use a timeout for failure. That replaced using estimated sleeps in tests.

**Comment by discordianfish** [comment]
Okay I see. I'll still experience some weird issues which look like race conditions in cluster bootstrapping. But will dig deeper and let you know (although the tests don't pass for me on my ubuntu 14.04 laptop, might open another issue for that one).
