### ISSUE TITLE
ACL is not not enforced by the agent

### ISSUE THREAD

**Issue by ManojaMishra** [hashicorp/consul#1313]
I have a consul server cluster with 3 nodes and one consul client agent
Consul version: Consul v0.5.2

Th servers agents are configured with the following config snippent

{
"datacenter": "dc1",
  "acl_datacenter": "dc1",
  "acl_master_token": "8fa14cdd754f91cc6554c9e71929cce7",
  "acl_default_policy": "deny",
}

The client Agent is configured like.
{
 "acl_datacenter": "dc1",
  "acl_default_policy": "deny",
}

I tried to register a service without any token

curl -i -v -X PUT -d @register_service.json  http://localhost:8500/v1/agent/service/register

the response from the agent is : 200 OK succes

but the client agent logs the below message
2015/10/16 17:30:19 [WARN] agent: Service '8888' registration blocked by ACLs

When I checked in the UI from the server, the service is not registered but the service is registered in the client agent

Executed on client agent: (the serviceA returned)
curl http://localhost:8500/v1/agent/services
{"8888":{"ID":"8888","Service":"serviceA","Tags":null,"Address":"10.10.10.2","Port":8083}}

On server agent: (no services returned)
curl http://localhost:9500/v1/catalog/services
{"consul":[]}

I am wandering if the service can not be registered in the server catalog, then why the client agent is registering it successfully and returning the 200 OK success response?

Please let me know if I am missing some config setting or is it the intended behavior.  I have a use case if my service cant not be registered successfully then the service should not run.

Thanks,
Manoja

**Comment by ryanuber** [comment]
Hey @ManojaMishra,

What you are seeing is the expected behavior currently. Registrations to the agent don't validate the ACL with the servers, the ACL is only validated when trying to sync services from the agent to the central catalog. I can see how it would be useful to do the validation up-front, and there are also cases where allowing the service to register on the agent without validation could be desirable (for example, to allow the agents to continue functioning even in the face of temporary server failures).

We've thought about this a bit before, and I think the right answer is going to be to add an additional configuration flag on the agents that would toggle this behavior, like a `force_check_token` flag, so that either case can be handled.

Thanks for reporting this! Going to mark it as an enhancement for now. Thanks!

**Comment by rytutis** [comment]
Hi, probably related. Found I can deregister any service with anonymous token if I go directly to agent. Agent ACL checks would make sense.
