### ISSUE TITLE
can't deregister service-id that contains slashes

### ISSUE THREAD

**Issue by pmbauer** [hashicorp/consul#1333]
We are using registrator and made the mistake of using a `/namespace/deploy-area/logical-name` pattern for our service ids and are trying to clean up.
`v1/agent/service/deregister/<service-id>` fails if `service-id` contains slashes. (see https://github.com/hashicorp/consul/issues/1096)
We've tried deregistering with `v1/catalog/deregsiter` but within 2 minutes, that service re-appears in the catalog.
Is there a way around this?

**Comment by ccl0326** [comment]
I have the same problem.The service can be removed.any idea?

**Comment by slackpad** [comment]
Yeah the catalog will get synced with the agent's state so that can't be used to remove it. If you registered the service via the agent API then I think it will be persisted in a json file inside the services directory of your agent's data-dir. If you delete it from there and restart the agent it should be gone (the agent will remove it from the catalog for you).

**Comment by josegonzalez** [comment]
@slackpad can confirm, removing everything from `/var/lib/consul/` seemed to fix a service that was registered by registrator. We ran registrator against the local consul-agent, so I'm assuming moving it to hit the consul-cluster instead may fix the issue...

**Comment by slackpad** [comment]
I'll close this since the slash issue is covered under #1096. Please let me know if you run into any other problems!
