### ISSUE TITLE
getKVValue 

### ISSUE THREAD

**Issue by hepengfei-ml** [hashicorp/consul#13396]
I want to get the key value in the consul by java .here is my code
           ConsulClient client=new ConsulClient("127.0.0.1",8500);
            System.out.println(client.getKVValue("feature").getValue().getValue());  
The result of this is   "aGVsbG8gd29yZA=="
But the key value I saved is "hello word"

**Comment by jkirschner-hashicorp** [comment]
Hi @hepengfei-ml,

The Consul HTTP API's KV Read endpoint returns the value in base-64 encoded format: https://www.consul.io/api-docs/kv#value.

After base-64 decoding `aGVsbG8gd29yZA==`, you receive `hello world`.

Which Java library are you using? Does it provide a means to base-64 decode the value for you? Perhaps something like [getDecodedValue()](https://www.javadoc.io/static/com.ecwid.consul/consul-api/1.2.5/com/ecwid/consul/v1/kv/model/GetValue.html#getDecodedValue()) instead of getValue()?

**Comment by jkirschner-hashicorp** [comment]
No problem :) thanks for reaching out, and welcome to the Consul community!
