### ISSUE TITLE
SSL/TLS vulnerabilities - POODLE and RC4

### ISSUE THREAD

**Issue by ajohnson1** [hashicorp/consul#1349]
I'm using Consul with https, but security scans of the machines are then failing as Consul offers SSLv3 on port 8501 which is vulnerable to the POODLE attack. Also RC4 ciphers are offered which have vulnerabilities.
Is there a way to configure Consul to use more up to date TLS and ciphers?

**Comment by macb** [comment]
It would appear that TLS/SSL in `consul` uses the default Golang setting which accepts a minimum version of SSLv3 for go1.4 or lower (with a max up to tls 1.2). go1.5 [changed the minimum to TLS 1.0](https://golang.org/doc/go1.5).

Relevant code in `consul` is [here](https://github.com/hashicorp/consul/blob/master/command/agent/http.go#L62-L65) and [here](https://github.com/hashicorp/consul/blob/master/tlsutil/config.go#L245-L281) and the [stdlib](https://golang.org/pkg/crypto/tls/#Config) explains the default (though for go1.5 which is TLS 1.0).

It seems like `0.6` will be built against `go1.5.1+` which mean all TLS servers will get bumped to TLS 1.0 at a minimum. I'm not aware of Golang's TLS 1.0 implementation being vulnerable to POODLE. So that seems like a reasonable default.

**Comment by ajohnson1** [comment]
Thanks - I'll look forward to 0.6 and try recompiling Consul 0.5.2 under go1.5.1

**Comment by slackpad** [comment]
Closing this since we've now updated Go.

**Comment by iammyr** [comment]
I've searched through the code for information on the supported cipher suites. I found AES-GCM 128, using PKCS7 padding and AES-GCM 128, no padding mentioned at https://github.com/hashicorp/consul/blob/6f0a3b9bf5c7fd0673213d451bbc9e66f7a9cad9/vendor/github.com/hashicorp/memberlist/security.go . Could you kindly confirm please that those are the ciphers specified by Consul for the TLS configuration that Golang needs to be fed with? Thanks a lot in advance
