### ISSUE TITLE
How to programmatically rotate encryption keys?

### ISSUE THREAD

**Issue by rosenhouse** [hashicorp/consul#1368]
Hello,

We'd like to write some Go code that rotates the encryption keys used by our Consul cluster.  We don't see a way to do this via the HTTP API or the Go `api` package and we'd like to avoid shelling out to the consul CLI `keyring` command.  We've considered reaching into the [`RPCClient` in the `command` package](https://github.com/hashicorp/consul/blob/master/command/rpc.go) used by the CLI, but are concerned about taking a dependency on something that isn't supported for public consumption.

What is the recommended way to programmatically rotate encryption keys?

Thanks!

cc @zaksoup

**Comment by highlyunavailable** [comment]
The RPC client is a public interface though:

https://consul.io/docs/agent/rpc.html

There's nothing explicitly "internal" about it other than the key ring commands aren't documented on that page.

**Comment by rosenhouse** [comment]
Great, thank you.

**Comment by zaksoup** [comment]
@highlyunavailable We're attempting to create fakes in order to unit test consumers of the `agent.RPCClient`. The problem we have now run into is that `agent.RPCClient.InstallKey()` returns a `keyringResponse` which is unexported. It seems like significant portions of the `RPCClient` (really, any of the various methods around keys) are actually unexported and therefor not necessarily suitable for 3rd party use.

**Comment by rosenhouse** [comment]
Appears to be addressed by https://github.com/hashicorp/consul/issues/1867#issuecomment-293511044
