### ISSUE TITLE
Adding a Datacenter, but only in the UI

### ISSUE THREAD

**Issue by kvz** [hashicorp/consul#1373]
Hi,

We're running Consul in several datacenters. So far we have no ties between datacenters whatsoever, and we'd like to keep it that way (even though it's a really cool Consul feature, we'd need to poke all kinds of holes in our infra to make use of it's multi-datacenter awareness, and we currently don't have much purpose for it)

We're also are happy users of the Consul Web UI, and were wondering if a hack were possible that it would still offer links to our other datacenters?

Our datacenters won't change much, so if I could just provide a mapping with names & URLs, I would be able to hop between datacenters conveniently without really tying them together in any way. I think the AWS Console works in a similar fashion, where datacenters have no knowledge of eachother, and the web UI just hardcodes a few links to the different regions.

![](https://dl.dropboxusercontent.com/s/uwe4w4d4vwt9wj7/2015-10-30%20at%2015.45.png?dl=0)

![](https://dl.dropboxusercontent.com/s/t138kd9hsx2tcmr/2015-10-30%20at%2015.52.png?dl=0)

**Comment by ryanuber** [comment]
Hey @kvz,

This might be possible by modifying the source of the UI in the `ui/` directory of the source tree. I don't know exactly where the insertion point would be, but that is definitely possible. Another option would be to just have like a general "datacenters" dashboard with hard-coded links to each one. Not quite as elegant-looking, but gives the same basic effect.

We don't have any plans on making this an officially-supported thing since it could cause confusion in the more general sense, so I'm going to close this out. Please let me know if you have any other questions though!
