### ISSUE TITLE
Prune expired intermediate CA certs from stored roots

### ISSUE THREAD

**Issue by kyhavlov** [hashicorp/consul#14159]
Consul currently doesn't remove expired intermediates from the stored root CA struct - it only ever appends new ones:
- https://github.com/hashicorp/consul/blob/201d1458c307e9b04fe3d6f22a2ad9d6d1358bdd/agent/consul/leader_connect_ca.go#L538
- https://github.com/hashicorp/consul/blob/201d1458c307e9b04fe3d6f22a2ad9d6d1358bdd/agent/consul/leader_connect_ca.go#L1101

This is currently only handled when a root rotation happens, because the old list of intermediates will get left behind, but when the intermediate cert TTL is significantly lower than the root's, it's possible to have many intermediate certs build up in the list. This can cause long certificate chains to be sent to Envoy proxies, which in turn can cause the TLS handshake to fail due to too many certs in the chain. We should add some logic to prune old expired intermediate certs from the list when a new one is appended, to prevent them from building up indefinitely.

**Comment by pratheekrebala** [comment]
We're hit somewhat regularly by this problem since we're using a very low TTL on the intermediate certificates along with spot instances. This problem is further exacerbated by the fact that calls to `/connect/ca/roots` often return the same intermediate many times. This second issue might be related to https://github.com/hashicorp/consul/issues/7018.

In the logs, the error message looks like this:

`2022-08-23T16:00:15.123Z [ERROR] agent.server.rpc: failed to read byte: conn=from=[redacted]:53625 error="tls: handshake message of length 77050 bytes exceeds maximum of 65536 bytes"`
