### ISSUE TITLE
Web UI counts serfHealth many times

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#1484]
In the "Services" view of the web UI, there is an integer total of the number of checks passing. It seems that this number re-counts the node-level checks for each service instance, causing the number to inflate curiously in cases like Docker where the same host may register multiple times with the same service.

This was reported in a Nomad issue, hashicorp/nomad#551.

**Comment by tymofii-polekhin** [comment]
@ryanuber it seems to me that if you don't specify `service` name in check, it will understand it as node-level check and apply to every service on that node. i got `docker` service says `passing 24` because it counts `docker` service itself + `serfHealth` + my own `dnsmasq` check, that doesn't have a `service` defined in the configuration. Am i getting it right?

**Comment by ryanuber** [comment]
@tymofii-polekhin yep exactly, that sounds like the exact symptom.

**Comment by mshean** [comment]
I'm experiencing the same problem. Every service has serfHealth listed under it.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
