### ISSUE TITLE
Session is not destroyed when restarting consul in single-node mode

### ISSUE THREAD

**Issue by omgold** [hashicorp/consul#1485]
I found something about sessions, that strikes me odd. I'm running consul in single-node mode and acquire a session without TTL, but with selfHealth enabled. When I then shutdown the consul server/agent for a while and restart it, the session is still there.

Is that supposed to be that way? To me it is quite unexpected, as I guess the session would be destroyed when running multiple consul servers, no?

**Comment by slackpad** [comment]
Hi @omgold this is the expected behavior with just a single node. The graceful restart means that the single node never sees itself as unhealthy so it just snapshots its data with the session intact and then restores it, which is also when the node is healthy. If you had 3 servers, one of the other two would have taken over as the leader and then destroyed the session.
