### ISSUE TITLE
Watch services vs long poll on /services behave differently

### ISSUE THREAD

**Issue by autoric** [hashicorp/consul#1498]
Version 0.5.2

I am observing different behavior between setting a consul watch on "services", and using the http api to perform block queries against the /services endpoint. Specifically, I am seeing:

 - A new service enters - both fire
 - A new instance of an existing service enters - block query fires, watch does not
 - A service health changes - block query fires, watch does not

It appears the the http api's blocking queries will fire a change when there is any change to a service, even though the body of the response does not change (for my use case, that's a good thing).

I understand that under the covers watches are implemented against the http api, but I assume that watches are somehow caching and doing an equality comparison.

Is this difference intentional? Can I rely on the behavior?

Generally speaking, for the purposes of service discovery, rp, load balancing, etc, I am interested in any change in any of my services. I want that use case to be as easy as possible to achieve, and a single blocking query against the /services endpoint appears to give that to me. But I don't want to implement against unintended behavior.

**Comment by slackpad** [comment]
Hi @autoric this is intentional. The watch does a check to make sure that the thing it is watching has indeed changed before it fires the handler:

https://github.com/hashicorp/consul/blob/master/watch/plan.go#L85-L87

In your case if you want to know if _any_ service has changed then making a blocking query to https://www.consul.io/docs/agent/http/catalog.html#catalog_services is the right way to go.

**Comment by autoric** [comment]
@slackpad Thanks for the info and link to code. I appreciate the response.

I'll implement using my own watcher process and blocking queries.
