### ISSUE TITLE
Changing from auto bootstrap to manual breaks leader election

### ISSUE THREAD

**Issue by raitech** [hashicorp/consul#1501]
I was doing some tests with three Consul servers, on 0.6.0. All three servers had

"bootstrap_expect": 3

in their configs. But I needed to test the environment with only one server. So, I changed the only server now to have

"bootstrap": true

When I restarted it, the server just did not grab the leadership. I had to remove /var/consul/raft directory to make it work.

Thank you for your attention! :)
Raimundo Santos

**Comment by slackpad** [comment]
Hi @raitech this is the expected behavior if the servers are shutdown but they don't leave the cluster, so the Raft layer thinks there should be three servers but only one is available so it can't elect a leader. If you have the servers gracefully leave, or update your peers.json file to remove the failed servers then it should work (removing the Raft directory also works since the peers.json file is in there).

This issue has some more context - https://github.com/hashicorp/consul/issues/750.
