### ISSUE TITLE
Please print logging about the domain the DNS is handling queries for.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul#1528]
We just spent a couple of hours chasing down an issue with DNS resolution on Consul clients, to realize later on that we were missing the custom domain configuration on them. If logging would have printed out that information upon agent startup, it would have taken minutes instead to find the culprit.

**Comment by slackpad** [comment]
Hi @c4milo sorry about the confusion on this one. I took a look through the DNS mux code and it doesn't look like it exposes a way to hook the default "failed" handler - it's all handled by the library and Consul doesn't see it. That's why there's no debug log output for this case. We can summarize that part of the config at startup though, along with the port information most likely.

**Comment by c4milo** [comment]
It's ok, having the information logged upon startup will do it. Thanks for looking into this @slackpad!

**Comment by slackpad** [comment]
Hi, this never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves.
