### ISSUE TITLE
How best to comply with RFC3274

### ISSUE THREAD

**Issue by johntdyer** [hashicorp/consul#1565]
I am trying to create a service which will allow me to have service names which comply with [RFC3263](https://tools.ietf.org/html/rfc3263).   Ideally my service would be discoverable with something like the following DNS query:

``` bash
dig @127.0.0.1 -p 8600 _sip._udp.ppid410.service.consul. SRV
```

To start with I tried the following config:

``` json
{
  "service": {
    "tags": [
      "_sip._udp"
    ],
    "port": 5061,
    "name": "ppid410"
  }
}
```

and this did work, eg my dig returned the correct service, I did notice the following error my logs:

``` log
Jan  5 13:15:33 rt2 consul[10806]: Service tag "_sip._udp" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
Jan  5 13:15:33 rt2 consul[10806]: Service tag "_sip._udp" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
```

This concerned me and so I tried changing the name of my service from {{ppid410}} to {{_udp.ppid410}} to see if I could stop the warning.  In doing so my config changed to the following:

``` json
{
  "service": {
    "tags": [
      "sip"
    ],
    "port": 5061,
    "name": "_udp.ppid410"
  }
}
```

and the dig still worked after this change but the error still persisted:

``` shell
Jan  5 14:54:40 rt2 consul[27024]: Service name "_udp.ppid410" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
Jan  5 14:54:40 rt2 consul[27024]: Service name "_udp.ppid445" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
```

So while my use case technically works in Consul today I am concerned that it may not in the future since the authors seem to feel I am doing something wrong.   In my case I am handcuffed by the RFC for the syntax here so I am hoping Consul's creators and/or community can help me get this working in a manner that won't break in 0.7.0 or 0.6.1 :smirk: :pray: .  

Thank you very much for your help in advance! 

-John

**Comment by slackpad** [comment]
Hi @johntdyer is Consul's support for RFC 2782 close enough to support your use case? Please take a look at https://www.consul.io/docs/agent/dns.html and look for the "RFC 2782 Lookup" section. For that you'd just use "udp" as the tag and then you could look up `_ppid410._udp.service.consul`. Not sure if you need another layer for "_sip" in there though, because that's not currently supported with Consul's RFC 2782 support.

**Comment by johntdyer** [comment]
@slackpad  in my case the service is __\_sip__, the protocol is __\_udp__ and we use the subdomain to classify the cluster ( __ppid410__ ).  Unfortunately in my use case I do need __\_sip__ or __\_sips__ ( for tls) to be there in addition to the protocol ( __\_tcp__ / __\_udp__ ).

**Comment by johntdyer** [comment]
@slackpad - Its worth mentioning that this is technically working today.... 

```shell
dig @127.0.0.1 -p 8600 _sip._udp.ppid410.service.consul. SRV

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.37.rc1.el6_7.5 <<>> @127.0.0.1 -p 8600 _sip._udp.ppid410.service.consul. SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20641
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;_sip._udp.ppid410.service.consul. IN	SRV

;; ANSWER SECTION:
_sip._udp.ppid410.service.consul. 0 IN	SRV	1 1 5061 rt1.node.wdc01.consul.

;; ADDITIONAL SECTION:
rt1.node.wdc01.consul. 0 IN A 10.108.198.90

;; Query time: 1 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Tue Jan  5 21:02:39 2016
;; MSG SIZE  rcvd: 202
```

**Comment by johntdyer** [comment]
@slackpad  any thoughts ?

**Comment by slackpad** [comment]
@johntdyer it's unlikely that we'd change the existing DNS behavior to break you, but if you want to be better insulated against future changes and avoid the warning message you could register a prepared query to handle this (https://www.consul.io/docs/agent/http/query.html). You could set the name to `_sip._udp.ppid410` and then set up the query to perform whatever service selection you want, and the DNS name becomes `_sip._udp.ppid410.query.consul`. Prepared queries don't encode any functionality into the name so they are less picky about the formatting, and it's not likely at all we'd change that because prepared queries have all their behavior defined in the query definition itself.

**Comment by slackpad** [comment]
Closing this out - it looks like there's no forward work on this one.
