### ISSUE TITLE
Consul Client default Admin Partition

### ISSUE THREAD

**Issue by Esity** [hashicorp/consul#15881]
If a Consul client only has access to a single admin partition then it should be assumed all nodes, services, kv, etc are related to that admin partition. In the current state, the admin partition has to be specified which is cumbersome and could be easier. 

Another option is to add a default admin partition config entry for all related services/nodes/checks/etc. 
Keep in mind this is different from specifying the admin partition for the Consul client. 

Example
node == foobar, admin-partition == hashi
If you want to export a service like
```
service {
  name = "wordpress"
  port = 9003
}
```
But in this scenario, it will try to create the service inside the default partition so you have to add `partition = "hashi"` but with this default config, we could make it easier for users of admin partitions. This could also be applied to namespaces

**Comment by jkirschner-hashicorp** [comment]
Hi @Esity,

It sounds like there's a usability challenge you're experiencing that important to improve*, but I'd like to make sure I understand the scenario correctly.

Are we referring to a scenario where you have the following?
- A Consul client agent (node `foobar`) in the admin partition `hashi`
- You are executing Consul CLI/HTTP API calls and config file loads against that client agent

And is your desired behavior that if an operation is acting on a partitioned resource (node, service, KV), that the operation uses the partition of the Consul client agent receiving the operation (node `foobar` in partition `hashi`) if no partition is explicitly specified? My understanding is that the `default` partition is currently always assumed unless otherwise specified... so your service definition file would put the `wordpress` service in the `default` partition even if loaded by node `foobar`.

* The Consul team will need to carefully think through potential backwards compatibility implications if we consider making a change based on this conversation

**Comment by huikang** [comment]
@jkirschner-hashicorp , what @Esity suggests sounds reasonable. Since a client agent can only be in one admin-partition: in the above example, the agent is in `hashi` partition. Then all API requests to a partitioned resource against this client agent should be defaulted to `hashi` partition. The API will fail if it uses a different partition.

If the API request is to a server, it is still safe to assume the request is for the default partition.

**Comment by jkirschner-hashicorp** [comment]
> If the API request is to a server, it is still safe to assume the request is for the default partition.
Unless the partition is otherwise specified in the request. This is already the current behavior.

**Comment by Esity** [comment]
@huikang Exactly

Example, RabbitMQ can integrate directly with Consul for clustering services which we use. 
https://www.rabbitmq.com/cluster-formation.html#peer-discovery-consul

But it doesn't support this admin partition functionality natively. If we had this default partition logic, then the people moving from OSS Consul to Enterprise, it is a drop in replacement instead of a reconfigure on both the RMQ and Consul side

Another example, Percona Postgres Cluster with Patroni and Consul
https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#consul

**Comment by huikang** [comment]
@Esity @jkirschner-hashicorp , I made some change to the internal consul repo, so keep this issue open for now.

**Comment by Esity** [comment]
It worked perfectly. Thank you for prioritizing this one
