### ISSUE TITLE
PreparedQuery Delete API is a "Query" rather than a "Write"

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#1591]
Is there any specific reason the PreparedQuery create API is a POST when every other API in Consul uses PUT for create/update (including the prepared query update API)?

Just something I discovered when adding this for the C# API and wondered about.

**Comment by highlyunavailable** [comment]
Also, the PreparedQuery Delete API is a "Query" rather than a "Write": https://github.com/hashicorp/consul/blob/master/api/prepared_query.go#L149 (compared to KV: https://github.com/hashicorp/consul/blob/master/api/kv.go#L199)

**Comment by slackpad** [comment]
Hi @highlyunavailable since this was a totally new API we wanted to be more REST-y, similar to the KV store, but we decided to separate out the create from the update operation since the ID is always generated by the Consul and never passed in when the query is created. It definitely could have been a PUT, but was sort of a style choice.

The API options thing is a bug, thanks for finding that!

**Comment by highlyunavailable** [comment]
Okay, fair enough. It wasn't a big deal, I just wondered because it was different. Thanks!

I edited the title of the issue to be the actual bug.
