### ISSUE TITLE
Feature request: Cache results of service nodes when stale read is allowed

### ISSUE THREAD

**Issue by tesseract2048** [hashicorp/consul#1604]

**Comment by hesamg** [comment]
This will be very useful feature.  We have an issue where we reboot a node (not the leader) within the cluster, and we don't get any DNS response for a few seconds.  We have turned on allow_stale, but that does not solve this issue.

**Comment by slackpad** [comment]
There's a lot of complexity adding a full cache capability that should be handled by other DNS tools. I'm going to close this in favor of fixing the root cause of the outage (see https://github.com/hashicorp/consul/issues/1554#issuecomment-178338209). If that isn't sufficient we can open this one again.
