### ISSUE TITLE
ulimit properties for Consul

### ISSUE THREAD

**Issue by st-isidore-de-seville** [hashicorp/consul#1628]
Are there any recommended ulimit settings for Consul?

**Comment by slackpad** [comment]
Hi @st-isidore-de-seville I'll tag this as docs since we should add a note about it.

For a Consul client agent there should be a fairly small number of open file descriptors. The gossip layers will perform transient connections with a few other nodes, each connection to the client agent (such as for a blocking query) will open a connection, and there will be connections to usually one of the Consul servers. There are small extra things like your watch handlers, health checks, log files, etc.

For a Consul server agent, in addition to the above, you should plan on an incoming connection from each node in the cluster. This shouldn't be the common case, you would get 1/(number of servers), but in the worst case if there was some problem with the other servers you'd expect the other client agents to all connect to a single server.

**Comment by st-isidore-de-seville** [comment]
Thank you for the response!

**Comment by st-isidore-de-seville** [comment]
Actually I probably should not have closed the issue since you have tagged it.  I will let you have the pleasure :smile:
