### ISSUE TITLE
Misleading part of the documentation (consul.io -> http api)

### ISSUE THREAD

**Issue by doertedev** [hashicorp/consul#1646]
OHAI.

2 DCs, many nodes. I have certain ways of having a server find out about nodes in a different Datacenter, but on the agents that do not run in server mode?

Documentation says:

## /v1/catalog/nodes

This endpoint is hit with a GET and returns the nodes registered in a given DC. By default, the datacenter of the agent is queried; however, the dc can be provided using the "?dc=" query parameter.

Adding the optional "?near=" parameter with a node name will sort the node list in ascending order based on the estimated round trip time from that node. Passing "?near=_agent" will use the agent's node for the sort.

.. I thought that'd be possible from a node's perspective. But then `consul members -wan` also told me that the agent needs to run in server mode in order to do so.

Are there other ways for a node to access informations about informations from a different datacenter?

**Comment by highlyunavailable** [comment]
This is because servers can participate in the WAN pool but agents never do. Also, `consul members -wan` only shows members of the WAN pool (that is, all servers in the WAN pool) but no agents since they can't be in the WAN pool, so this is not a complete list of nodes.

Can you let us know exactly what you're trying to do? The reason I ask is because there are much more efficient ways to do certain things - e.g. if you're trying to find a way to get all nodes in all datacenters of a particular service, there is a better way (prepared queries) than trying to list all nodes in all datacenters (the method I have written below).

You could combine 2 calls to get all nodes in all datacenters:
First, call [datacenters](https://www.consul.io/docs/agent/http/catalog.html#catalog_datacenters), which returns the list of all datacenters in the Consul topology (basically asks the server for the datacenters in the WAN pool).

Then, call [nodes](https://www.consul.io/docs/agent/http/catalog.html#catalog_nodes) as you pasted above with `?dc=<datacenter>` where <datacenter> is each one (foreach) of the datacenters you got from the previous query.

**Comment by doertedev** [comment]
Hey. Thanks for the response.

During node provisioning Ansible gathers facts about the instance it works on. Right now I persist all of it into the K/V store as json. Why? Because I do not know yet what pieces I will require in order to have a node correctly work during its lifetime and rerunning ansible sounds wrong. 
The first step (in ansible) is ofc to have a "dynamic inventory" (meaning a extended list of IPs with some metainformations mixed within) as a huge JSON string. At the beginning you use the EC2 python script that gathers all informations via the EC2 Api. Then you hit the EC2 API limit. Installed consul across the fleet, threw the gathered facts into the k/v store. Hacked a piece of python bäm done. 
The second part is for other nodes (that are neither server nodes nor have ansible installed) to receive IPs for services running in other datacenters (e.g. when you run certain services only in another DC). Why? Think of security groups. When I set up two datacenters in ec2 and I create security groups for consul (wan and lan) I need to interconnect the datacenters. In order to allow the other DC's consul IPs inbound I need their IPs. The node that does that, and is able to see Machines and k/v entries of other DCs, if I haven't overseen something, needs to be a consul server. Right?

Now that is just one example. E.g. my hubot has a script that queries informations from Consul. E.g. "give me all IPs running $service". Across datacenters. Again: server?

The set of names of installed datacenters is very well queryable from non-servers. I checked both /v1/catalog/nodes(?dc=) and /v1/agent/members(?wan=) and for both I cannot seem to gather the informations I need from non-servers. Is there another way to reach my goal? Maybe I have just overseen the corresponding API endpoint :)

Thanks in advance.

**Comment by highlyunavailable** [comment]
It looks like you have 3 questions here. I'll try to address what I see, but: you can do everything from a consul agent that you can do from a consul server. A server is just an agent that participates in Raft and the WAN pool.

> Think of security groups. When I set up two datacenters in ec2 and I create security groups for consul (wan and lan) I need to interconnect the datacenters. In order to allow the other DC's consul IPs inbound I need their IPs. The node that does that, and is able to see Machines and k/v entries of other DCs, if I haven't overseen something, needs to be a consul server. Right

Yes, you need to allow the servers to communicate but the agents proxy through them. Let's say we have 10.1.0.1 and 10.2.0.1, both Consul servers. You need to allow them to communicate on the Serf WAN and RPC ports. However, you do not need to allow any agents to communicate directly with each other.

If you have an agent in DC1, let's say 10.1.0.5, and you do a query for a service (like your Hubot example), you can query the [catalog endpoint for a particular service](https://www.consul.io/docs/agent/http/catalog.html#catalog_service) which lists all instances of that service in your current DC. If you want to ask for another DC, you need to make a query to that specific datacenter, because the agent queries its local server which then proxies the request to the target datacenter. So if you do a query for service `foo` in `DC2`, the traffic flow is actually `local agent -> DC1 server -> DC2 server -> return result to DC1 server -> send data to local agent from DC1 server`.

None of this requires that you be on a Consul Server to do the query. However, due to the architecture of Consul, which is fairly "local DC centric", you need to do extra work to get to other DCs, in part because if this routing/proxy mechanism of "all traffic from agents first goes to a server in their local datacenter".

If you're trying to set up a way to query other datacenters for specific services, in sort of "fallback ordering" mechanism or "give me the closest alive instance of this service" mechanism, then you want to use Prepared Queries, which abstracts all this away for you into a simple DNS or HTTP API endpoint.

**Comment by doertedev** [comment]
Thanks again! I'll try to somehow solve this with Prepared Queries even though I just need a member list and the POST method requires a Service field. Maybe with a dummy service for all nodes.

**Comment by doertedev** [comment]
Just a quick question: I've set up a prepared statement to query for a service in eu-west-1, which now can be queried on us-east-1 agent nodes via HTTP agent API.
Yet, I receive an internal IP:

```json
{
  "KnownLeader": true,
  "LastContact": 0,
  "Index": 0,
  "Failovers": 1,
  "Datacenter": "eu-west-1",
  "DNS": {
    "TTL": ""
  },
  "Nodes": [
    {
      "Checks": [
        {
          "ModifyIndex": 60260,
          "CreateIndex": 7906,
          "Node": "i-asdfasdf",
          "CheckID": "serfHealth",
          "Name": "Serf Health Status",
          "Status": "passing",
          "Notes": "",
          "Output": "Agent alive and reachable",
          "ServiceID": "",
          "ServiceName": ""
        }
      ],
      "Service": {
        "ModifyIndex": 64919,
        "CreateIndex": 64919,
        "EnableTagOverride": false,
        "Port": 8080,
        "Address": "127.0.0.1",
        "Tags": [
          "bla",
          "foo",
          "12polizei"
        ],
        "Service": "awesomesauce",
        "ID": "awesomesauce1456747988"
      },
      "Node": {
        "ModifyIndex": 82511,
        "CreateIndex": 7906,
        "Address": "172.31.10.76",
        "Node": "i-asdfasdf"
      }
    }
  ],
  "Service": "awesomesauce"
}
```

This resembles the `advertise_addr` from the consul config. How would I now receive an external IP for said node?

**Comment by doertedev** [comment]
I just made a workaround: writing the public IPs for agents into the k/v store. Is this the only way I can pull this off? Maybe a wan advertised IP would be a good idea, because eu-west-1-consul-1 might reach a node with the internal ip of an agent in us-east-1 that doesn't belong to me (well, not in amazon but in other setups it might be, depending on internal network setups).

**Comment by slackpad** [comment]
Hi @doertedev we have a feature coming out very soon that will let you use a node's configured WAN address (even for non-server nodes) when talking to that node from outside its datacenter - https://www.consul.io/docs/agent/options.html#translate_wan_addrs.

**Comment by doertedev** [comment]
Perfect! Awesome thanks @slackpad!
