### ISSUE TITLE
Still recommended to set GOMAXPROCS > 1?

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [hashicorp/consul#1679]
There is this [old thread on googlegroups](https://groups.google.com/forum/#!msg/consul-tool/qewFEqgAoF8/b9hxhmy1v6gJ) asking about why consul warns to set GOMAXPROCS > 1 on startup.  Then there's [a commit](https://github.com/hashicorp/consul/commit/a61d89d0e66c6698d4b166aa457bf020d5c383cc) which removes these warnings due to changes in Golang 1.5.  But what about machines with 1 core?  In this case is it necessary to manually set GOMAXPROCS to something else?  And if so, does it matter what, is `2` ok?

/cc @fraenkel

**Comment by highlyunavailable** [comment]
The only reason it needed to be set is in case cgo blocked a thread when talking to the data store (LMDB). Since Consul has moved to a pure Go data store (memory + snapshots to boltdb, if I recall correctly) `GOMAXPROCS` is fine to leave at 1 on 1-core machines. Basically, the only reason was cgo, and since cgo is no longer used, it is okay to leave gomaxprocs at the default, even if the default is 1 since Consul is pure Go now.

**Comment by slackpad** [comment]
That's correct - it should be fine to leave as-is for single core machines now that all the cgo stuff has been eliminated. This came in originally in https://github.com/hashicorp/consul/issues/10.

**Comment by Amit-PivotalLabs** [comment]
Perfect, thanks @highlyunavailable and @slackpad!

**Comment by fraenkel** [comment]
@Amit-PivotalLabs This is true for v0.6.0 or greater.

**Comment by Amit-PivotalLabs** [comment]
Thanks, noted.
