### ISSUE TITLE
make maxKVSize configurable

### ISSUE THREAD

**Issue by vrecan** [hashicorp/consul#1682]
We've decided to use consul as our main clustering technology for an internal platform we are building. We are running into one issue where we have use cases where we want to be able to insert larger then 512kb values into consul. We still want a limit like 5mb. What we are writing to consul is metadata about jobs that are being processed on the cluster but this can sometimes be large. This is not something being written frequently but does need to be written.

I am fine with doing the work to make it configurable, it looks like kvs_endpoint.go just needs to be able to get a config. 

As a side note not returning an error in this condition seems wrong as well and made it harder to diagnose:
```
	if req.ContentLength > maxKVSize {
		resp.WriteHeader(413)
		resp.Write([]byte(fmt.Sprintf("Value exceeds %d byte limit", maxKVSize)))
		return nil, nil
	}
```
EDIT: 
I see that its not loggin just writing it raw to the response. Still seems wrong that it doesn't return an error.
 the http client didn't know what to do with this and my app silently went along without knowing the write had failed.

**Comment by slackpad** [comment]
Hi @vrecan this is not something we really should support; Consul isn't designed to store large data blobs at all.

Having huge Raft log entries will trip a warning - https://github.com/hashicorp/consul/blob/eb27a02956e7e052c0bec6f96a0c0f7f6675f6a6/consul/rpc.go#L45-L47 because we've tried to keep the size capped for performance and throughput at the Raft layer.  Your best bet is to stick the data into another system and store a pointer to that in Consul. Another option is to chunk, similar to how `consul exec` does for command output.

**Comment by vrecan** [comment]
hmm that's unfortunate. Thanks.
