### ISSUE TITLE
Registering multiple service through one request

### ISSUE THREAD

**Issue by lym737** [hashicorp/consul#1683]
Hi,

I am trying to register multiple services to the consul atomically.
For example, if I want to register service with different ports (http, jmx, ajp).
Instead of sending three requests to consul, I want to register three services with each one of ports in single request so that either all three services are registered or none.

I used PUT request with JSON body. I was able to register single service with this body {"Name":"testService1", "Port" : 1234}.
But when I used JSON body with multiple services 
{
    "Services": [
        {"Name":"testService1", "Port" : 1234},
        {"Name":"testService2", "Port" : 1235}
    ]        
}
Consul is returning 400 (Missing service name) response.

Is there a specific format of JSON to register multiple services or is there other way to register multiple services through one request?

**Comment by sean-** [comment]
Hi @lym737 .  Right now you have to post one Service per API call.  In the future there might be a bulk register API, but the semantics around error handling become difficult (e.g. what do you do in a list of N services and service N-1 fails?).  Right now the semantics are clear and easy to understand, but it's something that has been considered in the past but never been fleshed out.

**Comment by ectogon** [comment]
@sean-  Is this still the case? This usage is documented here: https://www.consul.io/docs/agent/services.html

**Comment by xor-gate** [comment]
I did read through the doc and copy-pasted the example into a json file and PUT with curl. https://www.consul.io/docs/agent/services.html#multiple-service-definitions it also returns on consul v1.4.0: 

```
curl --verbose  --request PUT     --data @payload.json     http://127.0.0.1:8500/v1/agent/service/register
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> PUT /v1/agent/service/register HTTP/1.1
> Host: 127.0.0.1:8500
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 590
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 590 out of 590 bytes
< HTTP/1.1 400 Bad Request
< Vary: Accept-Encoding
< Date: Sat, 24 Nov 2018 22:13:39 GMT
< Content-Length: 20
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
Missing service name
```

**Comment by banks** [comment]
@xor-gate thanks, would you be able to open a new issue for that? The original one here was a request for a feature that now exists whereas your issue seems like a potential bug. In the new issue it would be great if you could include which versions you tried it on (e.g. is it a regression in 1.4.0?) do you have ACL enabled etc. (all the other things our bug report template will prompt for!).

Thanks!

**Comment by xor-gate** [comment]
Hi @banks I will investigate again. Probably I'm using the wrong endpoint and thought it was related to the original issue. I will file a new issue when I hit the problem again and able to reproduce.

**Comment by xor-gate** [comment]
To comment on my own comment, I was using the multiple service configuration from a file over HTTP API. Which of course would not work because you are unable to know which service could potential have an error. You have to submit one service per REST call. An because the first property of the map doesn't contain an `id` and `id` property as it says missing service name and the `services` property is simply ignored.
