### ISSUE TITLE
create / list events in the UI

### ISSUE THREAD

**Issue by lipanski** [hashicorp/consul#1722]
hello

I assume there is no way to create and/or list consul events in the UI at the moment (please correct me if I'm wrong), but is there any plan to enable this feature?

**Comment by slackpad** [comment]
Hi @lipanski this currently isn't supported and probably isn't something we'd add. Events in Consul are a pretty low-level mechanism, and are usually tied into some automation and not created manually (with the exception of `consul exec`, probably). Also, since they are managed at the gossip layer, displaying them would be pretty dependent on which agent you were talking to, unlike the other contents of the UI which comes from the state store managed centrally by the Consul servers, so it might change from agent to agent.

**Comment by lipanski** [comment]
ok, thx for the explanation.
