### ISSUE TITLE
Hardware requirement for Consul Cluster

### ISSUE THREAD

**Issue by rohitshrivastava04** [hashicorp/consul#1723]
Hello

Can anyone point me to the minimum hardware requirement for installing consul cluster for production environment? In terms of AWS can t2.micro work as consul server instances with auto scaling configured horizontally (is it feasible)?

Thanks

**Comment by polds** [comment]
**Disclaimer:** Purely non-scientific.

We've been running Consul in production since June of 2015. In our experience Consul isn't memory or CPU intensive so you shouldn't have too many issues running it on a t2.micro. That said we are running ours on m3.medium.

**Comment by slackpad** [comment]
Hi,

Darron Froese over at DataDog published some sizing examples in a recent
talk posted here:

https://blog.froese.org/2016/01/23/service-discovery-in-the-cloud-with-consul/

He did this with recent versions of Consul in a very large cluster in AWS,
so the numbers should give you a good feel for machine class -> approximate
cluster size.

In terms of auto-scaling you want to be careful not to get into a large
number of servers. 5 or 7 is typical for even large clusters, and because
they participate in a consensus protocol you don't want to go much beyond
that. Auto scaling at the Consul server level is usually just to maintain a
specific number of nodes to maintain availability/quorum, not to scale with
the cluster load.

Also, Consul will by default forward all the traffic to a single leader, so
if you want to take advantage of multiple servers you'll typically want to
reduce the consistency settings with something like
https://www.consul.io/docs/agent/options.html#allow_stale and use of
consistency modes available in the HTTP APIs
https://www.consul.io/docs/agent/http.html. These are settings you make in
the client agents in your cluster.

Hope that helps!

-- James

**Comment by rohitshrivastava04** [comment]
Thanks ! I get the gist.

**Comment by Vaccano** [comment]
It would be nice to know this in normal computer terms... (Not AWS terms.)

**Comment by polds** [comment]
@Vaccano m3.medium roughly equals 4 GB of RAM, Dual Core Processor. Our Consul cluster uses under 20 GB of hard drive space and it rarely spikes above 10 Mbps.

**Comment by slackpad** [comment]
We've tried to capture this in a new guide as well - https://www.consul.io/docs/guides/performance.html.

**Comment by Vaccano** [comment]
@polds @slackpad Thanks!

**Comment by willscripted** [comment]
> We've tried to capture this in a new guide as well - https://www.consul.io/docs/guides/performance.html.

Updated link here: https://www.consul.io/docs/install/performance
