### ISSUE TITLE
Services on failed node are shown healthy

### ISSUE THREAD

**Issue by kaskavalci** [hashicorp/consul#1763]
I deliberately failed a node and watch the behavior. Even though node is failed and serf status is not reachable, services (registered by nomad) still seem healthy. Manual netcat connection to that host port returns failure. Is that the expected behavior?

![2016-02-26 09_46_09-consul by hashicorp](https://cloud.githubusercontent.com/assets/1646238/13346731/f539a006-dc70-11e5-8cb3-5e2887ed1cda.png)

**Comment by highlyunavailable** [comment]
Yes. The Serf check is an agent-level health check so any Service-level checks will be passed over and the service instance will not be returned via DNS or HTTP as a healthy service, but it will still show as "healthy" because the last status check was a success, even if a different health status causes it to be overall unhealthy. I put in a similar issue a while back: https://github.com/hashicorp/consul/issues/1049 but the actual behavior via the APIs is what I stated above.

**Comment by kaskavalci** [comment]
Thanks for your response. Your issue seems to be fixed, months ago. How is the current behavior now?

**Comment by highlyunavailable** [comment]
My issue was a different one, and it was more of a display bug. The current behavior is as I described it.

**Comment by kaskavalci** [comment]
In my case display is still faulty, it shows service is passing on a node that fails? :)

**Comment by slackpad** [comment]
Hi @kaskavalci it should show the service health as not passing overall. Here's an example:

![image](https://cloud.githubusercontent.com/assets/673509/13661434/864f1654-e647-11e5-9194-92fc23d3edfd.png)

The fix was to change the status color of the top entry for that host, "consul-client-nyc3-2" in the example. @highlyunavailable is correct that some of the specific checks are showing green/stale since the node is dead, but since the `serfHealth` check is applied to the overall service health, the service is marked unhealthy overall for that node.

**Comment by kaskavalci** [comment]
Hi @slackpad thanks for the explanation, I didn't catch that part. However when we click on a particular service and list instances of that service in the cluster, then it will shown healthy, isn't it? Even though overall health is shown Critical, any watch that checks a particular service health will fail. Am I wrong?

**Comment by slackpad** [comment]
That screenshot was taken after clicking on the "redis" service, so the top bar showing orange means that instance of the service on "consul-client-nyc3-2" is failed, and in this case it's just from the serfHealth check. It's a bit confusing, but this lets you see why the service is failed rather than just setting all of its constituent checks as failed also.

**Comment by kaskavalci** [comment]
Maybe it's worth noting to people who use watches to check health status of services. If a watch is attached only to health check of the service, then we'll have faulty health information. Status should be logically and'ed with Serf Health Status. Example JSON of failing node:

```
"Checks":[
  {
    "Node":"myNode",
    "CheckID":"serfHealth",
    "Name":"Serf Health Status",
    "Status":"critical",
    "Notes":"",
    "Output":"Agent not live or unreachable",
    "ServiceID":"",
    "ServiceName":"",
    "CreateIndex":16414,
    "ModifyIndex":35340
  },
  {
    "Node":"myNode",
    "CheckID":"service.myService.myNode.20",
    "Name":"Service 'myService' check",
    "Status":"passing",
    "Notes":"",
    "Output":"[20160310.075757] TCP Port 9645 is up.",
    "ServiceID":"myService.myNode.20",
    "ServiceName":"myService",
    "CreateIndex":20734,
    "ModifyIndex":35309
  }
]
```

**Comment by slackpad** [comment]
@kaskavalci for that use case you probably want to do a service watch instead of one on the checks - it will do that for you (see the "Type: service" section here - https://www.consul.io/docs/agent/watches.html). That watches the health endpoint which takes into account all the node-level checks (like `serfHealth`) in addition to the service-level checks to provide a list of healthy instances.

**Comment by kaskavalci** [comment]
Thanks for the details.
