### ISSUE TITLE
Api for watches

### ISSUE THREAD

**Issue by JordyMoos** [hashicorp/consul#1771]
Is there an http api for waches or is it in the making?
I would like to backup all my configures watches but i can not find a http api call for it.

Thanks in advance

**Comment by highlyunavailable** [comment]
Watches are configured at the Agent level or manually run with `consul watch`. Please see https://www.consul.io/docs/agent/watches.html

If you back up or have a copy (e.g. config management tools) of your Consul config you will get a copy of your Watch configs.

**Comment by JordyMoos** [comment]
But there does not seem to be an api that returns the known watches for an agent, like so:
/v1/agent/watches
As i would be able to do for services: /v1/agent/services

**Comment by slackpad** [comment]
Hi @JordyMoos since watches can only be created via config files or through running command line processes, we don't have plans to expose them via an API. Services are exposed because in addition to being created through config files, they can be created on the fly through the REST API, so it makes sense to always be able to list them.

**Comment by alexnelson-es** [comment]
This is backwards.    All features should be available through the API and the tool should wrap the API.   In other words, instead of saying "you can't write via the API so we don't provide a read API", you should just allow for writing watches through the API.

**Comment by Yatharth0045** [comment]
Do we have any update on this?

**Comment by wangjia184** [comment]
https://stackoverflow.com/a/74417557/325320
