### ISSUE TITLE
Feature Request: Organize services in K/V-like tree

### ISSUE THREAD

**Issue by ChrisAubuchon** [hashicorp/consul#1779]
Some examples:
- `dev/webapp`
- `qa/webapp`
- `prod/webapp`
### DNS interface

The Current DNS interface in Consul resolves services like this:
- `tag.serviceName.service.domain`
- `_serviceName._tag.service.domain`

Using a K/V like tree structure, DNS resolution would look like this (using `group1/group2/.../groupN` as the service):
- `tag.service.groupN...group2.group1.service.domain`
- `_service._tag.groupN...group2.group1.service.domain`

Using `dev/eu/webapp` with tags `[ "http", "https" ]` as an example:

```
http.webapp.eu.dev.service.consul
https.webapp.eu.dev.service.consul
_webapp._http.eu.dev.service.consul
_webapp._https.eu.dev.service.consul
```
### Issues

Organizing services in a tree structure can introduce ambiguity in DNS resolution:

```
service eu/dev/webapp
service eu/dev with tag "webapp"
```

Both services are valid when trying to resolve `webapp.dev.eu.service.consul`. The solution for this would be to treat `webapp.dev.eu` as `eu/dev/webapp` first and `eu/dev with tag webapp` second. Essentially trying to match the longest service name.

Allowing '.'s in a tag could require more searches since, in the case of `webapp.dev.eu.service.consul` there could be no tag, `webapp`, and `webapp.dev` as a tag. Tags with '.'s don't really work in the RFC 2782 case so maybe tags with '.'s just don't resolve.

**Comment by stevendborrelli** [comment]
The idea behind this is to support kubernetes, which currently uses skydns as an add-on.

**Comment by BrianHicks** [comment]
Any update about this @slackpad? What are you thinking about here?

**Comment by slackpad** [comment]
We are thinking through a more general design for multiple tenants like dev, qa, prod so that may go deeper than just extra tag support. Also, trying to see how these types of lookups would work given our indexing in the state store so it can be efficient. Haven't had a chance yet to look at this in detail.

**Comment by slackpad** [comment]
Hi all - one thing I wanted to understand better is how this maps into Kubernetes concepts. Doing a quick look over there (I'm not experienced with k8s) there's the concept of a namespace and labels (which are flat). How does this map into the hierarchy proposed here? I can see one level of hierarchy where services are in a namespace, but with labels it seems like we are trying to do an equality selector with the additional groups. Where does k8s support hierarchy other than the namespace?

**Comment by ChrisAubuchon** [comment]
A normal k8s service would be `_namespace/_service` and resolve to `(_tag.)_service._namespace.service.consul`. A headless service would be `_namespace/_service/_pod` and resolve `(_tag.)_pod._service._namespace.service.consul`

This would also address https://github.com/hashicorp/consul/issues/1565. In that example, the service would be `ppid410/sip` with a `udp` tag and resolve `_sip._udp.ppid410.service.consul`

**Comment by momania** [comment]
Multi-tenancy/environment support like this or in any other way would be a very welcome feature!
I like the idea of the K/V style service registration as it's simple to manage as well as simple to understand and reason about it.

**Comment by yarmiganosca** [comment]
Another potential benefit here is extending this registration tree metaphor to the ui as well. We don't use kubernetes, but we do group services into groups we call "formations" (cluster was already taken by the database folks). Basically a formation is one component providing a specific piece of business functionality, and all it's immediate infra dependencies. So very similar to pods, but not quite pods, because of the lack of a locality assurance. Anyway, we have a fair number of these formations now, and each subcomponent of them (main app, load balancer, db, cache, whatever...) registers as a consul service. The consul ui dashboard has long been unglanceable (and therefore failing it's main job as a dashboard) because of all the registered services. This registration tree could extend to the ui layer--by providing a new view that showed the aggregate health status of each top-level namespace (not the root, because then there would just be one, but the immediate subroots). This would provide a less cluttered view to use as a component of a system health dashboard.

**Comment by jkirschner-hashicorp** [comment]
Hello all,

Consul added support for [namespaces](https://www.consul.io/docs/enterprise/namespaces) on Dec 2019 in Consul 1.7 Enterprise. Namespaces seem to address most of the use cases given here by providing a single level of hierarchy. The [DNS interface with namespaces](https://www.consul.io/docs/enterprise/namespaces) looks like `[tag.]<service>.service.<namespace>.<datacenter>.<domain>`.

Supporting an arbitrary number of additional levels for DNS resolution is something we have no plans to support at this time. As noted by the original poster, the resulting ambiguity in DNS resolution creates significantly more complexity. And we lack information about use cases which aren't already satisfied by namespaces to justify exploring that additional complexity.

If you have use cases for this which aren't satisfied by namespaces, please comment here.
