### ISSUE TITLE
Service remains registered and returning "Status" : "passing" when agent host is off

### ISSUE THREAD

**Issue by maroda** [hashicorp/consul#1790]
We have an environment where the service check is returning a false positive when the agent host isn't even running. Not only does it appear the service is available on that node, it is naturally causing consul to not deregister the agent. Meanwhile the serf health check is correctly being reported as failing.

In /var/log/consul you can see the VM (local on my laptop, the reason the Node is called localhost) "failing":

Mar  2 19:50:23 devint-consul-xv-03 consul[22766]: serf: EventMemberJoin: localhost.localdomain 10.0.2.15
Mar  2 19:50:36 devint-consul-xv-03 consul[22766]: serf: EventMemberFailed: localhost.localdomain 10.0.2.15
Mar  2 19:50:53 devint-consul-xv-03 consul[22766]: serf: attempting reconnect to localhost.localdomain 10.0.2.15:8301

Since then, consul just keeps trying to reconnect, unsuccessfully, because the VM isn't running. However, health checks for the service show a "passing" status:

`
   {
      "Node" : {
         "ModifyIndex" : 1505110,
         "Node" : "localhost.localdomain",
         "CreateIndex" : 1475406,
         "Address" : "10.0.2.15"
      },
      "Service" : {
         "Service" : "riak-forecasting-pb",
         "ModifyIndex" : 1475411,
         "Address" : "10.0.2.15",
         "Port" : 1399,
         "Tags" : null,
         "CreateIndex" : 1475409,
         "EnableTagOverride" : false,
         "ID" : "riak-pb"
      },
      "Checks" : [
         {
            "Notes" : "",
            "Status" : "critical",
            "Name" : "Serf Health Status",
            "CheckID" : "serfHealth",
            "ServiceName" : "",
            "Output" : "Agent not live or unreachable",
            "ServiceID" : "",
            "ModifyIndex" : 1505110,
            "Node" : "localhost.localdomain",
            "CreateIndex" : 1475406
         },
         {
            "CreateIndex" : 1475409,
            "ServiceName" : "riak-forecasting-pb",
            "Node" : "localhost.localdomain",
            "ModifyIndex" : 1475411,
            "ServiceID" : "riak-pb",
            "Output" : "HTTP GET http://10.0.2.15:8098/ping: 200 OK Output: OK",
            "Status" : "passing",
            "Notes" : "",
            "Name" : "Service 'riak-forecasting-pb' check",
            "CheckID" : "service:riak-pb"
         }
      ]
   }
`

This does not normally happen - in fact it's the first time I've seen it happen - so I don't know how repeatable it is, therefore I haven't tried restarting the consul service on devint-consul-xv-03, and do not want to manually deregister this until I get a better idea why it happened (or if something is needed for troubleshooting).

**Comment by slackpad** [comment]
Hi @maroda if a node drops off, the `serfHealth` check will fail but the other checks from that node will be stale and can remain in a "passing" state. The `serfHealth` check is included by default as part of each service, so that host should not show up in DNS queries for that service nor in the /v1/health HTTP queries for that service if "passing" is requested. Once Serf gives up on that node and reaps it (normally 72 hours) then it should be removed from the catalog as well. Does that makes sense, or do you think it's not working like this?

**Comment by maroda** [comment]
Ah, it looks like you are correct, if I use this:

curl -s "http://devint-consul-xv-01.xv.dc.openx.org/v1/health/service/riak-forecasting-pb?passing"

Even though the VM still shows up as "passing" in its health endpoint, actually asking for passing members does not show the VM. Excellent! Thanks for that.

So the best thing to do here is simply deregister through the catalog endpoint?

**Comment by slackpad** [comment]
You could deregister it from the catalog, or simply [force-leave](https://www.consul.io/docs/commands/force-leave.html) the node with Consul CLI.

**Comment by maroda** [comment]
Gotcha! Thanks so much, I think we can close this issue.

**Comment by vtahlani** [comment]
Because of default serf health my service because unavailable although it is running? Is thee a option not to add default serf health check with each and every srrvice checks? Is there a option to move service health check to other node I'd one goes off? Does consul not replicate? If I have 3 node if one is down then I want to still get all services registered with that node.
