### ISSUE TITLE
how to query health check ttl value?

### ISSUE THREAD

**Issue by leopay** [hashicorp/consul#18096]
we use /health/checks/:service to get the checks associated with the service provided on the path.

when the check type is TTL, how to get the TTL value about this check?
[
    {
        "Node": "xxxxxxxxxx",
        "CheckID": "testcheck",
        "Name": "testcheck",
        "Status": "critical",
        "Notes": "",
        "Output": "TTL expired",
        "ServiceID": "test01",
        "ServiceName": "testname",
        "ServiceTags": [
            "this",
            "is",
            "a",
            "test"
        ],
        "Type": "ttl",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {},
        "CreateIndex": 149881,
        "ModifyIndex": 149904
    }
]

**Comment by huikang** [comment]
@leopay , thanks for reporting.

It looks like the ttl field is missing in the API response. Which version of consul do you find this issue?

**Comment by huikang** [comment]
@leopay , after some internal discussion, the `ttl` value is missing in `/health/check response` by design. The rationale behind this is to decouple the definition from the result, e.g., for security purpose. `interval` and `timeout` were supposed to be removed from the API response. However, for the sake of compatibility, these two were not removed.
