### ISSUE TITLE
Create end-to-end TLS example + docs

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1834]
It would be nice to have a fully-working example with some basic cert creation.

**Comment by rascals77** [comment]
This would be useful.

**Comment by mterron** [comment]
Not documented but you could check my docker image that does TLS by default. The certs are regenerated as an example but have nothing magic in them. They are valid for the domain consul.service.consul and some others useful for testing.

See github.com/mterron/consul-autopilot and the image is on docker hub with the same name if you want to play with it.

**Comment by smutel** [comment]
Hello,

I setup TLS on consul, I didn't see any errors in the logs of the docker container ...
I am using envconsul to get the KV from consul and it works without any certificate provided to the command line.

```json
{
  "ca_file": "/consul/config/ssl/ca_cert.crt",
  "cert_file": "/consul/config/ssl/server.crt",
  "key_file": "/consul/config/ssl/server.key",
  "verify_incoming": true,
  "verify_outgoing": true,
  "verify_server_hostname": true
}
```

```sh
./envconsul -consul-addr https://consul -prefix / -consul-token=xxxxxx env
```
The KV is displayed here ...

What's wrong setup I did ?
If I don't provide certificate to envonsul, it should not work, correct?

Thanks.

**Comment by banks** [comment]
@smutel just a guess but did you do this from the docs "To enable the HTTPS API, you must define an HTTPS port via the ports configuration. By default, HTTPS is disabled." 

You also need to disable the HTTP port or consul will continue to listen on HTTP as far as I can see (this is a subtlety we don't do a great job of documenting hence this issue).

I think `envconsul` 's `consul-addr` is only the _address_ i.e. an IP or hostname and the protocol is ignored so your example works because you're server is still listening on HTTP port and envconsul is connecting to that by default (the https prefix is not the right way to tell it otherwise).

See https://www.consul.io/docs/agent/options.html#ports and https://www.consul.io/docs/agent/options.html#verify_incoming_https for consul config.

See https://github.com/hashicorp/envconsul#configuration-file for how to properly specify TLS connection in `envconsul`

**Comment by i0rek** [comment]
I just stumbled over this issue again and I think we have a perfectly fine example of TLS in our guides, right @hashicorp/consul-docs?!
