### ISSUE TITLE
watch api returns the whole list of original services instead of changed services

### ISSUE THREAD

**Issue by brucewinger** [hashicorp/consul#1840]
We watch a list of  available services, if the status of some services changes, the api would return the whole list of original service, rather just return changed services. I wondering the purpose of this design decision, or any work around ? Thx.

**Comment by slackpad** [comment]
Hi @brucewinger there's a discussion on this issue here - https://groups.google.com/forum/#!searchin/consul-tool/v2$20api/consul-tool/_2wQuRmyFHM/iOWKv8ViJQAJ. There's some design background there, as well as a possible workaround. Hope that helps! Please re-open / let me know if you have any more questions.

**Comment by hehailong5** [comment]
Hi @slackpad, I am looking for a way out for the same, I am using the blocking query instead. unfortunately, I am not able to access google servers in my country, could you please elaborate the workaround here? thanks a lot!
