### ISSUE TITLE
CAS index if no key?

### ISSUE THREAD

**Issue by lud4ik** [hashicorp/consul#1864]
I perform get, use meta.LastIndex for ModifyIndex in CAS
```
             &api.KVPair{
				Key:         q.cacheKey,
				Value:       body,
				ModifyIndex: lastIndex,
			},
```
But if no key exists, it returns some random number for response meta.LastIndex and always fails on CAS operation (false for first param in api).
Consul 0.5.0
```
2016/03/22 13:15:35 [DEBUG] http: Request /v1/kv/service/go-asterisk/flush/originate?consistent=&dc=dc1 (109.407µs)
2016/03/22 13:15:35 [DEBUG] http: Request /v1/kv/service/go-asterisk/flush/originate?cas=531&dc=dc1 (227.414µs)

```

If key is present everything works ok.

**Comment by slackpad** [comment]
Hi @lud4ik if you query and don't get a key back the index is set to the last index that modified the KV store, since there's no key present that you are querying (you could use this to do a blocking query to wait for that key to get created, for example). If the key doesn't exist you can use `?cas=0` which means "create the key only if it isn't already there". Hope that helps!
