### ISSUE TITLE
[question] How to reach agent from container

### ISSUE THREAD

**Issue by trong** [hashicorp/consul#1868]
I have the instance of consul agent on a host machine. How can I use consul inside container?

**Comment by slackpad** [comment]
Hi @trong, usually you'll run something like [dnsmasq](https://www.consul.io/docs/guides/forwarding.html) to expose Consul's DNS on port 53 without having to run Consul itself as root (dnsmasq will listen on port 53 and forward requests to Consul on port 8600). Then you'd edit your `/etc/resolv.conf` and put `127.0.0.1` in there so that Consul's DNS server is used for lookups on the host. Unfortunately, Docker won't let containers look up things on the `127.0.0.1` address by default because it runs it's own server on that address, so you'll need to have dnsmasq bind to some other address on the host that's reachable by the Docker containers (the machine's external IP, or bridge IP) and use that address in `/etc/resolv.conf`. Hope that helps!
