### ISSUE TITLE
Integrate Other Telemetry Outputs

### ISSUE THREAD

**Issue by lswith** [hashicorp/consul#1904]
Currently Consul only uses Statsd and Statsite as outputs for its telemetry. It would be useful to have a few more outputs. Examples include:
- json
- csv
- influxdb

P.S. If json was implemented, I could easily write a forwarder to parse json and move send it to the appropriate backend.

**Comment by slackpad** [comment]
Hi @Lswith thanks for opening an issue. Have you considered putting your forwarder on the other side of statsite? There are quite a few sinks floating around, including InfluxDB - https://github.com/armon/statsite/blob/master/sinks/influxdb.py.

**Comment by Lswith** [comment]
Yes but to facilitate all possible alternatives (we don't have statsd or statsite in production) Jason would be the best option.

**Comment by Lswith** [comment]
*json

**Comment by slackpad** [comment]
I'm thinking the effort to write a forwarder would be very similar. Instead of writing a web service to consume JSON from Consul servers, you'd run a statsite server and write a script (basically just a CLI tool) to take the statsite data stream and process it how you'd like. There's already a well-defined interface for what the stream looks like and it's super simple to work with - https://github.com/armon/statsite#writing-statsite-sinks.

I'd like to avoid the overhead of Consul serializing JSON for telemetry in order to keep Consul's core as lean as possible. That's the main reason I'm exploring the alternatives :-)

**Comment by Lswith** [comment]
Makes sense. Your solution seems reasonable

**Comment by discordianfish** [comment]
@slackpad This has all the downsides of push based metrics. You never really know when something happened. And beside that, if you have a pull based monitoring system like Prometheus not having any way to pull in metics and having to resort to some kind of bridge make it worse.

I think consul should provide the metrics on some point for pull. See this discussion: https://github.com/hashicorp/consul/issues/817

**Comment by slackpad** [comment]
Hi @discordianfish thanks for your thoughts on this. I haven't had any recent cycles to devote to this, but I'll give it another look.

**Comment by discordianfish** [comment]
@slackpad That would be great! Also see my suggestions in #817

**Comment by evilezh** [comment]
I can see few threads going on, not sure to which add.

So - exposing over REST endpoint same stats as i got sending USR1 would be easy and great step forward.  Now you are forced to install somewhere statsd ... then think how to transform for further usage etc.

As for possible forwarders ... i can suggest kafka. Every configurable n-seconds make json from metrics .. send. Mostly anything nowadays can read from it.

**Comment by slackpad** [comment]
Closing this in favor of #817, which seems to be a better approach, and should make it easy to do other metrics integrations outside of Consul.
