### ISSUE TITLE
is it possible to deploy consul in k8s?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#1925]
there are steps to start server, start client and join nodes, I don't know if a consul cluster could be deployed in k8s and if the gossip stuff is working in k8s.

**Comment by hingstarne** [comment]
If you use atlas integration it should work,
see [here](http://www.devoperandi.com/deploying-consul-in-kubernetes/)
But as there is no discovery domain like in etcd you would have to make dirty hacks to have it scale properly without atlas

**Comment by slackpad** [comment]
Hi @hehailong5 I'm going to close this out since it looks like there's an article here that can help you out. This might be a good type of question for the mailing list as well. If you can't run Atlas for joining, most folks run a handful of seed Consul agents and register those with their local DNS setup to use to join other nodes with the cluster. Please let me know if you have any more questions.
