### ISSUE TITLE
Consul semaphore docs need some work?

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#1940]
Using Consul 0.6.3

Trying to follow the consul semaphore docs and getting totally lost around some magic lock keys that apparently get created.

Step 1 - Creating the sessions is fine and understandable
Step 2 says:

The next step is to use a single key to coordinate which holders are currently reserving a slot. A good choice for this lock key is simply `<prefix>/.lock`. We will refer to this special coordinating key as `<lock>`.

Step 3 then says to read the prefix: `curl http://localhost:8500/v1/kv/<prefix>?recurse`
and "Within the list of the entries, we should find the `<lock>`"

This to me means, that the data returned from the curl http://localhost:8500/v1/kv/<prefix>?recurse, should include an entry which has ".lock" in it.

Which it doesnt.

So at this point, the docs totally lose me.

What I do get when I curl that URL is three of these with different session IDs:

```
  {
    "LockIndex": 1,
    "Key": "service/foobar/lock/25f4c456-0dd6-e857-b1e5-4ef94a9366a2",
    "Flags": 0,
    "Value": "c29tZX.....etc",
    "Session": "25f4c456-0dd6-e857-b1e5-4ef94a9366a2",
    "CreateIndex": 765626,
    "ModifyIndex": 765626
  }
```

Can someone update the docs to be correct please?

**Comment by paulchoi** [comment]
+1

**Comment by p1nkrock** [comment]
The document is still not updated with clear instructions to obtain a semaphore.  Like the original issue was reported. The <prefix>/.lock is not getting created by default. If not created, then what steps to follow.

Also, while creating the lock, thru HTTP requests how to specify the key lock holder limit? 
Thru 'consul lock' command, an option is provided to specify the limit, but how to provide the same thru http requests?

**Comment by qubitrenegade** [comment]
I wrote a [quick bash script](https://gist.github.com/qubitrenegade/88df929bdfb5d198a20ca6667ba33797) in an attempt to implement the documentation (and because I was tired of copy/pasting).

I have a number of questions, but where I'm really confused is this:

```

Within the list of the entries, we should find the <lock>. That entry should hold both the slot limit and the current holders. A simple JSON body like the following works:

{
    "Limit": 3,
    "Holders": {
        "4ca8e74b-6350-7587-addf-a18084928f3c": true,
        "adf4238a-882b-9ddc-4a9d-5b6758e4159e": true
    }
}

```

Does this mean to create a lock I need to on each contender:

1) get a full list of the lock, e.g. `curl 'http://consul01:8500/v1/kv/service/foobartest/lock?recurse'`
2) parse out the list of IDs
3) somehow figure out my limit
4) somehow figure out which nodes should be "holders"
5) craft my JSON response,
6) Then get a lock?

It seems to me that the entire point of the Semaphore is that I have 3 nodes that don't know who has the lock, and one node wants the lock... but by having to provide which nodes should have the lock, aren't I doing the job of the Semaphore myself?  Am I just misunderstanding what a Semaphore is?  Or how can my nodes figure out what the appropriate "holders" of the lock are?  In other words, how do I craft my response?  Also, couldn't node one say "limit: 1" but then node 3 say "limit: 3"?  And what is a "cas-modify-index"?  Because in my JSON output from `?result`? everyone has an index of 1... (see linked gist for output)

I.e.: to continue that above linked gist, what I'm getting from the documentation is I need to:

```
# assume this is a continuation of  https://gist.github.com/qubitrenegade/88df929bdfb5d198a20ca6667ba33797

curl -X PUT -d \
"{ \
  \"Limit": 2,\
  \"Holders\": { \
    \"${sess1}\": true,\
    \"${sess2}\": true,\
    \"${sess3}\": true\
    }\
} ${BASE_URL}/v1/kv/${LOCK}?cas=<lock-modify-index>
```

I mean, the only reason I have these three sessions is because I'm doing it from one script... but if there was three nodes, then they'd have to communicate with each other, or parse the whole output of the `?result` query...

I see that @slackpad added the "Unplanned" tag to this, so does that mean that the Seamaphore feature is being deprecated in Consul?  Or does that mean I should look elsewhere for assistance?  This is definitely a feature of Consul we'd like to leverage, but if it won't be supported and/or is being deprecated we'd definitely like to know before we go too far down this path...

Thanks!
- Q

**Comment by slackpad** [comment]
> I see that @slackpad added the "Unplanned" tag to this, so does that mean that the Seamaphore feature is being deprecated in Consul? Or does that mean I should look elsewhere for assistance? This is definitely a feature of Consul we'd like to leverage, but if it won't be supported and/or is being deprecated we'd definitely like to know before we go too far down this path.

We definitely are not going to deprecate any features around this! Just haven't had a chance to update the docs yet.

> It seems to me that the entire point of the Semaphore is that I have 3 nodes that don't know who has the lock, and one node wants the lock... but by having to provide which nodes should have the lock, aren't I doing the job of the Semaphore myself?

In a sense, yes. Consul doesn't natively have a semaphore, but you can build one with the primitives available in the KV store. In the [semaphore guide](https://www.consul.io/docs/guides/semaphore.html) a JSON limit + list of sessions is used to track who holds the semaphore, and clients must respect the limit. A check-and-set operation is used to atomically update this body to try to get the semaphore. Consul doesn't know this key is being used a semaphore, though, so doesn't have any first-class support for it like it does for locks.

**Comment by brd** [comment]
It would also be nice to see an example of how to do this with `consul lock`..

If I run 3 copies of this:
`consul lock -n=3 -verbose net "sleep 3600; echo true"`

Then look at the API (`/v1/kv/net?recurse`), I never see which are holding the lock like in the docs:

```
{
    "Limit": 3,
    "Holders": {
        "4ca8e74b-6350-7587-addf-a18084928f3c": true,
        "adf4238a-882b-9ddc-4a9d-5b6758e4159e": true
    }
}
```

**Comment by brd** [comment]
Oh I see.. the Web UI clued me in..  Hit the following end point:

`/v1/kv/net/.lock?recurse`

and base64 decode the Value field to find the "Holders"

But why is this info Base64 encoded anyways?

**Comment by pearkes** [comment]
I think these docs have been much improved the work in #4661 by @freddygv. I'm going to close this.
