### ISSUE TITLE
How to set service_ttl with http api

### ISSUE THREAD

**Issue by wxjs33** [hashicorp/consul#1949]
how can i set service_ttl for a service, i cant find any way to do it with http api

**Comment by wxjs33** [comment]
or is there some way to set service_ttl when registers a new service ?

**Comment by slackpad** [comment]
Hi @wxjs33 can you provide some more detail about what you are trying to do? Services don't have TTLs in Consul. Sessions have as TTL, as do TTL health checks - are either of those what you are looking for?

**Comment by wxjs33** [comment]
In my config i set a service named "web", its service_ttl is 10s, like this
 `"dns_config": {         
         "service_ttl": {
               "web": "10s"
         }
}`
The TTL of "web" is 10s when queryed with dns lookup,  
If i register a new service(example: "web2") with http api, how can i set service_ttl of "web2"  to 5s?
I want to set it with http api not to write in config，thx

**Comment by slackpad** [comment]
Ah sorry I wasn't thinking DNS TTL when I first saw this issue. The different ways of setting TTL are covered in the [DNS Caching Guide](https://www.consul.io/docs/guides/dns-cache.html), see "TTL Values" at the end. 

Unfortunately, that `service_ttl` map is only exposed through the configuration file. Currently, the only way to change TTLs on the fly is using [prepared queries](https://www.consul.io/docs/agent/http/query.html). You can register a query for your service with a given TTL and then look it up via DNS as `<query name>.query.consul`. Since prepared queries are defined server-side, you can alter TTL values on the fly and Consul agents will pick up the changes dynamically, so there's no configuration. There are also [prepared query templates](https://www.consul.io/docs/agent/http/query.html#templates) which allow you to make a single query definition that matches a range of services.

**Comment by wxjs33** [comment]
Thanks！
