### ISSUE TITLE
Integration with Rancher

### ISSUE THREAD

**Issue by throrin19** [hashicorp/consul#1951]
Hi, Have you an example to run Consul into Rancher and set correctly the registrator ?

I test correctly consul + fabio + registrator but it's very complicated to scale, maintain, install in production, so, I check differents orchestrator for Docker containers. I retain *Rancher* But, I can not correctly configure my environment to get the good IP of my containers.

Am I forced to used the registrator, or, because Ranger has the correct containers IP, am I a way to go through it to manage and fulfill Fabio?

Thanks

**Comment by slackpad** [comment]
Hi @throrin19 this is probably a better question for the mailing list because you'll get a wider group of folks who may have experience with these stacks. Unfortunately, I don't have direct experience with Rancher to give good advice here. You might also want to check out [Nomad](https://www.nomadproject.io/) which also has Consul integration for containers and service discovery. Hope that helps!
