### ISSUE TITLE
HTTP health check changes will not always trigger watches on the service health

### ISSUE THREAD

**Issue by polynatic** [hashicorp/consul#1961]
Hi, 
I'm using the /v1/health/service/?passing&wait=10m&index=12345 route to watch for healthy nodes. The health check for the nodes is configured to use an HTTP route on the node. Now when the reported status changes, the consul interface immediately shows the new status, but the watcher still keeps waiting in about 20% of all cases. After the timeout is reached it will return the updated list of nodes and a new consul-index as intended.
We tested the reproducibility on consul v0.6.4 by letting a node report a different status every 10 seconds. The health check is performed every second by consul.

**Comment by slackpad** [comment]
Hi @polynatic are you still seeing this in newer versions of Consul? We've done pretty extensive rework on the blocking query underpinnings so I'd be interested to see if this got cleaned up along the way.

**Comment by pearkes** [comment]
This issue was reported on a version of Consul that is quite old. Based on the volume of changes since that version we encourage you to try reproducing with the latest version of Consul. If you feel the issue is critical and on an older version of Consul, or still exists in the current version, do feel free to let us know and we can re-open it.

Thank you for your initial report, and again, do feel free to ask us to re-open or create a new issue, and be sure to include the suggested debugging information in the issue template.
