### ISSUE TITLE
HTTP API inconsistent?

### ISSUE THREAD

**Issue by feniix** [hashicorp/consul#1964]
A. Way to reproduce: 

1. Create a three node elasticsearch cluster
2. Register a consul service for each node (see the service definition below)
3. Terminate one node and add another node (also add the service for that one)

```
{
  "service": {
    "address": "10.0.2.xxx",
    "port": 8080,
    "checks": [
      {
        "http": "http://10.0.2.xxx:9200",
        "interval": "10s",
        "timeout": "1s"
      }
    ],
    "tags": [
      "elasticsearch"
    ],
    "name": "elasticsearch-master"
  }
}
```

B. Expected:

1. All the health checks for the removed nodes should fail

C. Actual output:

1. Curl this url: http://10.0.2.219:8500/v1/health/service/elasticsearch-master?passing
Output: https://gist.github.com/feniix/dba06e6d0568c824066ef067ff2b405b
Shows 3 elasticsearch-master healthchecks alive

2. Curl this url: http://10.0.2.219:8500/v1/health/state/passing
Output: https://gist.github.com/feniix/94f69a0bfbe4c8e374dc863c8d085692
Shows 4 elasticsearch-master healthchecks alive

**Comment by slackpad** [comment]
Hi @feniix if a node is terminated but doesn't leave the cluster (it will get reaped after to 72 hours) then all of its service health checks will go stale, but it's serfHealth check will fail because the cluster will realize the node is gone. The raw "passing" query will still show the stale checks, but the serfHealth check is AND-ed with those others, so the failed node won't be returned in a DNS query to Consul, and https://www.consul.io/docs/agent/http/health.html#health_service with the "?passing" parameter will omit that dead node. Hope that helps!
