### ISSUE TITLE
Stop use of HTTP Api from all interaction without supplied ACL token

### ISSUE THREAD

**Issue by fatlazycat** [hashicorp/consul#1991]
Appears from issues such as #1383 that you cannot lock down consul.

From what I understand authentication is done by SSL certs and authorisation by ACL's

In the company I work for I can only get client certs issued at one internal Certificate Authority, hence any internal cert will be valid when consul checks.

This could be solved if the ACL layer protected every call, but this appears not to be the case.

Am I missing something ? Is there a way to lock this down ?

Thanks

**Comment by slackpad** [comment]
Hi @fatlazycat we are currently expanding the coverage of ACLs, but the [Agent API](https://www.consul.io/docs/agent/http/agent.html) are currently not covered, mostly due to ACLs being enforced on the Consul servers. We've got a design in mind to cover agent functions as well, and are actively working towards it, but right now changes can be made at the agent level from someone with access to that agent's client interface. In the meantime, the best thing is to make sure that the client interface is not exposed outside the machine (bind to loopback or better yet a UNIX socket protected by appropriate file permissions).
