### ISSUE TITLE
leave_on_terminate not working

### ISSUE THREAD

**Issue by jtconnor** [hashicorp/consul#1992]
I'm testing consul 0.6.4 in AWS EC2 and have found that when I enable the `leave_on_terminate` setting, the consul agent attempts to gracefully leave the cluster but fails.  Any idea why leaving fails?

Here are the agent logs:
```
==> Caught signal: terminated
==> Gracefully shutting down agent...
    2016/04/27 13:24:08 [INFO] consul: server starting leave
    2016/04/27 13:24:08 [INFO] serf: EventMemberLeave: i-45a93bd8.us-east-1 172.31.50.116
    2016/04/27 13:24:08 [DEBUG] http: Shutting down http server (127.0.0.1:8500)
    2016/04/27 13:24:08 [INFO] agent: requesting shutdown
    2016/04/27 13:24:08 [INFO] consul: shutting down server
    2016/04/27 13:24:08 [WARN] serf: Shutdown without a Leave
    2016/04/27 13:24:08 [ERR] dns: error starting tcp server: accept tcp 127.0.0.1:8600: use of closed network connection
    2016/04/27 13:24:08 [INFO] agent: shutdown complete
```

and agent configuration:
```
{
  "server": true,
  "retry_join": [
      "172.31.48.37"
  ],
  "data_dir": "/var/consul",
  "datacenter": "us-east-1",
  "leave_on_terminate": true,
  "log_level": "debug",
  "node_name": "i-45a93bd8",
  "ui": true 
}
```

and `consul members` run from another node:
```
[ec2-user@ip-172-31-48-37 ~]$ consul members
Node        Address             Status  Type    Build  Protocol  DC
i-45a93bd8  172.31.50.116:8301  failed  server  0.6.4  2         us-east-1
i-5aa93bc7  172.31.50.117:8301  alive   server  0.6.4  2         us-east-1
i-5ba93bc6  172.31.50.118:8301  alive   server  0.6.4  2         us-east-1
i-eaab3977  172.31.48.37:8301   alive   server  0.6.4  2         us-east-1
```

Please let me know if you need any other information to aid debugging.  Thanks for your help!

**Comment by slackpad** [comment]
Hi @jtconnor this gets tricky because Consul doesn't always have enough time to gracefully leave when a machine terminates. For client agents this is rarely an issue because they will get expired after 72 hours. Servers will, too, but having an unclean leave will have undesired effects on the quorum. We are working on a process to have the remaining servers automatically clean up failed servers more quickly - that won't make it into Consul 0.7.0, but should be available shortly after that release.
