### ISSUE TITLE
Pass service information as environment variables to check scripts

### ISSUE THREAD

**Issue by predominant** [hashicorp/consul#202]
It would be glorious if check scripts could receive information such as port definitions, so that checks could be written in a generic way.

For example, a series of checks for a webserver are currently hardcoded to port 80, whereas if the check script could be passed the port definition from the service configuration, the check script becomes a generic port checker.

The linux example would change from:

```
/bin/sh -c /usr/local/consul/checks/port-80-listening.sh
```

to

```
CONSUL_SERVICE_PORT=80 /bin/sh -c /path/to/checks/port-listening.sh
```

Likewise, if you could pass arbitrary information such as tags through (or something else?) service checks could switch checks based on information such as protocol.

**Comment by andreparames** [comment]
Hi, I'm evaluating Consul for health checking a few dozen web services, has this been implemented?

**Comment by xytis** [comment]
@slackpad, we had a conversation about this issue in HashiDays. Do you need any help on this topic?

**Comment by s-christoff** [comment]
This issue was reported on a version of Consul that is quite old. Based on the volume of changes since that version we encourage you to try reproducing with the latest version of Consul. If you feel the issue is critical and on an older version of Consul, or still exists in the current version, do feel free to let us know and we can re-open it.

Thank you for your initial report, and again, do feel free to ask us to re-open or create a new issue, and be sure to include the suggested debugging information in the issue template.
