### ISSUE TITLE
How to persist data when running cluster in container way?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2066]
The problem is each time the nodes of the cluster will have different docker internal IPs. when using the old data to bootstrap the cluster, all the nodes would request to the old IPs to make votes, that would make leader selection fail. to make the cluster up again, you have to first clean up all the data preserved last time the cluster exited. in the end, we lost the data. then How to handle the persistence in this situation?

**Comment by shilov** [comment]
It's been a while since I tried this, but iirc you should be able to retain the data even if the IPs have changed by editing `raft/peers.json`

**Comment by hehailong5** [comment]
@shilov, does this workaround just make the cluster running again or the old data can be restored as well? I see some snapshot files also having IPs embedded. not sure what's in the raft.db.

**Comment by shilov** [comment]
No idea about the snapshot files, but if my memory serves me right the data will still be there. This will sound obvious but if you care about your data, you'll need to test this yourself. My knowledge is based on an experiment I did over a year ago and it might behave differently now. If you do end up testing this, I'd love to know the results. 

@slackpad the page https://www.consul.io/docs/guides/outage.html doesn't address cluster failure recovery, and it's more or less absent from the other pages, too. I'm not sure if that's intentional but I think it would help others if the issue was addressed with more clarity. Nobody anticipates an entire cluster to fail but should that happen, can it be recovered after removing bad servers from each peers.json file? What would be the best approach to take?

**Comment by slackpad** [comment]
IP address change issues are covered in https://github.com/hashicorp/consul/issues/1580 and we've since added more detail to the outage guide's manual recovery section - https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json.
