### ISSUE TITLE
Information about envoy supported versions

### ISSUE THREAD

**Issue by medinaLeo** [hashicorp/consul#20975]
Currently I have consul version 1.18.0 and envoy version 1.27.2. 

```console
[root@test ~]$ consul --version
Consul v1.18.0
Revision 349cec17
Build Date 2024-02-26T22:05:50Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

[root@test ~]$ envoy --version

envoy  version: b40c13219de36bd01ae83cf6cf8b3ef6f75f68a3/1.27.2/Clean/RELEASE/BoringSSL
```

- Looking at consul the documentation, i see that it is compatible with the following envoy versions

<https://developer.hashicorp.com/consul/docs/connect/proxies/envoy#supported-versions>

![2024-04-11 17_22_27-Envoy Proxy Configuration _ Service Mesh _ Consul _ HashiCorp Developer](https://github.com/hashicorp/consul/assets/110544872/cd1725f6-4a17-4339-81b1-80e58cc46581)

- According to the documentation, consul version 1.18.0 should not be compatible with envoy version 1.27.2. Is that correct? because everything works perfectly. I provide more data

- Checking the logs of the consul-ingress-gateway service I do not see any error and the service starts up without any problem

- The operating system where I have these packages installed is a almalinux 9.2

```console
[root@test]$ cat /etc/almalinux-release
AlmaLinux release 9.2 (Turquoise Kodkod)
[root@test ~]$
```

- If I look for what envoy package I have available to update, I see that I directly see version 1.28.0.

```console
[root@test]$ yum list --enablerepo=consul | grep envoy
hashicorp-envoy.x86_64                                                                   1.27.2-1                                       @consul
hashicorp-envoy.x86_64                                                                   1.28.0-1                                       consul
[root@test~]$
```

- If these versions that I have (both consul and envoy) are not compatible, please can someone tell me how to check?

- Am I understanding the documentation correctly?

- Thank you very much and I look forward to hearing from you

**Comment by jkirschner-hashicorp** [comment]
Hi @medinaLeo,

The compatibility table in the docs states that Consul 1.18.x CE is compatible with Envoy 1.27.4. Though the docs don't state this (even though they should), that specifically means:
- We're running our automated compatibility tests against Envoy 1.27.4 specifically and they all pass.
- It's likely that all versions of Envoy 1.27.x work, since Envoy patch releases shouldn't have breaking changes. That means we likely support 1.27.0 -> 1.27.latest.
- Envoy versions before 1.27.4 likely have CVEs, which is why we now test against 1.27.4 rather than earlier patches.

This is all to say: Envoy 1.27.2 should work, though there may be other reasons to run later patches of Envoy 1.27 (security patches).

Ideally, our docs would be updated to make this clearer.

**Comment by medinaLeo** [comment]
Hi !

Thank for your answer and explanation @jkirschner-hashicorp. Now I am clearer about the compatibilities and it would be great (as you say) that this is clearer in the documentation.  

Greetings and I proceed to close the issue
