### ISSUE TITLE
The build.sh does not work for multiple directory in GOPATH

### ISSUE THREAD

**Issue by shahuwang** [hashicorp/consul#2110]
Hi，
I cloned the current master branch and  ran `make` command to build consul in ubuntu 14.04 with Go 1.6, but I got this error:

`/mnt/hgfs/packages/src/github.com/hashicorp/consul/scripts/build.sh: line 41: /home/rickey/gocode/:/home/rickey/github:/mnt/hgfs/share/github/:/mnt/hgfs/packages/bin/gox: No such file or directory`

I found that in the build.sh, you use `$GOPATH/bin/gox` to run gox, but if there is multiple diretory in the GOPATH, it will cause an error as above.  Maybe you can split GOPATH by `:`  and set each bin directory of them to PATH, and then run `gox`

**Comment by sean-** [comment]
Hi @shahuwang , this should be fixed in 0180f20352ab1696a77fdbb37adcfbc6d3f8dd5c. Instead of splitting on the path separator, `scripts/build.sh` now uses `which` to determine the path of `gox`.  If a user has multiple directories in their `GOPATH` they can ensure the correct `$GOPATH/bin` is in their `PATH`.  Let us know if that doesn't work for you.  Cheers!
