### ISSUE TITLE
Create a cli dashboard

### ISSUE THREAD

**Issue by meskarune** [hashicorp/consul#2119]
There is a cool libarary in go that makes cli graphs and dashboard widgets: https://github.com/gizak/termui

I would love to have a cli dashboard for consul. I am new to programming and could try my hand at making something but you guys would probably do a better job.

**Comment by HalosGhost** [comment]
This would be an incredibly useful tool for system administrators.

I would particularly love to see this as an option to be run not on one of the nodes/servers but instead on any machine that is aware of the RPC interface of an agent (since this would allow me to monitor all my nodes from my local machine rather than having to ssh into another machine and run it there.

**Comment by slackpad** [comment]
Hi @meskarune that's a great library :-) This feels like something that should probably be a separate project as suggested by @HalosGhost that consumes the API, but I'll keep this open for a bit to think about any possible uses in the existing Consul CLI.

**Comment by slackpad** [comment]
We are going to close this out for now per https://github.com/hashicorp/consul/issues/2119#issuecomment-239048117. Seems like a neat project though :-)
