### ISSUE TITLE
Indexes are incrementing automatically

### ISSUE THREAD

**Issue by ajays20078** [hashicorp/consul#2164]
Have a consul setup with 3 nodes (all in server mode) with Load balancer on port 8500 to handle reads and writes to the cluster. We are observing the below 3 indexes increment automatically even when there are 0 requests from load balancer, are they meant to auto increment without writes? Is there something which i am doing wrong?

Indexes:

applied_index
commit_index
last_log_index

Consul v0.6.4
Consul info:

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	server = true
raft:
	applied_index = 413829
	commit_index = 413829
	fsm_pending = 0
	last_contact = 33.412637ms
	last_log_index = 413829
	last_log_term = 7
	last_snapshot_index = 410206
	last_snapshot_term = 7
	num_peers = 2
	state = Follower
	term = 7
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 60
	max_procs = 2
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 30
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 3
	members = 1
	query_queue = 0
	query_time = 1

**Comment by slackpad** [comment]
Hi @ajays20078 there are some background processes like network coordinates doing writes that will cause these to increment slowly over time (increasing by a few per minute since the updates are batched). If the index is increasing very rapidly that can often be caused by a health check where the output changes every time (like requesting a page with a time stamp) - those should be avoided if possible. How rapidly are the indexes counting up for you?

**Comment by ajays20078** [comment]
- Healthcheck is static, its checking for / on 8500, so no timestamp based requests there.
- They are increasing at around 8 per minute, is this something concerning?

**Comment by slackpad** [comment]
8 per minute lines up pretty well with the coordinate updates, so that seems totally normal. Hope that helps!
