### ISSUE TITLE
Failed to perform consul server rolling upgrade 

### ISSUE THREAD

**Issue by zankich** [hashicorp/consul#2172]
### `consul version` for both Client and Server

Upgrading consul servers from `0.5.2` to `0.6.4`, clients are still on `0.5.2` because upgrade failed.
### `consul info` for both Client and Server

N/A
### Operating system and Environment details

Ubuntu 14.04 on AWS
### Description of the Issue (and unexpected/desired result)

We have a 3 node cluster in a working state.  We were upgrading the cluster, where we update one node at a time.  We do a graceful leave, stop the server, and then restart.  In this case, we were also changing the node name.  In one case where we saw this fail, the first node, which was not the leader, successfully left and then rejoined.  Logs from the third node indicates that it got a successful join (serf and consul) from the first node.

Then the second node, which was the leader, leaves and shuts down.  At this point, we see both the first and third node fail to elect a leader amongst each other, with a ton of these logs:

```
    2016/07/05 16:39:32 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
    2016/07/05 16:41:00 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:41:02 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:41:24 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:41:45 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:42:05 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:42:21 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:42:38 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:43:02 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:43:30 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:43:49 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:44:16 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:44:40 [ERR] agent: failed to sync remote state: No cluster leader
```

We've tried this operation 3 times on fresh environments, and it failed 2 out of 3 time.

We also saw that the `peers.json` on the first and third node only has it's own IP Address and the second node had `null`.
### Reproduction steps

Described above.
### Log Fragments or Link to [gist](https://gist.github.com/)

https://gist.github.com/zankich/83d918eddddb31e8cf90fb010dfec205

**Comment by slackpad** [comment]
Hi @zankich did the IP addresses of the servers change as well, or just the node name?

**Comment by zankich** [comment]
@slackpad only the node names, the ip addresses stayed the same.

**Comment by slackpad** [comment]
The other thing to look at is if you were able to confirm the rolled server rejoined before you rolled another (did you have control over the leave/rejoin/roll another sequencing)?

**Comment by zankich** [comment]
The first node, which successfully rolled, was able to sync its raft logs with the cluster so it must have joined the cluster at some point before the second node rolled:

```
    2016/07/05 16:38:52 [INFO] agent: (LAN) joined: 3 Err: <nil>
    2016/07/05 16:38:52 [INFO] agent: Join completed. Synced with 3 initial agents
    2016/07/05 16:38:52 [WARN] raft: Failed to get previous log: 8367 log not found (last: 8338)
    2016/07/05 16:38:52 [INFO] raft: Removed ourself, transitioning to follower
    2016/07/05 16:38:53 [INFO] agent.rpc: Accepted client: 127.0.0.1:52401
    2016/07/05 16:38:53 [INFO] serf: Received list-keys query
    2016/07/05 16:38:53 [INFO] serf: Received list-keys query
    2016/07/05 16:38:54 [INFO] serf: Received install-key query
    2016/07/05 16:38:54 [INFO] serf: Received install-key query
    2016/07/05 16:38:54 [INFO] serf: Received use-key query
    2016/07/05 16:38:54 [INFO] serf: Received use-key query
    2016/07/05 16:38:58 [INFO] raft: Removed ourself, transitioning to follower
```

We also see logs in the third node indicating that the first joined:

```
    2016/07/05 16:38:52 [INFO] serf: EventMemberJoin: consul-server-0 10.85.59.91
    2016/07/05 16:38:52 [INFO] consul: adding server consul-server-0 (Addr: 10.85.59.91:8300) (DC: dc1)
```

After that time, we see on the first and last node that the middle node is leaving:

```
    2016/07/05 16:38:59 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
    2016/07/05 16:39:20 [ERR] agent: failed to sync remote state: No cluster leader
    2016/07/05 16:39:31 [INFO] serf: EventMemberLeave: consul-server-partition-2c24411ca84164481893-1 10.85.56.93
    2016/07/05 16:39:31 [INFO] consul: removing LAN server consul-server-partition-2c24411ca84164481893-1 (Addr: 10.85.56.93:8300) (DC: dc1)
```

Note, the first node to roll gets named `consul-server-0`, the next node to roll, which fails, is `consul-server-2`, and the node that never rolls is `consul-server-1`.  Just to let you know since the numbering in the node names doesn't necessarily match the order of rolling, so you don't get confused.

We sort of have control over the sequencing.  We do one at a time, where we gracefully leave, shut down the server, restart with a `--retry-join` flag, and also `--bootstrap-expect` value of 3.  We also check that the last log index and commit index are equal, and greater than 0, before moving on to the next node.  We've stripped some of our custom logs out of the above gists, but we can add some of them back in to show where we do the sync verification before moving on to the next node.

**Comment by slackpad** [comment]
Interesting - looking through the logs it looks like one of the servers might be leaving again as it replays the Raft logs after starting up. If you are upgrading in place, it's generally a little safer to avoid doing the graceful `consul leave`, set [`skip_leave_on_interrupt`](https://www.consul.io/docs/agent/options.html#skip_leave_on_interrupt) to `true`, and make sure [`leave_on_terminate`](https://www.consul.io/docs/agent/options.html#leave_on_terminate) is left at `false`. By not doing the leave you don't mess with the peer configuration - the leader will keep retrying contact with the server while it's down.

Your `--retry-join` setting looks good and `--bootstrap-expect=3` is harmless but should apply here since the cluster is already bootstrapped (that only works when starting the cluster for the first time).

**Comment by zankich** [comment]
If we're scaling down (e.g. decreasing the cluster from 5 nodes to 3 nodes "permanently"), should we gracefully `consul leave`, or is it also safe to just pull the plug in that situation too?

**Comment by slackpad** [comment]
For scaling down you'll definitely want to do the leave, that'll remove the servers from the peers and lower the quorum requirements.

**Comment by zankich** [comment]
Will renaming a node cause confusion in a cluster if we do not `leave` before we perform the name change?

**Comment by slackpad** [comment]
Ah that's true. I was thinking from the Raft POV it's managing addresses but from Consul's gossip POV there's going to be a leave on the old node name and a join on the new node name which could cause a blip in Raft. We are working on a stronger identity concept for Raft to help in situations like this, but the current version could get confused.

Is there any way you can change the address at the same time you change the node name? I think this would work around the issue.

**Comment by Amit-PivotalLabs** [comment]
@slackpad we would like to change our orchestration to detect whether the cluster is scaling down vs. being rolled, and either leave or pull the plug accordingly.  Right now, we can't change that, and it will always leave.

We want to consider the following option:

1. Tear down the existing cluster (each node doing a "leave") -- we will lose all data with this, which is okay.
2. Bring up a brand new cluster with new names, but at the same old IPs.
3. Somehow make sure all clients can start talking to the new cluster without having to roll all clients.

We don't have control over the teardown logic, but we do have control over the startup logic.  We're concerned that when all the nodes leave, the clients will forget about them, and then when the nodes come back up, the servers (having lost all data) won't know about clients, and the clients have no reason to remember the servers because they've received the leave announcements.  Is there a way on startup for the new servers to reannounce themselves to the clients, assuming we could tell them a list of client IPs?  If so, would we need to know all client IPs or just some, and then rely on Serf to propogate the presence of the new servers to the rest of the clients?

**Comment by slackpad** [comment]
Oh ok - if you can rebuild the servers and lose all the data then this should be easy :-)

1. Teardown the servers however you'd like.
2. Upgrade consul, reconfigure the node name, etc.
3. Before starting, blow away the Consul data-dir.
4. When starting, give the servers a few client IPs to join (you don't need an exhaustive list, it could even be a single client IP or small list).

If you have `-bootstrap-expect=3` the servers will form the Raft cluster once they all see each other, and since you've joined the servers with the old cluster via the client IPs. The clients will discover the new servers automatically via gossip and should start using them. As long as the servers are joined with the existing client cluster all should be ok.

**Comment by Amit-PivotalLabs** [comment]
Thanks @slackpad, good to know we have that option.  One more question, let me know if you'd rather I start a different issue or ask on the mailing list instead, but if I have access to a node's raft.db, is there any way to determine what its name was before being shutdown?  The scenario I'm imagining:

* 3 node running cluster, under one naming convention
* one node leaves, stops, disk is detached, new VM is created, old disk re-attached, and something on the new VM deduces what the node's name was based on what's in raft.db
* the consul server is started on the recreated node, being fed its old node name.

Would there be a way to find out what the node name was for the VM I'm on?  Would probably need to be able to do this without the Consul server running, since by then the server needs to have a node name given.  And I believe this rules out obvious things like running `consul members` or something like that.

**Comment by slackpad** [comment]
Hi @Amit-PivotalLabs this one is a little tricky because it's not really in the Raft log or any single place in a super easy form. The only thing I could come up with would be to parse <data-dir>/serf/local.snapshot and see what node name is associated with that machine's IP address. This is basically some state the Serf layer holds so it can come up more quickly, so it will be available even if Consul isn't running. Here's how that file looks:

```
alive: consul-server-nyc3-1 104.236.102.246:8301
alive: consul-server-nyc3-2 104.131.60.172:8301
alive: consul-demo-proxy 45.55.129.90:8301
alive: consul-server-nyc3-3 104.236.37.221:8301
alive: consul-client-nyc3-2 159.203.76.7:8301
alive: consul-client-nyc3-3 104.131.122.233:8301
alive: consul-client-nyc3-1 104.236.250.54:8301
clock: 802
event-clock: 105
query-clock: 0
coordinate: {"Vec":[-0.010035522947371292,-0.004009599942510413,0.03422651530998632,0.00030934430647050037,-0.019785256105176847,-0.018125761307681548,-0.013859997564311007,0.005678
042941435041],"Error":0.2071270120537952,"Adjustment":0.00022749533503982792,"Height":1.038380890255847e-05}
...
```

It's a bunch of single lines, so should be pretty easy to grep | awk to pull out the info. If I can come up with something cleaner I'll report back.

**Comment by Amit-PivotalLabs** [comment]
Thanks @slackpad!

We'll have a think about using that, but we have a workaround if there are any issues with it.  As usual, thanks for all the help.

**Comment by slackpad** [comment]
No problem - I'll close this out for now since I think we've got everything addressed. Feel free to shoot any further questions on here and I can re-open.

**Comment by iverberk** [comment]
We hit more or less the same issue yesterday. I can reproduce the problem very simply:

1. Start three virtual machines in a private network (let's say 192.168.33.5 , .6 and .7)
2. Start consul on all three with the following command:

```
./consul agent -bind=192.168.33.5 -client=192.168.33.5 -data-dir=./data -server -ui -node=consulX -bootstrap-expect=3 -log-level=debug
```
Replace the 'X' with number 1,2,3.
3. Issue a join to form the cluster:
```
./consul join -rpc-addr=192.168.33.6:8400 192.168.33.5 192.168.33.6 192.168.33.7
```
4. The cluster is successfully formed. Now do a graceful leave of node 1:
```
./consul leave -rpc-addr=192.168.33.5:8400
```
5. The node is removed and in the 'left' state. Now restart the agent but change the node name to something else than it was before.
6. Issue the same join command. The node will appear as a new node, but share the ip with the node that we previously put in the 'left' state. It's still the same VM but Serf(?) registers it as a new node.
7. Now watch it all fall apart. It seems that it gets stuck in some kind of loop where the peer-set is sometimes all three servers and then falls back to two.

Logs:
Node1: http://pastebin.com/N4DBJz2W
Node2: http://pastebin.com/v4BFHuDx
Node3: http://pastebin.com/VZhg3tZe

We even cleared the data directory for the restarted node and rejoined with the old name but it stays unstable with occasional leader loss. Any ideas what is going wrong here and how to recover without tearing it all down?

**Comment by iverberk** [comment]
@slackpad do you have any insight on what's happening here? Can we rename a server while keeping the same ip address?

**Comment by slackpad** [comment]
Closing this out against https://github.com/hashicorp/consul/issues/1580, which captures handling IP address changes.

**Comment by eknudtson** [comment]
Just ran into this the other day while renaming a server on 0.8.0.
