### ISSUE TITLE
Register a service without local agent running

### ISSUE THREAD

**Issue by ofbizbrazil** [hashicorp/consul#2173]
I have registered a service using Spring Cloud Consul, but for this I had to run a Consul local agent which establishes a channel communication to Consul server node (running as bootstrap).

For example:
```
#Server
consul agent -server -bootstrap -bind -data-dir data -ui-dir web_ui

#Desktop
consul agent -data-dir consul -ui-dir consul/dist -join server_ip_address
```

Is there any way to avoid of having this local agent in my desktop, I mean from my desktop Spring Cloud Consul would register the service to server node?

An example of this is what Netflix Eureka client does with Netflix Eureka server, no external agents running in machines to bind services names.

**Comment by Kenovo** [comment]
(imo) You must have a consult agent running for consul to work because of health checks, DNS service and key/value store, Gossip Protocol ... Let me know if i am wrong :+1:

**Comment by slackpad** [comment]
Hi @ofbizbrazil, @Kenovo is right that Consul is designed around running an agent on every node and registering the services on a given node with the local agent. There's a layer of health check that the Consul agent's do through the gossip protocol, so if the agent fails it will take its services out of service discovery (such as via DNS). Also, the agent use the cluster's gossip mechanism in order to locate the Consul servers, manage connections to them, and deal with server failures for you. If you don't run local agents then you'd have to deal with all that in your application which isn't ideal. It's technically possible to use the Catalog API to do everything manually without an agent, but that's not taking advantage of a lot that Consul offers. Hope that helps!

**Comment by bhargavchukka234** [comment]
hi @slackpad can you share me how to use Catalog API to register a service without running an agent

**Comment by slackpad** [comment]
Hi @bhargavchukka234 you'd point your application at the Consul servers and interact with https://www.consul.io/docs/agent/http/catalog.html directly.
