### ISSUE TITLE
Consul Connect: Can't connect to a sidecar service from another datacenter after upgrading to Workload Identities

### ISSUE THREAD

**Issue by Himura2la** [hashicorp/consul#21863]
#### Overview of the Issue

We have several consul+nomad datacenters with Service Mesh. Before migrating to Workload Identities, we were able to add the following block to a job spec (and configure intensions) to connect a task to a service in another datacenter:

```hcl
service {
  connect {
    sidecar_service {
      proxy {
        upstreams {
          destination_name = "external-service"
          local_bind_port  = 28621
          datacenter = "dc2"
        }
      }
    }
  }
}
```

But after the job redeploys with workload identities enabled, the connection is lost. 

---

#### Reproduction Steps

1. Upgrade an existing consul+nomad cluster to workload identities
2. Try to deploy a job that connects to a service in another datacenter via service mesh/consul connect (no gateway)
3. `curl http://$NOMAD_UPSTREAM_ADDR_external_service` does not work.

### Consul info for both Client and Server

<details>
  <summary>Client and server version</summary>
<pre>
build:
        prerelease =
        revision = 9f62fb41
        version = 1.19.1
        version_metadata =
</pre>
</details>

### Operating system and Environment details

Debian 12, amd64

### Log Fragments

Here are some suspicious lines in the log, though I'm not sure that these lines are related to the issue:

```
2024-10-17T17:35:46.100+0300 [WARN]  client.alloc_runner.task_runner.task_hook.api: error creating task api socket: alloc_id=9eb232c4-f492-1b79-c4f3-311d3de5a950 task=connect-proxy-my-service path=/opt/nomad/alloc/9eb232c4-f492-1b79-c4f3-311d3de5a950/connect-proxy-my-service/secrets/api.sock error="listen unix /opt/nomad/alloc/9eb232c4-f492-1b79-c4f3-311d3de5a950/connect-proxy-my-service/secrets/api.sock: bind: invalid argument"

envoy_bootstrap: error creating bootstrap configuration for Connect proxy sidecar: exit status 1; see: <https://developer.hashicorp.com/nomad/s/envoy-bootstrap-error>            

2024-10-17T17:35:46.355+0300 [ERROR] agent.http: Request error: method=GET url=/v1/agent/service/_nomad-task-9eb232c4-f492-1b79-c4f3-311d3de5a950-group-my-service-my-service--sidecar-proxy from=169.254.1.1:32772 error="unknown service ID: _nomad-task-9eb232c4-f492-1b79-c4f3-311d3de5a950-group-my-service-my-service--sidecar-proxy"
```

**Comment by blake** [comment]
@Himura2la Can you please provide a copy of your Nomad job spec and details of how you have configured the Consul ACL binding rule(s)?

**Comment by Himura2la** [comment]
## Sample jobspecs:

```
job "service-consumer-test" {
    datacenters = ["dc1"]
    group "service-consumer-test" {
        task "service-consumer-test" {
            driver = "docker"
            config {
                image = "alpine"
                interactive = true
            }
        }
        service {
            name = "service-consumer-test"
            connect {
                sidecar_service {
                    proxy {
                        upstreams {
                            destination_name = "service-provider-test"
                            local_bind_address = "127.0.0.1"
                            local_bind_port  = 8080
                            datacenter = "dc2"
                        }
                    }
                }
            }
        }
        network {
            mode = "bridge"
        }
    }
}
```

```
job "service-provider-test" {
    datacenters = ["dc2"]
    group "service-provider-test" {
        task "service-provider-test" {
            driver = "docker"
            config {
                image = "nginx"
            }
        }
        service {
            name = "service-provider-test"
            port = 80
            connect {
                sidecar_service { }
            }
        }
        network {
            mode = "bridge"
        }
    }
}
```

## Intensions:

![Screenshot 2024-10-22 190135](https://github.com/user-attachments/assets/084f447d-4e1d-483e-9078-2017536e9482)

## The result:

```
$ nomad alloc exec -i -t -task service-consumer-test 8128ab4d /bin/sh
/ # wget -O- http://127.0.0.1:8080
Connecting to 127.0.0.1:8080 (127.0.0.1:8080)
wget: error getting response: Connection reset by peer
```

When I deploy them in the same datacenter, I get the correct response.

## Service identity ACL :
### dc1

Scope:    local 
```
service "service-consumer-test" {
	policy = "write"
}
service "service-consumer-test-sidecar-proxy" {
	policy = "write"
}
service_prefix "" {
	policy = "read"
}
node_prefix "" {
	policy = "read"
}
```


### dc2

Scope:    local 
```
service "service-provider-test" {
	policy = "write"
}
service "service-provider-test-sidecar-proxy" {
	policy = "write"
}
service_prefix "" {
	policy = "read"
}
node_prefix "" {
	policy = "read"
}
```

Seems like I can't change these generated policies, because they were generated by binding-rule with bind-type='service', as per [the manual](https://developer.hashicorp.com/nomad/docs/integrations/consul/acl#migrating-to-using-workload-identity-with-consul)

**Comment by rboyer** [comment]
Consul auth methods can either vend tokens of the "global" or "local" variety controlled by [this field on the auth method definition](https://developer.hashicorp.com/consul/api-docs/acl/auth-methods#tokenlocality-1). Local tokens are usable only with the same Consul cluster that created them, and are not replicated or otherwise usable in other connected Consul datacenters.

Notably, if a Consul server detects that a RPC destined to be forwarded to another datacenter is using a local token, that token is stripped before the forward (because it wouldn't work anyway). The request arrives at the other side token-less.

The suggested setup of the Consul auth method used for Nomad workload identities sets up tokens in "local" mode. This differs from how Nomad vended Consul tokens prior to workload identities, where tokens were created in "global" mode and would be usable everywhere.

If you wish to simply restore the prior behavior, update [the field](https://developer.hashicorp.com/consul/api-docs/acl/auth-methods#tokenlocality-1) appropriately.

There is a big resiliency catch however to be aware of before making this change blindly. Global Consul tokens write RPCs are *always forwarded to the primary datacenter*. The data is written there exclusively and *asynchronously replicated to all connected secondaries* with [acl token replication enabled](https://developer.hashicorp.com/consul/docs/agent/config/config-files#acl_enable_token_replication).
  * If a secondary datacenter tries to create a new Consul token for use in a just-launching-nomad-job, and the primary Consul datacenter is down or otherwise partitioned from the secondary *then token creation will fail, as will the job launch*. 
  * If replication is slow, or the two networks are far enough away, this can mean that a secondary datacenter may not be able to immediately use a token it just created if the read happens too quickly after the write before the replication has occurred.

Over in [`consul-k8s`](https://developer.hashicorp.com/consul/docs/k8s) there is a nearly identical situation when multiple consul clusters on Kubernetes are federated and in that situation we have chosen the following:

- Each k8s cluster gets its own auth method, in `local` mode.
- To handle cross-cluster service discovery we install a very liberal `service:*:read + node:*:read` policy for the anonymous token.

So for your situation you could either choose to use global tokens, or possibly mirror the k8s solution with local tokens and a liberal anonymous policy.

**Comment by Himura2la** [comment]
Thank you for the detailed research and explanation, I really appreciate it! I decided to give permissions to the anonymous token, and seems like it works now! But I still have some questions left:

1. In the legacy approach (before workload identities) the service tokens were also local, but for some reason everything worked. What exactly changed?
2. The [Consul Service Mesh | ACLs](https://developer.hashicorp.com/nomad/docs/integrations/consul/service-mesh#consul-acls) paragraph states that the following: 
    > Consul agents will need to be configured with [default anonymous](https://developer.hashicorp.com/consul/docs/security/acl/acl-tokens#special-purpose-tokens) *(broken link, btw)* ACL tokens with ACL policies of sufficient permissions
    When I read it, it seems like they say about consul agent tokens (node identities) from consul agent configs, but in reality I should add permissions to the `00000000-0000-0000-0000-000000000002` token. Why is it so? I thought the anonymous token should never be used if all agents have their own tokens. I even checked it right now: the `consul acl token read -self` with no `CONSUL_HTTP_TOKEN` var gives a token of a random consul server... Why stripped token leads to using the `00000000-0000-0000-0000-000000000002` instead of a node identity token?

**Comment by rboyer** [comment]
> In the legacy approach (before workload identities) service identity tokens were also local, but for some reason everything worked. What exactly changed?

Not sure how that worked in the pre-WI setup then. I falsely was assuming y'all had been using the default/global setting for that previously. I guess if the secondary datacenter had ACLs configured as `default_policy = "allow"` then it could have worked, but then you would have had to set that up yourself and also change it co-incident with the nomad switch to WIs. :shrug: 

> The [Consul Service Mesh | ACLs](https://developer.hashicorp.com/nomad/docs/integrations/consul/service-mesh#consul-acls) paragraph states:
> 
> Consul agents will need to be configured with [default anonymous](https://developer.hashicorp.com/consul/docs/security/acl/acl-tokens#special-purpose-tokens) (broken link, btw) ACL tokens with ACL policies of sufficient permissions.

> When I read it, it seems like they say about consul agent tokens (node identities) from consul agent configs, but in reality I should add permissions to the 00000000-0000-0000-0000-000000000002 token. Why is it so? I thought the anonymous token should never be used if all agents have their own tokens. I even checked it right now: the consul acl token read -self with no CONSUL_HTTP_TOKEN var gives a token of a random consul server (we use DNS balancing)... Why stripped token leads to using the 00000000-0000-0000-0000-000000000002 instead of a node identity token?

I believe the wording of that section of the Nomad docs could be improved.

Consul agent's will **only** use their `agent` token for their own internal purposes, typically just related to service registration anti-entropy. They will not use this for RPCs or user requests. This token typically needs `node:MACHINE-NAME:write` and nothing else.

If a request comes into the http API without a token it first tries to use the `default/user` token, and if that is not configured it will use the empty string for the token (which implies the anonymous token).

**Comment by Himura2la** [comment]
Thank you for explaining, I just noticed that we use agent tokens in `acl.tokens.default` instead of `acl.tokens.agent` option, and we don't expect to ever fallback to the anonymous token. 
And for some reason, the node's default token is not used in cross-dc requests with local tokens.
Anyway, it's clear now, thanks a lot for help <3
