### ISSUE TITLE
Healthcheck should be checked immediately after service registered 

### ISSUE THREAD

**Issue by janisz** [hashicorp/consul#2314]
Healthcheck is now checked with some delay so service after registration appear as unhealthy when actually it's healthy. To solve this problem health should be checked just after service is registered.

**Comment by kshep** [comment]
Would it be possible to perform the healthcheck *before* the service appears in the registry, so its initial status reflects the true status of the service?

**Comment by slackpad** [comment]
Hi @janisz and @kshep, some health checks can be expensive, and multiple services might get registered all in one go, such as with a `consul restart`, so we always stagger them to try to randomize their phase. You can set the initial health state, so you can default healthy or unhealthy until the first check. Having it not show up until it has run the first check is an interesting idea. It's practically the same as starting it unhealthy, but I could see how you might care about that if you have monitoring set up.

**Comment by janisz** [comment]
> You can set the initial health state, so you can default healthy or unhealthy until the first check.

How to set initial health state?

**Comment by slackpad** [comment]
There's a `status` field described in the "Initial Health Check Status" section of the [checks guide](https://www.consul.io/docs/agent/checks.html):

> By default, when checks are registered against a Consul agent, the state is set immediately to "critical". This is useful to prevent services from being registered as "passing" and entering the service pool before they are confirmed to be healthy. In certain cases, it may be desirable to specify the initial state of a health check. This can be done by specifying the status field in a health check definition, like so:

```
{
  "check": {
    "id": "mem",
    "script": "/bin/check_mem",
    "interval": "10s",
    "status": "passing"
  }
}
```

> The above service definition would cause the new "mem" check to be registered with its initial state set to "passing".

**Comment by kshep** [comment]
>You can set the initial health state, so you can default healthy or unhealthy until the first check. Having it not show up until it has run the first check is an interesting idea.

It'd be slick if there were either a fourth(?) initial health status like 'check' that indicated the corresponding service shouldn't be registered until a check is performed.

> It's practically the same as starting it unhealthy, but I could see how you might care about that if you have monitoring set up.

That's exactly our use case.

**Comment by takeda** [comment]
This is related to #2450, my take on that when new healthcheck is added consul should keep the same state of the service until healthcheck is performed. Perhaps this could be implemented by having initial state "unknown"? that makes consul not take it into account when determining service state. Of course this is only when check was added while consul was running, otherwise old behavior is fine.

**Comment by Kane-Sendgrid** [comment]
Btw, I've found that initial status is not always respected. I set initial status to "passing"
```
service := &api.AgentServiceRegistration{
    Name: c.groupName,
    Port: 50511,
    Checks: api.AgentServiceChecks{
        &api.AgentServiceCheck{
            HTTP:     "http://127.0.0.1:50513/healthcheck",
            Interval: "10s",
            Status:   "passing",
        },
    },
}
err := agent.ServiceRegister(service)
```

Randomly service starts in "critical" state until first healthcheck is ran (actually that happens more often than not). Tried on 0.7.3.

**Comment by saule1508** [comment]
I have a script check for which the frequency can be very low (either because the check is expensive or because we don't immediate feedback), for example a check on a disk array. If I set the interval to 1hour, then during 1 hour after startup my check will critical (or Passing if I use the status field, but in my case the use case is that after boot the user will check the health).
What I would need is a way to specifiy an interval + a way to express that the first check should be done immediately and not at the end of the first interval.

**Comment by ChipV223** [comment]
Hi all!

I'm messing around with this using the latest version(v1.9.4) and I'm noticing that both the service and its healthcheck are both synced in the catalog as soon as the service is registered:

```
2021-04-08T12:48:58.148-0400 [INFO]  agent: Synced service: service=default/simpleHTTP
    2021-04-08T12:48:58.149-0400 [DEBUG] agent: Check in sync: check=default/SimpleHTTPServer-service
    2021-04-08T12:48:58.149-0400 [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/register from=127.0.0.1:9196 latency=10.3516ms

    2021-04-08T12:48:58.149-0400 [DEBUG] agent.http: Request finished: method=GET url=/v1/internal/ui/services?dc=dc1&index=11255 from=[::1]:9192 latency=8.7607534s
    2021-04-08T12:48:58.149-0400 [DEBUG] agent.http: Request finished: method=GET url=/v1/internal/ui/nodes?dc=dc1&index=11255 from=[::1]:9192 latency=7.9239267s
    2021-04-08T12:48:58.150-0400 [DEBUG] agent: Node info in sync
    2021-04-08T12:48:58.163-0400 [DEBUG] agent: Service in sync: service=default/simpleHTTP
    2021-04-08T12:48:58.166-0400 [DEBUG] agent: Check in sync: check=default/SimpleHTTPServer-service
    2021-04-08T12:49:24.593-0400 [DEBUG] agent: Check status updated: check=default/SimpleHTTPServer-service status=passing
    2021-04-08T12:49:54.558-0400 [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
    2021-04-08T12:49:54.558-0400 [DEBUG] agent: Node info in sync
    2021-04-08T12:49:54.558-0400 [DEBUG] agent: Service in sync: service=default/simpleHTTP
    2021-04-08T12:49:54.559-0400 [DEBUG] agent: Check in sync: check=default/SimpleHTTPServer-service
    2021-04-08T12:49:54.903-0400 [DEBUG] agent: Check status updated: check=default/SimpleHTTPServer-service status=passing
```

Furthermore, when I was investigating the issue that @kanekv brought that the status field was not being respected, I'm not seeing that behavior in my end. I currently have the status as `passing` in my service payload

```
{
  "service": {
    "name": "SimpleHTTPServer",
	"id": "simpleHTTP",
    "port": 8080,
    "tags": ["simpleHTTP"],
	"check": {
       "name": "SimpleHTTPServer HTTP Health Check",
	   "id": "SimpleHTTPServer-service",
       "HTTP": "http://localhost:8080",
       "interval": "30s",
	   "status": "passing"
    }
  }
}
```

and as soon as the service is introduced in Consul, the status shows up as passing both in the logs as well as the `Services` tab in the Consul UI.

I'll go ahead and close this since the many improvements in the past couple of years have led to a better experience with registering services + healthchecks, but do feel free to reach out if any of you have any questions!
