### ISSUE TITLE
deregister_critical_service_after works only with service_id defined

### ISSUE THREAD

**Issue by sokie** [hashicorp/consul#2338]
Consul version: 0.7.0 rc2
With the new consul 0.7.0, we added support for `deregister_critical_service_after`. This currently works only for checks with `service_id` defined, but it would be useful to have it for generic checks that apply for all services ( that may be considered as critical ).

**Comment by slackpad** [comment]
Hi @sokie which service would get deregistered in that case? It seems unexpected if all services get deregistered.

**Comment by sokie** [comment]
If we register a health check without service_id, then it gets registered on all services. 
If the check for that service fails ( eg. out of memory check ), then it means all the services that fail that check will be deregistered.

**Comment by slackpad** [comment]
Hi @sokie Consul will already stop giving any service on a node with a failing node-level check out over DNS. It seems a little strange to actually deregister them because you'd then need to have all of your services know how to re-register themselves after this condition clears. We targeted the `deregister_critical_service_after` at specific services under the assumption that it's registering itself or it's a one-shot kind of thing _and_ that the check is making sure the service is still there and alive. Having node-level checks cause services to be deregistered seems like it will lead to a lot of confusion for operators.
