### ISSUE TITLE
[Security] /v1/acl/info/<ID> endpoint is open for anybody

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#2422]
### `consul version` for both Client and Server
Client: `Consul v0.7.0`
Server: `Consul v0.7.0`

### Operating system and Environment details
ACLs enabled, anonymous user's ACL is

```
service "" {
    policy = "read"
}

query "" {
    policy = "read"
}
```

### Description of the Issue (and unexpected/desired result)

An anonymous user is able to retrieve ACL definitions.

Expected result: HTTP 403.

### Reproduction steps

Create an ACL, use it ID from incognito browser window to access `/v1/acl/info/<ID>`

**Comment by slackpad** [comment]
Hi @Ashald in this case the user needs the ID of a valid token in order to get information about it, so this doesn't expose any information to an anonymous user who doesn't have a given token already. The /v1/acl/list endpoint is protected so anonymous users can't list ACLs and discover new tokens. 

Thanks for taking the time to report this issue, but for security-related matters, we ask that you use our responsible disclosure policy https://hashicorp.com/security.html.
