### ISSUE TITLE
option for autoderegister service after specific number of failure

### ISSUE THREAD

**Issue by raisomain** [hashicorp/consul#2445]
As title says

currently DeregisterCriticalServiceAfter value specify service removal after a specific time period.
It would be great if there's a config to specify service removal after specified fail healthcheck,
ex: removal after 10 times failed healthcheck

**Comment by slackpad** [comment]
Hi @raisomain thanks for opening an issue. We looked at this method when we added the feature but it added a bit more complexity internally (we'd have to track counts and time) so we opted for the time period since that covered a more general set of use cases. Also, it would add more complexity to the config. You should be able to set it to N times the interval to get roughly the same behavior.
