### ISSUE TITLE
Metrics issues can prevent Consul agent from starting

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2567]
If there's an issue with Circonus (in our case we hit a usage limit) we weren't able to start the Consul agent at all:

```
==> Failed to start Circonus sink. Got: [ERROR] API response code 400:...
```

Since we are depending on an external service, we should probably be robust to outages there. A few different mitigations might be possible:

1. Print a warning and periodically retry, adding the sink when Circonus is available.
2. Print a warning and skip creating the sink.
3. Register a health check for metics that we can set to a failed state if we have issues with an external metrics provider.

This probably isn't limited to Circonus so we should apply whatever we do to all of them.

/cc @phinze @sean-

**Comment by maier** [comment]
I copied what the other sinks were doing w/re to emit error and return 1. For us, specifically, it may be best to just emit the error and skip adding the sink so that any other sinks would still function and the process as a whole would proceed. If metrics are not flowing as expected the first thing to do would be to look at the log to see if there was a error initializing the sink.

**Comment by slackpad** [comment]
Closing per the linked issue above - since go-metrics doesn't have an API that would easily support retries outside of a sink, this is probably our best option.
