### ISSUE TITLE
GraphQL endpoint

### ISSUE THREAD

**Issue by mytototo** [hashicorp/consul#2589]
Hey,

Do you have plans about a GraphQL endpoint admin so we can consume it instead of the REST API ? Way much easier for a dashboard.

Thanks.

**Comment by jippi** [comment]
since this is repeated in https://github.com/hashicorp/nomad/issues/2080 and https://github.com/hashicorp/vault/issues/2174 as well, I'll just keep my comment here

My personal feeling is that the current REST API is more than sufficient, and a GraphQL version of the API should be maintained as a 3rd party (hashicorp or community) layer on top, rather than bundled inside each project. 

Would be surprised if this was a pre 1.x feature for any of the projects you requested it for tbh

**Comment by mytototo** [comment]
I understand your point of view. Thank you for your quick answer @jippi.

**Comment by jippi** [comment]
@mytototo keep in mind I'm not in any way associated with HashiCorp here, just voicing my own opinion on it :)

**Comment by mytototo** [comment]
Oh ok! Keeping it open waiting for an official answer then. But I guess your point of view is right.

**Comment by slackpad** [comment]
Agree with @jippi on this one :-) This isn't on the roadmap at this time.
