### ISSUE TITLE
QName Invalid Error Message

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/consul#2625]
Consul keeps reporting this error message in our logs and the reported domains are all valid domains.
```
QName Invalid: <domain name>
```
Do you have some hints on how to go about debugging this? To give an overview of the configuration:
* Every machine has `consul` as the DNS server
* `consul` has the config entry for `recurse` to the data center DNS 
* The `/etc/resolv.conf` has the data center domain name as the first `search` entry followed by the `consul` domain
### `consul version` for both Client and Server
Client: `0.7.0`
Server: `0.7.0`

### Operating system and Environment details
Ubuntu 14.04

**Comment by slackpad** [comment]
Hi @vrenjith that error is produced when consul is given a name that it is supposed to resolve (something in `.consul.`) but it doesn't parse correctly. Can you share an example name that's failing?

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.

**Comment by cmarasescu** [comment]
Hello @spawluk ,

This warning usually occurs because of the "search" directive in /etc/resolv.conf.
Let's say you have an address to search such as "example.wrong.address".
Your DNS client will try to search it against you primary DNS servers, and then will try to append the domain suffix and eventually will try to append the search suffix.

For example, if you have the following line in /etc/resolv.conf:
search mydomain.local testing.consul

You will probably have errors thrown by consul:
[WARN] dns: QName invalid: example.wrong.address.testing
