### ISSUE TITLE
Customise min supported version of TLS and cipher suites

### ISSUE THREAD

**Issue by iammyr** [hashicorp/consul#2664]
Hi all, 

thanks for the amazing job you're all doing with Consul!
However, I could not find any mention of which cipher suites are supported by Consul when implementing TLS. @macb [mentioned](https://github.com/hashicorp/consul/issues/1349) Consul relies on Golang (now updated to the latest 1.7 version) which supports TLS back to TLS 1.0 included.

1. Could you please tell me which cipher suites are supported?

I found AES-GCM 128, using PKCS7 padding and AES-GCM 128, no padding mentioned at [security.go](https://github.com/hashicorp/consul/blob/6f0a3b9bf5c7fd0673213d451bbc9e66f7a9cad9/vendor/github.com/hashicorp/memberlist/security.go). Could you kindly confirm please that those are the ciphers specified by Consul for the TLS configuration that Golang needs to be fed with?

2. Also, usually a cipher suite for TLS is comprised of key-exchange algorithm, bulk cipher algorithm and MAC (Hash) algorithm, e.g. TLS_RSA_WITH_3DES_EDE_CBC_SHA. Since in the mention of "AES-GCM 128" AES is for key exchange and GCM is the bulk cipher alg, which hash algorithm are you using?

3. Finally, it would be great to have the possibility to customise the cipher suites used and the minimum supported version of TLS.

Thanks a lot in advance.

**Comment by slackpad** [comment]
Hi @iammyr thanks for the kind words!

Consul's Go TLS config is set up here - https://github.com/hashicorp/consul/blob/master/tlsutil/config.go. We don't make any tweaks to the `CipherSuites` configuration, so the implementation is up to the Go library (depending on the version of TLS in use). I'd point you at the Go library implementation for details about which are preferred and supported, since Consul lets the library decide what to use.

In #2699 we just added the ability to configure a minimum TLS version for Consul (that will ship shortly in Consul 0.7.4). We currently don't have plans to allow customization of specific cipher suites unless there's a lot of demand for it. Hope that helps!
