### ISSUE TITLE
Feature request: DNS TXT resource records

### ISSUE THREAD

**Issue by sodre** [hashicorp/consul#2709]
@sean- 

As discussed, It would be useful for Consul to serve TXT records at multiple levels in the domain hierarchy. One use-case in mind is a Kerberized cluster configured purely through DNS. This requires that the DNS server respond to `TXT _kerberos[.data center]<.domain>` with the configured realm name.

One thought is to store this information is in the key-value store, perhaps in a format such as...
key: `/service/dns/req=TXT/<FQDN>` value: `TXTDATA`.

**Comment by slackpad** [comment]
There might be a nice path for this now that we have node metadata, and we plan on service metadata as well.

**Comment by sodre** [comment]
That would be awesome. Can you point me to an example of how to use the metadata? I can try to come up with the first version of this feature.

**Comment by slackpad** [comment]
Node metadata is configured in https://www.consul.io/docs/agent/options.html#node_meta, and is exposed in all the catalog and health APIs.

**Comment by slackpad** [comment]
Closed via https://github.com/hashicorp/consul/pull/3343.

**Comment by sodre** [comment]
This is not fully addressed yet. For example, there is no way to assign TXT records to the base domain yet.

**Comment by neurostream** [comment]
In case anyone else also arrives here wondering about how the DNS API for a TXT record might translate to the HTTP API, here were a couple related thoughts I've discussed with other colleagues/Consul fans: 

The basic feature model of Consul that circles around one's head is, especially from the HTTP API perspective, primarily:

```
- Nodes
- Services
- KV
```


From the DNS API perspective, it might seem to follow such that:

```
- Nodes    = DNS Resource Record Type: "A" 
- Services = DNS Resource Record Type: "SRV"
- KV       = DNS Resource Record Type: "TXT"
```

First consider the way "Nodes" are mapped under _.node.consul_, and the way "Services" are mapped under _.service.consul_.  And then consider that a "Value" of a Consul K:V pair would fit naturally into a TXT record - but mapping the kv/path/for/the/Key to a ( for example ) _.kv.consul_ domain name doesn't quite hold up.  

_key.the.for.path.kv.consul_ or _path-for-the-key.kv.consul_ would seem to be a bit presumptuous - either for subdomain levels that are too deep or to presume it OK re-format the kv/path/for/the/Key with some other DNS domain -friendly delimiter in order to key in from a single domain name level below .kv.consul.  base64 encoding the URL KV path/for/the/key into a single DNS domain name level might end up with an '=' sign or other non-DNS friendly DNS record names.

So, Node meta data seems like a good way to not let go to waste a super-handy DNS TXT resource record type.

**Comment by rtbellows** [comment]
Any chance of getting servicemeta returned as TXT records through consul dns? This would be very useful for DNS-01 letsencrypt challenges, for example.

**Comment by sodre** [comment]
I am willing to implement if you post my me to where the metadata for services is stored. This should be no different from what I did with nodes.

**Comment by i0rek** [comment]
I am closing this issue since the corresponding PR was also closed. We don't have time to add this feature, but I would be happy to review a PR and provide feedback. Thanks all!
