### ISSUE TITLE
/v1/agent/service/register with node address and service address ?

### ISSUE THREAD

**Issue by grosser** [hashicorp/consul#2756]
I'm trying to register a service via http api that has a health check, but I also want to specify the Node / Node-Address and ServiceAddress ... how would I do that ... googled a bunch and looked at the docs in https://www.consul.io/docs/agent/http/agent.html#agent_service_register but cannot find anything :(

**Comment by grosser** [comment]
ah ok ... so the /agent only operates on the local node ... so no need to set node name and address

**Comment by lpmontx** [comment]
Somewhat related:   Docs I see suggest using agent (not catalog) for service registration with a local client.  This thread suggests node is implied from the clients node  ( I agree and understand).   However the agent API  does not support node metadata and the catalog API does.    I want to register with node metadata (like OS name and version). I see no way to do that with agent API.  I know how to do it with catalog API but based on reading it seems to be incorrect to call catalog API on local client instance.    Please advise.

**Comment by slackpad** [comment]
@lpmontx node-metadata can be set per-service (we have plans to eventually add service-meta for this), but for now the only service-level attributes you can use for those kinds of use cases are tags. Things like OS name and version should be set when your agent starts up, though, not when services are registered, since that is global to the whole agent.
