### ISSUE TITLE
make consul/api not depend on serf/coordinate

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#2758]
`github.com/hashicorp/consul/api` has two transitive dependencies:

* `github.com/hashicorp/go-cleanhttp`
* `github.com/hashicorp/serf/coordinate`

As a lightweight client library I can understand the `go-cleanhttp` dependency to help with the actual REST parts of the api.  What doesn't make sense is exposing serf internals in the client library like that.

Is this dependency actually desirable, or can it be broken safely with some light copying?

**Comment by slackpad** [comment]
Hi @rboyer we could probably remove the dependency, though there is some behavior that's pretty useful (https://github.com/hashicorp/serf/blob/master/coordinate/coordinate.go#L99-L112) since these are a little weird to interpret and would be unfortunate to duplicate. That's part of the reason we broke the coordinate calculation part out of Serf.

**Comment by slackpad** [comment]
Will keep the dep for now since there's non-trivial behavior in there that's related to the API types.
