### ISSUE TITLE
Consul Vault TLS mode setup

### ISSUE THREAD

**Issue by sbatchu0108** [hashicorp/consul#2873]
I'm trying to setup Vault HA using consul with TLS mode enabled.

I have 3 ec2 instances(Node A,B,C) running consul client+vault and 3 other ec2 instances(Node D,E,F) which are running consul server cluster.

Vault Version:
```
Vault v0.7.0
```
Consul Client
```
Consul v0.7.5
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
Vault Config on Node A (Similar Config on Node B, C):
```
backend "consul" {
  address = "NodeAIP:8080"
  path = "vault"
  scheme = "https"
  tls_cert_file = "/etc/vault.d/tls/vault.crt"
  tls_key_file = "/etc/vault.d/tls/vault.key"
  tls_ca_file = "/etc/vault.d/tls/root.cer" 
}

listener "tcp" {
 address = "NodeAIP:443"
 tls_cert_file = "/etc/vault.d/tls/vault.crt"
 tls_key_file = "/etc/vault.d/tls/vault.key"
}

disable_mlock=true
```
Consul Client Config on Node A (Similar Config on Node B, C):
```
{
  "datacenter": "us-east-1",
  "data_dir": "/var/lib/consul",
  "ui_dir": "/opt/consul/web_ui",
  "disable_update_check": true,
  "log_level": "INFO",
  "enable_syslog": true,
  "enable_debug": true,
  "server": false,
  "service": {
    "name": "Apache",
    "tags": [
      "HTTP"
    ],
    "port": 80,
    "check": {
      "script": "curl localhost >/dev/null 2>&1",
      "interval": "10s"
    }
  },
  "node_name": "consulclient1",
  "rejoin_after_leave": true,
  "retry_join_ec2": {
    "tag_key": "consul",
    "tag_value": "consulserver"
  },
  "verify_outgoing": true,
  "verify_incoming": true,
  "key_file": "/etc/consul.d/tls/vault.key",
  "cert_file": "/etc/consul.d/tls/vault.crt",
  "ca_file": "/etc/consul.d/tls/root.cer",
  "addresses": {
    "https": "NodeAIP"
  },
  "ports": {
    "https": 8080
  }
}
```
Consul Client Status on NodeA:
```
==> Consul agent running!
           Version: 'v0.7.5'
           Node ID: 'xxxxx-xxxxxx-xxx'
         Node name: 'consulclient1'
        Datacenter: 'us-east-1'
            Server: false (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: 8080, DNS: 8600, RPC: 8400)
      Cluster Addr: NodeAIP (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: true, TLS-Incoming: true
             Atlas: <disabled>
```
Consul Server Config Node D(Similar Config on Node E, F):
```
{
  "disable_update_check": true,
  "data_dir": "/var/lib/consul",
  "datacenter": "us-east-1",
  "log_level": "INFO",
  "enable_syslog": true,
  "enable_debug": true,
  "server": true,
  "node_name": "consulserver1",
  "bootstrap_expect": 3,
  "leave_on_terminate": false,
  "skip_leave_on_interrupt": true,
  "rejoin_after_leave": true,
  "retry_join_ec2": {
    "tag_key": "consul",
    "tag_value": "consulserver"
  },
  "verify_outgoing": true,
  "verify_incoming": true,
  "key_file": "/etc/consul.d/tls/vault.key",
  "cert_file": "/etc/consul.d/tls/vault.crt",
  "ca_file": "/etc/consul.d/tls/root.cer",
  "ports": {
    "dns":  -1,
    "https": 8500,
    "http":  -1   }
}
```

Consul Server Agent status:
```
==> Consul agent running!
           Version: 'v0.7.5'
           Node ID: 'xxxxxx-xxxxxx--xxxx'
         Node name: 'consulserver1'
        Datacenter: 'us-east-1'
            Server: true (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: NODEDIP (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: true, TLS-Incoming: true
             Atlas: <disabled>
```

1. From the above consul agent and server status i can see TLS is enabled but I am really trying to figure out is there any way i can say communication is happening over TLS rather than from the status . I tried to parse through the consul logs but that didn't provide me valid information that i can say ok communication is over TLS. I am trying gather some logs where i can say the config which i used is really using TLS mode for compliance purpose.

2. Is my config setup flags are valid ? Is that really define the correct way of setting up the TLS ? If there any pointers or suggestions stating that i have to tweak some configs would be appreciated.

**Comment by moofish32** [comment]
@sbatchu0108  

In order to verify this to my self I did a couple of things. First remove the certs from a server and try to restart the node. The `consul members` command will show all your nodes, but check out the log which should show you:

```  
    2017/04/07 03:06:58 [ERR] agent: failed to sync remote state: No cluster leader
    2017/04/07 03:07:02 [ERR] consul.rpc: failed to read byte: tls: no certificates configured from=***masked IP info ***
    2017/04/07 03:07:03 [ERR] agent: coordinate update error: No cluster leader
    2017/04/07 03:07:03 [ERR] consul.rpc: failed to read byte: tls: no certificates configured from=*** masked IP info ***
    2017/04/07 03:07:03 [WARN] raft: Election timeout reached, restarting election
```

If that is not enough for you, the next step for me is to use tcp dump. SSH into one of the servers and install tcpdump if you need to; then run
```
sudo tcpdump -i eth0 -w /tmp/tcpdump.log -nnvvXSs 1514
```
SCP that file locally and inspect with [Wireshark](https://www.wireshark.org/). Now Wireshark will not detect TLS natively on irregular ports, so follow [these instructions](https://ask.wireshark.org/questions/34075/why-wireshark-cannot-display-tlsssl) and add 8300, 8301, and 8302 and you should see the TLS information, attached is a redacted screen shot from a local cluster:

<img width="1333" alt="screen shot 2017-04-06 at 8 15 46 pm" src="https://cloud.githubusercontent.com/assets/664280/24784303/686f7cd8-1b06-11e7-9527-f5b26c3a69cd.png">

Disable TLS on your servers and dump again to compare the difference if you like.

Your configuration looks correct for TLS, I reviewed the [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-secure-consul-with-tls-encryption-on-ubuntu-14-04) and [this](https://www.mauras.ch/securing-consul.html#tls). Something not covered in either of those but you may want to consider is separating the server and client certificates and enabling [verify_server_hostname](https://www.consul.io/docs/agent/options.html#verify_server_hostname). Those settings mitigate the ability of compromised client to escalate it self as a server. I would also disable [remote execution](https://www.consul.io/docs/agent/options.html#disable_remote_exec), this is default in 0.8 versions. You have chosen not to encrypt gossip which is easier to manage, but your compliance team might request all communication use encryption.

If this answers your question please feel free to close this issue.

**Comment by moofish32** [comment]
@sbatchu0108  -- one more comment, you no longer need ui_dir. You can simply [ui: true](https://www.consul.io/docs/agent/options.html#ui), and I would not disable mlock on vault.

**Comment by sbatchu0108** [comment]
@moofish32 Mike, i was generating self signed certificates using this link [https://dunne.io/vault-and-self-signed-ssl-certificates](url) for consul and vault. When i used the Instance IP's in the SAN name, TLS setup is working but these are dynamics instances,so we cannot go with the IP approach. I tried to use wildcard domain name but the when i try to curl the consul leader it throws me an error : 
```
curl -v https://NodeAIP:8500/v1/status/leader 
```
```
x509: cannot validate certificate for NodeAIP because it doesn't contain any IP SANs
```
Is there any other workaround to address this kind of issue ? I am trying to find some alternative solutions on how to setup the certs dynamically, any pointers/suggestions would be appreciated.

**Comment by moofish32** [comment]
@sbatchu0108 - for the UI/8500 access layer we actually use nginx in front of Consul. Pretty much like this thread states [here](https://groups.google.com/forum/#!topic/consul-tool/sWwWDEj9FKg). In addition to that set up we actually use another self signed on Nginx and we use a classic ELB with TCP pass through restricted by known IP ranges. By enforcing mutual TLS we effectively "auth" with the certificate. This allows some automation to reach into that API. Since you have Vault in this architecture you could control that certificate with PKI backend (we currently do not leverage Vault). In my conversations with other Hashi consumers, the Nginx-Vault TLS setup requires a little extra `foo` in your Consul Template to re-order the cert plus key in the PEM file.

**Comment by slackpad** [comment]
I'll close this out for now, thanks for the assist @moofish32. We also have https://www.consul.io/docs/agent/options.html#verify_incoming_https coming in 0.8.2 which lets you not verify incoming HTTPS connections, which was a popular request related to this so you don't need a proxy just to do that.
