### ISSUE TITLE
In the golang API, provide a way to cancel a blocking request

### ISSUE THREAD

**Issue by stephane-martin** [hashicorp/consul#2992]
Hello,

when performing a (HTTP) blocking request to consul, there is no way to cancel the running request (there is a timeout, though...).

It should be possible to pass a context.Context (golang >= 1.7) to the requests. For example this is useful to correctly manage program termination. Without Context, we must wait for the timeout to cleanly stop the program. With a Context, we can call the CancelFunc.

Thank you!

**Comment by slackpad** [comment]
Hi @stephane-martin thanks for opening an issue - adding context would be a nice enhancement to the API client. We don't have immediate plans to do this, but I'll tag it for future consideration (or potentially for a community PR, though we'd probably want to talk through the details first before getting into the code).

**Comment by edef1c** [comment]
9eaf56bfe33e700d913ff75a57928353a42ab37a appears to touch upon this, but doesn't really follow the recommendations of the `context` package:
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

The `net/http` API demonstrates how to handle it for structs: implement `func(*T) Context() context.Context` and `func (*T) WithContext(context.Context) *T`. Unfortunately, this is already public API as of `0.8.5`, so I'm not sure what to do about it.

In addition, that commit only covers `QueryOptions`, not `WriteOptions`, which makes it mostly useless for me. I got a little excited seeing this issue after having written my own PR, but it looks like I'll still have to maintain my own Consul client for work.

**Comment by slackpad** [comment]
We had a specific need for this internally to consul to cancel blocking
queries for watches and debated about deviating from the go guideline but
decided that the query options struct was essentially part of the function
signature and a one time use struct. We didn't want to duplicate all the
function signatures to make a with context variant, at least not yet. We
will keep thinking about the best way to use context here since this did
end up being a little non standard, but it is super useful for cancelling
long running blocking queries.

**Comment by edef1c** [comment]
My own patch just adds `Context` and `WithContext` methods to both `QueryOptions` and `WriteOptions`, which mimics with the way `net/http.Request` handles contexts. I'm not at all interested in duplicating every function to have a context parameter.
As far as I can tell, the only API function that would need to pay any attention to it is `(*Session).RenewPeriodic`.

**Comment by slackpad** [comment]
Thanks @edef1c and /cc @preetapan we should take a look at tweaking our implementation to match `net/http`, which seems like a simple change to bring it inline w/the standard lib (https://golang.org/pkg/net/http/#Request.Context) and (https://golang.org/pkg/net/http/#Request.WithContext). Seems like we should just break the API as part of 0.9 since this hasn't even been part of a major version yet.

**Comment by preetapan** [comment]
@edef1c @slackpad thanks, its not that big a change to add WithContext to bring it in line with net/http. 

`(*Session).RenewPeriodic` is tricky to get right with Context because of existing method semantics that expect it to run forever until the done channel is closed, which doesn't mesh well with anyone passing a WriteOptions with a context that has a deadline or timeout.  I am not sure if deadline even makes sense for that method, it would change the behavior of that method to be "keep renewing sessions every n seconds, but stop either after duration _K_ OR if I close the done channel". We also have to create new child contexts for every periodic http request it calls under the covers, so that cancelling the parent cancels all of them.

**Comment by edef1c** [comment]
@preetapan generally I handle context cancellation as a lightweight "kill" - no new actions should be undertaken as a result. iirc etcd's session renewal also just abandons renewal when the context is cancelled.
