### ISSUE TITLE
Possible to return ModifyIndex on KV updates

### ISSUE THREAD

**Issue by cosborne83** [hashicorp/consul#304]
It would be useful if KV updates via PUT were able to return the new ModifyIndex at least when performing CAS operations. Unless I'm missing something, as it stands it doesn't seem possible to do sequential CAS operations without an issuing a GET inbetween to determine the latest ModifyIndex for use on the next CAS update.

**Comment by semarj** [comment]
This would be useful for me as well.

**Comment by mrwilby** [comment]
I was surprised this isn't implemented. To use CAS, if I understood, I have to:

1) Get the current key value

2) Do a PUT with the index value set to either:
a) '0' if the response to Step 1 was that the key did not exist or
b) the value of the associated KV ModifyIndex returned in Step 1

3) If the prior PUT returns true, I then need to do a GET on the key in order to obtain the new ModifyIndex value. NB: The docs make no mention of whether the ModifyIndex is incremented upon success so I assume the value of ModifyIndex after a PUT is an implementation detail.

However, it's possible that after Step 3 some other client might've updated the same key, in which case my client may retrieve a new value for ModifyIndex which represents the result of the other client's PUT action, rather than the ModifyIndex value associated with Step 2.

How can my client determine the new value for ModifyIndex in (and only in) relation to Step 2 ?

Possibly I am missing the obvious here :)

**Comment by slackpad** [comment]
Hi @mrwilby you are correct - with the current implementation you can't get the ModifyIndex from your PUT without another GET, so there's the possibility of a race condition there. There's no easy way to predict the index value either (it's not a simple increment), so we really need to update the API to allow for sequential CAS operations.

**Comment by radai-rosenblatt** [comment]
+1, would indeed be useful

**Comment by donmikel** [comment]
+1

**Comment by slackpad** [comment]
This was added as part of the new /v1/txn API that shipped with Consul 0.7 - https://www.consul.io/docs/agent/http/kv.html#txn.

**Comment by slackpad** [comment]
The txn page moved to https://www.consul.io/api/txn.html.
