### ISSUE TITLE
health/service is do not working correctly in case passing parameters "near" and "passing" together

### ISSUE THREAD

**Issue by dmitriyGarden** [hashicorp/consul#3078]
Consul v0.8.2
For example curl http://127.0.0.1:8085/v1/health/service/rabbitmq?near=_agent&passing=true return all passing services, but services are not sorted by near parameter.

**Comment by dmitriyGarden** [comment]
The same problem in the preparedQuery

**Comment by slackpad** [comment]
Hi @dmitriyGarden it's your shell treating the `&` as special. If you do this it should work:

`http://127.0.0.1:8085/v1/health/service/rabbitmq?near=_agent\&passing=true `

Hope that helps!

**Comment by dmitriyGarden** [comment]
Hi. Obviously, i escaped the shell command, But
behavior  remained wrong

**Comment by slackpad** [comment]
Hmm ok will take another look.

**Comment by pearkes** [comment]
This issue was reported on a version of Consul that is quite old. Based on the volume of changes since that version we encourage you to try reproducing with the latest version of Consul. If you feel the issue is critical and on an older version of Consul, or still exists in the current version, do feel free to let us know and we can re-open it.

Thank you for your initial report, and again, do feel free to ask us to re-open or create a new issue, and be sure to include the suggested debugging information in the issue template.
