### ISSUE TITLE
Consul commands give forbidden when not in a cluster

### ISSUE THREAD

**Issue by jarro2783** [hashicorp/consul#3094]
### `consul version` for both Client and Server
Client: `0.8.3`
Server: `N/A`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 6
	services = 3
build:
	prerelease = 
	revision = ea2a82b
	version = 0.8.3
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 44
	max_procs = 2
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 599
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 113947
	members = 286
	query_queue = 0
	query_time = 2
```

But before connected also a 403.

### Operating system and Environment details

Ubuntu 16.04.

### Description of the Issue (and unexpected/desired result)

When consul is not connected to the cluster, commands such as `reload` and `info` fail with `Error reloading: Unexpected response code: 403 (Permission denied)`.

### Reproduction steps

Start consul on a host that can't connect to any masters. Run `consul reload`.

**Comment by slackpad** [comment]
Hi @jarro2783 if ACLs cannot be resolved because no servers are available, that's when the [`acl_agent_master_token`](https://www.consul.io/docs/agent/options.html#acl_agent_master_token) must be used. Take a look at the table on https://www.consul.io/docs/guides/acl.html#enabling-acls for more details. Specifically this description of the `acl_agent_master_token`:

> Special token that can be used to access Agent API when the ACL datacenter isn't available, or servers are offline (for clients); used for setting up the cluster such as doing initial join operations

An alternative is to set [`acl_down_policy`](https://www.consul.io/docs/agent/options.html#acl_down_policy) to allow on your clients, but that's a less safe configuration in general. Hope that helps!

**Comment by jarro2783** [comment]
Ok thanks. Which version was this changed in?

**Comment by slackpad** [comment]
The "version 8 ACLs" and the `acl_agent_token` were added in 0.7.2, but were off by default (https://www.consul.io/docs/agent/options.html#acl_enforce_version_8 defaulted to `false`). In 0.8.0 we defaults `acl_enforce_version_8` to `true`.
