### ISSUE TITLE
DNS Record or IP address for consul cluster

### ISSUE THREAD

**Issue by refaelyehuda** [hashicorp/consul#3168]
Hi,
I have a consul cluster and the behavior of the cluster works well but when leader server failed I need to change DNS record to the new server that takes the leadership.
My question is if there is an option to create for consul cluster IP/Record that will redirect the traffic to the new server when the leader failed and my DNS record will point to this  IP/Record ?

**Comment by magiconair** [comment]
If you query the local agent then this should do what you want since the requests are forwarded to the current leader unless you have `allow_stale` set to `true`.

**Comment by refaelyehuda** [comment]
But if the agent is down I can't query the agent and get some info. So I need a record that always point the request to the leader.
For your second question: 
I have 
"dns_config": {
        "allow_stale": true,
        "max_stale": "15s"
    },

**Comment by magiconair** [comment]
I think what you want is to make DNS queries highly available. Requests are always sent to the leader by the agents. You can make DNS highly available by adding a DNS proxy like dnsmasq in front of consul.

**Comment by magiconair** [comment]
Also, since you are allowing stale responses you get locally cached results anyway. Depending on your query load you could just point the dnsmasq instance to the servers or if you have recursion enabled make consul the primary DNS server by configuring the servers in `/etc/resolv.conf` (assuming you're on Linux or some other Unix OS)
