### ISSUE TITLE
UI dir check in #2918 breaks on Windows

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3229]
This captures the follow up from https://github.com/hashicorp/consul/pull/2918#issuecomment-313203445:

> This breaks for me on Windows, between using release `0.8.0` and `0.8.5`.  I do not use `ui_dir` (only `ui` set to `true`) in the config.  Since upgrading, I now get that (incorrect) error message, and now it will not launch.  Even adding in a line for `"ui_dir": ""` with blank string value I thought might work after looking at the diff, but does not. Maybe there is a default or something that only happens on Windows?

Simplified it down to this only to still reproduce the symptom:

```
{
  "addresses": {
    "http": "0.0.0.0"
  },
  "advertise_addr": "192.168.1.123",
  "datacenter": "foo",
  "log_level": "info",
  "node_name": "bar",
  "server": true,
  "ui": true
}
```

Results in log:
```
==> Both the ui and ui-dir flags were specified, please provide only one
```

**Comment by tylerwalts** [comment]
Thanks @slackpad  for the help.  After looking closer, I am using choco to install and manage consul via nssm, and looking deeper into how it is launched I see that the CLI is passing the ui-dir arg in. Sorry for the false alarm and I'll leave this up in case anyone else has a similar issue:

![image](https://user-images.githubusercontent.com/346433/27896185-29a1540a-61cd-11e7-81ad-7f5f66e71479.png)

My "fix" is to remove the "ui": true from my config, since the CLI arg sets the UI path out of box and it is redundant. Everything working as expected now 👍

**Comment by slackpad** [comment]
Got it - thanks for the follow up @tylerwalts. Glad it was something simple - this one didn't make sense otherwise :-)
