### ISSUE TITLE
ui: make consulHost configurable

### ISSUE THREAD

**Issue by magiconair** [hashicorp/consul#3310]
The ui has a `consulHost` option in the `index.html` file which allows the ui to run on a different server/host than the consul agent. With 0.9.0 the ui is no longer a separate download which makes it difficult to overwrite this value. 

See #3292

**Comment by jippi** [comment]
For a quick stopgap, hashi-ui got consul ui too, that support proxying directly :)

**Comment by bender316** [comment]
any news on this issue?

**Comment by johncowen** [comment]
Hi @bender316 

Apologies for the delay! I've just noticed this issue myself so the issue itself has not been on my radar. This is actually in my backlog for the new Consul UI, so that is on my radar.

I've tagged this issue as `ui` and added a link here from my backlog, I can't promise any more news on when we might add this but at least I won't lose you!

Thanks,
