### ISSUE TITLE
Adding unknown config line fails the start\reload

### ISSUE THREAD

**Issue by Moshem123** [hashicorp/consul#3325]
On consul 0.9 a new configuration property was introduced: `"enable_script_checks"`.
In order to be able to mass upgrade the consul version on multiple servers, I have added the line in advance so the update job won't fail and I won't have to change it to add the line.
Some of the servers were upgraded and some will wait couple of days but all of them have the new configuration.
The problem I'm facing is when trying to reload or restart the service on the servers that weren't upgraded, it fails probably because of an unknown configuration.
```
[root@PROD]$ consul reload
Error reloading: Unexpected response code: 500 (1 error(s) occurred:

* Failed to reload configs)

```
When removing the new added line, the reload works fine.
Since you can't comment out lines in JSON, is there any chance the next version would just ignore unknown configurations instead of failing the config files loading?
Thanks.

**Comment by FraserPol** [comment]
Hi @Moshem123 I ran into this issue as well. 

This isn't part of the reloadable configuration. It needs to be in place as part of the initial client [start](https://github.com/hashicorp/consul/issues/3323).

I rectified this by adding the configuration below;

`{
  "log_level": "trace",
  "enable_script_checks": true
}
`

Then having each Consul agent leave the cluster and rejoin.

**Comment by slackpad** [comment]
Hi @Moshem123 and thanks @FraserPol,

> Since you can't comment out lines in JSON, is there any chance the next version would just ignore unknown configurations instead of failing the config files loading?

This would unfortunately cause a lot of chaos I think, where people may be thinking they are setting a parameter but it's a typo, etc. and doesn't get applied. Even a warning would probably not be sufficient here.

This one was unusual because we were sort of introducing a breaking change not based on an existing configuration item, we don't expect to do this very often and always try to avoid this. Sorry for any trouble!

We also plan to support HCL config files soon, and those support comments :-)
