### ISSUE TITLE
web-ui missing in 0.9.0

### ISSUE THREAD

**Issue by arogozin** [hashicorp/consul#3341]
Hello, I noticed that consul_0.9.0_web_ui.zip is missing from 0.9.0 release. It is available in 0.9.0-rc1.

**Comment by preetapan** [comment]
@arogozin As of 0.9.0 we stopped including the UI as a separate package, and this was mentioned in the list of breaking changes in the changelog (https://github.com/hashicorp/consul/pull/3292).

**Comment by slackpad** [comment]
Hi @arogozin we intentionally stopped publishing that since the UI has been built in to Consul for some time. Please see https://www.consul.io/docs/upgrade-specific.html#web-ui-is-no-longer-released-separately for more details. We did realize after the release that some folks who use proxies were tweaking the web assets and deploying them, so that's being tracked in https://github.com/hashicorp/consul/issues/3310. Hope that helps!
