### ISSUE TITLE
Ability to specify separate ACL for Consul Web UI and Consul Agent

### ISSUE THREAD

**Issue by manuwelakanade** [hashicorp/consul#3399]
### `consul version` for both Client and Server
0.9.0

### Description of the Issue (and unexpected/desired result)
Setup: acl_datacenter parameter configured by all consul servers and consul agents. There is a acl_master_token configured by consul servers. All the consul agents have configured acl_token (This is set to an all allow kind of ACL) so that they can directly talk to consul servers without having to use env variable/override token every time. 
Since acl_token has been specified all the DNS lookups (nslookup, dig) from the cluster nodes is also working fine. 

Shortcoming: With the above setup, when consul UI is accessed using one of the agent endpoints 8500, all the consul services/nodes/KV entries are visible. The requirement is that even though agents should be able to talk to server and nslookups should work from nodes, consul UI should be disabled by default. 

Workaround: As a workaround, it is possible to enforce a separate restrictive ACL and use it in the Browser setting for consul web UI. But then once anybody uses "Reset Defaults" option this ACL enforcement no longer works and all the services/nodes/KV are again visible. 

![consul_settings](https://user-images.githubusercontent.com/13866824/29361589-ee48a8dc-82a5-11e7-9d78-0823ef522c50.png)

Solution: 1. Is there a way ACL enforcement can be done separately for agents and UI? That would help in such cases
2. Can the reset defaults button be removed or disabled from consul web UI. Doesnt it defeat the purpose of having the ACL Token setting for browser?

### Reproduction steps
Setup: acl_datacenter parameter configured by all consul servers and consul agents. There is a acl_master_token configured by consul servers. All the consul agents have configured acl_token so that they can directly talk to consul servers without having to use env variable/override token every time. 
Since acl_token has been specified all the DNS lookups (nslookup, dig) from the cluster nodes is also working fine. 

Try to access web UI now

**Comment by slackpad** [comment]
Hi @manuwelakanade unfortunately to Consul it can't tell when the UI is talking to it or something else, since the UI just consumes Consul's regular REST APIs. There's no way for the Consul agent to know if it is servicing a UI request or otherwise.

The best way to set up something that's read only out of the box is to run a dedicated Consul agent for hosting your UI, and give that agent an [`acl_token`](https://www.consul.io/docs/agent/options.html#acl_token) that has the correct read-only permissions you are looking for. All your other agents shouldn't run the UI and should only bind their client interfaces to loopback (or a UNIX socket) so they are not available outside the machine.

With this setup, the `acl_token` on the UI agent lets anonymous users browse in read-only mode (or whatever policy that token has), and they can set up a more powerful token in their browser for additional operations. Hope that helps!

**Comment by timm088** [comment]
@slackpad any hints or guides you can pass me to to create what you describe? i.e., an agent for only the ui, that has the acl_token with the read_only policy.

**Comment by pearkes** [comment]
@timm088 Take a look here: https://www.consul.io/docs/guides/acl.html#create-tokens-for-ui-use-optional-. You'll need to change the key policy to "read" (from write) to get what you want.
