### ISSUE TITLE
Return 404 if an item has been deleted already

### ISSUE THREAD

**Issue by drnic** [hashicorp/consul#348]
Currently `DELETE` on a non-existing item(s) returns 200. If it returned 404, and if consul-api was updated to use that distinction, then we'd have a way of knowing if someone else had already deleted a KV item (or if it never existed). 

Follow on from http://twitter.com/drnic/status/512367558566375424

**Comment by chmp** [comment]
I hope it's alright to ask for clarification on this quite old ticket. I am currently playing around with consul and have to admit I am confused by the DELETE + cas behavior. 

When the key exist the behavior of DELETE + cas is as expected

```bash
$ curl -X PUT -d "foo" localhost:8500/v1/kv/bar
true
 
$ curl -X DELETE localhost:8500/v1/kv/bar?cas=1
false
```

When I now delete the key without cas and then try to delete it again with cas, I still get the response `true` and a 200 HTTP status. Is this expected?

```bash
$ curl -X DELETE localhost:8500/v1/kv/bar
true

$ curl -X GET localhost:8500/v1/kv/bar -v
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8500 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/kv/bar HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Vary: Accept-Encoding
< X-Consul-Index: 3489
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Thu, 12 Jul 2018 17:28:39 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact 

$ curl -X DELETE localhost:8500/v1/kv/bar?cas=1 -v
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8500 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> DELETE /v1/kv/bar?cas=1 HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< Date: Thu, 12 Jul 2018 17:27:29 GMT
< Content-Length: 5
< 
true
* Connection #0 to host localhost left intact
```

I am running consul `1.2.0`.

**Comment by banks** [comment]
@chmp yep this is a regression. I spent way to long tracking down the fact that during a major refactor of state store in 2015 the specific implementation Armon made here to ensure a 404 was lost.

All other behaviour was preserved of course (just the return status) and apparently no one noticed until now.

As far as I can tell it's been this way since 0.6.0 (December 3, 2015).

Despite being a regression it's arguable whether "fixing" it is now a breaking change since there have been 3 years of different behaviour to code against in the interim. If you feel strongly about this, please open a new issue for it, it's likely we can't make the change until a minor release though (couple months out).

**Comment by chmp** [comment]
@banks, thanks for hunting down the change and clarifying. My original idea is anyway not applicable, as I overlooked a series of changes that are not caught by delete+cas and would introduce inconsistencies in the data. So I do not feel strongly about this issue.
