### ISSUE TITLE
Cluster with 2 servers not work when one server is in failed status

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#3504]
I remember from sometime on, consul supports one active/others left. 
In my case there are 2 server nodes for the cluster and when one node is down (unplugged), the cluster becomes one active/one failed,  and you will get "No Cluster leader" since then, after the offline node comes back online, the cluster didn't recover.

How to handle this situation?

**Comment by sean-** [comment]
Huh.  That certainly is an interesting problem.  Interesting.  So.

Can you explain how you think one server would know that the other is alive?  Or for that matter, how distributed consensus is supposed to operate when one half of your two servers are offline?  The servers themselves can't make forward progress because the offline server can't acknowledge the write.  I think quorum would be very difficult in this situation.  I wouldn't advise running with `-bootstrap=1`, but you could.  It also strikes me that - without further details - if you have only two servers, use of a distributed consensus system (such as `consul`) may not be an appropriate solution to your problem.  May I suggest that you familiarize yourself with the Raft protocol?

**Comment by hehailong5** [comment]
Just curious that the Consul can handle one active/others left, but Not one active/others failed. although in the former case, the quorum still does not meet.

**Comment by sean-** [comment]
Setting aside that a quorum of two is dangerous and not recommended, the handling a write to an offline node versus a write to a single node is quite different. In the case of the offline mode, the write request will block indefinitely until the offline mode comes back online. In the other case, where one server has left the quorum, the number of required writers decrements from 2 down to 1. Unless you like playing with yourself, there isn’t a lot of consensus to be had from a cluster of only one. But you can and are more than welcome to enjoy yourself because the outcome is always predictable.

But please, don’t use two servers. I’ve heard it leads to blindness. :wink:

**Comment by slackpad** [comment]
Hi @hehailong5, @sean- is right that Consul doesn't support an active/standby model. You need at least 3 servers in order to handle a single server failure without an outage. See https://www.consul.io/docs/internals/consensus.html for more details, and in particular https://www.consul.io/docs/internals/consensus.html#deployment-table. We definitely don't recommend a 2 server configuration under any circumstances, as the loss of either server would put you into an outage state. You'd have to manually recover using https://www.consul.io/docs/guides/outage.html to get the remaining server working on its own.

**Comment by slackpad** [comment]
> Just curious that the Consul can handle one active/others left, but Not one active/others failed. although in the former case, the quorum still does not meet.

You can take a cluster from 2 to 1 server if the server leaves cleanly - the leader can remove it from the quorum. If it fails, though, the leader can't make any more writes since it can't meet the 2/2 quorum needed.

**Comment by hehailong5** [comment]
@slackpad , are you saying I can still recover from one active/one failed with the outage guide? 
restarting the active node with itself in the peers.json? and -bootstrap=1 ?

**Comment by slackpad** [comment]
> @slackpad , are you saying I can still recover from one active/one failed with the outage guide?
restarting the active node with itself in the peers.json? and -bootstrap=1 ?

You won't need to set -bootstrap-expect=1, but if you shut that remaining server down and place just that server into the peers.json you should be able to recover. You really want to run 3 servers, though - Raft's not designed to run like that. This recovery is just a contingency similar to https://www.consul.io/docs/guides/outage.html#failure-of-multiple-servers-in-a-multi-server-cluster.

**Comment by hehailong5** [comment]
Appreciate your advice. thank you!
