### ISSUE TITLE
Consul CLI commands don't display detailed help

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3536]
Running any of the Consul CLI commands with `-help` or `-h` only displays the summary of the command, not any of the detailed help for the options, which is expected.

**Comment by magiconair** [comment]
I've monkey patched mitchellh/cli in May with https://github.com/hashicorp/consul/commits/c068066 to work around this issue before. Since we have refactored the config handling I can address this properly now.

**Comment by magiconair** [comment]
The main reason this breaks is that the `mitchellh/cli` library has changed its behavior some time ago to support `consul agent -h` instead of `consul -h agent`. The consequence of that change is that the `Run()` method is no longer called to populate the flag set before generating the help output. It only calls `Help()`. If the `Help()` method does not populate the flag set then no help for flags will be written. 

To fix this without monkey patching the `cli` lib again we have to refactor all commands and move the flag initialization into a separate method which is then called from both `Run()` and `Help()`.

**Comment by magiconair** [comment]
We have chosen to first backport the fix we had before and work on a better implementation after the 1.0 release. #3538 will be a basis for this but not the final implementation.
