### ISSUE TITLE
lock: transition scripts

### ISSUE THREAD

**Issue by guestisp** [hashicorp/consul#3616]
Would be great to add some transitioning script when lock is acquired/lost.

In example:

`consul lock mylock /bin/testcommand --promote /bin/mypromote --demote /bin/mydemote...`

**Comment by slackpad** [comment]
Hi @guestisp this is a pretty big difference from the normal `consul lock` behavior where it would now need to run the command even without the lock, so it might be kind of a new thing and more of a process supervisor. I think this would be better done with a wrapper script / program rather than try to take on more of that behavior in Consul's core. Also tagging https://github.com/hashicorp/consul/issues/1637 as somewhat related.
