### ISSUE TITLE
Validate Node Name with TLS Name

### ISSUE THREAD

**Issue by wkennington** [hashicorp/consul#362]
Currently, when TLS is enabled and verification is turned on it is possible to spoof another node by simply changing your node name. We should verify the name of the node with the common name or name on the certificate to provide stronger guarantees of authenticity.

**Comment by sethvargo** [comment]
Hi there,

We talked about this, and while we agree it would be a nice enhancement, this isn't something we see as a potential attack vector if you're using TLS properly. If all traffic is encrypted and you require client certificates to communicate with consul, you can sign the client certificates to IP SAN instead of the DNS issue to get around this. It's a really small surface area that's already in an isolated environment. We would gladly review a PR for this functionality, but I this is not something we will implement ourselves. Sorry!
