### ISSUE TITLE
Method post not allowed

### ISSUE THREAD

**Issue by badounan** [hashicorp/consul#3659]
When I call the cosul rest api, it returns 405: method post not allowed.

Consul version is 1.0.0.

It's very right when I use the version of 0.6.3.

I think it is a cross-domain issue. But when use put instead of post, it returns right.

I don't know why. Everyone can help me???

**Comment by slackpad** [comment]
Hi @badounan Consul 1.0 started enforcing HTTP verbs in many endpoints where before anything was allowed. It sounds like you need to use `PUT` for whatever endpoint you are having trouble with. Here's a full list of the endpoints that were locked down from the [Consul 1.0 Change Log](https://github.com/hashicorp/consul/blob/v1.0.0/CHANGELOG.md). Since older versions of Consul didn't check these, you should be able to update your client/application before upgrading Consul without any compatibility issues. Hope that helps!

| Endpoint | Required HTTP Verb |
| -------- | ------------------ |
| /v1/acl/info | GET |
| /v1/acl/list | GET |
| /v1/acl/replication | GET |
| /v1/agent/check/deregister | PUT |
| /v1/agent/check/fail | PUT |
| /v1/agent/check/pass | PUT |
| /v1/agent/check/register | PUT |
| /v1/agent/check/warn | PUT |
| /v1/agent/checks | GET |
| /v1/agent/force-leave | PUT |
| /v1/agent/join | PUT |
| /v1/agent/members | GET |
| /v1/agent/metrics | GET |
| /v1/agent/self | GET |
| /v1/agent/service/register | PUT |
| /v1/agent/service/deregister | PUT |
| /v1/agent/services | GET |
| /v1/catalog/datacenters | GET |
| /v1/catalog/deregister | PUT |
| /v1/catalog/node | GET |
| /v1/catalog/nodes | GET |
| /v1/catalog/register | PUT |
| /v1/catalog/service | GET |
| /v1/catalog/services | GET |
| /v1/coordinate/datacenters | GET |
| /v1/coordinate/nodes | GET |
| /v1/health/checks | GET |
| /v1/health/node | GET |
| /v1/health/service | GET |
| /v1/health/state | GET |
| /v1/internal/ui/node | GET |
| /v1/internal/ui/nodes | GET |
| /v1/internal/ui/services | GET |
| /v1/session/info | GET |
| /v1/session/list | GET |
| /v1/session/node | GET |
| /v1/status/leader | GET |
| /v1/status/peers | GET |
| /v1/operator/area/:uuid/members | GET |
| /v1/operator/area/:uuid/join | PUT |

**Comment by Harries** [comment]
change post to put  ，it works
