### ISSUE TITLE
Add blocking query for returning all service details

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#377]
I'm working on a utility ([riemann-consul-receiver](https://github.com/bluestatedigital/riemann-consul-receiver)) that sends Consul health check results to Riemann.  For a given service on a node, I want to include the service's tags in the event I send to Riemann.  I can accomplish this by querying Consul for the details of every service, but that means hundreds of requests to the agent every time I refresh this information, and I have no idea how fresh that data is.  

I would like an endpoint akin to `/v1/health/state/any` that returns the details of every service, and blocks until updated.

**Comment by s-christoff** [comment]
This issue was reported on a version of Consul that is quite old. Based on the volume of changes since that version we encourage you to try reproducing with the latest version of Consul. If you feel the issue is critical and on an older version of Consul, or still exists in the current version, do feel free to let us know and we can re-open it.

Thank you for your initial report, and again, do feel free to ask us to re-open or create a new issue, and be sure to include the suggested debugging information in the issue template.
