### ISSUE TITLE
consul agent -server -bootstrap -data-dir /tmp/consul..... I am trying to run the above command but I am receiving the error below:

### ISSUE THREAD

**Issue by eddamalique01** [hashicorp/consul#3790]
==> Multiple private IPv4 addresses found. Please configure one

 you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @eddamalique01 Consul's trying to determine a private IP address to bind to and/or advertise but you must be running on a machine with multiple interfaces. Usually you can configure https://www.consul.io/docs/agent/options.html#_bind in order to pick one. I'll update the error message to lead over to this configuration item. Hope that helps!
