### ISSUE TITLE
show Consul version in webui

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/consul#3856]
### Description of the Issue (and unexpected/desired result)
Currently the Consul version is not shown on the WebUI.
It would be a great if the Consul WebUI started showing the WebUI.

### `consul version` for both Client and Server
Client: `[client version here]`
1.0.3

Server: `[server version here]`
1.0.3

Regards,
Shantanu

**Comment by slackpad** [comment]
To make this work well we might want to add the Consul agent version information to the catalog so we can display it for the entire cluster in a consistent way.

We can't really make use of https://www.consul.io/api/agent.html#read-configuration or even https://www.consul.io/api/agent.html#list-members since that'll depend on the agent you are connected to, and users of the web UI are probably looking for a cluster-level result here.

**Comment by shantanugadgil** [comment]
Thanks for considering this.
Any information which captures the equivalent of "consul members" would be good.
I usually run only my **server** agent with the "-ui" parameter.

👍

**Comment by opihana** [comment]
We added the Consul version to the WebUI in the footer with [#4086](https://github.com/hashicorp/consul/pull/4086/files#diff-db420c40e534581f83e3ea4003339abaR56). 🎉
