### ISSUE TITLE
Facing issue while adding already existing agent into consul members

### ISSUE THREAD

**Issue by umapathy** [hashicorp/consul#3898]
Hi
I am facing some issues in consul while adding already existing agent into consul members
docker exec -t consulagent consul agent -node foo -data-dir /tmp/consul -advertise=172.17.0.5 -join=172.17.0.3
==> Starting Consul agent...
==> Error starting agent: Failed to start Consul client: Failed to start lan serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 0.0.0.0:8301: bind: address already in use
i am getting this issue
can anyone tell me about where the issue is coming?

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
