### ISSUE TITLE
Support for using different domains for query/node/service dns addresses

### ISSUE THREAD

**Issue by myuen4** [hashicorp/consul#3912]
Consul supports the ability to set the default domain for dns queries e.g. https://www.consul.io/docs/agent/options.html#_domain it would be useful to be able to customise the how the domains a little more.

Right now I can specify `domain = foo.com` and i get `query.foo.com`, `node.foo.com` and `service.foo.com`.

It would be useful to be able to specify `query_domain = foo.com`, `node_domain = node.foo-catalog.com` and `service_domain = service.foo-catalog.com` this would be nice in cases when most users shouldn't be interested in catalog related records as we could direct queries to the root of the domain.

**Comment by banks** [comment]
Interesting idea. 

> this would be nice in cases when most users shouldn't be interested in catalog related records as we could direct queries to the root of the domain

Can you expand on your use-case a little more? 

Why are different domain required? What does it enable that you can't do just as easily by setting up your system DNS differently for different users?

**Comment by myuen4** [comment]
Hi @banks, your right, we could (and do already to some extent) modify the dns results as they propagate through something like unbound/dnsmasq/bind. So this is not out of reach today.

Mostly I think I'm asking because

1. It would be quite nice from my POV to have first class support for tuning more dns features like this in consul without deploying other products along side consul.
2. I'm curious if we're the only ones that don't really want everything in the catalog exposed through DNS by default but might like some finer grained control.

**Comment by banks** [comment]
For access control, you can already limit which services are exposed via DNS in a blunt way since we only show DNS results for services where the `anoymous` ACL token has `read` access. See https://www.consul.io/docs/guides/acl.html.

So if you just want blanket "don't show in DNS" that might be an option already. Since DNS has no way to pass a token though we can't make it only work for some users for example.

I'm still not quite sure your actual reasons for not wanting to expose things though and that matters quite a lot  in terms of implementing a feature like this - are they security concerns? Privacy concerns?

Can you give us one or two examples situations you have that would benefit from this so we can discuss what could be done.

For example you proposal of separate domain for services/query/node is a very specific solution to the problem of limiting access to different groups of users - other users might want to do the same but instead limit to only some services etc. It's hard to know what a good level to consider this is without concrete examples of use-cases to work from :)

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
