### ISSUE TITLE
Allow redirecting UI to HTTPS

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#3980]
We want to use HTTPS wherever we can but most browsers default to HTTP at the moment, which means that we end up usually having our services listen on port 80 and 443 but simply redirecting HTTP to HTTPS. It seems that Consul doesn't provide any configuration option to allow redirecting HTTP to HTTPS. We could, of course, proxy the Consul web UI through nginx or Apache and do the redirection there instead, but it seems like overkill to use a reverse proxy just for HTTP->HTTPS redirection.

**Comment by pearkes** [comment]
Hey @joshuaspence!

You can disable HTTP for the API/UI (use port `-1`) and enable TLS in your cluster, if you haven't already. This takes a bit of effort, but can give you what you're looking for. You'll also likely need to disable verifying incoming TLS for HTTPS otherwise your browser experience won't work out of the box.

See:

- https://www.consul.io/docs/agent/options.html#verify_incoming_https
- https://www.consul.io/docs/agent/options.html#https_port
- https://www.consul.io/docs/agent/options.html#http_port

Otherwise, it is not uncommon for folks to use reverse proxies in front of the Consul UI, for things like this (listening on a standard 443 port) or layering authentication that is not the Consul ACL system in front, like basic auth.

Hope that helps, feel free to re-open if that doesn't solve things for you.
