### ISSUE TITLE
consul validate fails when data_dir is not defined in the config file

### ISSUE THREAD

**Issue by mterron** [hashicorp/consul#4065]
### Description of the Issue (and unexpected/desired result)
```sh
$ consul validate /etc/consul/consul.json
Config validation failed: data_dir cannot be empty
```
Expected result: validation succeeds as the config file is perfectly valid since data_dir can be a command line parameter. This behaviour started at v1.0.6 

### Reproduction steps
run `consul validate` on a file that doesn't have data_dir defined.

**Comment by pearkes** [comment]
@mterron This is by design for the `validate` command. It basically treats the configuration passed as the agent would, requiring anything the agent would at startup. I could see a potential feature request either specifying some kind of `ignore` parameter for scenarios where you're mixing command line and file configuration. Feel free to open a request as such!
