### ISSUE TITLE
Consul Doubts

### ISSUE THREAD

**Issue by banank1989** [hashicorp/consul#4068]
I know its not the issue actually but I have some doubts.

a) Are agents single point of failure? What happens when  agent dies?
As for example I have two boxes A & B, each have 5 java services running,

Now lets say consul agent on A dies. Now will services of A registers via consul agent of B? How does consul server keeps current state of services of A?

Also what about health checkup now? Who will do the health checkup of services on A box?

b) Considering every thing works fine, how are the health checkup of consul agents(clients & servers) done? I mean agents keep polling services for health checkup. 

c)I want to integrate Consul with haproxy. Is there some documentation how to do that via consul-template.

**Comment by jhmartin** [comment]
The agent is a SPOF for the machine on which it lives. If it dies, the services on the machine will be marked as unavailable for the rest of the environment. It is responsible for performing the healthchecks of the apps on that node as well -- other nodes won't do it.

b) The agents all healthcheck each other (consul-only), so a loss of a agent will be quickly noticed by the environment.  Everything otherwise health-checks itself.

c) https://github.com/hashicorp/consul-template should cover that, plus I found http://sirile.github.io/2015/05/18/using-haproxy-and-consul-for-dynamic-service-discovery-on-docker.html#testing-template-generation.

**Comment by banks** [comment]
Hey @banank1989 I think @jhmartin did a great job answering your questions here so I'll close this.

In general though questions like this might be better on the [mailing list](https://groups.google.com/group/consul-tool/)

Thanks @jhmartin.

In addition HAProxy recently added the ability to discover backends using DNS SRV records which Consul exports natively so you can just have it work that way with no consul-template in the middle: https://www.haproxy.com/blog/haproxy-and-consul-with-dns-for-service-discovery/
