### ISSUE TITLE
Special Characters in Keys.

### ISSUE THREAD

**Issue by karthik0132** [hashicorp/consul#4070]
### Special Characters in Keys
Keys containing special characters are returned with special characters in encoded format instead of returning the value as entered on the UI. This also happens while inserting key value pairs using ansible scripts.
For instance, while entering a key value pair
**Input**
key: module1,module2 
value: value1 
**Expected values:**
key: module1,module2
value: value1
**Actual values:**
key: module1%2Cmodule2
value: value1

### Reproduction steps
1. From consul UI click key/value tab.
2. Click plus sign
3. In Create Key: Enter a key name containing special characters including: ,(comma)
$(dollar),%(percentile) etc
4. Click create

### `1.0.6` for both Client and Server
Client: `[1.0.6]`
Server: `[1.0.6]`

**Comment by pearkes** [comment]
This issue is for a version of the web UI we currently support but plan to deprecate in the near future. As a result, we're only fixing critical bugs or security issues. However, we will take this issue into account as we continue to develop the replacement version of the UI. Unfortunately due to how old this UI and its depedencies are, fixing these problems is more complex than it should be. The redesign and rebuild to modern dependencies should fix this.

Thank you for the report, hope that makes sense.

**Comment by shantanugadgil** [comment]
@pearkes
Any timeline/version when the new UI is landing?

**Comment by pearkes** [comment]
@shantanugadgil we have a beta planned for the next release! If you keep an eye out we should be opening a PR with the new UI here in the next week or two. Once stable we'll promote it to the default.
