### ISSUE TITLE
TCP - Health check issue

### ISSUE THREAD

**Issue by satishviswanathan** [hashicorp/consul#4099]
I have my service registered in Consul with the following configuration which uses TCP protocol. Now this setting is creating a telnet session in my application during it's health check. We had this same issue while using F5 load balancer but it was resolved by having half TCP connection. 

Can this same achieved inConsul?

{
   "ID": "TelnetServer2",
  "Name": "TelnetServer2",
  "Notes": "TelnetServer 2",
  "Address": "10.202.XX.XXX",
  "Port": 2301,
  "Tags": ["urlprefix-:2301 proto=tcp"],

  "EnableTagOverride": false,
  "Check":{
  	"DeregisterCriticalServiceAfter": "90m",
    "TCP": "10.202.XX.XXX:2301",
    "Interval": "10s"
    
  }
}

**Comment by pearkes** [comment]
I'm not totally sure what you're looking for but it sounds like the [TCP check](https://www.consul.io/docs/agent/checks.html) should accomplish what you're trying to do here. I don't see where you're using telnet in the configuration you posted.

Anyways, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

**Comment by leonardobsjr** [comment]
@pearkes Sorry for bringing this up - Got here by the same reason as @satishviswanathan. Some applications log the tcp connection because it's a full TCP connection. F5 has the option of using half-TCP connections, kinda like scanners work.
