### ISSUE TITLE
How to get Consul metrics for the nodes which metrics include Memory, Storage, CPU and stale cache in grafana dashboard.

### ISSUE THREAD

**Issue by Sree9345** [hashicorp/consul#4107]

**Comment by guidoiaquinti** [comment]
Looks like opening this may have been an accident?

**Comment by eugenepaniot** [comment]
@Sree9345 https://www.consul.io/docs/agent/telemetry.html

**Comment by pearkes** [comment]
@Sree9345 We output runtime metrics which include `alloc_bytes` (mem) among other things. You can see these prefixed with `runtime.` on the telemetry page linked by @eugenepaniot. However, those are just metrics related to the Consul agent.

Consul does not provide telemetry about the host. You can use other metrics systems that support statsd or otherwise such as [Telegraf](https://docs.influxdata.com/telegraf/v1.6/) in combination with Influx for displaying graphs in something like Grafana.

In the meantime I'm going to close this issue as telemetry about the host isn't something we'll be adding to Consul in the future.
