### ISSUE TITLE
show port numbers and tags for services 

### ISSUE THREAD

**Issue by freeseacher** [hashicorp/consul#4115]
#### Feature Description

Please show ports for services on services tabs

#### Use Case(s)

We are using consul along with python multithreaded app. So we have to launch multiple instances for each cpu core. Our app is designed to get random port on start and register it in consul. So in consul we have lots of services on same node and with same name. The only difference is port number and tags. 
that is how it looks like in ui
![default](https://user-images.githubusercontent.com/289277/39957372-84779bd8-55fa-11e8-9a48-862dc363c11f.png)
and after drill down
![default](https://user-images.githubusercontent.com/289277/39957373-9787abf0-55fa-11e8-981a-22af84812a8b.png)

that is how it looks like in hashiui
![default](https://user-images.githubusercontent.com/289277/39957379-c8988368-55fa-11e8-8845-08a42be86572.png)

as far as you can see we have __port__ and tags per instance. 

I think service discovery without exposing essential info about service is pretty useless. 

BTW. new ui is really cool! tnx.

**Comment by freeseacher** [comment]
ok. it seems there are way to see port in services tab on node tab. 
but still info there is unsorted, unsortable and search box there doesn't works.

**Comment by mterron** [comment]
Adding :port to the ip address might be a simple useful addition. Also the tags (in the new style suggested in #4119) in each card.

**Comment by opihana** [comment]
@freeseacher Thanks for your feedback here! For each Service, there are actually multiple instances running, so on the the Service _list_, there would be multiple ports for each Service. In HashiUI, you can see the port after selecting a Service, and that port will be specific to each node. This is the same case in our UI, but as you pointed out, it's unfortunately hidden by multiple clicks. 😢  Thanks so much for bringing this to our attention so that we can improve that! 

In your second comment on this thread, you say:

> ...unsorted, unsortable and search box there doesn't works.

Yes, our search box there is only searching by Service name. **To make sure I understand you--would you like to also be able to search by port?** (Ideally, we'd expose the port earlier in your UX flow, so that you don't have to dig all the way to this page, but we might be able to make a quicker change, like searching by port here.)

@mterron great ideas 👍

**Comment by freeseacher** [comment]
@opihana 
hi! about filter and order it is just way to get neeed info quicker than with search. I mean that search will do backend request but filter and sort table is just a js action. 
I'am pretty unsure if search by port is ordinary usecase, but for me it is.

**Comment by johncowen** [comment]
Hi @freeseacher ,

I'm just checking back in to see if you've been able to try out the UI in 1.2.0? We added port searching in the 'Node > [Service Tab]' listing.

We also added the port of the service in the 'Service > Nodes' view alongside the ip address.

We were already showing the tags for services, but we've made them more visible in the UI now, which hopefully helps.

I'm looking to close this issue as we now show ports and tags, so if you could let me know if that has addressed your issue that would be great (or feel free to close the issue yourself if so)

I can see that there are other 'sub issues' above, which we've taken note of, but feel free to submit further issues to cover these (alongside anything else you would like to see)

Thanks,

**Comment by johncowen** [comment]
Hi @freeseacher 

I'm closing this issue now, as I believe it's complete, feel free to reopen if it's not working as expected.

Thanks,
