### ISSUE TITLE
ACL tokens are hidden in new UI

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#4124]
Hi folks,

Just noticed that in the new UI, you can see the ACL rule name but not the actual token.

Is it an intended change? The behavior is close enough either way, just curious.

Thanks in advance!

Before, always displayed:

<img width="1204" alt="screen shot 2018-05-14 at 1 48 45 pm" src="https://user-images.githubusercontent.com/1475276/40022692-95b5d6c4-577d-11e8-82c9-c2d6e77bab18.png">

After, have to copy it:

<img width="1189" alt="screen shot 2018-05-14 at 1 50 26 pm" src="https://user-images.githubusercontent.com/1475276/40022766-ce2c99fc-577d-11e8-92e5-5a53fc9751f1.png">

**Comment by scalp42** [comment]
I'm currently debugging some ACL tokens issues and comparing a JSON file I have with a bunch of ACLs to the UI.

I can't unfortunately search in the page to find the token I'm looking for :(

Tried to use workaround with inspecting the page but it's all in JS:

<img width="1391" alt="screen shot 2018-05-14 at 2 31 42 pm" src="https://user-images.githubusercontent.com/1475276/40024580-9a441f88-5783-11e8-83f4-c5431e3873a7.png">

The search bar is only for the ACL name as well:

<img width="1201" alt="screen shot 2018-05-14 at 2 32 25 pm" src="https://user-images.githubusercontent.com/1475276/40024596-ad425f6e-5783-11e8-9f9a-7bc772270f62.png">

**Comment by DingoEatingFuzz** [comment]
@scalp42, if you open up Chome Devtools and do a search in the Elements tab, it should work like you expect it to in View Source!

**Comment by opihana** [comment]
@scalp42 Thanks for the info. Are you searching by the token itself? Can you elaborate on your use case there? For example, were you looking to find the policy info associated with that token ID?

**Comment by scalp42** [comment]
@DingoEatingFuzz thanks for the tip!

@opihana yes, that was exactly this.

**Comment by opihana** [comment]
@scalp42 Thanks for that clarification. 

Yes, after the beta period, the old UI will become deprecated (as in, we'll no longer be updating it), but it will still be available with an env variable. At that time, we'll ideally have fixed some of the beta issues, so just keep us in the loop if any other issues pop up that continue to keep you on the old UI. 😄

**Comment by scalp42** [comment]
@opihana thanks for the feedback, great to hear about the old UI being available!

I hear you about issues but do you know if the ACLs will be visible moving forward?

**Comment by opihana** [comment]
@scalp42 We've put together some designs for ACL token visibility. We had originally decided to hide them from view because they're important security tools. Users wanted to be able to share screens or have someone looking over their shoulder without revealing sensitive information. But, it sounds like we went too far in hiding them! 

We've come up with two changes (_with no confirmation yet on the timing of these changes_): 

1. First, making sure you can search by token. 
2. Second, showing the ACL token in the list view and in the edit view, but semi-hidden with the ability to toggle between viewing the full token and hiding it. We're thinking this could be a good middle ground between security and usability.

Here's a mockup that shows both of those changes: 

![acl list](https://user-images.githubusercontent.com/6323933/40443680-ba4c259a-5e8c-11e8-9dc6-3d3ecbd405a2.png)


![acl edit](https://user-images.githubusercontent.com/6323933/40443886-4769ed68-5e8d-11e8-8c82-009e785180c5.png)


I'd be curious to hear your thoughts on this approach.

**Comment by scalp42** [comment]
@opihana that is looking really good!

I'd be really happy if there was a global "eye" button (near the `ACL tokens` title for example) that would show or hide them all, while keeping possibility to hide specific ones I'm assuming.

So if the "global eye" icon is on, hide every token, but you can click on one and show it like in your mockup. And vice-versa if the icon is off.

Thanks a lot for the feedback and mockup, greatly appreciated!

**Comment by johncowen** [comment]
Hi @scalp42 ,

We've recently released an RC that includes a completely new ACLs system, plus UI to go with it. I'm not sure if you are able to try it out on a non-production system. The biggest change in regards to this issue is that ACL tokens now have non secret unique ID's as well as the secrets themselves. We display a short version of these non-secret ID's in the listing to help people distinguish between tokens, and also we display the actual secret itself (behind a unhide button) in the token detail/form page.

Moving forwards I would guess it's highly unlikely we'll give the option to show all secrets in the listing page now, but hopefully the additional features address the root of your issue (being able to search for individual tokens easily).

I'm going to close this issue, but feel free to reopen if this doesn't address your issue.

Thanks,

John
