### ISSUE TITLE
Consul Client Cluster join issue

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4126]
I created consul in my windows machine using the below command
**consul agent -dev -client="IpAddress1"**

Again i created Consul in another windows machine using the same below command
**consul agent -dev -client="IpAddress2"**

Now i tried to create Cluster from machine1 with machine2, using the below command. 
**consul join "IpAddress2:8301"**	

But i could not create it. I keep on facing the below error. Can any one suggest me to resolve this issue.
 
**Put http://127.0.0.1:8500/v1/agent/join/IpAddress2:8301: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
Failed to join any nodes.**

**Comment by seafoodbuffet** [comment]
When you use IpAddress1 for the client option, it means that you can ONLY contact the agent using that IP. Consul cmdline defaults to 120.0.0.1 for the http address which won’t work in your case.

Instead do
consul join -http-addr http://IpAddress1:8500 IpAddress2

That said, are you trying to build a cluster or just running a dev server and a client? I don’t believe you should run the second consult agent using -dev if the later and you really shouldn’t run either using -dev if you want to build a cluster.

**Comment by karthikrajakandasamy** [comment]
@seafoodbuffet Thanks for your reply. I tried to execute the above command, but now am facing the below error.

 **Failed to join IpAddress2: dial tcp 1IpAddress2:8301: connectex: No connection could be made because the target machine actively refused it.)
Failed to join any nodes.**

**Comment by seafoodbuffet** [comment]
Okay, in that case, you definitely do NOT want to run in -dev mode. Furthermore, please read about Consul clustering and Quorum, running with two nodes is not really any better in terms of failure tolerance. You need a minimum of three server nodes in order to tolerate failure of a node.

I've never work with Consul on windows, but here's a guide for Linux that you might be able to adapt to your environment:
https://www.digitalocean.com/community/tutorials/how-to-configure-consul-in-a-production-environment-on-ubuntu-14-04

**Comment by karthikrajakandasamy** [comment]
@seafoodbuffet  i achieved the above requirement in windows. To do that we have to follow the below steps,
**Instance 1 (Machine 1) => consul agent -dev -client="IP address of Machine1" -bind= IP address of Machine1
Instance 2(Machine 2) => consul agent -dev -client=" IP address of Machine2" -bind= IP address of Machine2**

Then to join both the instances,  we have to use the below command
**consul join -http-addr http:// IP address of Machine1:8500 IP address of Machine2**


Can you please tell me how to achieve **Consul SSL** in **Windows**

**Comment by pearkes** [comment]
Thanks for your help here @seafoodbuffet, but because issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
