### ISSUE TITLE
Consul SSL On Windows

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4137]
Can anyone suggest me the list of steps needed to execute **Consul SSL on windows.**

**Comment by karthikrajakandasamy** [comment]
@mterron  how to setup the SSL in consul server in windows

**Comment by mterron** [comment]
https://www.consul.io/docs/agent/encryption.html

**Comment by karthikrajakandasamy** [comment]
@mterron Thanks for your Interest. I followed the below steps for Consul SSL on Windows

1. Created the key using below command
    **openssl genrsa -out consul.key 4096**
2. Created certificate consul_ca.crt using below command
    **openssl req -new -x509 -days 365 -key consul.key -subj '/C=US/ST=Somestate/L=sometown/O=somecompany/OU=someorg/CN=someguy' -out consul_ca.crt**
3. Created CSR using below command
**openssl req -new -key consul.key -out consul.csr -subj '/C=US/ST=Somestate/L=sometown/O=somecompany/OU=someorg/CN=*'**
4. Created consul.crt  file using the below command
**openssl x509 -extfile openssl.conf -extensions ssl_client -req -days 365 -in consul.csr -CA consul_ca.crt -CAkey consul.key -out consul.crt -set_serial 01**

5. After i created the above certificates, i used the below Configuration in my config file
"ca_file": "/opt/consul_0.4.1/conf.d/consul_ca.crt",

"verify_incoming": true,
"verify_outgoing": true,
"cert_file": "/opt/consul_0.4.1/conf.d/consul.crt",
"key_file": "/opt/consul_0.4.1/conf.d/consul.key".

6. Then i started my Consul with the above configuration.

My consul started and running but when i tried to access the consul UI using https the page is not loading.
Could you please provide me any solution for this issue?

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
