### ISSUE TITLE
consul Only one node registered successfully.

### ISSUE THREAD

**Issue by MRwangyd** [hashicorp/consul#4144]
my consul version is: Consul v0.9.2

Here's how I started it. All three nodes are like this.
ip=$(/sbin/ifconfig | grep -oP "(?<=inet )$ip[\d.]*"  | head -n 3|grep 10.200)
hostname=$(hostname)

[ ! -d $data_dir ] && mkdir -p $data_dir
chown -R tomcat.tomcat $app_dir $data_dir
su - tomcat -c "nohup $app_dir/consul agent -server -bootstrap-expect 2 -data-dir $data_dir -node=$hostname -bind=$ip  -client=0.0.0.0 -ui $data_dir -dc=dc1 > $app_dir/consul.log &"

The cluster status is as follows:
Node            Address           Status  Type    Build  Protocol  DC
VM_0_13_centos  10.200.0.13:8301  alive   server  0.9.2  2         dc1
VM_0_15_centos  10.200.0.15:8301  alive   server  0.9.2  2         dc1
VM_0_4_centos   10.200.0.4:8301   alive   server  0.9.2  2         dc1

The configuration of the application services.:

spring.cloud.consul.host=consul-node1.mapbar.com
spring.cloud.consul.port=8500
spring.cloud.consul.enabled=true
spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.instanceId=${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring.cloud.consul.discovery.serviceName=${spring.application.name}
spring.cloud.consul.discovery.hostname=10.200.0.9
spring.cloud.consul.discovery.port=${server.port}
spring.cloud.consul.discovery.healthCheckUrl=http://${spring.cloud.consul.discovery.hostname}:${server.port}/health
spring.cloud.consul.discovery.healthCheckInterval=10s

The current problem is that only one node of the two nodes can be registered successfully, and both services are started at the same time, and only one can be used in the service.

Please help me, thank you.

**Comment by MRwangyd** [comment]
Some people see yao, need help

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
