### ISSUE TITLE
Watch handler run more then once at one event

### ISSUE THREAD

**Issue by vinglogn** [hashicorp/consul#4152]
**Consul version：v1.1.0**
#### Overview of the Issue:
I register a watch handler for redis service to change the service tag of redis (master->slave or slave->master) in case of the master redis service down. With this method, I can use dns interface for the redis master service discovery. 
eg. 
**~#redis-cli -h master.redis.service.consul -p 6379** 

Problem:
In the following two case：
1） consul  reload
2）the master redis service killed by human for test
The registered watch handler will run more than once.  Some times , it can run more than 5 times.  
I don't known why it happen? Is it a right thing or wrong, a handler run so many time with one event?

### watch.json
.........
{
"watches": [{
         "type": "service",
         "tag": "master",
         "service": "redis",
         "handler_type": "script",
         "args": ["sh", "-c", "/usr/local/bin/watch-redis.sh"]
     }]
}
............

### redis.json
.....
{
"services": [
    {
      "id": "red0",
      "name": "redis",
      "tags": ["slave"],
      "address": "10.x.x.1",
      "port": 6379,
      "enable_tag_override": true,
      "checks": [
        {
          "id": "redis1",
          "name": "redis1 tcp helth check",
          "tcp":"10.x.x.1:6379",
          "interval": "5s",
          "timeout": "20s"
        }
      ]
    },
    {
      "id": "red1",
      "name": "redis",
      "tags": ["master"],
      "address": "10.x.x.2",
      "port": 6379,
      "enable_tag_override": true,
      "checks": [
        {
          "id": "redis2",
          "name": "redis2 tcp helth check",
          "tcp":"10.x.x.2:6379",
          "interval": "5s",
          "timeout": "20s"
        }
      ]
    }
   ]
}
..............................

**Comment by banks** [comment]
Hey watches use [blocking queries](https://www.consul.io/api/index.html#blocking-queries) and the docs there state:

> When [using blocking queries], the HTTP request will “hang” until a change in the system occurs, or the maximum timeout is reached. A critical note is that the return of a blocking request is **no guarantee** of a change. It is possible that the timeout was reached or that there was an idempotent write that does not affect the result of the query.

On top of that, we track changes to a service at the entire service granularity - that means even if your watch is filtering to a specific tag we don't know if that filtered view is updated or not when any instance of the service changes state so all watchers of the service will be notified.

I'd assume that all 5 or so events you receive have different `ModifyIndex` and are caused by multiple writes to the whole service - for example one will occur when the health check status turns to critical. Probably another time a bit later something external changes the tag of master to a new node which may be one or more writes to the service catalog etc.

Given the guarantees above your watch handlers need to be idempotent.

We have tentative plans to support alternative watch mechanisms  in the medium/long term that might mitigate some issues with filtered views like this as an optimization, but in general it will always be true that we can't guarantee exactly once behaviour.

If you still think there is a specific bug here can you post example payloads of all the watches - you can use `consul watch` or just log the entire payload handed to your watch script for that to dump the raw results when one of your "trigger" events occurs?

**Comment by vinglogn** [comment]
I got it, thanks a lot! @banks
