### ISSUE TITLE
Service ID is hidden in the new UI.

### ISSUE THREAD

**Issue by dperetti** [hashicorp/consul#4153]
In the old UI I can see the the ID of the service :
![image](https://user-images.githubusercontent.com/845612/40487681-30836984-5f65-11e8-84e1-7e3eb19990e7.png)

In the new UI I have no way to know :
![image](https://user-images.githubusercontent.com/845612/40487730-57dc9bf4-5f65-11e8-9ce8-15ec43fb563e.png)

**Comment by johncowen** [comment]
Hi @dperetti , thanks for trying things out for us! Good spot, we'll have a chat about this over the next few days and come back to you.

Please keep anything else coming.

Thanks

**Comment by opihana** [comment]
Hi @dperetti 👋

Thanks for your patience. After looking further into this, what you've circled here is actually a CheckID as seen in this [Sample Response](https://www.consul.io/api/agent/check.html#list-checks). It can be confusing, because CheckID [will default](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L1634-L1639) to a Service ID (`service:$SERVICEID`), which [will default](https://www.consul.io/api/agent/service.html#id) to Service Name. Meaning, each of these IDs could potentially be the same, or each could be unique.

With that, can you clarify if you are more interested in the UI showing the Service ID or the CheckID? We can (and should) show any unique IDs in the UI, but I just want to make sure we understand your specific need in this issue.

**Comment by dperetti** [comment]
Thanks for the clarification! 
I expected the Service ID but that's my personal case.
Also the Check ID makes sense too.

**Comment by ezraroi** [comment]
Hi All,
we also miss to find the service id in the new UI.

It was very helpful to have it in the old UI as if we want to manually de register service we could find the ID easily.
