### ISSUE TITLE
the number of services is confusing

### ISSUE THREAD

**Issue by eatgrape** [hashicorp/consul#4158]
for new UI
![image](https://user-images.githubusercontent.com/11503591/40542052-01234622-6051-11e8-99a9-9db92fd65ba4.png)
it displays number 8, but actually, there are 4 instances of uuid service.
maybe it contains Agent alive, and which is counted 4 times. it's confusing.

![image](https://user-images.githubusercontent.com/11503591/40542244-f4b8aba6-6051-11e8-8261-2e65b3ef00c4.png)
And on this page, for each instance of uuid, if service id or service name or tags is displayed, it will be more clear. for example, if deploying multiple instances on one node, every instance looks the same(only node name and its ip address).

thanks!

**Comment by johncowen** [comment]
Hi @eatgrape thanks for trying things out for us! We should be catching up with the rest of the team next week, so we'll keep you updated with any further news on this.

Please keep any other feedback coming!

Thanks

**Comment by opihana** [comment]
Hi @eatgrape. This is great feedback on how our UI could show Services instances better. We'll continue thinking on that subject. 

The numbers that you're seeing there on the Service list are actually the number of Health Checks for each service, _not_ the number of instances for each Service. Sorry if that was confusing!

Thanks again for the feedback!

**Comment by dekimsey** [comment]
This has come up at my workplace as well. On the Services page people seem to expect it to be a count of instances of said service that are healthy and not a count of checks of the service that are healthy.

**Comment by gertcuykens** [comment]
Hmm I run a identical server and client, the node tab makes sense 

![image](https://user-images.githubusercontent.com/863731/48119568-de158680-e26f-11e8-9cbd-9c4facb5b6c1.png)
![image](https://user-images.githubusercontent.com/863731/48119936-f33ee500-e270-11e8-9e3e-2d3cfa5e0464.png)
(img snipped)

10 = 2 nodes each having 5 identical checks

But this is just wtf? The total should be also 5 * 2 health checks for each node right? Not 24 sprinkelt around ?
![image](https://user-images.githubusercontent.com/863731/48119645-15843300-e270-11e8-8477-3fd987d0e605.png)

**Comment by johncowen** [comment]
Hi @gertcuykens ,

Thanks for the report here. I do agree that this can be a little confusing.

The Node Health column numbers are based on the API response:

![screen_shot_2018-11-07_at_09_11_40](https://user-images.githubusercontent.com/554604/48121654-6b0b1080-e26d-11e8-86a6-933b4ac4da30.png)

In your case this is the numbers in the 'Node Health' column:

6 + 6 + 2 + 4 + 6 = 24

These numbers and the ones in the filter buttons refer to 'number of healthchecks', not 'number of services'.

So in your case '24 Passing Healthchecks' is what the API is telling me, so that is what the UI shows you.

Should we make this a little clearer that this is number of healthchecks rather than services? I also think it could be worthwhile having an additional count of services here, would that help? Or should we change it so that it is 'number of services with healthchecks 100% in this state'?

I have seen future design options (out of many) that completely remove these top buttons and all the counts (whether we make them counts of the state of healthchecks or services). Do you prefer being able to see 'counts of things' or not?

Other than that, if you think it is a problem with the actual count I'm/you're receiving in the API response then let me know and we can file another issue.

Lastly I may have misunderstood your report completely, if so please let me know.

Thanks,

John

**Comment by gertcuykens** [comment]
Hmm I think it's the actual api health check count that is wrong let me investigate and report in another ticket. The interface is perfectly fine as it is. Now that you mention the api count I think I have some ghost services in the api registered for some reason

**Comment by johncowen** [comment]
Perfect! (well.. not but you know what I mean 😄 )

Let me know what the outcome is. We are keeping particular UI issue open as its something we really want to make work better (there's work in progress on this).

Thanks!

**Comment by johncowen** [comment]
Hi all 👋 

We've made a very small change to the text here, but we feel it might help in a large way.

https://github.com/hashicorp/consul/pull/5115

I'm 'almost' sure that we can close this issue? Please anyone feel free to give me you thoughts on that, I'll be chatting to the team later, and may close tomorrow if everyone on the team and here thinks similar.

Thanks!

John

**Comment by xumingxiang** [comment]
wtf ui

**Comment by xumingxiang** [comment]
I have the same problem, help~~~~~

**Comment by Clyde69** [comment]
I have what I think is the same issue.
![image](https://user-images.githubusercontent.com/8068513/52335093-6b947e00-29f9-11e9-8a7a-be0284e633e3.png)
I have one (local) node so each service should show either a pass or fail, but this appears to be showing a total of all service checks for each service. Surely this isn't right?

**Comment by johncowen** [comment]
Hi all,

Thanks all for pitching in here. We know that many of you are having problems with this aspect of the UI, and we’re committed to improving it. The issues are a bit nuanced, so we’re providing a summary of issues and plans in place below.

### Summary of issues

We need to:

- Show a total count of services registered
- Remove the total counts from the filter buttons that represent health checks for _all_ your services

### Short Term Plan

We’re aiming to fix these two bullets quickly. First, we’re going to add a count of all services:

![screen shot 2019-02-06 at 11 05 53 am](https://user-images.githubusercontent.com/554604/52367242-7ecc3b80-2a43-11e9-883b-399701682ab7.png)

Second, we’ll qualify the text within the filter buttons themselves to refer to _health checks_, not services, like so:

![screen shot 2019-02-06 at 11 25 46 am](https://user-images.githubusercontent.com/554604/52367263-8f7cb180-2a43-11e9-939c-15543b87218f.png)

Selecting, for example, the filter for “Critical Checks” will show you any services that have at least one health check identified as critical for a service instance. 

Third, we'll also remove the counts in the filter buttons. We believe that the counts caused more confusion than guidance. Furthermore we show the amount of critical checks _per service_ in each 'service row' - so we’re hearing that the _total_ health check count across all services isn’t hugely useful to you.

Fourth, we’ll change the order of the filter buttons, to start with "All (Any Status)" to "Critical", then "Warning", then "Passing" because people care more to investigate services with _critical_ checks than they do services that are doing fine.

### Longer Term Plan

And finally, the filter options for health status will change dramatically after we finish a larger project in progress: a search component with significantly more options and flexibility. Follow [this issue](https://github.com/hashicorp/consul/issues/4201) for more information on that in the future. 

If you’re interested in providing further feedback on the Consul UI, please consider filling out this [brief (<2 minutes) survey](https://goo.gl/forms/FLGXCuNK5AdY118j1) for us.

Thank you!

**Comment by johncowen** [comment]
Hi All,

All the changes detailed here (and in the linked PRs) ended up in Consul 1.5. Hopefully it's clearer now what the numbers mean.

The new search interface is ongoing, and will eventually look to make use of the new filtering abilities of the Consul API, meaning you'll be able to perform much more powerful filtering from the UI.

I'm going to close this, but feel free to reopen if you think there is still something outstanding regarding confusing numbering.

Thanks,

John
