### ISSUE TITLE
send multiple URL to access consul Cluster in Consul .Net for Load Balancing

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4170]
Am using consul in my project for service discovery . So i created Consul with cluster. That cluster contains three machine, Machine 1,Machine 2,Machine 3 Respectively. 

I registered one external service to consul, Now i can able to use service discovery by accessing above any one of the machine details. 
Below is the .Net code to achieve the above scenario

**List<Uri> serverUrls = new List<Uri>();
var consuleClient = new ConsulClient(c => c.Address = new Uri("http://Machine1IP:8500")); 
var services = consuleClient.Agent.Services().Result.Response;**

My problem is, in that code  you can see the new Uri,where we can able to pass only one URL. i need to pass three machine URL and if any one of the URL is down then consul should go to other URL and return the  discovery result.

In the consul .net sdk code i dont find any method to pass multiple URL. Can anyone suggest me to achieve my goal.

**Comment by kyhavlov** [comment]
If you're running the code from somewhere with a Consul agent, you can either use the local agent's http address (i.e. `localhost:8500`) or `consul.service.consul` if you want load balancing against the servers. If that's not an option, you'll want to open an issue against the .NET api repo (since that's a separate community thing that we don't maintain). Hope that helps!
