### ISSUE TITLE
Service meta in new UI

### ISSUE THREAD

**Issue by dayyeung** [hashicorp/consul#4173]
Is service meta currently accessible in the new UI?
If not, any reason why?

**Comment by opihana** [comment]
Hi @dayletter! Great question. Support for Service Metadata was a relatively recent addition. With our beta UI, we were aiming to replicate functionality with the pre-existing UI, while improving the styles. Only now are we beginning to move toward increasing the functionality found in the UI, and we will be considering adding Service Metadata. Can you tell me more about what your Service Metadata typically looks like, or how you would ideally use it, so that we can design it well for the new UI?

**Comment by dayletter** [comment]
Thanks for the quick reply.

We are not using service meta, but instead using tags as a workaround to somehow replicate the effect, mostly because the old UI could only display tags. However, since tags are not designed for this, they are not very readable.

We currently use tags to record service instance version, instance id and port protocol. We would like to expose more data (potentially a lot more, e.g. app config, JVM info, container info, process info, URLs to other monitoring tools, etc), but adding more tags would only make it even less readable. This is why we wish the new UI would support service meta.

Not sure if I should create a separate issue, but I think being able to display node meta would be another great addition.

**Comment by Imaclean74** [comment]
adding a plus one. We're using Meta to store things like service documentation, metrics dashboard links and other useful metadata. As a first cut - just being able to see the Meta block at all would be very useful. And actually, a raw json view would be pretty handy. That way any new additions to the service definition ( or other Consul data ) would at least be viewable right away - before new UI elements are specifically added. Of course - right now there is always the raw REST api ...

**Comment by outer-damien** [comment]
One of our use-case is to have _platform service_ subscription via those metadata. The (consul) service subscribes to some (platform) services by exposing that it wants to be considered. Our first work is for backups in the case of a DB: it exposes the frequency of the backups it needs. Two services are relying on those metadata: the one doing the backup and the one alerting if a backup is too old.
For now I have to rely on the prometheus discovery to have a UI showing me the metadata. this is less than obvious.

**Comment by bfg111** [comment]
Any update on this - this has been out for a while and it would be really nice to see this.

**Comment by johncowen** [comment]
Hey All 👋 ,

The Consul 1.6 release surfaces meta data in both 'Service Instance detail' views and 'Node detail' views. The meta is shown as a simple readonly table for the moment at least, although we are likely to expand on that as we move forwards. I'm going to close this issue but feel free to open a new issue(s) for any more specific improvements/feature requests you have in mind.

Thanks!

**Comment by pierresouchay** [comment]
> One of our use-case is to have _platform service_ subscription via those metadata. The (consul) service subscribes to some (platform) services by exposing that it wants to be considered. Our first work is for backups in the case of a DB: it exposes the frequency of the backups it needs. Two services are relying on those metadata: the one doing the backup and the one alerting if a backup is too old.
> For now I have to rely on the prometheus discovery to have a UI showing me the metadata. this is less than obvious.

@outer-damien If you need a Read-Only UI displaying all meta, there is one: https://github.com/criteo/consul-templaterb (you can test it in a few minutes with https://hub.docker.com/r/discoverycriteo/consul-templaterb ) It is also very hackable as the whole source is plain text editable: https://github.com/criteo/consul-templaterb/tree/master/samples/consul-ui )
