### ISSUE TITLE
consul-ui is not coming up if i stop agent agent running on one node.

### ISSUE THREAD

**Issue by srihithasri** [hashicorp/consul#4178]
Hi,

I have consul-cluster running with 3 nodes and all nodes have consul & consul-ui installed.

node1:

{
"bind_addr": "10.211.203.xx",
"addresses" : {
    "http": "10.211.203.xx"
  },
"client_addr": "0.0.0.0",
"datacenter": "dc1",
"data_dir": "/var/consul",
"encrypt": "F6EoBhdFeIdPUabUI1jgEg==",
"log_level": "INFO",
"enable_syslog": true,
"enable_debug": true,
"node_name": "ConsulServer1",
"server": true,
"bootstrap_expect": 3,
"leave_on_terminate": false,
"skip_leave_on_interrupt": true,
"rejoin_after_leave": true,
"retry_interval": "30s",
"retry_join": [
  "10.211.203.xx:8301",
  "10.211.203.yy:8301"
  "10.211.203.zz:8301"
  ],
"ui_dir": "/usr/local/share/consul/ui"
}

node2:

{
"bind_addr": "10.211.203.yy",
"addresses" : {
    "http": "10.211.203.yy"
  },
"client_addr": "0.0.0.0",
"datacenter": "dc1",
"data_dir": "/var/consul",
"encrypt": "YKV9r5zmAI3oGbf4UR2DMQ==",
"log_level": "INFO",
"enable_syslog": true,
"enable_debug": true,
"node_name": "ConsulServer2",
"server": true,
"bootstrap_expect": 3,
"leave_on_terminate": false,
"skip_leave_on_interrupt": true,
"rejoin_after_leave": true,
"retry_interval": "30s",
"retry_join": [
  "10.211.203.xx:8301",
  "10.211.203.yy:8301"
  "10.211.203.zz:8301"
  ],
"ui_dir": "/usr/local/share/consul/ui"
}

node3:

{
"bind_addr": "10.211.203.zz",
"addresses" : {
    "http": "10.211.203.zz"
  },
"client_addr": "0.0.0.0",
"datacenter": "dc1",
"data_dir": "/var/consul",
"encrypt": "GdjHXQkQ+KrIZTsMmZ+tDw==",
"log_level": "INFO",
"enable_syslog": true,
"enable_debug": true,
"node_name": "ConsulServer3",
"server": true,
"bootstrap_expect": 3,
"leave_on_terminate": false,
"skip_leave_on_interrupt": true,
"rejoin_after_leave": true,
"retry_interval": "30s",
"retry_join": [
  "10.211.203.xx:8301",
  "10.211.203.yy:8301"
  "10.211.203.zz:8301"
  ],
"ui_dir": "/usr/local/share/consul/ui"
}

COnsul agent is running on all nodes:
consul agent -config-dir /etc/consul.d/ -bind=10.211.203.XX -ui-dir /usr/local/share/consul/ui

consul agent -config-dir /etc/consul.d/ -bind=10.211.203.YY -ui-dir /usr/local/share/consul/ui

consul agent -config-dir /etc/consul.d/ -bind=10.211.203.ZZ -ui-dir /usr/local/share/consul/ui

Now if i open consul-ui with node 1 ip i can see dashboard but if stop that agent running on node 1 i am not able to view any dashboard..I have installed consul-ui in all nodes..but if i check dashboard for node 2 ip it is not working

I am getting error like this

curl http://10.211.203.YY:8500/
<a href="/ui/">Moved Permanently</a>.

Can some one help me in solving his issue?

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here. From a brief look it seems like you need to follow redirects with your curl command (eg `curl -L`), as the UI is hosted on `/ui` and not the root of the HTTP address.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
