### ISSUE TITLE
Unable to deregister a service registered on a remote agent from server agent.

### ISSUE THREAD

**Issue by VenkatJaladanki** [hashicorp/consul#4186]
Unable to deregister a service registered on a remote agent from server agent.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
