### ISSUE TITLE
Server health checks don't work with iptables' OUTPUT rules

### ISSUE THREAD

**Issue by TheLorax** [hashicorp/consul#4195]
#### Overview of the Issue

In a 3 server setup, "A", "B", "C", if server "A" is isolated by using a combination of INPUT and OUTPUT rules on "B" and "C" to drop all incoming and outgoing traffic to "A", "A" is never actually removed from the server cluster.

#### Reproduction Steps

Steps to reproduce this issue:

1. Create a cluster with 0 client nodes and 3 server nodes
2. Run iptables
on "B"
iptables -A INPUT -s "A IP" -j DROP
iptables -A OUTPUT -s "A IP" -j DROP
on "C"
iptables -A INPUT -s "A IP" -j DROP
iptables -A OUTPUT -s "A IP" -j DROP

view node status:
note is is marked "Alive", yet there is no traffic to or from "A".

### Operating system and Environment details

Reproduced on 1.0.0 and 1.1.0 on Linux.

### Log Fragments

Failed to send ping: write udp 192.168.132.44:8301->192.168.132.43:8301: sendto: operation not permitted

I bet that consul's logic wont ever mark a node as offline if it gets an "Operation not allowed" error instead of no response from the peer.

**Comment by mkeeler** [comment]
@TheLorax It does look like for operation not permitted it will never mark it as dead. To me this seems like correct behavior. The error returned here is an error about the setup of nodes B & C and does not reflect the state in the overall cluster or A being generally unhealthy/offline.

For example if you had nodes A, B, C, D and E with only B & C firewalled from A. D & E can still reach A and thus A is still alive and part of the cluster. In this scenario even if B & C proceeded further to the point of marking node A as suspect they would then ask the other nodes in the cluster they knew (D & E) about the state of A and they would refute the suspect message and the state of A in the cluster would still be alive.

In the scenario where a node is firewalled from ALL other nodes in the cluster, my question is what is the point? Why not just take the node offline or `consul force-leave <node A name>`. Or you could firewall things on node A in which case it becomes a proper timeout for the other nodes rather than a host networking "permissions" issue.

What is your use case for why you would want different behavior?

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
