### ISSUE TITLE
Configure consul using .Net framework instead of .Net core

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4197]
I found all the samples used some configurations in .net core to register the service in consul. How to use those configurations in .net framework services. Let say below  URL has the sample to register service in consul using .net core. It is working fine for me. But how to use those configurations if i use .net framework services. Can any one help me to achieve this thanks in advance.
https://cecilphillip.com/using-consul-for-service-discovery-with-asp-net-core/

**Comment by mkeeler** [comment]
@karthikrajakandasamy Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here. In particular you probably want to check out the [Google Group](https://groups.google.com/forum/#!forum/consul-tool). Other users are in that forum and may have similar experiences with using .Net framework whereas most of us monitoring GitHub issues are Go developers.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
