### ISSUE TITLE
traffic from leader to followers

### ISSUE THREAD

**Issue by ice-8** [hashicorp/consul#4199]
We have 3 servers and about 430 clients in cluster. At some moment we found out that network traffic from leader to followers is about 1.5Gb/s (for every follower). Is it a normal network load or something wrong?

**Comment by MichaelLogutov** [comment]
We too have the same problem. One of the issues were that services health checks responded with non constant info (like datetime in response). But even after eliminating this problem we still have heavy traffic between masters. I think this might be because we're using service discovery through local consul agent (via v1/health/checks api) and default consistency mode *might* call master every time instead of cached local information. Can anyone confirm this? And if there a way to force consul client to use "stale" consistency mode by default?
