### ISSUE TITLE
Service filtering is limited (used to be able to use regular expressions)

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#4201]
1.1.0 Beta UI

**Describe the problem you're having**

The original UI let you do (intentionally or not) regex based filters. Such as: `^security|^session`. This functionality is missing in the beta ui.

**Describe the solution you'd like**

I'd like some sort of improved searching. It doesn't have to be regex. But being able to filter particularly alternations of a couple of items is needed.

**feature time!**
Improved filtering by tag (or meta) would be _amazing_! We'd love to be able to tag or use meta fields to identify app versions and project or team names and then be able to search for that reasonably well.

The UI is the first thing most of our Engineering, Operations, and QA will experience when looking or trying to find services. Being able to present a friendly relevant list of services would be very helpful.

**Share inspiration**

Searching is hard.

**Comment by johncowen** [comment]
Hey @dekimsey , good spot! There are plans to look at improving the searching overall, but a regex search is definitely something that is we've missed out from the old UI. Will chat to the team and come back to you.

Please keep anything else coming!

Thanks,

**Comment by Imaclean74** [comment]
Any plans to add filtering by tags / meta as requested ? as @dekimsey mentions, this can make the UI much more usable - particularly with large numbers of services and different teams sharing the same consul cluster.

**Comment by johncowen** [comment]
Hi @Imaclean74 

Right now you can search using tags, if you type a tag into the search field at the top right of the page your results will include any services with that tag.

Re: metadata, we'd like to add more visibility to meta data in the UI, and we are talking about how we are going to do this across the UI, but for now you can maybe think of tags as 'meta data for searching'.

For example, Wikipedia describes tags as:

> [Tags are a] kind of metadata helps describe an item and allows it to be found again by browsing or searching

Not sure if that helps for your use case? But overall we are looking to improve the UI here.

I'm very interested at the moment in the size of users' clusters, could you give me some idea on how many services you have in your cluster?

Thanks,

John

**Comment by Imaclean74** [comment]
thanks John,
Apologies - as you say tag search is already working in the new UI which is great. And I get how tags are metadata for search - but there is still a case for searching/filtering by Meta KV pairs. Maybe it will help if I give a couple of examples of how we're currently using Meta. 
- host categorization ID. In our internal infra setup, hosts are grouped under logical "Applications" with each one having a unique ID. Being apply to filter by AppId=A or AppId in [A,B] would be super useful. You could make this work with tags by doing something like APPID101, APPID102 as the tag name but that's a little clunky - it would be nice to be able to be explicit.
- Various utility links. For example the relevant ES / Kibana link for browsing logs for that service. Grafana link for metrics, gitlab link to jump right to the source code for that service etc. Having this all in one place and registered at service deploy time means we don't need to maintain a static wiki page for this and there is always a single source of truth for the useful metadata about a service. 
- component deployed version numbers. Useful for tracking where we have older versions deployed. ie version < X etc. 

We've actually built a minimal react UI on top of consul for devOps monitoring purposes ( Intern project ) that supports some of this, renders http// meta values as clickable links etc and finding that super useful. Seems like a use case that others would find useful too.

Re cluster size - we're relatively new to consul - so right now something close to ~1000 service instances, something like 50 logical "services" . However, we're leveraging a custom proxy / sidecar to automatically register legacy services ( > 10yr old c++ processes ) to simplify plant management and monitoring. Once that's fully deployed it will be several thousand all up. At which point, being able to quickly search and filter will be critical - since we want to be able to use this for day to day SRE operations. Probably our case is a little unusual since a) it's all on-prem and b) we're applying it to super legacy infrastructure that doesn't fit exactly into a standard microservices model. However- we are also building / deploying new microservices in parallel - also registered to the same cluster. 

As an aside - I think there was another request some time back for something like hierarchical namespaces. This would allow partitioning by application - and in theory, the UI could be set to filter by certain nodes in that hierarchy. Clearly, that's more work than leveraging Meta for API queries and UI - but could be very powerful.

Ian

**Comment by Imaclean74** [comment]
Hi John,
thanks. Happy to help. Yes you're right  #4465 is a better match for what we're looking for. 

I'd be happy to help out with user testing. Whats the best way to co-ordinate that? 

Ian
