### ISSUE TITLE
Token cloning UX is a bit confusing

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#4209]
1.1.0 Beta UI

**Describe the problem you're having**
The second token created when cloning has an identical name. This makes it difficult to tell which is the clone and which is the original. I just accidentally changed the ACL permissions on my nomad servers vs clients as a result. Whoops!

**Describe the solution you'd like**
Replace cloned token name with "[cloned] ..." or "Clone of ..." or "... [cloned]". (I actually prefer the latter just because it sorts gracefully.) Also, possible improvement would be redirecting to the newly cloned token rather than the main ACL listing.

**Share inspiration**
Not sure, I'm sure it's been done.

**Comment by jkrcma** [comment]
+1

This happened to me few minutes ago, I had to dig deep into our production k8s cluster to find which of the tokens was the original one used by developers. The old UI didn't redirect to the listing after cloning a token.

**Comment by johncowen** [comment]
Hi @dekimsey ,

We've recently released an RC which includes a completely new ACL system. Specifically the token cloning has been changed slightly so that the cloning of a token gives you clearer messaging, plus every token now has a unique id.

Right now we haven't added a 'Clone of' or similar to the descriptions, as for me personally, I'm trying to avoid 'Clone of Clone of' or 'Copy of.....1' 'Copy of ... 2' etc etc. There is also something that makes me reluctant to automatically write any type of data back to consul, even meta data, without consent from the operator. 

Instead of doing this there are 3 things that help operators to distinguish between the original and the cloned token.

1. Each token now has a unique ID.
2. We print the unique ID of the newly cloned token in the notification at the top of the screen once your token has been cloned.
3. We order the tokens currently by creation time, this means your cloned token will be at the top of the list.

> Also, possible improvement would be redirecting to the newly cloned token rather than the main ACL listing

I can definitely agree that this would be ideal. One thing that makes this problematic right now from a UX perspective is the [Cancel] button that would be on the form for the newly cloned token. Would the user expect that upon clicking this the cloned token should be removed? i.e. the cloned has been cancelled? Or would the user expect this [Cancel] button to undo any changes that I've made to the token post clone?

Overall, there is a planned large-scale change to the overall flow of the UI which could help us address this detail moving forwards (similar to what @jkrcma mentions). But for now, I think these changes make the token cloning UX much easier.

I'll close this issue for now, but please feel free to reopen if it doesn't address the root issue.

Thanks,

John

**Comment by dekimsey** [comment]
> We've recently released an RC which includes a completely new ACL system. Specifically the token cloning has been changed slightly so that the cloning of a token gives you clearer messaging, plus every token now has a unique id.

Woohoo! I look forward to getting a  chance to try the new UI. I can totally understand the desire to not have the Windows-esque "shortcut of" spam. It's ugly if anything else.

> I can definitely agree that this would be ideal. One thing that makes this problematic right now from a UX perspective is the [Cancel] button that would be on the form for the newly cloned token. Would the user expect that upon clicking this the cloned token should be removed? i.e. the cloned has been cancelled? Or would the user expect this [Cancel] button to undo any changes that I've made to the token post clone?

My random thoughts:

A pop-up toast notification, "token created" while redirecting to the new token may address this. If it doesn't already have a notification. There's a Delete button on the page already so I don't think there'd be a whole lot of confusion there. Maybe a clickable link in the toast notification?

Personally, I've always preferred forms that indicated one had changes to be saved. Okay/Cancel buttons that are grayed unless the form's been altered from it's load-state. Personally, I've done this with on-page-load digests of the form details vs current state.

**Comment by johncowen** [comment]
Hi @dekimsey 👋 

I'm just doing a little sweep of my backlog and noticed this. I wondered if you got the chance to try out the new ACLs UI? Hopefully it makes the token cloning less confusing (we now put your cloned token to the top of the list and add the AccessorID to the notification at the top of the screen).

I think the making the AccessorID in the notification is a nice idea, but as we put your token to the top of the list it wouldn't be needed (yet). We plan on doing an UI wide 'sortable tables' feature reasonably soon, so that idea 'may' come in handy then.

Thanks!

John
