### ISSUE TITLE
Autoupdate UI

### ISSUE THREAD

**Issue by SpatialJ** [hashicorp/consul#4221]
**New UI**

It would be really useful to have the ui auto update itself. So one can see / monitor a service or node going unhealthy. 
For example i would like to filter the ui only for critical services/nodes and then always have the live view.

Thanks,
Johannes

**Comment by johncowen** [comment]
Thanks for the feedback @SpatialJ ! Definitely a good suggestion 👍

**Comment by kamaradclimber** [comment]
You can have a look at criteo/consul-templaterb examples which we are using to build such UI.

**Comment by johncowen** [comment]
Hi @SpatialJ and @kamaradclimber (and @shantanugadgil and @valentinsiryk)

Just to let you know there is work going on for this here:

https://github.com/hashicorp/consul/pull/5070

I'm collecting/linking issues related to autoupdating and UI blocking queries to that PR so that I can close them easily once we've merged it down, but if you want to give feedback or be updated when this lands that is the best place to follow progress for the moment.

Johannes, specifically I've just added a GIF to the above PR that pretty much shows the usecase you describe above.

Thanks,

John

**Comment by johncowen** [comment]
Hi @SpatialJ, @kamaradclimber, @shantanugadgil and @valentinsiryk

We've added live updates/auto update for the Catalog only (for the moment) in version 1.5. We are aware of some noisy clusters so we also made it off by default for the moment. You can enable it in the settings for the UI.

Future versions of the UI will move this to 'on by default' and also roll it out across the rest of the UI.

I'm going to close this issue as it specifically talks about services/nodes etc, which is the most common usecase for this.

Thanks,

John
