### ISSUE TITLE
K/V not recognised as filled when pasted with mouse

### ISSUE THREAD

**Issue by chenger** [hashicorp/consul#4304]
When adding new key+value if pasting it with middl-mouse click or by right-click menu UI do not recognise pasted part until key pressed in field
Xubuntu Linux 16.04 (xfce), Firefox 60.0.2
![1234](https://user-images.githubusercontent.com/2116107/42033488-af891f76-7ae5-11e8-8cde-a6b3fa2332b8.png)

Value field have the same bug, when value is notfilled, the key can not be edited after saving.

**Comment by johncowen** [comment]
Hi @chenger ,

Thanks for submitting this, good spot.

So just to confirm, in order to make the [Save] button become enabled you have to enter something into both the 'Key or folder' field and the 'Value' field. Once you have done that you can then press the [Save] button.

When I say 'enter something' above here, it specifically means 'enter something using the keyboard', which as you point out is not ideal! Although it does look like, as long as you have either already entered at least one character using the keyboard, and then paste using your mouse (or vice versa) the [Save] button does enable?

I'll update you here on progress with this, and I can see if we can get it addressed for the next release.

Thanks,

**Comment by chenger** [comment]
Hi, @johncowen!
Save button is enabled when there is anything filled with keyboard in any field - key or value. While i paste something in field with paste, it is not recognized.

**Comment by johncowen** [comment]
Perfect (well to make sure I'm drilling down to the issue 😄 )!

I'll hopefully be looking at this soon, I'll come back here with any more info.

Thanks!
