### ISSUE TITLE
Problem with getting the address of active vault

### ISSUE THREAD

**Issue by kathiravanI** [hashicorp/consul#4312]
Can anyone tell me the steps to get the address of active.vault.service.consul using Consul Service Discovery.?

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
