### ISSUE TITLE
Can't list keys in new UI with limited ACL token

### ISSUE THREAD

**Issue by jodawill** [hashicorp/consul#4324]
#### Overview of the Issue

Given an ACL with limited access (such as write access to `foo/bar/`, but no access to `foo/`), the user can't list their own keys.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a new cluster running 1.2.0
2. Create the folders `foo/` and `foo/bar/` and a key called `foo/bar/data`
3. Create an ACL with the following rules:
```
key "" {
  policy = "deny"
}

key "foo/bar/" {
  policy = "write"
}
```
4. Using the test ACL, you will see nothing on the key/value page (which is unfortunate, but identical to the old UI). But if you visit https://192.168.99.100:8500/ui/dc1/kv/foo/bar/, you should see the `data` key, but instead, we get a blank page. (And even using the master token, if you go to this URL, you're redirected to the top level prefix, which I think is a separate issue.)

It's worth noting that this does work with the API:

```
jodawill: docker-consul-cluster (master)$ curl "https://192.168.99.100:8500/v1/kv/foo/bar/?keys&seperator=/&dc=dc1&token=e6864d20-00e6-1ae2-0075-e60823e1037e" --insecure
["foo/bar/","foo/bar/data"]
```

### Consul info for Server

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 28141971
	version = 1.2.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.0.0.8:8300
	server = true
raft:
	applied_index = 471
	commit_index = 471
	fsm_pending = 0
	last_contact = 54.356352ms
	last_log_index = 471
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:f1bfbe28-c5e5-78f3-7afc-05ab730b5a96 Address:10.0.0.8:8300} {Suffrage:Voter ID:ea9e588c-b984-7e32-2b4b-de23dc29383a Address:10.0.0.7:8300} {Suffrage:Voter ID:035f2dcc-eaa6-87f8-8ae2-3d5345de3971 Address:10.0.0.6:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 84
	max_procs = 1
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Running in Docker Swarm with docker-machine on MacOS 10.13.4.

### Log Fragments

No relevant log entries.

**Comment by johncowen** [comment]
Hi @jodawill ,

Sounds like a doozy, thanks for submitting the issue! I'm going to have a look to see if I can dig into this today. Short term, if this is getting in the way of your workflow, be aware you can revert to the old UI using the CONSUL_UI_LEGACY environment variable, other than that I'll try and keep you updated here with progress on this.

Thanks again!

**Comment by johncowen** [comment]
Hi @jodawill ,

I've just had a first go at trying to replicate your issue, ~and I am unable to~, I'll list out what I do here so we can try to figure out what I am doing different to you. I'd like to try to replicate your issue exactly before I try to fix it.

1. I start up consul with acls enabled (as detailed here https://www.consul.io/docs/guides/acl.html#bootstrapping-acls)
2. I use my master token in the UI to create a `foo/bar/data` with the value `value`
3. I use my master token to create a new 'client' ACL token using the UI with rules as specified in your issue above.
4. I use the [Use token] button to switch to that newly created ACL (and confirm in localStorage that it has indeed been applied)
5. I navigate to the KV listing using the [Key/Value] link in the main navigation. I get a page saying 'There are no Key / Value' pairs
6. I manually enter the url `/ui/dc1/kv/foo/bar/` which shows me the `data` key within the `foo/bar` folder. I click on the KV and it takes me to `/ui/dc1/kv/foo/bar/data/edit` where I can edit and save the value.

..ah actually in writing that out I've just realized. I think the issue is that we should forward you to the `edit` page if you enter the URL of a 'key' as opposed to a 'folder'. Folders display fine, but the urls for keys has been tweaked to require the `/edit` part appending.

So if you are manually entering URLs for KVs via the location bar in the browser you should use:

`/ui/dc1/kv/foo/bar/data/edit`

vs

`/ui/dc1/kv/foo/bar/data`

A forward to `/edit` if you don't do this would be a nicer though 👍 

Does this sound right to you?

Thanks,

**Comment by jodawill** [comment]
Hi @johncowen,

Thanks for testing this out. Having to add `/edit` to the key URL isn't what I was referring to, but I may have found why you didn't encounter the issue. Did you first go to the URL for the key, then click to the subfolders? I just discovered that I can list keys that way. But if I only know the name of the folder, and not the name of any of the keys within the folder, I have no way to list the keys in a folder if I don't have access to the top level prefix.

I just tested this with a simple configuration to make sure this is reproducible. I ran a Consul container as follows:

```
docker run -p 8500:8500 -e CONSUL_LOCAL_CONFIG='{ "acl_master_token": "FDF3C1C8-07E5-4781-AF89-EACE05644B86", "acl_datacenter": "dc1", "acl_token": "FDF3C1C8-07E5-4781-AF89-EACE05644B86" }' consul:1.2.0
```

Here's a video demonstrating the issue: https://youtu.be/DOku7DKqsAY

Thanks!

Josh

**Comment by johncowen** [comment]
Oh wow, amazing! Thanks for the video! Super helpful!

I'll have another pop at this with your config, probably tomorrow for me now.

Speak tomorrow 👋

**Comment by johncowen** [comment]
Hi @jodawill ,

Sorry for the delay in coming back to you!

I've had a little bit more of a look into this, and I continue to see the correct KV when I navigate to:

`/ui/dc1/kv/foo/bar/`

..but I watched your video a few times and noticed you only get the blank page when you don't end the url with a trailing slash.

So if you use:

`/ui/dc1/kv/foo/bar`

you get a blank page, but if you use

`/ui/dc1/kv/foo/bar/` or indeed `/ui/dc1/kv/foo/bar/data/edit`

...it works as expected.

I think the issue should be resolvable by us tweaking the redirects slightly. So if people do need to type in the url and they miss a slash off, we do a better job of sending them on to where they actually want to go. In the meantime could you confirm that if you add a trailing slash to the urls it works as expected for you? If this is definitely the root of the issue I can have a look at it asap.

Thanks,

**Comment by jodawill** [comment]
Hi @johncowen,

Thanks for looking into this again. In the video, I did try it with the trailing slash at one point, but a redirect removed it, like this:

```
jodawill: ~$ curl -I "http://localhost:8500/ui/dc1/kv/foo/" -H "X-Consul-Token: FDF3C1C8-07E5-4781-AF89-EACE05644B86"
HTTP/1.1 301 Moved Permanently
Location: ../foo
Date: Thu, 05 Jul 2018 14:08:50 GMT
```

Do you not get the redirect when you go to `/ui/dc1/kv/foo/bar/`?

Josh

**Comment by johncowen** [comment]
Ahh no, ok cool I pretty sure I know what's going on. Thanks for bouncing this around, you've been a great help!

Will come back to you when I have more news on this (or I end up needing to bouncing something else of you 😄 )

Thanks!

**Comment by jodawill** [comment]
Sounds good. Thanks!

**Comment by revdennis** [comment]
Under 1.2.2  the issue is improved. 

v 1.2.1 behavior:
Given a policy "foo" that gives read access to "config/AB" and storing data in /config/AB/foobar/data

Using a token created with the foo policy you can load http://127.0.0.1:8500/ui/dc1/kv/config/AB/data/edit and then you can navigate stepwise down to to the config folder normally until you get to kv then the UI will show no values to navigate back up.

If you start at any other level in the path with that token you get no results.

v 1.2.2 behavior
 Using a token created with the foo policy you can load http://127.0.0.1:8500/ui/dc1/kv/config
and navigate forward and backward as normal. However if you go to http://127.0.0.1:8500/ui/dc1/kv/ the folder config is not found. Under 1.2.2 only the config folder is hidden from the kv/

**Comment by johncowen** [comment]
Hi @revdennis 

Thanks for the feedback!

The behavior in 1.2.2 that you report sounds very much like how it worked in the old UI and similar to @jodawill 's description above:

> Using the test ACL, you will see nothing on the key/value page (which is unfortunate, but identical to the old UI)

And I'm pretty sure that this is due to how the ACLs and KVs work from a backend perspective. I'll try and check this again to be sure.

Other than that its good to know that this is an improvement over 1.2.1, I'm pretty sure this is as far as we can go with pure frontend, but again I'll try and check again and come back to you to be sure.

Thanks,

**Comment by johncowen** [comment]
Hi @revdennis,

Apologies for the delay, I've had another look at this just incase, and using Consul UI 1.2.2.

Given a KV at `config/AB/foobar/data` with the value 'hi',
and the ACL ruleset:
```
key "" {
  policy = "deny"
}

key "config/AB/" {
  policy = "read"
}

```
Then I use the created ACL token,
and I visit `/ui/dc1/kv/config/AB/foobar/data/edit`

everything works as expected.

I can then use the breadcrumbs to navigate back up the path, and use the KV listing pages to navigate all the way back down. The only page that shows me no results is the 'root' KV listing, this is because the API gives me no results to show in the UI, and this is expected behaviour (due to the ACL set up).

This is also how the old UI worked.

Let me know if this answers your query, if not we can look to re-open this, or file a separate issue if its a request for the API to work differently (as opposed to the UI)

**Comment by revdennis** [comment]
Could I modify the ACL so that it grants no other additional access but allows the root kv folder in the UI to not show blank ? I would want it to show the config folder at the root kv level but no other values and no other folders within the config folder except AB.

**Comment by jodawill** [comment]
^^ We would also appreciate this.

**Comment by johncowen** [comment]
Hey folks!

I'm just thinking it maybe best to keep this 'UI issue' closed and to reopen another linking to this just as reference.

The general idea with the UI is that it is just a thin client over the Consul HTTP API, it only does what the API tells it to do.

I'm pretty sure that when you set up ACLs in the way you are describing the API will respond with an empty json array at the root of the KV api, therefore the UI shows an 'empty' result. If the API were to respond with a different resultset, then the UI would show that. This is why I think that the issue or request is not a UI issue but a request to change how the API and or the ACLs/KVs work, not sure if that makes sense?

I could also remove the ui label here and call in some other members of the team who work on the API to give you further details, they may be able to help here.

@pearkes could you comment on this and advise?

Thanks

**Comment by revdennis** [comment]
That makes a lot of sense because the issue is now no longer one that can be addressed via the UI. Let's leave this issue closed but definitely link it to the new one.

**Comment by johncowen** [comment]
Hey @revdennis ,

I'm just trying to exhaust any thoughts from a UI perspective. The only further thing I could possibly think of where I new UI feature could help would be something I've briefly considered before, and that is to add a 'bookmarking' concept to the UI, so people could bookmark say a certain KV that wanted to monitor, (or a service or node or whatever).

Looking at your use case above, having a bookmark or favourite the KV so it wouldn't seem to to the user that it has 'disappeared' would address that. My biggest qualm with this is that we are duplicating native browser functionality, but maybe there is an argument to add something similar further down the line? Do you have any thought on this?

Back to the issue here, I think @banks might be able to comment further from a backend perspective. I'll leave it with him to take this up with you.

Thanks again both of you for walking it through with us!

**Comment by banks** [comment]
If I understand correctly, the ask here now is to have `GET /v1/kv/?recurse` still work even if the token has no permission to read the root directly.

I think that's reasonable. Obviously it would have to filter any keys that are not permitted but there seems no other sane way of making a UI capable of browsing whatever KV space _is_ permitted.

Practically I'd have to look more into if there are issues with that - it might get extremely inefficient for example on a large KC to have to iterate the entire KV just to see if any of the keys are permitted. It might be possible to iterate through the prefixes allowed by the policy first and then do more targeted reads for efficiency. Technically the UI _could_ do that without API changes now but it would require it fetching and parsing the `hcl` ACL policy and reasoning about the syntax etc. which is clearly a non-starter.

I'd suggest though opening a separate issue as an API enhancement request with a link here and this suggestion and we can consider it.

**Comment by revdennis** [comment]
The other option would be an ACL expansion request where you can explicitly give permission to view a folder without granting additional access to additional subfolders or keys.

**Comment by revdennis** [comment]
New issue created:

https://github.com/hashicorp/consul/issues/4513
