### ISSUE TITLE
Concul watch events return all keys without any info for event type (add,update,delete)

### ISSUE THREAD

**Issue by mfaizanse** [hashicorp/consul#4329]
Hi.
I am using console watch api with my go application and I am watching for keys with a prefix, the behavior I have got is that whenever I add/update/delete a key with that event, the watcher returns a new event but the events data contains the list of all keys with that prefix. What I want is that it the event should contain the event type like whether a key with that prefix is added or updated or deleted, and also which key it was.

Is there anything I am missing here?

**Comment by freddygv** [comment]
What you are seeing is the current expected behavior. The keyprefix watch will return the latest state for all keys that match the prefix you are watching, with the new value encoded in Base64. 

If you would like to know what key was changed you would need to track the last known state and compute the difference when the update arrives.

Additionally, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

A question like this would be a great fit for the [consul mailing list](https://www.consul.io/community.html).

Regardless, I hope this explanation clarifies the behavior. We will keep your request in mind as a potential future enhancement.

**Comment by pearkes** [comment]
Going to close per @freddygv's comment above.
