### ISSUE TITLE
New UI - Tags are not displayed properly in Services Tab

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4332]
**Old UI or New UI**
New UI

**Describe the problem you're having**
Tags are not displayed properly in Services Tab.
the UI only displays the last tag.

**Describe the solution you'd like**
Here is a snapshot of the Services tab - 
![image](https://user-images.githubusercontent.com/11939618/42222611-59e7fcf2-7ede-11e8-9373-5ae0a3eec56a.png)

when in fact, there are multiple nodes with different tags - 
![image](https://user-images.githubusercontent.com/11939618/42222688-8616289e-7ede-11e8-9b8c-734c96a86003.png)

**Comment by johncowen** [comment]
Hi @giladsh1 

Pretty sure this is due to #4222 ?

It looks like the backend API isn't sending the entire list of tags to the UI.

If you're happy that it's the same issue I can close this one, or feel free to close it yourself.

Thanks,

**Comment by giladsh1** [comment]
Hi @johncowen 
It's not the same issue.
there are 4 different nodes, each with the one tag.
the UI only displays the last tag.
I would expect it to show all 4.

**Comment by johncowen** [comment]
Hi @giladsh1 ,

Just to drill down into this, looking at your screengrabs above. It looks like the tags in your second screengrab on the 'service detail' page are correct? It shows four tags 'dor', 'ilan', 'ronen' and 'stas'. From your comment above it sounds like this 'view' is correct?

The first screengrab you have posted (the 'service listing' page) seems to only show one of these tags whereas it should actually show the same four tags 'dor', 'ilan', 'ronen' and 'stas' as the 'service detail' page.

I understand that the issue is that the 'service listing page' shows only 1 tag when it should show 4, is that what the issue is here?

Thanks,

**Comment by giladsh1** [comment]
hi @johncowen 
yes, that's exactly right.
Thanks

**Comment by johncowen** [comment]
Hey, pretty sure its the same issue as #4222 then, if you have a look at the response from:

`/v1/internal/ui/services`

It gives you a response with a list of services, but those services only have one tag each.

Pretty sure this one can be closed as a dupe of #4222 ?

**Comment by giladsh1** [comment]
you're correct - my bad.
thanks!
