### ISSUE TITLE
Systemd Notify support in bootstrap mode

### ISSUE THREAD

**Issue by jameshartig** [hashicorp/consul#4380]
#### Feature Description

In https://github.com/hashicorp/consul/issues/2121 `sd_notify` support was added but it doesn't seem to notify if started with `-bootstrap`. I would've thought that as soon as the instance marked itself as the leader it would've notified but instead it looks like it only notifies if it joins with another instance.

I wasn't sure if this was a feature request or a bug but since the last request was for when it joined a cluster and this isn't technically joining a cluster (depending on your interpretation) I filed it as a feature request. I'd be willing to fix this myself but I wasn't sure exactly where to start.

#### Use Case(s)

We have vagrant instances that our developers use which only have a single master and are running in `-bootstrap` but we can't use `Type=notify` which means that systemd thinks that the service started up before it actually is ready.

**Comment by anonymouse64** [comment]
For an additional use case here, the EdgeX Foundry open source project, which is meant for running on IoT devices, is using Consul as it's reference registry service. In the snap distribution of EdgeX we only have a single instance of Consul running that runs with `-bootstrap` and it would be great to be able to have Consul notify systemd when it is finished starting up.
We currently can't do that without writing a somewhat complicated wrapper around consul that forks Consul, then waits in a loop with something like curl checking the status of Consul, then once Consul is ready writes directly to the notify socket using from the same process (we can't just fork a process to write to the unix notify socket because we aren't allowed to use a notify access other than `main` inside snaps, and as such systemd only accepts notify messages that are sent from the same pid that systemd itself started), then waits on the original Consul process to exit. We'd rather not maintain a go/python/C/etc. program to check on Consul's status in a loop until it's ready and then write to the systemd socket when Consul could be made to do this itself.

**Comment by david-yu** [comment]
Also resolved by https://github.com/hashicorp/consul/pull/16845
