### ISSUE TITLE
[Question] "Key contains invalid characters"

### ISSUE THREAD

**Issue by wrfly** [hashicorp/consul#4422]
https://github.com/hashicorp/consul/blob/63d5c069fc84281aa1f77a305147e2e1994e347e/agent/structs/structs.go#L86

https://github.com/hashicorp/consul/blob/63d5c069fc84281aa1f77a305147e2e1994e347e/agent/structs/structs.go#L386-L388

Why don't allow the metadata key contains `:` ?

Some components use `:` to split fields so I cannot understand why remove the `:`.

```txt
Couldn't load metadata pair ('check:id.102.co:5', 'passing'): Key contains invalid characters
```

**Comment by wrfly** [comment]
If the character `:` bothers others (or `consul` use `:` to split things), I think you can encode(base64 for example)  the original metadata key to avoid that. Cause other programs may also want use `:` to split things.

**Comment by wrfly** [comment]
As well as other user-defined keys(such as service name, service id, check id balabala), I think this restriction is not friendly.

**Comment by banks** [comment]
Hi wrfly,

Thanks for the suggestion. The main reason it's restrictive is because we've learned the hard way that being more restrictive and relaxing it when there is a good reason is better than the other way around - starting wide open and then having to make breaking changes when incompatibilities result.

I _assume_ you are referring to `Service.Meta` here from the context rather than `Node.Meta` but please confirm.

`Service.Meta` was a recent addition and so we just re-used the rules we always had for `Node.Meta` as a reasoable starting point.

The reason `Node.Meta` was restrictive was that it was originally designed to hold records that would be added as DNS TXT records and the keys for those must be valid DNS names.

We could relax that globally but then would end up in the unpleasant situation that if you actually want to use them as DNS TXT records we have no good way to flag up that you've named them badly except warnings in agent logs which are rarely being watched by a user trying to configure a service.

> If the character : bothers others (or consul use : to split things), I think you can encode(base64 for example)

Consul internals have no issue with the chars, but Base64 doesn't for example solve the DNS issue.

> As well as other user-defined keys(such as service name, service id, check id balabala)

We actually have the _opposite_ problem there! Service names have almost no restrictions at all which means it's easy to create service names that are _not_ valid DNS entries which then breaks DNS service discovery. We can't back out of that decision now easily without breaking lots of people's existing setups. On the other hand, even though we do log warnings in agent logs when you register a service with a DNS-incompatible name, it still confuses users why it doesn't work.

Are you specifically concerned about `Node.Meta`,  `Service.Meta` or both? There is an argument to say we could relay `Service.Meta` some easily since that is never used in DNS but then it might be confusing that the rules are different between them. We could relax both and just make the UX bad if you actually want to use `Node.Meta` in DNS records... What do you think?

**Comment by wrfly** [comment]
Hello Paul,

Thank you for your patient explanation, and I'm not stuck in this problem any more. I didn't meet the problem with DNS TXT records, we only use consul a service discovery component, so I can't public my opinions here...

I didn't check the documentation about these restrictions before, but I did confused with the restriction of `Service.Meta`. I used to use this `Service.Meta` to pass some configurations, but now the problem was solved, by not using it... 

> The meta object is a map of max 64 key/values with string semantics. Key can contain only ASCII chars and no special characters (A-Z a-z 0-9 _ and -). For performance and security reasons, values as well as keys are limited to 128 characters for keys, 512 for values. This object has the same limitations as the node meta object in node definition. All those meta data can be retrieved individually per instance of the service and all the instances of a given service have their own copy of it.

Thanks again.

**Comment by Macrame** [comment]
@banks Hello Banks. I encountered an exception `OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('user.name', 'spring_boot'): Key contains invalid characters')`  that was related to this issue. So I am commenting to this. I actually want to use `Service.Meta` to pass come configurations containing a special characters `.` such as `user.name` or `user.password`. Could you relax the restriction about `Service.Meta`?

**Comment by banks** [comment]
Hi @Macrame 

Would it be possible to open a new issue as a feature request for this - we can't effectively track the request as a comment on a long-closed question!

I'd say that we _could_ make that chance but that it's not obvious that we _should_. As described before the user experience of either having different rules for Node vs Service meta is not great, and if we allowed it in service meta that it would break DNS TXT records.

In your case is it impossible to use DNS-valid key names like `user-name` for example? If you feel like this isn't workable, feel free to open a new issue as a feature request we can triage, decide on the impact to other users and decide if we want to make a change here!

Thanks for reporting!

**Comment by pierresouchay** [comment]
@banks It is true that for services meta, many people want to push `.`, mostly in the Java world because it is the common way to define properties. We had to patch in many places our SDKs/injections systems to replace those with `_` for instance.
Maybe allowing it in Service meta would not be such a big problem for Consul and would definitely help many people, but I see your point regarding the differences between Node.Meta and Service.Meta. However, there is a big difference: Node.Meta is mostly injected by Infrastructure (eg: chef), so it is possible easily to enforce some rules regarding the naming in 1 single place, while service.Meta might be injected by various systems (Java, Ruby, python, C# and friends) with many libraries that consider service.Meta like a commodity and do not take such limitations, so, for the the sake of UX, I would tend to say that it would be a good move to be a bit more permissive for Service.Meta

**Comment by HaojunRen** [comment]
I also agree with removal the limitation for dot(.), because no other Registration Middlewares limit this, ex Zookeeper, Eureka, Etcd. I suggest you can provide a config file in Consul Server to let people to enable/disable the limitation. If they met DND TX, they enable the limitation
