### ISSUE TITLE
Service Mesh on Amazon ECS

### ISSUE THREAD

**Issue by hermes-pimentel** [hashicorp/consul#4440]
Hi There, 

Anyone was able to deploy and configure Consul Connect on Amazon ECS?

**Comment by mkeeler** [comment]
@hermes-pimentel Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
