### ISSUE TITLE
Log file configuration

### ISSUE THREAD

**Issue by ollio** [hashicorp/consul#445]
Hi,

It would be nice to be able to change log file location and name. We use a logwatch that is looking in a specific folder and fetches all *.log files.

An entry in consul.conf like "log_file":"/path/to/my/file.log" would be nice.

**Comment by ryanuber** [comment]
As @i0rek mentioned, normally to get file-based logging, you redirect stdout to a file. You can also achieve this by forwarding messages to a syslog server, allowing it to do what it is good at and redirect your logs wherever you want them to go. I'm going to close this, because I don't see us adding this as a core consul feature. Thanks!
