### ISSUE TITLE
change the const value of DefaultMaxHeaderBytes

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#4451]
Hi,

Is DefaultMaxHeaderBytes configurable via config file or command line?

**Comment by mkeeler** [comment]
@hehailong5 Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)

With that being said it doesn't look like we allow configuration of MaxHeaderBytes
