### ISSUE TITLE
Why are we calling SyncChanges() for TTL updates?

### ISSUE THREAD

**Issue by flyinprogrammer** [hashicorp/consul#4460]
AgentCheckPass
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent_endpoint.go#L431

AgentCheckWarn
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent_endpoint.go#L449

AgentCheckFail
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent_endpoint.go#L467

All call a blocking call of `s.syncChanges()`:
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent_endpoint.go#L342-L346
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/local/state.go#L1062-L1063

What I'm failing to understand is why do we do this?

All three methods call `s.agent.updateTTLCheck(checkID, api.HealthCritical, note)`:
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent_endpoint.go#L428-L430 
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent.go#L2498-L2524

Which calls: `check.SetStatus(status, output)`:
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/agent.go#L2510

Which calls `c.Notify.UpdateCheck(c.CheckID, status, output)`:
https://github.com/hashicorp/consul/blob/8cbeb29e73411854568e36ae6c61196c6915bd96/agent/checks/check.go#L280

Which goes to this code block:
https://github.com/hashicorp/consul/blob/7fa6bb022f8cbd9c9dc8de89132cf47333050966/agent/local/state.go#L469-L544

Which either calls `l.TriggerSyncChanges()` or not, depending on whether or not the check update is important:
https://github.com/hashicorp/consul/blob/7fa6bb022f8cbd9c9dc8de89132cf47333050966/agent/local/state.go#L519

Which is setup when we start the agent:
https://github.com/hashicorp/consul/blob/0e0227792b5de60ea29cbdbe9838ae04c55e7277/agent/agent.go#L346-L351

Which is used to notify the syncer to do a partial sync
https://github.com/hashicorp/consul/blob/0e0227792b5de60ea29cbdbe9838ae04c55e7277/agent/ae/ae.go#L275

Which calls the same `SyncChanges()` method we're going to force every API call to call:
https://github.com/hashicorp/consul/blob/0e0227792b5de60ea29cbdbe9838ae04c55e7277/agent/ae/ae.go#L197

Seems to me if the syncer is working, we wouldn't ever have to call that extra sync on each api call; however, I'm still learning go, so if someone has cycles to explain to me why my thinking is wrong I would be extra appreciative!

**Comment by freddygv** [comment]
Hi @flyinprogrammer, the reason for calling `s.syncChanges` is that it directly triggers a sync against the catalog. 

TriggerSyncChanges notifies [retrySyncFullEventFn](https://github.com/hashicorp/consul/blob/0e0227792b5de60ea29cbdbe9838ae04c55e7277/agent/ae/ae.go#L230), but for that to be handled, the `StateSyncer` FSM needs to be in the [partialSyncState](https://github.com/hashicorp/consul/blob/0e0227792b5de60ea29cbdbe9838ae04c55e7277/agent/ae/ae.go#L186). Getting to this state can be delayed by up to 30 seconds due to transient errors in the full sync state. 

Because of this, calling `s.syncChanges` in the HTTP handlers can allow us to push user updates faster than if we only let the `StateSyncer` handle them. However, if the `StateSyncer` does get to the request first, then `syncChanges` will only do a small amount of work to find out that nothing needs to be synced. 

So you're right, we don't need to call `syncChanges` to update a given TTL status, but it can speed up the sync for little extra cost.

**Comment by flyinprogrammer** [comment]
thanks for being awesome @freddygv - this was helpful follow up!

**Comment by 249043822** [comment]
In the AgentCheckPass() endpoint, it would call `if err := s.agent.vetCheckUpdate(token, checkID); err != nil {
		return nil, err
	}`
and
`s.syncChanges()`
sequentially.

sometimes, maybe due to network io delay, `s.syncChanges()` may be blocked for a long time, as inside `s.syncChanges()` , it got a Write Lock, then the following TTLs would be blocked because they could not get RLock while runing the line ` if err := s.agent.vetCheckUpdate(token, checkID); er`, then the ttl timeout, our service becomes critical.
After a while, when the first `s.syncChanges()` break out, it return to normal.

we have met such problem many times,  any suggestions?

**Comment by freddygv** [comment]
Hi @249043822. Given current options, I can't think of a better solution than increasing the TTL interval for that check. 

There is no configuration option to adjust the 10 second timeout for the RPC to sync the check status. 

Additionally, `syncChanges` _needs_ to acquire a lock because check states can be updated concurrently by multiple goroutines.

One way to mitigate this could be to refactor `SyncChanges()` so that we release the state lock after constructing a list of services and checks that were deleted or aren't in sync. That way the catalog update isn't done while holding the lock. This would require some more thought to ensure it's safe to make that change.
