### ISSUE TITLE
Consul script check restarting microservices

### ISSUE THREAD

**Issue by rohit02bits** [hashicorp/consul#4489]
Consul Version : 1.2.1
I am trying to put in a script check and watcher for microservice. My ingestion service is port less. The configuration as follows

{
"name" : "ingest_document",
"tags" : ["ingest_document"],
"check" : {
     "id" : "ingest_document",
      "name" : "ingest_document service",
      "args" : ["/opt/disk1/checkService.sh", "DOC"],
      "interval" : 10s
      "timeout" : 1s
      }
}

"watches": [   

        {

            "type" : "service",

            "service" : "ingest_document",

            "args" :  "/opt/disk1/launchIngest.sh abc"

        }]

The service check service just checks if the PID>0 then return correct state or else critical state.

This set up just restarts the service after every 5-10 min. On the contrary the microservices that are enabled with tcp port check works properly. Any idea how to solve this issue.

While checking for health state for the server via rest end point. I get the following issue
fork exec error: /opt/disk1/checkService.sh mo such file or directory

Please let me know if this issue can be fixed as it stops me from taking consul to production.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
