### ISSUE TITLE
Web UI should not have inline JS

### ISSUE THREAD

**Issue by oninoshiko** [hashicorp/consul#4490]
The web UI should load all JS as a seperate file, rather then using line JS. Inline JS limits the abilty to use tight Content-Security-Policies. Loading JS in a seperate file allows the use of "script-src 'self'". While it's theoreticly doesn't affect consul-ui, it's a good practice, particlularly if there is other things on a web-server.

**Comment by johncowen** [comment]
Hi @oninoshiko 

Thanks for the feedback, definitely some good info in there.

Could you show me/point out to me the inline JS you are referring to? When using 'View Source' or the Web Inspector 'Elements' tab, I don't see any inlined JS, the only `<script>` tags I see are the Ember 'vendored' dependencies JS file and the application JS file itself. Apart from those two (which `src` external JS files), I cannot see any other javascript included in the app, whether via script tags or using inline event listeners or any other means.

Maybe I'm misunderstanding what you are referring to?

Could you also confirm you are using the new Consul UI shown here:

https://demo.consul.io/

And not the older one (the older one looks very different from the above link)

Thanks,

**Comment by oninoshiko** [comment]
I am using 1.1.0 with the older UI. From your demo setup there, the new one looks quite nice. I'll update, switching to the new UI and see if I still have to override my CSP settings. 

I'll report my findings tomarrow.

**Comment by oninoshiko** [comment]
(I Lied, I looked today)

I updated to 1.2.2, which uses the new UI by default.

The new UI is defintely useable with CSP set to 'self' which is awesome! I do still get CSP errors from inline styles and svg, but the page is still useable even with those items blocked. I'll do some more looking into that when I get some free time.

**Comment by johncowen** [comment]
Hi @oninoshiko 

Good stuff! Thanks for getting to that so quickly! I've checked this by using the HTTP headers we use in our other UI's and everything continues to work as expected.

Any inline styles will be added via javascript and will be necessary for the layout of individual elements, and we usually use svg for crisp icons etc when it's not trivial to achieve that with CSS alone.

I'm guessing this issue was an issue with the old UI that we've solved with the upgrade, so I'm going to re-label and close the issue.

Please feel free to re-open if you continue to have issues.

Thanks,
