### ISSUE TITLE
support prefix with service_ttl

### ISSUE THREAD

**Issue by wdauchy** [hashicorp/consul#4509]
Hello,

Currently service_ttl only support exact match https://github.com/hashicorp/consul/blob/master/agent/dns.go#L984
I would like support for prefix on service_ttl.

Thank you,

**Comment by pierresouchay** [comment]
@wdauchy both regexp or prefix based match should be possible, regexp being linear for lookups while everything is ready for prefix based, I'll try to provide a patch with prefix-based if prefix is followed by *

my-service1: 10s -> exact match
service-lb*: 30s -> prefix match

@wdauchy Ok for you?
@banks @mkeeler would you consider this for merging this upstream?

**Comment by wdauchy** [comment]
@pierresouchay sounds great :+1:

**Comment by pierresouchay** [comment]
@pearkes implemented in https://github.com/hashicorp/consul/pull/4605

**Comment by frederikbosch** [comment]
Is there any reason that prefix implemented, but postfix is not possible? I understand the use case for prefixes, it allows to have a different TTL for a more specific service. However, what if you want to have a different TTL for the same service on a different interface?

`service-a-interface-a` => global TTL (0 seconds)
`service-a-interface-b` => specific TTL (config specific, e.g. 60 seconds)
`service-b-interface-b` => specific TTL (config specific, e.g. 60 seconds)

Since `service_ttl` does not allow a different TTL per tag, you will have to use the prefix. This leads to unclear naming of the service.

My suggestion would be to have one of the following added: a different TTL for specific tag or a different TTL for a specific postfix. Would the Consul team agree to either of those?

I would prefer tag-based TTLs, because it allows maximum flexibility. However, it would lead to the follow-up question: how to implement precedence? I think tag-based TTLs should have precedence over other TTLs.

**Comment by pierresouchay** [comment]
yes, radix trees (implementation to perform lookups in Consul) work great with prefixes, not so much with suffixes... so performance gap with full regular expressions would be significant.

Tags TTL is probably possible, might be implemented if your create another issue
