### ISSUE TITLE
cluster issue with leader

### ISSUE THREAD

**Issue by ikozhukhov** [hashicorp/consul#4516]
we have setup - 4 server nodes in cluster.
setup based on : illumos based platform DilOS, setup 2 physical servers, consul server run in global zone and zone per server = 2 consul servers per physical server.

problem is: if we lost one physical server with leader - 2 others consul can't define leader.

we want's to use consul servers on primary nodes and several others physical servers as agents.
but, we need stable cluster, where if we lost one physical server with leader, it should be defined on another host, but it is not working.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
