### ISSUE TITLE
NodeMeta Data is not stored in snapshots

### ISSUE THREAD

**Issue by nickmy9729** [hashicorp/consul#4524]
When issuing command consul snapshot save /somedir/filename.snap.  The snapshot produced does not contain the NodeMeta data.  This is important when you have registered an external node that is not using a Consul agent via the /v1/catalog/register API that include NodeMeta.  Once restoring the snapshot the node is visible but it's MetaData is gone.

I have also seen similar behavior when all servers have been restarted the NodeMeta would not persist in the data directory, even though on closer inspection it appears to be in the raft.db file.

**Comment by mkeeler** [comment]
@nickmy9729 Thanks for the report.

I think the problem is around here in the code:

https://github.com/hashicorp/consul/blob/e305443db4ba8295510faf2402e584650efeb3f8/agent/consul/fsm/snapshot_oss.go#L74-L79

I ran into a similar issue recently where we weren't putting some of the data into the snapshot and restoring it out of a snapshot properly. That is when its in raft too. So the situation sounds pretty similar.

**Comment by shubheksha** [comment]
I'll pick this up!

**Comment by nickmy9729** [comment]
I just submitted a PR that seems to fix this issue #4527
