### ISSUE TITLE
Can i use the key-value/service in a consul watch command?

### ISSUE THREAD

**Issue by sanjaykrkundu** [hashicorp/consul#4537]
this is what i'm trying to do...
lets say i have 2 services A,B.
and kv contains an url for each service kvURL-A,kvURL-B

i want to call the url(s) when the service is modified.
change in service A
   - call kvURL-B

change in service B
   - call kvURL-A

**Comment by freddygv** [comment]
Yes that is certainly possible. You can set up a watch for each service that invokes an executable implementing your logic to call the kvURLs.

The documentation for service watches is [here](https://www.consul.io/docs/agent/watches.html#type-service). 

Lastly, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)
