### ISSUE TITLE
Is it possible to hide Serf Health Status in UI

### ISSUE THREAD

**Issue by Mariius** [hashicorp/consul#4552]
Is it possible to hide Serf Health Status in UI for nodes?

**Comment by freddygv** [comment]
Hi Mariius,

That is not possible to do as a user with the current UI. However, if you would like to describe the use case for it, we could consider it as a feature request for a future release.

Additionally, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)
