### ISSUE TITLE
Is there a way to know if a lock is released?

### ISSUE THREAD

**Issue by aakashgyl** [hashicorp/consul#4553]
I am working on a code where multiple goroutines want to acquire lock on a key. Is there a way by which my code can get to know that lock is released or I have to continuously try to acquire lock till I succeed? I feel the latter approach is not good.
Please help.

**Comment by freddygv** [comment]
It seems that you may be using Consul's Go API. If that is the case, calling [Lock](https://github.com/hashicorp/consul/blob/master/api/lock.go#L133:16) will block until the call succeeds so you don't need to continuously retry. A small example of locking and unlocking is visible in the tests for `lock` [here](https://github.com/hashicorp/consul/blob/master/api/lock_test.go#L33).

If you want to know if the lock is being held (without acquiring it), you can check if there is a session associated with the key. See [here](https://www.consul.io/docs/guides/leader-election.html#discovering-a-leader) for an example. [Blocking Queries](https://www.consul.io/api/index.html#blocking-queries) can be helpful in this situation. 

Lastly, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)
