### ISSUE TITLE
Proxy health check should use valid client certificate

### ISSUE THREAD

**Issue by pearkes** [hashicorp/consul#4565]
Proxy health checks should be performed with valid client certificates to avoid error messages in the proxies logs or elsewhere. Currently, we check the health of the proxy with TCP and generate unnecessary noise as a result.

**Comment by shantanugadgil** [comment]
Does this seem related to #3936 ?

**Comment by pearkes** [comment]
@shantanugadgil I think so. That would be providing a generic approach for health checks, vs. this issue being focused on the Connect proxy, but depending on how we solve this we could potentially close both issues.

**Comment by adams-sarah** [comment]
Pasting my progress for the next person (notable help from @rboyer and some from @banks):

Reproduce:
```bash
./tlsserver # go server

**Comment by adams-sarah** [comment]
Pasting my progress (notable help from @rboyer and some from @banks). @pearkes FYI

#### Steps to Reproduce:

```bash
# 1. start server listening on :8181
./tlsserver # throw away go echo server

# 2. Start a service
# 2.a. Define service
echo '{"service": {"name": "tlsserver", "port": 8181, "connect": { "sidecar_service": {} }}}' > $HOME/dev/consul.d/tlsserver.json

# 2.b. Start service
consul agent -log-level=debug -dev -config-dir=$HOME/dev/consul.d

# 3. Start proxy
consul connect envoy -sidecar-for tlsserver -- -l debug
# spurious log msg:
# [2019-07-30 19:23:10.311][24939][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:168] [C1] handshake error: 5
```

#### Thoughts around code modification
*(I don’t have much context, so take these with a big grain of salt)*

0. Note check is registered in agent/sidecar_service.go:170
```go 
// Setup default check if none given
    if len(checks) < 1 {
        checks = []*structs.CheckType{
            &structs.CheckType{
                Name: "Connect Sidecar Listening",
                TCP:      ipaddr.FormatAddressPort(sidecar.Proxy.LocalServiceAddress, sidecar.Port),
                Interval: 10 * time.Second,
            },
       // ...
        }
    }
```

1. In [agent/checks/check.go:470](https://github.com/hashicorp/consul/blob/master/agent/checks/check.go#L470)
Add `TLSClientConfig *tls.Config` field to CheckTCP (mimicking types CheckHTTP, CheckGRPC) 
2. In [agent/checks/check.go:530](https://github.com/hashicorp/consul/blob/master/agent/checks/check.go#L530) 
In `func (c *CheckTCP) check()`: check for TLSClientConfig - if exists, use `DialWithDialer` instead of `Dial` (eg. tls.DialWithDialer(c.dialer, `tcp`, c.TCP, c.TLSClientConfig)`,
3. In [agent/agent.go:2507](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L2507)
Set the new TLSClientConfig field in `tcp := &checks.CheckTCP{…}`


That’s as far as I got. Code suggestions have a big chance of being wrong! Note: I'm new to the project / no context.

#### Some thoughts from other team members (somewhat paraphrased):

1. perhaps the only way we’ll avoid log noise is by generating a magical cert that we auto-authorize which has security implications - if anyone else gets hold of that cert then it’s a free pass to access any connect service regardless of intentions. If we can get away with generating a cert locally that doesn’t even validate but still stops the “connection closed” error then great. but it may just replace it with a different handshake failed error. then we would have to generate a real cert from connect which is OK but it may still cause a log error when we decline the AuthZ call. if it doesn’t do that in INFO mode then it may be the winner.
2. Maybe there's some trickery you could play with SNI headers to announce "this is a healthcheck; please disregard"
3. Having to actually successfully auth to avoid a log may not be worth it from a complexity/payoff standpoint

**Comment by pearkes** [comment]
Based on the potential ways forward following @adams-sarah's investigation being very complex one other option as we triaged and discussed with @banks could be just documented the error message in the logs in the short-term for awareness when users see it (concern about the message led to the initial issue creation).

Could still potentially tackle one of the real solutions down the road, but that might be a good step for the moment. Going to milestone for visibility and possibly slotting that take-away into a near-term release.
