### ISSUE TITLE
Consul proxy connect blocking query documentation improvement

### ISSUE THREAD

**Issue by bedis** [hashicorp/consul#4596]
#### Overview of the Issue
The consul connect documentation misses some information on how to do the blocking query for the managed proxy configuration: https://www.consul.io/api/agent/connect.html#managed-proxy-configuration
Basically, the reader is instruct to use the ContentHash JSON field for the "hash-based" blocking query.
What the documentation does not say, is how to use the value.
I refered myself to https://www.consul.io/api/index.html#blocking-queries to find out a way, until I understood I had to send a query string parameter "hash=<value>" to be blocked until an update occurs.

Would be great to update the documentation, maybe in the table which summarizes the blocking query status, to provide the source value (here ContentHash JSON parameter) and the query string parameter for the request (here "hash").

**Comment by banks** [comment]
@bedis thanks for reporting this! 

That endpoint is actually deprecated since 1.3.0 but we use the same mechanism for another agent endpoint now. The docs explicitly call out the hash blocking with a link to https://www.consul.io/api/index.html#hash-based-blocking-queries as you found. I forget if this was like this at the time you found this issue.

![Uploading Service - Agent - HTTP API - Consul by HashiCorp 2018-11-12 11-46-23.png…]()

Does that make it clear enough? We don't generally give explicit examples of how to do blocking inline just because it takes up a bunch of space and is the same everywhere (for regular blocking now). Hash based blocking is a little different but is something we might consider supporting everywhere in the future which is why it was documented in the same way rather than more explicitly inline. Does that make sense?

I think adding that to the table might be tricky visually since in the future we expect most (GET) endpoints to support both forms anyway.
