### ISSUE TITLE
UI Tag search filling browser history for every keystroke

### ISSUE THREAD

**Issue by cricket007** [hashicorp/consul#4614]
On the new 1.2.2 UI tag search feature, is it to be expected that the browser history gets inserted into on every keystroke?  

Note: Might only happen when there is a status that has been selected 
![image](https://user-images.githubusercontent.com/1930631/44743962-7f8e9800-aac9-11e8-89e8-d3e5c17f8aa2.png)

While I'm not a webdev person myself, isn't there some front-end router library that would maintain that history stack itself? Then when you actually hit back on the browser, it would send you back to the actual last page not only "undo the last keystroke"? For example, if I came from ACLs to the services, search a tag, then hit back, I think I would expect to go back to ACLs (I didn't actually test if this was the case or not).

**Comment by johncowen** [comment]
Hi @cricket007 ,

Firstly thanks for submitting the issue! 😄 

I think this was a mix between the old UI adding query param changes to the browser history and following what our other products do whilst searching/changing query params.

I'm pretty sure our framework gives us the ability to not add these entries to the history if that's what's required. I think the main thing is making sure we do the right thing here. Me personally, I wouldn't add keystrokes to the history, but others might prefer that we did.

I'm going to bring this up with the rest of the team, just to make sure not adding search keystrokes to the history is the desired behaviour before I change it. I'll try to keep you updated here with the result of that.

Thanks,

John

**Comment by DingoEatingFuzz** [comment]
To get the best of both worlds (search history without flooding), you can debounce the updates to the `filter` call. 

This would mean binding the search input to some intermediary property, then using `run.debounce` to call `onChange` with the value of that intermediary.

Something like this: https://github.com/hashicorp/nomad/blob/master/ui/app/components/search-box.js

**Comment by johncowen** [comment]
Hi @cricket007 

I've just been looking into this a bit further, and now I can see why I was a little unsure of what was happening here.

I was pretty sure that when I initially built this functionality I followed what we had in the old UI, which was to add an entry to the history for 'filtering' by health, but not to add an entry to the history for 'freetext searching'.

Your screengrabs above and on the referenced PR confused me a little as it does look as though the new UI adds entries to the history for every keypress in the search bar (i.e. freetext searching) which wasn't the desired functionality.

Just to pause before I continue, it's worthwhile pointing out a distinction here - what I've realised is there are 2 things we are discussing here:

1. 'Adding to the history' in that it adds more entries to your back button so that when you click and hold the back button you see a list of entries in the dropdown menu there.
2. 'Adding to the history' in that it adds more entries to your 'View History' page in your browser.

The new (and the old UI) does point 2 above, but not point 1.

In that typing in the search bar adds to your 'View History' page but does not add history to the dropdown on your back button, so if you press 's' 5 times and then you click the back button it will take you back to the previous page - not delete the 5th 's', but all these entries/keypresses will appear in your 'View History' page.

I'm not massively sure if its possible to keep URL changes out of the 'View History' page of your browser. We are already using the javascript history API to keep entries out of your actual back button, and I 'think' the 'View History' page itself is something that we cannot control.

The only option would be not to change the URL at all when we type in the search bar. This would also prevent people from being able to share links to a search result, and therefore reduce functionality - so I doubt that it is something we'd consider removing.

Something we have spoken about, which doesn't address your specific issue, is adding an entry to the back button when you unfocus the search text field. I don't think we'd ever want to add back button entries on every single keypress, even debounced slightly - but if we can assume the search being finished by detecting when the search field is unfocussed, this might be valuable for someone to have in their back button history.

Lastly, I'm going to have a look into this a little further before closing to be sure it's not something we can't address. It was definitely an interesting one though, so thanks for submitting!

If you spot that I've not understood something here, feel free to comment and I can re-look also, indeed even after this issue is closed.

**Comment by cricket007** [comment]
Thanks for the update @johncowen

From a user perspective, I'm personally fine with the 'View History' being filled since I doubt many people really go through those menus in the browser anyway. 

I do understand the point about URL linking, which is nice, although, as noted, requires at least one person's history to get filled up. 

I didn't play around too much with the back button, but I did mention my expectations at the end of the my post. And I'm assuming that the alternative is pressing back is essentially an "undo keystrokes" until one reached the initial input field state, and then it would finally go back to the previous page.

I think a defocus or some small keystroke delay makes sense, though I'm not super familiar with all these Javascript APIs nowadays

**Comment by johncowen** [comment]
Hey @cricket007 

Thanks for the info. Reading you comments here I'm wondering if we are seeing different things, which possibly could be a bug somewhere, or I'm misunderstanding what you are expecting to happen. Can we check just incase?

Does this work for you exactly the same as me?

1. I go to https://demo.consul.io/ui/dc1/nodes
2. I click the [Service] navigation button in the top menu bar to take you to the services page
3. I enter the search term 'api' in the search bar (by typing each letter)
4. I see the 'api' and 'api-proxy' services only.
5. I click the back button in my browser.
6. I am immediately taken back to the https://demo.consul.io/ui/dc1/nodes page

Hopefully you see the same as I do with that walkthrough?

You mentioned it possibly being a problem between the status filtering and the search. Choosing a status doesn't affect the search/history functionality of the searching, but choosing a status will enter an entry into you browser history (and therefore you can navigate back after that using the back button).

Thanks for your patience, I just want to make absolutely sure I'm not missing anything here.

Thanks!

John

**Comment by cricket007** [comment]
Alright, now that I am pressing the back button, here is what I see, which is tangentially related to this issue. 

1. I go to https://demo.consul.io/ui/dc1/nodes
2. I click the [Service] navigation button in the top menu bar to take you to the services page
3. I hit Passing, Warning, Critical, then back to Passing
3. I enter the search term 'proxy' in the search bar (by typing each letter)
I see the services that I expect. (those 4 services ending with `-proxy`) 
I click the back button in my browser.
I am **not** taken back to nodes, and the `status=passing` filter is still applied, and no services are changing, even though the url is changing to `warning` or `crtical`, for example. The only way the filter gets correctly applied, I need to click on those button tabs.

**Comment by johncowen** [comment]
Hey @cricket007 

Aaaah yeah, gotcha. So this is slightly different to what I'd understood, but yeah I get what you mean now. Let me check in with the team on this one and get back to you. Will leave this issue open now until I have a better answer for you.

Thanks again for bringing it up!

John
