### ISSUE TITLE
How to Modify Web UI ?

### ISSUE THREAD

**Issue by veryrich** [hashicorp/consul#4657]

**Comment by pierresouchay** [comment]
@veryrich The question is a bit vague, but you can recompile Consul with you patches (the UI has a specific target IIRC)

If you want read only, you can also have a look to http://github.com/criteo/consul-templaterb which comes with a full featured static UI you might serve with your favorite web-server, see: https://github.com/criteo/consul-templaterb/tree/master/samples/consul-ui

Since this full UI is just a template, you can customise if fully for your needs
