### ISSUE TITLE
Server IP address in cluster is 127.0.0.1

### ISSUE THREAD

**Issue by kinguru** [hashicorp/consul#4684]
Hi dear developers and community,

I've observed, that one server and client in cluster getting 127.0.0.1 in server members list.
How is it possible?  

Scenario in my case:
1. reboot one of the servers and one client node
After start sometimes cluster get broken - unable to select a leader. Error message "consul: failed to wait for barrier: leadership lost while committing log".
![inkedscreenshot_2_li](https://user-images.githubusercontent.com/54497/45609461-c3d5de00-ba60-11e8-8c28-c0efa280b4f5.jpg)

Best regards,
Ilya

**Comment by shantanugadgil** [comment]
Hi, as a debug helping step, can you post the relevant bits (the various _addr values) from the consul configuration file

**Comment by kinguru** [comment]
Sure! 
Each server has own retry_join - excepting itself (is it required?).
All other settings in config file are same for all servers (5).
{
  "datacenter": "AWS-****-****",
  "data_dir": "D:\\consult_data\\data",
  "log_level": "INFO",
  "node_name": "OS-EU-STG-WEB01",
  "server": true,
  "bootstrap": false,
  "rejoin_after_leave": true,
   
  "bootstrap_expect" : 3,
   
  "ui": true,
  "disable_remote_exec" : true,
  "disable_update_check" : true,  
  "retry_join": [ "100.***.***.251", "100.***.***.247", "100.***.***.177", "100.***.***.136" ],
  "addresses" : {
    "http": "0.0.0.0"
  }
}

**Comment by kinguru** [comment]
Hi Shantanu,
Looks like a defect in Consul public IP detection. I believe that there must be no way to register loopback address in a cluster.

**Comment by kinguru** [comment]
Up ;)

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here. Hopefully you and @shantanugadgil can continue the discussion there 😄.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
