### ISSUE TITLE
How can i specify a encrypted key_file when start consul

### ISSUE THREAD

**Issue by bigthanbig** [hashicorp/consul#4685]
Hi dear developers and community,

    Due to safety concerns，we need to specify a encrypted key_file when start consul, what should i do ?

Best regards,

**Comment by banks** [comment]
Hi @bigthanbig we currently don't have a mechanism to work with encrypted private key files.

One of the reasons is that you then have to pass the encryption key to Consul process via some other means anyway - e.g. via ENV var or in another config file. Arguably files are the most secure way to pass secrets since they are protected by filesystem permissions so it's hard to see which attack vectors you prevent by encrypting one file and then having to pass the key to decrypt via another config file or ENV var anyway.

Can you specify which mechanism of providing the encryption key would satisfy your "safety concerns"? What attack vector are your trying to mitigate? Or what is the exact security rule you are trying to comply with by encrypting the key file?

We plan to re-work some of the TLS config soon so if you have a specific request around this, as much detail as possible would be useful to see if we can satisfy it as part of that work.

**Comment by bigthanbig** [comment]
> ttack vector are your trying to mitigate? Or

hi banks
    thank u for your answer, i used nginx and tomcat before.
    nginx can specify a encrypted key_file and ask the user to input the password when nginx load the key file
    tomcat also could deal with encrypted key_file by decrypt it using the decrypt plugin provided by user.

and the Gossip Encryption are stored in clear text in the configuration file also, has the same problem as key_file.

Best regards

**Comment by i0rek** [comment]
Thanks @bigthanbig for your answer! 

I think so far we didn't consider providing a way to let the user input the password when consul loads, because it seems very cumbersome. I can see how you do it for 5 Consul agents, but not above 20. But we will keep it in mind! 

You also mentioned a secret provider, which is Vault for us! We are certainly thinking about ways to take advantage of Vault's features for Consul's TLS. The same is true for Gossip encryption which suffers from similar problems, but since it is DNS based, everything is little different there.

Rest assured that we are aware of these issues and are working towards a better solution.

**Comment by i0rek** [comment]
I will close this issue now, but I would be happy to reopen in case I missed something!
