### ISSUE TITLE
How to use query api create a service name prefix search?

### ISSUE THREAD

**Issue by PrinsWu** [hashicorp/consul#4690]
I watch the document for query API (https://www.consul.io/api/query.html)
I can use the service full name to search and get the result, but prefix not work.
ex:
I have 4 services [user_1, user_2, order_1, order_2] with 2 types.
And I want to search by the service prefix name likes 'user' or 'order' to filter services have the same type.
Someone can give me an example to complete this issue, Please!
Or use service tag in search, let me can filter that!

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
