### ISSUE TITLE
how to config multiple service instances with different port numbers in one host easily with consul ?

### ISSUE THREAD

**Issue by chgliu2018** [hashicorp/consul#4726]
The service is in a docker. Thank you~

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
