### ISSUE TITLE
Feature Request: Transfer leadership

### ISSUE THREAD

**Issue by ctro** [hashicorp/consul#476]
I'm running an immutable infrastructure, of which our Consul Cluster is a part.  Sometimes we need to upgrade our consul cluster, perhaps because the underlying OS has needed updates.

It's super easy to spin up new nodes and join them to the existing cluster.  It's also super easy to `consul leave` the old nodes that _aren't_ leader.  Everything just works.

But running `consul leave` on the "old" cluster's leader leaves us with a "new", but leaderless cluster.

It would be great if there were some sort of leadership transfer command that would allow me to transfer cluster leadership to one of the "new" nodes before running `consul leave` on the last remaining "old" node.

**Comment by AirbornePorcine** [comment]
Same issue as @francois here, playing around with Consul (0.5.0 now) in a Vagrant environment. 

@armon I had a look at the outage guide, but the problem is that the content of the peers.json file on all three nodes is the string "null". Removing the file didn't seem to make a difference, nor did restarting the server agents with or without -bootstrap-expect - they simply won't elect a leader without wiping my data directory.

**Comment by AirbornePorcine** [comment]
Played with this a little more - I can get it to elect a new leader if I start two nodes without any bootstrap information, then join the third node with -bootstrap -join=<IPs of other nodes>

Not sure if this is perhaps a unique situation?

**Comment by armon** [comment]
@AirbornePorcine If the peers file is blank, this means you had the nodes do a graceful leave. This is expected behavior. If the nodes leave, you don't want them to disrupt the existing cluster unless they rejoin. You would have to use the `-bootstrap` flag as you discovered at that point.

The `-bootstrap-expect` flag only operates if the cluster is fresh (e.g. no data in the Raft log) otherwise it is potentially unsafe.

**Comment by AirbornePorcine** [comment]
Great, thanks @armon !

**Comment by plombardi89** [comment]
@ctro never responded back with his experience unfortunately, but we're running a very similar immutable setup and have run into the same situation with 0.5.0. Is there a suggested process to follow here? I do not fully understand why the cluster goes into outage mode when during the upgrade process we balloon out from cluster size of 3 to 6 nodes (1 leader, 5 peers). Shouldn't we never lose quorum if we have six nodes and then shutdown the older nodes thus returning us to a size of three? Should I force-leave the old nodes instead?

**Comment by armon** [comment]
@plombardi89 It depends on how you are removing the older nodes. If they do not leave gracefully, then they are still part of the raft replication group. This means only 3 of 6 members are reachable and quorum is lost. If they leave gracefully or you remove one, then force leave, remove another, etc, then it will be okay as well.

As it stands you are dividing the cluster in half, and it is no longer able to safely commit new transactions.

**Comment by ctro** [comment]
@plombardi89 
Well, that took me forever :)
I just upgraded our consul boxes to 0.5.0.  Bringing up 3 new 0.5.0 nodes to join the old cluster worked.
Simply `consul leave`ing on each of the "old" nodes successfully transferred leadership to one of the "new" nodes.  Yipee :)

@armon, at this point I'll leave closing this issue up to you...
