### ISSUE TITLE
Consul Docker image is not persistent with Vault data

### ISSUE THREAD

**Issue by danielman111** [hashicorp/consul#4765]
I am using Vault Docker image with Consul Docker image as its storage. My problem is that if supposedly the Consul container will go down, and I will try to run a new container, I need to init the vault all over again, and the data that was saved by Consul get lost.

Anyone know what I need to do in order to get the data to be persistent?

Command to run the Vault image:

`docker run -d -p 8200:8200 -v /root/vault:/vault --cap-add=IPC_LOCK vault server`

And the vault configuration file content:

```
{
            "listener": [{
                    "tcp": {
                            "address": "0.0.0.0:8200",
                            "tls_disable" : 1
                    }
            }],

            "storage" :{
                    "consul" : {
              "address" :"consulIP:8500"
              "path"    :"vault/"

                    }
            }
            "max_lease_ttl": "10h",
            "default_lease_ttl": "10h",
            "ui": true,
}
```
Creating the consul volume:

`docker volume create consul --label description='Persistent data for consul'
`

consul configuration file content:
```
{
    "log_level": "DEBUG",
    "server": true,
    "ui": true,
    "bootstrap": true,
    "client_addr":"0.0.0.0"
}
```

Command to run the Consul image:

`docker run -d -p 8400:8400 -p 8500:8500 -p 8600:53/udp --net mynet -v /root/vault/consul:/consul --mount type=volume,source=consul-volume,target=/consul/data --name consul -it consul`

Now still after all this, the data is not persistent in case I bringing up new consul constainer.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
