### ISSUE TITLE
import command failing

### ISSUE THREAD

**Issue by pritam97** [hashicorp/consul#4844]
I have below json 
{
"bar":"test"
}

#### Overview of the Issue

am trying to import above json in consul am getting below error. 
consul kv import @abc.json
Cannot unmarshal data: json: cannot unmarshal object into Go value of type []*impexp.Entry

consul version: Consul v1.2.2

version ubuntu 16.4 LTS

**Comment by pritam97** [comment]
@rboyer : Thank you for quick response. 
 I have nested json with more than 1000 keys/values, it is not feasible for me convert each key into base64 format. do you have any idea about any utility that can easily import json. and my json contains the LIST as well. 

Thanks you 
Pritam K

**Comment by rboyer** [comment]
There are many ways to bend your json into the correct shape. The full solution is going to be very specific to your inputs, but here's a way forward for you utilizing the fantastic tool [jq](https://stedolan.github.io/jq/manual):
```
# Your example input, shaped similarly to your original inquiry.
$ cat > orig.json <<EOF
{
  "key1" : "value1",
  "key2" : "value2"
}
EOF

# Use the jq tool to walk the map of kv pairs and reshape it
# into the format consul kv import expects.
$ <orig.json jq '. | to_entries | . | map({key:.key, value:(.value| @base64)})' > new.json
$ cat new.json
[
  {
    "key": "key1",
    "value": "dmFsdWUx"
  },
  {
    "key": "key2",
    "value": "dmFsdWUy"
  }
]

# verify the results
$ consul kv import @new.json
Imported: key1
Imported: key2
$ consul kv get -recurse
key1:value1
key2:value2
```

I hope this helps!

As this isn't a bug in Consul I will close this issue.

Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here in the future.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)
