### ISSUE TITLE
connect: Getting started on localhost makes it easy to misconfigure an infinite proxy loop

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#4896]
#### Overview of the Issue

https://learn.hashicorp.com/consul/getting-started/connect

`consul agent -dev -node home -config-dir=consul.d`

Managed to screw myself again in less then 5 minutes tinkering with the tutorial :D The following will blow up your laptop :P 

Can we have a noob protection check please or drawings maybe to prevent it :)

#### Reproduction Steps
home.json
```
{
  "service": {
    "name": "app",
    "tags": ["home"],
    "port": 8080,
    "connect": {
      "proxy": {
        "config": {
          "upstreams": [{
            "destination_name": "socat",
            "local_bind_port": 8181
          }]
        }
      }
    }
  }
}
```
socat.json
```
{
  "service": {
    "name": "socat",
    "port": 8181,
    "connect": {
      "proxy": {}
    }
  }
}
```

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 2
        services = 4
build:
        prerelease = rc1
        revision =
        version = 1.4.0
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 127.0.0.1:8300
        server = true
raft:
        applied_index = 19
        commit_index = 19
        fsm_pending = 0
        last_contact = 0
        last_log_index = 19
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:a5cb466b-cca4-042a-70d9-76e7c14ee2da Address:127.0.0.1:8300}]
        latest_configuration_index= 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 117
        max_procs = 8
        os = darwin
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```
</details>

### Operating system and Environment details

OSX

### Log Fragments

```
2018/11/04 05:34:33 [DEBUG] http: Request GET /v1/health/connect/socat?connect=true&passing=1&stale= (149.981µs) from=127.0.0.1:51748
    2018/11/04 05:34:33 [DEBUG] http: Request POST /v1/agent/connect/authorize (149.966µs) from=127.0.0.1:51784
    2018/11/04 05:34:33 [DEBUG] http: Request GET /v1/agent/connect/ca/roots (98.49µs) from=127.0.0.1:51748
    2018/11/04 05:34:33 [DEBUG] http: Request GET /v1/health/connect/socat?connect=true&passing=1&stale= (159.439µs) from=127.0.0.1:51748
    2018/11/04 05:34:33 [DEBUG] http: Request POST /v1/agent/connect/authorize (136.476µs) from=127.0.0.1:51784
    2018/11/04 05:34:33 [DEBUG] http: Request GET /v1/agent/connect/ca/roots (102.185µs) from=127.0.0.1:51748
    2018/11/04 05:34:33 [DEBUG] http: Request GET /v1/health/connect/socat?connect=true&passing=1&stale= (178.638µs) from=127.0.0.1:51748
    2018/11/04 05:34:33 [DEBUG] http: Request POST /v1/agent/connect/authorize (140.115µs) from=127.0.0.1:51784
    2018/11/04 05:34:33 [DEBUG] http: Request GET /v1/agent/connect/ca/roots (120.143µs) from=127.0.0.1:51748
...BOOM!...
```

**Comment by banks** [comment]
Hi, thanks for posting this.

For anyone else reading, I shoudl note that the guide on learn.hashicorp.com was the older one with managed proxies for a few days after launch due to timing - those are now deprecated, details [here](https://www.consul.io/docs/connect/proxies/managed-deprecated.html).

@gertcuykens do I unserstand correctly that you configured the proxy to proxy to itself (same listen port for listener and target service)? If that's the case, I'll rename the issue as it's not really a race condition.

In general it's not super obvious what we can do to prevent proxy loops in general - it's a complex problem to detect configurations which might result in a loop even ignoring application code we don't know anything about.

We could mention this in getting started documentation I suppose but we already try to direct the reader to set up correctly. This typically only happens when running through "getting started" with everything on localhost too - in production the remote server would be off host and so would never bee binding to the same local listener as a proxy in order to form a tight loop like this.

Do you have any specific suggestions for warnings/wording that would have helped you avoid this? Perhaps a callout in the proxy config examples that the local_bind_port should _not_ match the target's listening port for now as it's all on localhost?

Thanks!

**Comment by banks** [comment]
@kaitlincarter-hc FYI.

**Comment by kaitlincarter-hc** [comment]
Hi @gertcuykens I am the Education Engineer for Consul at HashiCorp. I appreciate all types of feedback as it helps me understand the many use cases of Consul. I am curious, if you had a specific use case in mind when you set the `local_bind_port` and target listening port as the same? Could you expand on your thought process for selecting port `8181` for both instead of copying the example?

**Comment by trujillo-adam** [comment]
I know this is a very old post, but I was going to update the tutorial and close this issue out. First, the tutorial has evolved since this issue was first posted. Have the changes addressed the issue? If not, would adding a link to the `local_bind_port` documentation (https://www.consul.io/docs/connect/registration/service-registration#local_bind_port) be acceptable? Where would we put the link? Would it make sense to add it to the next tutorial in the series:  https://learn.hashicorp.com/tutorials/consul/service-mesh-with-envoy-proxy?in=consul/getting-started#create-the-dashboard-service-definition

**Comment by trujillo-adam** [comment]
The change described in my previous comment was pushed: https://learn.hashicorp.com/tutorials/consul/service-mesh-with-envoy-proxy?in=consul/getting-started#create-the-dashboard-service-definition

Marking as closed.
