### ISSUE TITLE
The master token shouldn't be able to delete itself

### ISSUE THREAD

**Issue by nitsh** [hashicorp/consul#4897]
#### Feature Description

I was testing 1.4.0-rc1. I was able to delete the master token using the master token. Now I tried to see if I can set a new token as specified here : https://www.consul.io/docs/agent/options.html#acl_tokens_master
The documentation says : The master token is only installed when a server acquires cluster leadership. If you would like to install or change the acl_master_token, set the new value for master in the configuration for all servers. Once this is done, restart the current leader to force a leader election. If the master token is not supplied, then the servers do not create a master token.

But that doesn't create a new token i set in the config. It also doesn't seem to work when I just want to change the master token.

#### Use Case(s)

I don't think any token needs to delete itself.

**Comment by banks** [comment]
As noted in the mailing list, there is a way back from this that is currently not documented but will be shortly with 1.4.0 release. It follows the bootstrap-reset method Nomad uses: https://www.nomadproject.io/guides/security/acl.html#resetting-acl-bootstrap.

It seems reasonable to disallow deleting the same token making the request in general.

**Comment by mkeeler** [comment]
While reasonable for the current ACL goals, preventing deletion of a token using that token could limit any future login/logout operations with temporary tokens. In addition to those limitations it still wouldn't prevent deletion of the master token, it would just prevent the master token from deleting itself.

It sounds to me like the real problem was that changing the master token in the configurations was not applied like was expected.
