### ISSUE TITLE
ACL token not working | Error 403 on all consul stuff

### ISSUE THREAD

**Issue by joshk132** [hashicorp/consul#4908]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I am trying to reload consul but getting error 403 and I think it is because of the ACL token not being accepted. 

#### Reproduction Steps

Create a new server and use our cookbook to configure it (designed for 0.7.1 but trying to use 1.3.0 as part of and upgrade), then use the curl command to hit the local API to register a check using the below command.

curl -v -H "Content-Type: application/json" --header "X-Consul-Token: <token>"  --request PUT --data @ping.json http://localhost:8500/v1/agent/check/register

### Consul info for both Client and Server
can't do consul info get the same error 403 issue as with my actual issue.

### Operating system and Environment details

Consul 1.3.0 
Ubuntu 16.04 LTS
Cookbook designed for 0.7.1 but should be compatible with current changes other than existing checks which have been disabled.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
