### ISSUE TITLE
have a tag to detect consul leader: leader.consul.service.consul

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/consul#4945]
#### Feature Description

Let's assume we have `consul.service.consul`
It would be handy a tag the will return: `leader.consul.service.consul`

#### Use Case(s)

- no need to query APIs to get the leader.
- writing directly to leader avoiding the stale slave entries. 
- maybe handy to put the leader behind haproxy/nginx

**Comment by banks** [comment]
Thanks for the suggestion.

Can you elaborate on the use cases? In general we dont really want the leader to be treated differently.

In fact our own RPC client deliberately _doesn't_ connect clients to the leader and if they are connected to the leader, their connection will be shuffled to a different server periodically to maintain good spread in client load.

It's an important scalability aspect of the design that we do this - even though write and non ?stale reads are proxied to the leader anyway, having an even client load across servers helps significantly with leader load and stability etc.

Not to mention that DNS is eventually consistent so we'd be very wary of adding this and giving users the implication they can rely on that DNS _always_ resolving to the leader. If you depended on that for safety for example you'd end up with "split brain" during failovers, even with no DNS caching that's true since it's connectionless and you need to poll constantly to get the "latest" value.

**Comment by maxadamo** [comment]
thanks for your prompt reply. 
In the past I've tried to implement Consul as a backend to Hiera with Puppet. 
The problem with it, is that it was too slow (tremendously slow) and I had to switch to Redis. 
My impression (correct me if I'm wrong) is that every time I was hitting a "slave" (I know it's not a slave, but allow me to use the word for simplicity :) ), the slave was contacting the leader to ensure that this entry was not stale. 
I don't really know if that was the only problem, maybe my redis is also faster because I'm using the Unix socket (p.s.: would it be an option, to add Unix socket to the linux version of consul? I could raise another request... in this case I could add a cluster member locally and connect through the socket)

**Comment by banks** [comment]
> p.s.: would it be an option, to add Unix socket to the linux version of consul?

You can already list on unix sockets!

If you're goal is performance then using `?stale` on all requests (or setting config to allow stale/cached DNS responses) is going to be much more beneficial than trying to skip the one extra hop between the non-leader and leader.

In practice any scheme derived from a DNS tag is not going to provide any stronger consistency guarantee than `?stale` already does and this way you get to serve requests from all of your servers which makes it much more scalable. Actually it can be more safe since we provide a `Last-Contact` header in response if you use HTTP API which you can use to bound how stale you are willing to accept. `?stale` requests get answered directly from memory by which ever server the agent is connected to so no extra hop to leader if it's not the leader.

Another performance difference with redis is that you probably used their pipelined API which means very high throughput on a single connection whereas if you were reading thousands of individual keys in Consul, each in a separate HTTP request it would have way more overhead. You can instead read prefixes provided they are selective enough not to pull way more data than you need, or you can use the transaction API to batch fetch many individual keys or prefixes in one round trip.

My recommendation would be to profile the workloads more thoroughly if there is some performance issue as there are many ways to increase performance but I'm not sure this request will help with that!

**Comment by banks** [comment]
I think on the basis of my responses above here I'm going to close this for now unless @maxadamo or anyone else has a really compelling need for this.

**Comment by maxadamo** [comment]
I got your point. 
P.s. I didn't know that Consul had UNIX sockets.
