### ISSUE TITLE
agent: Deregistered service  when consul client docker restarted

### ISSUE THREAD

**Issue by wukq** [hashicorp/consul#4955]
HI @slackpad 

The consul  client agents are run as a DaemonSet on kubernetes.
I  delete consul client and restart consul client，it will clear persistence data.
but all the services on the consul client be deregistered.
it very bother me.
```
    2018/11/14 10:30:17 [INFO] agent: Deregistered service "proplusfdafadfads"
    2018/11/14 10:30:17 [INFO] agent: Deregistered check "service:proplusfdafadfads"
    2018/11/14 10:30:17 [INFO] agent: Synced node info
```
Please give me a hand？

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
