### ISSUE TITLE
How to deregister service？

### ISSUE THREAD

**Issue by xiongmaodada** [hashicorp/consul#4992]
if a serviceid is `http://127.0.0.1:21000/api`,   I use  Service - Agent HTTP API  to deregister as follows:
```
curl -v -X PUT http://localhost:8500/v1/agent/service/deregister/http://127.0.0.1:21000/api
```
the result:
```
301 Moved Permanently
```
In addition，when I use Consul Catalog as follows:
```
curl -X PUT -d '{"Datacenter": "dc1", "Node": "foobar", "ServiceID": "http://127.0.0.1:21000/api" }' http://127.0.0.1:8500/v1/catalog/deregister
```
the node was removed but then reappears within 30-60s,  so how to deregister service that ServiceID is `http://127.0.0.1:21000/api` ?

Consul version：
```
# consul version
Consul v1.2.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Comment by pierresouchay** [comment]
Your ID is weird (avoid '/' if possible), deregistration in catalog is not needed as soon you are properly deregistering from local agent, the 30-60s is normal, this is due to anti-entropy mechanism.

You are not properly deregistering in local agent as you should escape the ID since it contains '/', so you have to urlescape (with %xx for / and : chars) for local agent deregistration to work. As soon as local deregistration is not working, it sends some http 301, when it will work, you will receive http 200.

Nice advice for later: use only ASCII [A-Za-z0-9-] for chars in IDs as well as in names (names are used when IDs are not provided) thus you won't have issues like this or problematic names for DNS (especially for node names and services)

**Comment by xiongmaodada** [comment]
thanks for your reply very much. 
 if ID does not include 'http://', it works by local agent.  
Another problem ： if I urlencode `http://127.0.0.1:21000/api` to `http%3a%2f%2f127.0.0.1%3a21000%2fapi` ,  I use agent api as follows:
```
curl -v -X PUT http://localhost:8500/v1/agent/service/deregister/http%3a%2f%2f127.0.0.1%3a21000%2fapi
```
the result:
```
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 301 Moved Permanently
< Location: /v1/agent/service/deregister/http:/127.0.0.1:21001/api
< Date: Tue, 27 Nov 2018 03:26:55 GMT
< Content-Length: 0
```
it does not work.

**Comment by xiongmaodada** [comment]
@pierresouchay  thanks for your reply sincerely,  In the process of testing, I found that I don't  deregister  service whose ID is at beginning of '/' (for instance  `/testid`)  when I used api as follows:
```
curl -v -X PUT http://localhost:8500/v1/agent/service/deregister/%2testid
```
```
curl -v -X PUT http://localhost:8500/v1/agent/service/deregister//testid
```
```
curl -v -X PUT http://localhost:8500/v1/agent/service/deregister/testid
```
This could be another scenario.

**Comment by pierresouchay** [comment]
@xiongmaodada I think this is the same cause, aka `//` is not routed to the proper function

**Comment by xiongmaodada** [comment]
ok, I understand.

**Comment by pearkes** [comment]
I believe @pierresouchay helped answer these questions so going to close this.
