### ISSUE TITLE
Docs vs Blogs

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5039]
Make sure blogs kept uptodate to prevent google from indexing deprecated configuration above current docs.

Example when reading  
https://www.hashicorp.com/blog/load-balancing-strategies-for-consul
I expected to find the keyword backend in
https://www.consul.io/docs/agent/services.html

Or it could be I totally missing the point :D

**Comment by pearkes** [comment]
Hey @gertcuykens great suggestion. I'm betting there are more examples of blog posts being out-of-date in terms of examples. We may want to go back and bring some of that content into our documentation where appropriate, or replace the content with a link to guides we've since introduced.

I hope we can also potentially add some process for new posts that make them maintainable down the line too.

**Comment by gertcuykens** [comment]
If the blog is from the hashicorp then google index it as first class, from a  seo standpoint it's worth the effort to go trough all hashicorp blogs and as a bonus if it includes links to the specific consul documentation that would be great.

**Comment by pearkes** [comment]
I'm actually going to close this here but we are aware internally at HashiCorp about the discrepancy -- just won't likely be something we fix in one go.
