### ISSUE TITLE
allow consul join to use cloud discovery

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/consul#5098]
#### Feature Description

a command line switch for `consul join` to use cloud auto-join

`consul join -auto "provider=aws tag_key=... tag_value=..."`

or an environment variable for the same

`CONSUL_JOIN="provider=aws tag_key=... tag_value=..."`

#### Use Case(s)

currently the `consul join` command is vastly superior to configuring `retry_join` when trying to automate the joining of an agent to a cluster using basic orchestration for the purpose of running a command after the agent has actually joined the cluster

if I spawn the agent in the background, I can [easily wait until it's running by monitoring the pid file](https://github.com/Snapkitchen/concourse-terraform/blob/master/bin/consul-wrapper#L77-L99), however I can't easily know if it has successfully finished the `retry_join` or not.

I could add a `sleep` before running the command, and hope that the client has joined the cluster, but it's non-deterministic which is frustrating for automation.

This means my only option is to not use `retry_join` at all, and instead use `consul join`.

`consul join` actually has a much better automation-oriented experience, as it errors if the join fails

this means wrapping it with simple shell retry logic is straightforward, and in some cases, you want to error immediately after the initial join failure anyway

so I'd like to be able to use this automation-friendly way of joining a cluster while also leveraging cloud auto join

thus I would expect that `consul join -auto "provider=aws tag_key=... tag_value=..."` would return non-zero if if failed to join, and I could retry with the shell or fail out

#### Alternate Solution

Another option would be to provide a command that surfaces the auto-discovery feature as a direct command, e.g.:

`consul discover "provider=aws tag_key=... tag_value=..."`

I could then capture that output and provide it to `consul join`

**Comment by pearkes** [comment]
This could be accomplished by passing the result of `go-discover` to the `consul join` command, though we do continue to recommend the configuration stanza for `retry_join`. Typically though, it is not uncommon for retry_join to _eventually_ succeed in your cluster bootstrap example, so I'd say you're better off watching for health of the cluster instead of sleeping, then executing the appropriate command.

Regardless, `go-discover` can be [used as a CLI tool](https://github.com/hashicorp/go-discover#command-line-tool-usage) accomplishing what you suggest with `consul discover`. That seems like a fine solution to provide IPs with the same underlying mechanism that Consul uses if you don't want to use `retry_join`. 

I'm going to proactively close this in favor of that as I think it solves your use-case.

**Comment by pearkes** [comment]
Great! #3953 will probably help a bit with making that cleaner.
