### ISSUE TITLE
How to configure consul watch to invoke script only when service goes down?

### ISSUE THREAD

**Issue by codingkapoor** [hashicorp/consul#5104]
**Consul Watch Doc**
> As an example, you could watch the status of health checks and notify an external system when a check is critical.

How can this be achieved? Consul watch seems to execute the script/endpoint everytime there is the change in the status of a service. How can we narrow it down to invoke the script/endpoint when the service goes down or something? Please suggest

**Consul watch type:** Service
**Consul version:** v1.4.0

My configurations:
**Service Config**
```
{
    "service": {
        "name": "web",
        "port": 8080,
	    "tags": ["mps1", "mps2"], 
        "check": {
            "http": "http://localhost:8080",
            "interval": "10s"
        }
    }
}
```

**Common Config**
```
{
    "retry_join": ["172.20.20.31"],
    "data_dir": "/tmp/consul",
    "client_addr": "0.0.0.0",
    "disable_remote_exec": false,
    "watches": [{
        "type": "service",
        "service": "web",
        "handler": "/home/vagrant/notifier.sh"
    }]
}
```

**Comment by codingkapoor** [comment]
Anyone?

**Comment by pearkes** [comment]
The watch handler contains data that will include the status of the service you are watching. See here for more: https://www.consul.io/docs/agent/watches.html#handlers

Basically, your notifier script should do a check on the status of the service as provided by the JSON formatted data described there.

For a more generic solution or examples, you can look at community projects such as:

https://github.com/AcalephStorage/consul-alerts

Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here in the future.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
