### ISSUE TITLE
Assume anonymous if token doesn't match any available.

### ISSUE THREAD

**Issue by FearTheBadger** [hashicorp/consul#5105]
#### Feature Description

Please allow for the assumption of an anonymous user if you have an ACL token stored but it doesn't match anything in the current DC.

#### Use Case(s)

I have two data centers, which I have joined together. Each DC has it's own set of ACL's to protect data from the adjoining DC. If I store a client or master ACL token of DC1, I can no longer see any data on DC2. All I get is the loading pinwheel with no return. I have to remove the key completely to even get a response from DC2. If my current token doesn't match anything in the selected DC, it should just default the user to Anonymous for any ACL interactions.

**Comment by banks** [comment]
@FearTheBadger thanks for the info. Can you share which version of Consul you are using? If it's 1.4.0, are you using the new ACL system or the legacy one?

**Comment by FearTheBadger** [comment]
It is in the legacy version. With you saying that I just realized it could be a non-issue now.

I'll go rebuild and close if it is working as desired.

**Comment by banks** [comment]
I don't think we changed that behaviour in 1.4.0 ACLs just wanted to be
clear on what is being talked about!

Overall it sounds like a reasonable ask, we'll think about the
repercussions it could have. It would at least need to be opt-in since it's
a breaking change and would potentially allow more access in a way that was
not intended by anyone who relied on the current behaviour.

**Comment by FearTheBadger** [comment]
With 1.4.0 this is no longer an issue.

For those reading at home:
When you switch from DC to DC it logs you out of your ACL session.
