### ISSUE TITLE
Set format of the value in K/V by the consul cli or api

### ISSUE THREAD

**Issue by smutel** [hashicorp/consul#5121]
#### Feature Description

In the current version of consul (1.4.0), values in the K/V store have some parameters:
- code: true or false
- language: json/hcl/yaml

Currently this parameters can be changed only in the web user interface.
I suggest to add the capability to set these parameters when adding a new value by the command line or the API.

#### Use Case(s)

With this feature we will be able to set these parameters when the K/V are added by the command line.
Going to the web UI after to do the change will no longer be needed.

**Comment by johncowen** [comment]
Hi @smutel ,

Thanks for bringing this up!

Before I apply a GH label to this, I just wanted to double check your usecase here.

Is this purely so that you don't have to select code/language **in the Consul UI** or do you have some other usecase for wanting to set/know what is 'kind of like' the mimetype of the KV value?

Thanks,

John

**Comment by smutel** [comment]
The usecase for the moment is just to avoid going to the web ui to select code/language.

**Comment by johncowen** [comment]
Great stuff thankyou!

We have talked about the possibility of saving this selection at a 'UI level' per KV, instead of having this work as a 'global' UI setting, would that help? You would still have to at least set it once per KV in the UI, but at least it would remember per individual KV what your code/language was between browser restarts (if you changed the code/language of the value of an individual KV outside of the UI, it would then also be wrong)

There is another option that I'm aware of, I just want to triple check some assumptions with the rest of the team, I'll try and come back to you here and explain further if that option is viable.

Thanks!

John

**Comment by smutel** [comment]
Perhaps an example is a better way to explain my feature request ...
`consul kv put dcos-bootstrap true -code=true -format=json`

New options:
```
-code=<true|false>
-format=<json|hcl|yaml>
```

Thanks.

**Comment by johncowen** [comment]
Hi @smutel 

We've had a quite a bit of discussion here about this. I think the main point here is that it seems like this is a feature purely related to our UI, so unless there is another usecase, right now the feeling was that we shouldn't add anything specifically to `consul` for this.

We did talk about various approaches to making an iterative improvement to this using only our Consul UI itself. So potentially we could be adding something near term to try to improve this slightly.

I'll try to keep you updated here when if/we do.

Thanks,

John

**Comment by peimanja** [comment]
Any updates on this issue? We are also interested in this feature.
Our use case is programmatically right to Consul KV (e.i write some of our global configs to Consul like list of AWS accounts and then reference it in our other Terraform workspaces, format need to be hcl in our case but we have to enable this for every key we write consul manually which is far from ideal)

**Comment by rboyer** [comment]
The KV store is very versatile and there are numerous ways to use it to solve this problem without the need for a new feature. One suggestion would be to encode the filetype as a suffix to the key name like `server/myconfig.json` or to write your file contents in the primary key `server/myconfig` and put the file type in a child key like `server/myconfig/.mimetype`. 

As @johncowen indicated above to implement this directly as a native feature would likely require adding the ability to annotate KV entries with some sort of additional metadata beyond just the `Value`, and then having the UI/CLI make use of that general metadata layer to store a very specific label like `{"content-type":"hcl"}`.

The added complexity of implementing this as a native feature would likely outweigh the minimal benefits it would bring, and seeing as how there are various ways that the existing KV system can be used to work around its absence  I'm going to close this for now as we have no plans to implement this feature at this time.
