### ISSUE TITLE
consul connect: Filter proxy destination by tags and/or meta

### ISSUE THREAD

**Issue by billietl** [hashicorp/consul#5208]
#### Feature Description

Currently, proxies upstreams are setup using service names or service ids.

It would be usefull to be able to filter upstream services by tags and/or meta informations.

#### Use Case(s)

In a project involving many entrypoint and many micro-services, some micro-services might run in different versions at the same time, or multiple tiers running in the same consul cluster (let's say integration, staging and performance testing). It would be handy to tell consul something like "connect me to a service foo registered with meta 'version=12.3.4' " or "connect me to a service baz registered with tag 'staging' ".

**Comment by banks** [comment]
Thanks @billietl 

Yeah that's something that's somewhat planned but we don't have it tracked as an issue so this would be great!

Prepared queries can sort of work around this for built-in proxy currently but these are not supported for Envoy yet (but 🔜 #4969).

**Comment by billietl** [comment]
I haven't looked much about prepared queries, but the fact that you could setup your services (and attached proxies) via configuration files, but not the prepared queries (on which it would depends) is kind of odd for me.
Maybe something in-between (like some kind of statically prepared query defined inside the proxy definition) would be more useful than my first idea ?

**Comment by banks** [comment]
Right, prepared queries are a slightly different flow as they are global state in Raft and have to be managed via API/UI/CLI/Terraform etc.

Your original idea is planned in some form so I think we are good there! prepared queries are just a possible workaround until that's added.

We are considering adopting something more generic - closer to kubernetes' selectors rather than add more "tag/meta" fields to things but that's far from decided yet.

We are also considering first-class support for "versions" of services which is what you are aiming to achieve here. This would also be part of allowing centralised config (so you don't have to configure hundreds of proxy parameters in every service definition along with you application-level registration stuff for example).

So this is all good, but those discussions are still in the works which is why we may or may not just do the simple thing right away of adding a tag/meta filter.

We want to solve the use case one way or other soon though!

**Comment by billietl** [comment]
Nice, then we'll patiently wait for you to sort all of this out :)

**Comment by matthoey-okta** [comment]
@banks If "version" did have first class support would it have the same concept as kubernetes' labels? To allow for routing of labels like "canary", "stable", "release", etc?

Would also like to implement prepared queries for upstreams but am using envoy so +1 for https://github.com/hashicorp/consul/issues/4969

**Comment by banks** [comment]
@matthoey-okta yes something like that - it would go beyond "v1", "v2" etc. at least. As I mentioned something like Kube Label selectors might be a good option, but not designed the detail yet!

#4969 should be fixed very soon by #5224 😉

**Comment by mikemorris** [comment]
👋 We've added [`service-resolver`](https://www.consul.io/docs/connect/l7-traffic-management.html#resolution) configuration for Connect proxy upstreams in [Consul 1.6.0](https://www.hashicorp.com/blog/hashicorp-consul-1-6-general-availability), could this be a solution to the functionality you're looking for @billietl @matthoey-okta?

**Comment by billietl** [comment]
Looks neat, but I might to play a bit with it because I can't fully figure out how it blends with the rest of consul. Maybe there will be some screencast of how to use it ?

**Comment by mikemorris** [comment]
@billietl https://www.hashicorp.com/blog/canary-deployments-with-consul-service-mesh is the only walkthrough we have currently, but we'll be working on building out more guides and learning content after HashiConf US.

We'd definitely appreciate your feedback if ^ is a helpful introduction and if there are specific questions that would be useful for us to address as we build out for content around service mesh and L7 routing.

**Comment by banks** [comment]
Stale bot's date maths seems off here. We'll check that out.

**Comment by jsosulska** [comment]
Closing as marked this as done.
