### ISSUE TITLE
How to set only one attribute when using Consul Go client

### ISSUE THREAD

**Issue by remilapeyre** [hashicorp/consul#5234]
Hi, I would like to be able to set only one attribute when calling https://www.consul.io/api/operator/autopilot.html#update-configuration.

Since all parameters are optional, I would like to be able to set only `CleanupDeadServers` (https://www.consul.io/api/operator/autopilot.html#cleanupdeadservers) and leave other parameters to their defaults.

I'm using https://godoc.org/github.com/hashicorp/consul/api#Operator.AutopilotSetConfiguration to call Consul HTTP API but I can't find a way not to specify some parameters in AutopilotConfiguration, they all default to their default Go value which is not the same than the ones from Consul HTTP API.

Is this by design ?

**Comment by mkeeler** [comment]
@remilapeyre If you do not know all the values you want in the autopilot configuration then you will have to first retrieve the current configuration with [`AutopilotGetConfiguration`](https://godoc.org/github.com/hashicorp/consul/api#Operator.AutopilotGetConfiguration), modify the `CleanupDeadServers` value and then set with [`AutopilotCASConfiguration`](https://godoc.org/github.com/hashicorp/consul/api#Operator.AutopilotCASConfiguration). This is how the `consul operator autopilot set-config` command works. Using `AutopilotCASConfiguration` ensures that if other updates happen between the get and set operations, then the new updates will error out instead of reapplying old data. This is by design.
