### ISSUE TITLE
service/checks should support integers within json

### ISSUE THREAD

**Issue by jesusch** [hashicorp/consul#5285]
#### Overview of the Issue

While configuring services and/or checks using json integers the parsing fails.

#### Reproduction Steps

create a service like this: 

```
{
  "service": {
    "checks": [
      {
        "args": [
          "/opt/sensu/embedded/bin/check-redis-ping.rb",
          "-p",
          6379
        ],
        "interval": "5s",
        "timeout": "3s"
      }
    ],
    "enable_tag_override": false,
    "id": "redis",
    "name": "redis",
    "port": 6379,
    "tags": [
      "sensu"
    ]
  }
}
```

startup/reload throws this error:
```
Jan 29 08:40:16 sensu-europe-west1-jf5b consul[26786]: * 'service.checks[0].args[2]' expected type 'string', got unconvertible type 'float64'
Jan 29 08:40:16 sensu-europe-west1-jf5b consul[26786]:     2019/01/29 08:40:16 [ERR] agent: Reload config failed:  1 error(s) occurred:
Jan 29 08:40:16 sensu-europe-west1-jf5b consul[26786]: * Failed to reload configs
Jan 29 08:40:16 sensu-europe-west1-jf5b consul[26786]:     2019/01/29 08:40:16 [ERR] http: Request PUT /v1/agent/reload, error: 1 error(s) occurred:
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 0bddfa23
	version = 1.4.0
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 54
	max_procs = 2
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 9
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1403
	members = 88
	query_queue = 0
	query_time = 1
```

</details>

**Comment by pierresouchay** [comment]
Those args are sent to fork/exec which has no clue about int parameters, having a converversion would likely cause issues, such as ietf conversions for float... Not sure it really make sense

**Comment by jesusch** [comment]
having int in terms of json may make sense or not, but the unconvertible type error comes from Go - not any shell call. not sure why the former "script" parameter has been removed anyhow, but some tools (puppet) generate consul checks with json+integer :(

**Comment by pierresouchay** [comment]
@jesusch when do you stop then? Do consul has to convert false to "false“? How is supposed 1.00 to be read by Consul and sent to fork? (I mean read 1.00 is not trivial as you have to get full control over serialization library to avoid reading 1.0 )

Fork/exec take strings, maybe doc should state that args is strings only, but adding implicit conversions might render the API unpredictable.

For the records, I had the exact same issue with chef (and ruby). The fix was to always call `.to_s` to each member of the array. Your favorite lib should probably do the same for `args` array. The fact that your language does not enforce type for arrays does not mean the API should follow the same principles IMHO, especially since fork /exec has only string semantics.

**Comment by i0rek** [comment]
What @pierresouchay said. Closing here since no comment from issue creator for some time. I would be happy to reopen though in case I missed something.
