### ISSUE TITLE
Trim '/' while KV put.

### ISSUE THREAD

**Issue by rjsaran** [hashicorp/consul#5318]
We can trim '/' also during KV put as we are doing it in KV get and delete.

Any specific reason for not trimming while KV put?

**Comment by i0rek** [comment]
Could you explain more detailed what you mean?
Consul kv is flat and doesn't make assumptions about your key, that is the reason we don't strip keys.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
