### ISSUE TITLE
Consul watch not getting triggered

### ISSUE THREAD

**Issue by harika224121** [hashicorp/consul#5320]
Hi,

I am trying to execute a script in dc2 using consul watch by monitoring the changes in the service of dc1. but the script is not getting triggered. 

Is this the correct format? can I use "datacenter" option of consul watch as below or do I need to make any changes here please let me know:
{
	"watches": [
	 {
		"type": "service",
                "datacenter": "DC1",
		"service": "service-name",
		"handler": "/file.sh"
	 }
	]
}

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
