### ISSUE TITLE
Envoy 1.10 support

### ISSUE THREAD

**Issue by matthoey-okta** [hashicorp/consul#5323]
#### Feature Description

What would it take to validate envoy 1.9.0 with consul? We are currently using it in labs due to needing some retry logic only available in 1.9.0, but would want it officially supported if we go beyond labs.

#### Use Case(s)

Anyone who wants to use more advanced listener configs and features in those configs that are in later versions than 1.8.0

**Comment by banks** [comment]
Hey @matthoey-okta, at the moment not a lot since we only setup L4 proxying and the API surface there hasn't changed a lot in my experience. We don't yet have a good integration test though so it would be somewhat manual but the surface areas is not huge so far.

If you have tried it and can list the specific configs tested that would be a great start. We're getting into building out L7 features which will require a much more sophisticated (i.e. existent!) integration testing solution but that might be some way out.

**Comment by matthoey-okta** [comment]
@banks Thanks for getting back to me. I agree as long as official support doesn't change beyond what is currently supported it hopefully won't be too painful for you all to test.

We're mainly focused on adding the http connection manager to our upstreams in connect. We wanted to get HTTP response code-based metrics and we also are using route.RouteAction.RetryPolicy. Specifically we use the `retriable-status-codes`, `connect-failure`, and `refused-stream` policies. The first one is the new one that got introduced in 1.9.0 so we can retry on 502's. So far have not run into any errors.

Can't wait for the L7 features to come out, but the escape hatch is working fine for us for now so really appreciate you implementing that feature. :)

**Comment by banks** [comment]
Just starting testing with 1.10 and hit a couple of issues so far:
 - https://github.com/hashicorp/consul/issues/5363 is known and reasonably easy to fix as it wasn't really needed for older versions anyway.
 - It seems that 1.10 changed the gRPC service name for the AuthZ filter which means AuthZ fails with 1.10. I'll investigate that.

**Comment by banks** [comment]
As an update here: https://github.com/hashicorp/consul/pull/5558 adds an integration testing suite which qualifies 1.9.1 as working with Consul Connect and will be released with Consul 1.5.0. note that based on these tests, 1.9.1 should work fine with older versions of Consul too and will be recommended for all users due to the two CVEs it patches.

Envoy 1.10.0 is now stable but has a couple of breaking changes that will need a larger refactor to support which we will defer until after the current push to release Consul 1.5.0.

The good news is that we now have an integration test suite that gives use confidence to qualify new versions.

**Comment by matthoey-okta** [comment]
That is great news! Thanks for all the hard work @banks
