### ISSUE TITLE
Lost the anonymous acl token

### ISSUE THREAD

**Issue by rudziankou** [hashicorp/consul#5331]
Hi folks,
I bootstrapped acl on my Consul cluster and then I lost the anonymous token. How Can I reset an acl and bootstrap acl again? I found something about reset procedure, but I cannot find any other documents related to this topic.

![screen shot 2019-02-11 at 3 31 18 pm](https://user-images.githubusercontent.com/1725954/52601144-a7bd4980-2e12-11e9-84c6-8bf5f74d8891.png)

**Comment by Aestek** [comment]
Anonymous token is not a "real" token, it is an hardcoded string used internally for requests made *without* token.

**Comment by mkeeler** [comment]
@Aestek with v1.4.0 the anonymous token is a real token (It has a reserved AccessorID of `00000000-0000-0000-0000-000000000002`). Its SecretID is "anonymous". However in every other respect it is a normal token. You can assign it policies, rename it etc. You cannot delete it or change the accessor/secret but otherwise every other normal operation will work.

@rudziankou I believe you mean that you lost your initial token from when you bootstrapped ACLs. The reset procedure is to:

1. Run `consul acl bootstrap`. If you have already bootstrapped you should see it output an error like: `Failed ACL bootstrapping: Unexpected response code: 403 (Permission denied: ACL bootstrap no longer allowed (reset index: 13))`

2. Write the reset index number from the output in step 1 into a file called `acl-bootstrap-reset` within the data directory of the leader.

3. Run `consul acl bootstrap`. This time it will succeed and will have deleted the acl-bootstrap-reset file you created.

The new token created by the bootstrap reset procedure has full privileges and can be used for further ACL management including finding your first token.

**Comment by rudziankou** [comment]
Thanks, @mkeeler.

**Comment by next-joaquinfernandezcampo** [comment]
Could we keep this issue open until the docs are updated? @mkeeler

**Comment by lkysow** [comment]
The docs now link to https://learn.hashicorp.com/consul/advanced/day-1-operations/acl-guide#ensure-the-acl-system-is-configured-properly but that guide doesn't explain how to reset the ACL system.

**Comment by lkysow** [comment]
Fixed by https://github.com/hashicorp/consul/pull/6633 (the new link is https://learn.hashicorp.com/consul/day-0/acl-guide#ensure-the-acl-system-is-configured-properly)
