### ISSUE TITLE
memory leak on 1.4.0

### ISSUE THREAD

**Issue by danielingd** [hashicorp/consul#5333]
#### Overview of the Issue
We have problem with memory after upgrade our servers from version 0.9.3 to 1.4.0. It looks like memory leak in our environment which we observing increasing values of metric “runtime.alloc_bytes”; When the memory mean value start to be ~919611008 we start have problems with another metrics “raft.leader.lastContact” which mean starts be above 280ms. In our production environment consul have only 25-30 hours of working, after this time we need restart our leader.

In our test environemnt we do not see this problem in first time - beceause memory leak show up on dashboards after 2 weeks of working leader. In test environment we have 234 client nodes.

#### Reproduction Steps

We have 3 servers in version 1.4.0 which was migrate from 0.9.3 (node-by-node). 
Client nodes 411 -> ```consul members | wc – l``` all of them have 0.9.3 version.

key="*runtime.alloc_bytes" - 7 days
![image](https://user-images.githubusercontent.com/47526467/52631656-a6962600-2ebf-11e9-9d19-d47b6b656d5a.png)

Dashboard for key="timing.consul.raft.leader.lastContact - 7 days
![image](https://user-images.githubusercontent.com/47526467/52631728-d9d8b500-2ebf-11e9-8f5b-57bf3c97c518.png)

We enable debug mode, and generate off-line svg by pprof:
[goroutine.pdf](https://github.com/hashicorp/consul/files/2855515/goroutine.pdf)
[heap.pdf](https://github.com/hashicorp/consul/files/2855516/heap.pdf)
[profile.pdf](https://github.com/hashicorp/consul/files/2855517/profile.pdf)

### Consul info for both Client and Server
<details>
  <summary>Client info</summary>
```
    agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 2
    build:
        prerelease =
        revision = 112c060
        version = 0.9.3
    consul:
        known_servers = 3
        server = false
    runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 39
        max_procs = 16
        os = linux
        version = go1.9
    serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 161
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 24152
        members = 410
        query_queue = 0
        query_time = 8 
```
</details>
<details>
  <summary>Server info</summary>
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = enabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.X.Y.A2:48303
        server = true
raft:
        applied_index = 193754537
        commit_index = 193754537
        fsm_pending = 0
        last_contact = 44.501µs
        last_log_index = 193754537
        last_log_term = 263
        last_snapshot_index = 193753450
        last_snapshot_term = 263
        latest_configuration = [{Suffrage:Voter ID:1c6d3eb2-3e19-13a0-df30-e8be1df6c08b Address:10.X.Y.A1:48303} {Suffrage:Voter ID:59bc4fcc-d00f-2c0b-0744-edb83b7ca1ac Address:10.X.Y.A2:48303} {Suffrage:Voter ID:14162376-6b2d-1d8e-7c73-57ea34f61063 Address:10.X.Y.A3:48303}]
        latest_configuration_index = 179829531
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 263
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 22652
        max_procs = 4
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 161
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 24152
        members = 410
        query_queue = 0
        query_time = 8
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 14
        members = 3
        query_queue = 0
        query_time = 8
```
</details>

### Operating system and Environment details
OS on servers is Linux Red Hat Enterprise Linux Server release 7.6.
OS on clients nodes is linux RHEL or winsows.

CPU
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               2095.143
BogoMIPS:              4190.28
Hypervisor vendor:     Microsoft
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm 3dnowprefetch ibrs ibpb spec_ctrl
```

MEM
```
cat /proc/meminfo
MemTotal:        3868784 kB
MemFree:          156476 kB
MemAvailable:     511120 kB
Buffers:              24 kB
Cached:           641292 kB
SwapCached:        92068 kB
Active:          2520120 kB
Inactive:         747816 kB
Active(anon):    2218156 kB
Inactive(anon):   585092 kB
Active(file):     301964 kB
Inactive(file):   162724 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4194300 kB
SwapFree:        3344892 kB
Dirty:               124 kB
Writeback:             0 kB
AnonPages:       2575880 kB
Mapped:           136704 kB
Shmem:            176628 kB
Slab:             255604 kB
SReclaimable:     175504 kB
SUnreclaim:        80100 kB
KernelStack:       18224 kB
PageTables:        22372 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6128692 kB
Committed_AS:    4852688 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      108908 kB
VmallocChunk:   34359549952 kB
HardwareCorrupted:     0 kB
AnonHugePages:    567296 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       81320 kB
DirectMap2M:     4110336 kB

```

### Log Fragments

Mostly:

2019/02/08 13:02:14 [DEBUG] http: Request GET /v1/catalog/service/serviceA (377.507µs) from=127.0.0.1:60958
2019/02/08 13:02:15 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844663 (978.893341ms) from=127.0.0.1:32828
2019/02/08 13:02:15 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844664 (15.521564ms) from=127.0.0.1:32828
2019/02/08 13:02:15 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844665 (13.952138ms) from=127.0.0.1:32828
2019/02/08 13:02:15 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844667 (15.954971ms) from=127.0.0.1:32828
2019/02/08 13:02:15 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844669 (14.065239ms) from=127.0.0.1:32828
2019/02/08 13:02:15 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844672 (15.621366ms) from=127.0.0.1:32828
2019/02/08 13:02:16 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844673 (709.659964ms) from=127.0.0.1:32828
2019/02/08 13:02:16 [DEBUG] http: Request GET /v1/kv/?recurse=true&index=190844674 (16.44828ms) from=127.0.0.1:32828
...

2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceA (181.303µs) from=127.0.0.1:32880
2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceB (355.906µs) from=127.0.0.1:32880
2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceC (326.806µs) from=127.0.0.1:32880
2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceD (322.905µs) from=127.0.0.1:32880
2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceE (334.806µs) from=127.0.0.1:32880
2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceF (291.405µs) from=127.0.0.1:32880
2019/02/08 13:02:20 [DEBUG] http: Request GET /v1/catalog/service/serviceG (305.005µs) from=127.0.0.1:32880

**Comment by banks** [comment]
Hi, thanks for all the details. We've started digging into the profiles and not drawn strong conclusions yet about if this is a true leak or some effect of changing client behaviour caused by some other factor that changed between the versions (we've seen a few of those with people upgrading from much older versions).

We see a _lot_ of the memory is being used by blocking queries - around 15,000 which seems very high for the number of clients you report. Can you give us some idea what sort of workload the clients runs? Do they all watch every service in the catalog? how many services/service instances total? What software is making the health queries - consul-template or something else? How large is the KV that we see bing recursed (number of keys)?

Do you have metrics on the number of RPC/s especially blocking queries?

In the CPU profile there are 18336 in-flight RPC calls to the servers which is a lot! The root cause then is to figure out why your clients are making so many requests and why that request load appears to keep growing over time. The scale of growth smells more like badlying handling some error case and issuing lots of retries rather than intended growth in the workload (like new services being added) but any context you can share there can help us figure that out.

Thanks for the great debug info here - much appreciated. For future reference, consul 1.4.0 added a `consul debug` command that can automate pulling the profiling and other metrics in a handy archive format. Please note the security notices in the docs for that command, although on a test cluster this should be less of a concern.

**Comment by danielingd** [comment]
Thank You for Your answer.

> Can you give us some idea what sort of workload the clients runs?

Could you specified what data need to known?

> Do they all watch every service in the catalog? 

Generally no, we approximate that every single instance have 10 watches.

> how many services/service instances total? 

We have services = 135

![image](https://user-images.githubusercontent.com/47526467/52714110-5f7c6380-2f99-11e9-81b0-27e9eac61dcf.png)
![image](https://user-images.githubusercontent.com/47526467/52714134-6a36f880-2f99-11e9-9881-fe68a9437075.png)


> What software is making the health queries - consul-template or something else? 

com.orbitz.consul:consul-client:0.9.1

> How large is the KV that we see bing recursed (number of keys)?

On production KV = 1734 keys mostly 1kB-2kB
On TEST environment KV = 3465

> Do you have metrics on the number of RPC/s especially blocking queries?

Do you have any idea how to collect this data?

```  "ports": {
    "serf_lan": 48301,
    "serf_wan": 48302,
    "http": 48500,
    "dns": 48600,
    "server": 48303
  },
```
  
On server:

```
>netstat -antu | grep :48500 | wc -l 
>940
```

**Comment by banks** [comment]
Thanks!

> Could you specified what data need to known?

That's what the following question were so should be all good!

> > What software is making the health queries - consul-template or something else?
> com.orbitz.consul:consul-client:0.9.1

**Comment by danielingd** [comment]
> What software is making the health queries

In our aplications we use library https://mvnrepository.com/artifact/com.orbitz.consul/consul-client; We only use java implementation.

> I meant the software that's actually generating the watch queries _to_ the clients?

Form application code we register health check per service which is used, not for all services registered in our cluster.

> Or are you using `consul watch` command or just agent-configured watches to invoke an external script?

No, we do not use `consul watch`, the only thing we use is blocking web API; All watches are based on HTTP health requests;

![image](https://user-images.githubusercontent.com/47526467/52996235-3e929300-341d-11e9-88ad-14c67777e913.png)

> I was asking if you have data for the `consul.rpc.query` and `consul.rpc.request`.

Below our charts for last 30 days with 1h span per host;

![image](https://user-images.githubusercontent.com/47526467/52996360-ad6fec00-341d-11e9-822c-55153dcf9793.png)

![image](https://user-images.githubusercontent.com/47526467/52996559-443ca880-341e-11e9-8401-a6495386d84d.png)

> `consul debug` command

Thank you for that oportunity.
We created it last time - I have some problems with such big emails 30MB/per snap. I will send without trace.out - for that I need some form of uppload service.

**Comment by banks** [comment]
Hmm so it looks like Since the upgrade your clients are indeed making increasing numbers of blocking queries.

So this isn't a "memory leak" in the sense that a resource is being leaked and not release - it's more that something is causing your clients to increase their load until the server fails/restarts it seems.

It *might* be that the blocking queries are failing for some reason and returning to the client early but not freeing the server goroutine (this might happen if your clients are crashing very often and dropping their side of the connection then restarting and making new queries while server is still serving the old ones). But I don't know why the rate would increase over time - I'd expect it to rise for 10 minutes until the first queries timeout naturally and get freed and then stay constant at a rate determined by how fast your application is dropping and re-establishing their queries.

That is all speculation though, can you confirm that the your application or infra didn't have any other change at same time as the 1.4.0 upgrade that might affect this?

> In our aplications we use library https://mvnrepository.com/artifact/com.orbitz.consul/consul-client; > We only use java implementation.

Sorry you did say that before I just missed the Maven reference!

I'll try to look at the debug output when I can but in the interim, are you able to see from logs or `consul monitor` with DEBUG level what the queries actually look like? Are the parameters for the index and wait being set sensibly by the client? Look out particularly for 0 value indexes which will never block.

Can you see from your application logs anything suspicious like lots of errors when making Consul queries?

## I think I might know what this is:

One thing that changed here was that in a few places service health watching got optimized more so that indexes returned are per-service now and maintained for non-existent services instead of always being zero. 

One issue with that was that in some cases clients might have seen the index for a service's health go backwards. Well-designed clients like all of the internal ones should handle that case by resetting their internal index but that Java client may not which _could_ be part of the problem.

See the release notes here: https://www.consul.io/docs/upgrade-specific.html#consul-1-0-7

The fix if this is the case is simply to restart all of the client applications that are requesting this data (assuming they haven't persisted the index of query but that lib doesn't seem to). I realise that's not a trivial thing in production, but if it's easy for you to try that to verify in your testing environment I suspect it is the root of the issue.

**Comment by danielingd** [comment]
> That is all speculation though, can you confirm that the your application or infra didn't have any other change at same time as the 1.4.0 upgrade that might affect this?

Yes, our infra didn’t have any major changes in this particular day, we see the same problems on every environment, but of course the problem is only on production because of scale. Our two test environments have only ACC – half nodes from production 248; HotFix – 185; For example on ACC we need almost 2 weeks to have “consul.raft.leader.lastContact.mean” over 200ms. Yes the problem exists, however, it is not so painful.

> 'll try to look at the debug output when I can but in the interim, are you able to see from logs or `consul monitor` with DEBUG level what the queries actually look like? Are the parameters for the index and wait being set sensibly by the client? Look out particularly for 0 value indexes which will never block.
Thank you, I’ll send You debug logs when leader have problems. In logs I have found:

```
2019/03/02 06:45:02 [ERR] yamux: keepalive failed: i/o deadline reached
2019/03/02 06:45:02 [ERR] consul.rpc: multiplex conn accept failed: keepalive timeout from=10.X.Y.1
2019/03/02 06:45:22 [ERR] memberlist: Failed fallback ping: write tcp 10.X.Z.F:52510->10.X.Y.13
```
> Can you see from your application logs anything suspicious like lots of errors when making Consul queries?

Unfortunately not

> The fix if this is the case is simply to restart all of the client applications that are requesting this data (assuming they haven't persisted the index of query but that lib doesn't seem to). I realise that's not a trivial thing in production,…

It was not a simple task, and it took a lot of time to prepare such action. For obvious reasons, we cannot restart all application in the same time, but in one week time window with 99% confidence restarted all applications which use consul. Unfortunately, this did not solve our problem even for a moment.

So, next step we create ‘wrong customer’ of consul and run in test environment, unfortunately, we did not recreate the scale of the problem from production environment.

**Comment by danielingd** [comment]
Dear Support,

We could not wait any longer, we decided to withdraw/test the version to 1.3.1. Our test environment show Us that is good direction. At the moment we have version 1.3.1 in which the above problems do not occur.

runtime.alloc_bytes

![runtime alloc_bytes](https://user-images.githubusercontent.com/47526467/56184929-32d9dc00-601c-11e9-8878-06c0c4f40757.png)

leader.lastContact

![leader lastContact](https://user-images.githubusercontent.com/47526467/56184956-48e79c80-601c-11e9-9d44-6e18dfe27b89.png)

rpc.query

![rpc query](https://user-images.githubusercontent.com/47526467/56184963-500eaa80-601c-11e9-9f50-5641820f2cb9.png)


**The problem is with the 1.4.x versions!!!**

Best Regards,
Daniel

**Comment by banks** [comment]
@danielingd interesting thanks. That does rule out my hypothesis.

Would you be able to show use the heap profile and request rate metrics just like you did before but on 1.3.1 so we can compare the difference?

It still seems like it's not really (or only) a memory leak but rather a regression or change that causes your clients to behave differently and make increasing numbers of requests now. But narrowing it down to 1.3.1 -> 1.4.0 helps.

**Comment by danielingd** [comment]
@banks I will try heap profile send You tomorrow, for now:
rpc.request for last 30days

![rpc request](https://user-images.githubusercontent.com/47526467/56206556-f96d9480-604c-11e9-8e29-1e8fd4971e7d.png)

**Comment by danielingd** [comment]
> **1.4.0 (November 14, 2018)**
> New command consul debug which gathers information about the cluster to help resolve incidents and debug issues faster. [GH-4754]

@banks Which is the best way to do heap profile for 1.3.1 version without development tools?

**Comment by banks** [comment]
Hey in older version, provided debug is enabled in config you can make the
profile with Go tooling. You will need the Go compiler/toolchain installed
on a machine with access to the Consul instance (can be a remote host but
if so you'll need to copy the binary running on the server to it) then you
can use `go tool pprof` as described here:
https://github.com/hashicorp/consul/issues/3941#issuecomment-371853850 (you
can see why we made this easier in 1.4.0!).

**Comment by danielingd** [comment]
Hey, 
Sorry for the delay, it took a lot of time in my work reality, but the profiles were sent to the email. 
Heap from the leader on production in version 1.3.1:

![heap_08_leader](https://user-images.githubusercontent.com/47526467/58073130-1ba18780-7ba2-11e9-9959-71401262b849.png)

**Comment by danielingd** [comment]
@banks You have some information about our case. Currently we have blocked the possibility of updating - for fear of repetition of problems.
