### ISSUE TITLE
How to create a cross dc lock

### ISSUE THREAD

**Issue by denglifeng3** [hashicorp/consul#5373]
Hi, I met the a issue, the consul had started. I can read some kvs from consul already. I tried to create session minutes later, and the same error occur.

`2019-02-22 09:21:24.250 [] PST [info] c.c.o.d.s.r.l.ConsulLock - the session created:af3d4161-7490-b967-3021-253ef1cac915

2019-02-22 09:21:24,271 DEBG 'service-iam-data-external' stdout output:
2019-02-22 09:21:24.269 [] PST [info] c.c.o.d.s.r.l.ConsulLock - try to add request lock in dc:rcdn-dev success:af3d4161-7490-b967-3021-253ef1cac915.

2019-02-22 09:21:24,409 DEBG 'start_consul' stdout output:
2019/02/22 09:21:24 [ERR] consul: RPC failed to server 10.0.38.115:8300: rpc error: rpc error: rpc error: Missing node registration
2019/02/22 09:21:24 [ERR] http: Request PUT /v1/session/create?dc=alln-dev, error: rpc error: rpc error: rpc error: Missing node registration from=127.0.0.1:54982

2019-02-22 09:21:24,411 DEBG 'service-iam-data-external' stdout output:
2019-02-22 09:21:24.409 [] PST [error] c.c.o.d.s.c.ScimResourceController - Resource Creation Exception
com.orbitz.consul.ConsulException: Consul request failed with status [500]: rpc error: rpc error: rpc error: Missing node registration`

I want to add a lock in two dcs, I create session in its own dc succssfully, but the other failed.
`for (String dc : dcList) { String sessionIdTemp = createSession(dc);`
Is it not correct ?
If I want to create a cross dc lock, what shall I do ?

Thank you so much.

**Comment by banks** [comment]
By design cross-DC coordination is not really possible in Consul. We try to keep separate DCs as independent as possible which is why KV and catalog are not replicated directly.

For that reason, you can't create locks across DCs - there is not consensus protocol operating between the two independent DCs so there is no way to enforce the safety guarantees needed for a lock.

It may be possible to have a node (client1) in dc1 create a KV attached to a lock session in dc2 but as you find that lock session can't be attached to client1 node holding the lock in dc1 since dc2 doesn't know anything about the nodes in another DC. It's not in the same gossip pool so it can't know if that node fails to abort the lock.

In theory it would would to create a cross-DC lock with an empty session - i.e. it will never be lost unless you manually release it or kill the session actively. But then you still have to solve the problem of accurate failure detection externally which is a hard (technically impossible via the [FLP result](https://www.the-paper-trail.org/post/2008-08-13-a-brief-tour-of-flp-impossibility/)) problem to solve.

I'd instead recommend you re-think your architecture so only nodes in the same DC coordinate via locks and cross DC uses another strategy that is more tolerant of partitions. If you can't do this, then Consul doesn't really provide strong enough guarantees by design for what you need - you may need to consider implementing your own consensus protocol across your DCs!

Hope this helps.

**Comment by denglifeng3** [comment]
@banks ,Sure, thank you so much for your suggestion.

**Comment by rhyas** [comment]
FWIW, this used to work in 1.1.x. I'm not sure when the functionality changed, but it's definitely a negative change. I understand the idea behind the sessions and lock timeout/release/etc. But not having the ability to use a global lock removes a *lot* of use cases for using consul around scheduling, leader election, etc. for cluster technologies that are cross-region/cross-dc.

**Comment by banks** [comment]
> FWIW, this used to work in 1.1.x

I'm not sure what you are referring to but Consul has never supported cross-DC locks. I explained before how this is well outside Consuls fundamental design decisions and that hasn't changed at any point!

Can you elaborate on what you did with 1.1.x that led you to believe cross-DC locks were working?
