### ISSUE TITLE
How to set up a Highly Available cluster using consul

### ISSUE THREAD

**Issue by shayan1995** [hashicorp/consul#5378]
Hi guys, I'm trying to setup a highly available cluster with automatic failover that stores large files on two physical servers(two copies of the file), and create a mapping system to keep track which server has which actual copy and which server has the backup. So in case of failure, I can update the table to route the requests to the backup server.

Would Consul be a good tool to accomplish this? I was thinking about using the KV store to keep track of the mappings and run a consul server on each one of my nodes to keep track of their health status, and upon the failure of any of the nodes update that mapping.

Also How can I get the health status of the nodes(serf health status) outside of the local network?

Thank you in advance to take the time to answer this.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
