### ISSUE TITLE
enhancement for consul agent client that support circuit breaking to protect consul server.

### ISSUE THREAD

**Issue by Agent-Tao** [hashicorp/consul#5417]
Consul Agent Client only transfer request to server and little things to protect the server.  I met a problem a few day age that One service query consul crazily because that can not got a empty service list they need to invoke.  this bug lead the consul cluster overload and new service can not be registed.
if the consul agent client has the circuit breaking feature ,this would not happen. so is there a plan that add some feature to consul agent client like circuit breaking or rate limiter to protect the whole cluster?

**Comment by banks** [comment]
Hey, Consul already has [RPC rate limits](https://www.consul.io/docs/agent/options.html#rpc_rate) that we recommend you set on all clients to a sensible value that will protect the server's from bad behaviour.

We also intend to add mechanisms into the servers that will protect themselves from overload better in the future although not on the roadmap currently.

The problem with doing anything smarter like dynamically applying a rate limit if the RPCs are erroring is that it's incomplete - a badly behaved client may still hammer server with requests that are not errors for example the empty list you described.

I'm going to close this for now just because we are tracking broader overload work on servers elsewhere (internally with our research team) and the client rate limiting solution you suggest already exists. Let me know if you think there is something else we should consider specifically and we can re-open.
