### ISSUE TITLE
node_name set to the FQDN by default

### ISSUE THREAD

**Issue by bigon** [hashicorp/consul#5532]
Hi,
#### Overview of the Issue

consul seems to use the FQDN by default for the node_name instead of just the hostname

That means that by default, consul shows the following warning:

> [WARN] agent: Node name "foo.example.com" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

#### Reproduction Steps

Steps to reproduce this issue, eg:
1. Start consul

The hostname command shows the following
```
root@foo:~ # hostname
foo.example.com
root@foo:~ # hostname -s
foo
```
### Operating system and Environment details

RHEL 7
Consul: 1.4.3

Shouldn't consul take the hostname instead of the FQDN by default?

**Comment by pierresouchay** [comment]
Agree with that, but this change would likely break many of existing Consul installations as renaming nodes is hard ;(

**Comment by pearkes** [comment]
It is definitely non-optimal but unrealistic we'd want to introduce a change to this behavior given the potential challenges associated with renaming nodes as @pierresouchay noted, not only due to the internal gymnastics of renaming nodes but also due to the dependency folks likely have on the node names as currently designed. This is an unfortunate side-effect but it seems _mostly_ cosmetic unless I'm incorrect. I'm going to close this as we will likely not change this behavior directly.

**Comment by Lord-Y** [comment]
Still having this issue almost 1 year after. I'll switch to short name
