### ISSUE TITLE
UI Head Menu is not pretty

### ISSUE THREAD

**Issue by cnisky** [hashicorp/consul#5581]
The head part of consul UI is really urgly.  
Check screen capture below.
![image](https://user-images.githubusercontent.com/13595791/55223167-93110580-5248-11e9-9cc6-f13e41d1966f.png)

**Comment by johncowen** [comment]
Hi @cnisky 

That does look quite urgly! Could you let us know what platform you are running i.e. OS, Browser version etc? And also confirm the Consul version you are using?

Thanks,

John

**Comment by cnisky** [comment]
Hi John,
I found this issue in MS IE browser,  and it looks good in chrome.

BR

**Comment by johncowen** [comment]
Hey @cnisky 

Thanks for the extra info! Do you know the specific version of MS IE? We don't support all versions, and I'm guessing the one you tried isn't one we support.

Glad everything is good for you in Chrome. I'll just hang on a while to check that IE version, otherwise I'll close this in a week or so.

Thanks,

John
