### ISSUE TITLE
Define watch for cluster and not one agent

### ISSUE THREAD

**Issue by GolanPachu** [hashicorp/consul#5605]
Hi,
I'm using Consul v1.4.4, I have a cluster of 3 nodes and I want to watch a key change, so I defined a watch on the first, but if the agent will fail, the watch wouldn't work.
I don't want to define the same watch on all of the agents because then it will fire 3 times every update.
So how can I define a watch to the whole cluster instead of a specific agent?

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
