### ISSUE TITLE
How to convert a consul server from Voter=false to Voter=true?

### ISSUE THREAD

**Issue by moizmmz** [hashicorp/consul#5644]
How to convert a consul server from Voter=false to Voter=true?

**Comment by kyhavlov** [comment]
This should happen automatically after the server is added to the cluster. Initially a new server is added as a non-voter and isn't part of the quorum, then after a short time (5s is the default) it's promoted to voter as long as it's considered healthy by the leader, meaning it's caught up enough on Raft logs and has kept up on raft heartbeats. There's no way to manually force a server to get promoted to a voter currently.

**Comment by moizmmz** [comment]
Okay. Do you know how I can find out whats going wrong? Sorry I'm a little new to this.

**Comment by moizmmz** [comment]
> This should happen automatically after the server is added to the cluster. Initially a new server is added as a non-voter and isn't part of the quorum, then after a short time (5s is the default) it's promoted to voter as long as it's considered healthy by the leader, meaning it's caught up enough on Raft logs and has kept up on raft heartbeats. There's no way to manually force a server to get promoted to a voter currently.

**Comment by pearkes** [comment]
There are a lot of reasons why something may be a non-voter. I'd recommend reading a bit of background on how Consul works in this regard: https://www.consul.io/docs/internals/consensus.html.

Otherwise, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here, such as the [Consul mailing list](https://www.consul.io/community.html).
