### ISSUE TITLE
Unable to join to Consul cluster

### ISSUE THREAD

**Issue by abhayJava** [hashicorp/consul#5660]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
unable to join to consul cluster using consul join http-addr=http://x.x.x.x:8300

#### Reproduction Steps

Started a consul agent on system 1using consul agent **consul agent -data-dir=/consulLogs**
Tried to Joined from system 2 i.e. my local using consul join http-addr=http://x.x.x.x:8500

Error Logs

Error joining address 'http-addr=http://x.x.x.x:8500': Put http://127.0.0.1:8500/v1/agent/join/http-addr=http://x.x.x.x:8500: dial tcp 127.0.0.1:8500: connectex: No connection could be made because the target machine actively refused it.
Failed to join any nodes.

**Comment by pearkes** [comment]
I'm guessing the target IP didn't have Consul running or wasn't reachable for some reason. However, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
