### ISSUE TITLE
HTTP API deregister service with service definition file

### ISSUE THREAD

**Issue by keefien** [hashicorp/consul#5682]
#### Feature Description

the Consul CLI offers two possibilities to deregister a service, using the serviceID or the service definition file which was used to register the Service. But the HTTP API only offers the possibility to deregister services using the ID.

In our particular case we are using k8s lifecycle hooks to register services in postStart section, which works really well, also we deregister services in the preStop section, but here we can only use the ID. So far it would be no problem, but we pull the service definition from consul KV. following an example:

`{
  "ID": "$POD_NAME",
  "Name": "pushgateway",
  "Tags": ["prometheus", "monitoring", "metrics"],
  "Address": "$POD_IP",
  "Port":9091,
  "checks": [{"id": "metrics", 
              "name": "HTTP Metrics on port 9091",
              "http": "http://$POD_IP:9091/metrics",
              "interval": "60s",
              "timeout": "10s"
             }]
}`

So Service ID is at the moment always the $POD_NAME, but if i have a pod including multiple workloads they will override each other in the startup process. for this i wanna use something like that:

`"ID": "$POD_NAME-metrics"`

But if i will use this, my deregistration process will not work because the ID references to the $POD_NAME without any extension.

Also i don't want to register and deregister services directly to the catalog, this makes everything only more complex.

I'm not sure if this is a big deal to implement, but it would be a very useful extension of the HTTP API

Note: i've also tried the consul-k8s catalog syncer which basically works, but i dindn't found any possibility to add there healthchecks or predefined service definitions.

**Comment by pearkes** [comment]
If I understand correctly, I'm not sure how this may work if you don't have the ID of the specific service you're deregistering. I believe the CLI when provided a configuration is just parsing this ID to utilize the same deregistration API (https://www.consul.io/api/agent/service.html#deregister-service) so that fit your use-case.

If you don't have the ID ahead of time I'm not sure how you might be able to manage the lifecycle of service. I might misunderstand you, though.

> Note: i've also tried the consul-k8s catalog syncer which basically works, but i dindn't found any possibility to add there healthchecks or predefined service definitions.

I'd be sure to vote on or open up an issue with that feedback over there! I think our recommendation in this scenario for integrating the Consul service lifecycle with Kubernetes would be to utilize the first-class integrations. I understand there may be limitations there currently but maybe we can resolve those for your scenario.

I'm going to close this proactively as I don't think we'd implement this feature given the current options – they seem sufficient for the majority of use-cases when not using the catalog. Thanks for your feedback!
