### ISSUE TITLE
Improved API Data Models

### ISSUE THREAD

**Issue by jameswestover** [hashicorp/consul#5708]
#### Feature Description

Currently in order to get a service + all its nodes with ip / port info + the health of each node + the full set of tags associated with a service requires 3 different API calls. When trying to construct routing tables for load balancing or service mesh this can become computationally expensive. Ideally one api call would retrieve all of this data at once.

`v1/health/state/any` - returns health state of a node, but not port / ip / all combined service tags
`/v1/catalog/nodes` - returns ip address for a given node with a service id 
`v1/catalog/service/<nodeId>` - returns a single node ip address and port

In order to compile a list of nodes in a service, their ip and port combination, plus the health state of each node requires `<number of nodes in the system> + 2` api calls to generate an accurate routing table. This, at large numbers of services and instances, becomes highly expensive. Ideally this data could be represented in a single API call.

Ideally, i would be able to call an API endpoint and retrieve the data returned from `v1/catalog/service/<nodeId>` + associated health data for all nodes in the system.

#### Use Case(s)

The primary use case is for using consul as a catalog for creating dynamic load balancing routes. Optimizing the data flow between consul -> load balancer decreases the time in which a route update takes to propagate from a node coming online to it being put into a load balancer.

**Comment by pierresouchay** [comment]
@jameswestover /v1/health/service/:service Name already does that

**Comment by jameswestover** [comment]
Yeah, thats perfect. Was this added recently with the connect code? I've been searching for this exact endpoint for forever.

**Comment by pierresouchay** [comment]
Forever I think (at least for more than 1 and half year when I started using Consul)

**Comment by jameswestover** [comment]
That endpoint model is perfect, but I still would like to see a "bulk" API endpoint for it, somethign like `/v1/health/services` that gives me that data for everything consul knows about...otherwise im still stuck in a position of making `<number of services>` API calls to generate an entire route table.

**Comment by pierresouchay** [comment]
We are doing this constantly to generate a UI for Consul as seen here https://github.com/criteo/consul-templaterb/blob/master/samples/consul-ui/consul_services.json.erb this works quite well on large clusters (7k+ nodes per DC, more than 3k kind of services)

You can also build it yourself from 3 endpoints nodes + checks + services

**Comment by mkeeler** [comment]
@jameswestover If I understand it correctly, the feature request is now essentially asking for a way to get the data that is output by `/v1/health/service/:service` but to do so for all services Consul knows about?

**Comment by jameswestover** [comment]
Correct.

**Comment by mkeeler** [comment]
The main problem with providing more of a bulk endpoint to gather all that data is that blocking queries on a larger amount of the catalog are going to be very inefficient.

Every time one of the nodes/services/checks that you are blocking on get updated Consul now would have to send the entire data set back to you. Therefore in general it would be better to issue multiple blocking queries to the `v1/health/service/:service` endpoint so that only the updated data gets sent back to you.

In the more medium term we are looking at a way to improve these sorts of scenarios where you want to essentially mirror part of the data Consul has. The current thinking is that we should provide a way to stream update deltas from Consul to other processes in a somewhat pub/sub fashion where you could opt-in to updates for only what you care about. There are many uses for having these capabilities including cross-dc replication which Consul does a fair bit of already. There is no concrete timeline for any of this but the overall issue is one we are aware of and wanting to fix.

**Comment by pearkes** [comment]
I was a bit on the fence about closing or keeping this open but I think will lean towards closing this as this a serious concern the project has that touches many different areas. To pull out a good quote from @mkeeler above:

> In the more medium term we are looking at a way to improve these sorts of scenarios where you want to essentially mirror part of the data Consul has.

Given this has many implications and bottlenecks various pieces of work in progress, it will likely not be solved in one fell swoop but rather in quite a few incremental improvements. Specifically, we're running into this in the context of the Connect feature and distributing similar data to the edge.

So this is not closing as in _we won't be fixing it_, and expect to see improvements here down the road. I do think there is merit for us maybe outlining our roadmap there once it is more concrete and getting feedback  – will keep that in mind.
