### ISSUE TITLE
[ui] with Consul 1.5.x, when creating/updating a token allow specifying the token UUID

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#5860]
With Consul 1.5.0 allowing to set the token ID again, it'd be great if the UI would allow setting that UUID when creating or updating a token.

**Comment by johncowen** [comment]
Hey @scalp42 ! 👋 

Good to see you again!

With the new v2 ACL system it was decided that we shouldn't let a user specify UUIDs for tokens. We've since added the functionality back in, but the usecase was for machine use only i.e. external configuration management systems etc, hence we still decided to keep it out of the UI.

There's some history here:

- https://github.com/hashicorp/consul/issues/4977
- https://github.com/hashicorp/consul/pull/5307

(just noticed you are involved in that last one, but I've kept the links here for others)

We'd be interested to hear any usecases for being able to do this specifically from the UI though.

I'm going to close this at least for the moment, but feel free to add any more comment and we could potentially reopen.

Speak again soon! 😄 

John
