### ISSUE TITLE
Consul Multidatacenter on AWS

### ISSUE THREAD

**Issue by hbmelachuru** [hashicorp/consul#5908]
We are trying to create consul multidatacenter on EKS cluster. Consul server and consul client version are 0.8.4.
I have created ingress service for consul. But instead of an IP, it gave me an elb in aws.
`NAME                           TYPE                 CLUSTER-IP                EXTERNAL-IP        PORTS  

consul-ingress   LoadBalancer   172.20.197.127   af40d435f7f7911e9b31-160xxxx60.us-west-2.elb.amazonaws.com  8500:30152/TCP,8400:30040/TCP,8301:31331/TCP,8302:30789/TCP,8300:30147/TCP,8600:31095/TCP 
`

But when I tried to deploy consul server, the server is failing to start up with the following error:
`2019-05-29 17:33:35,499 DEBG 'start_consul' stderr output:
==> Error starting agent: Failed to parse advertise address for WAN: af40d435f7f7992186-160xxxx60.us-west-2.elb.amazonaws.com`

1. Should advertise_wan_addr, needs to be an IP, is there any specification?
2. If so, How do we join the 2 clusters with ingress that has been created in aws service.
3. Do we have any documentation on creating consul multidatacenter on aws
Thank you for the help in advance.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul community forum](https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
