### ISSUE TITLE
retry-join support for Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by StuporHero** [hashicorp/consul#5918]
#### Feature Description

I would like the ability to use retry-join with Oracle Cloud Infrastructure using tags like I can on AWS and Azure. I've actually already created a [PR](https://github.com/hashicorp/go-discover/pull/117) with the core functionality already working on the [go-discover repository](https://github.com/hashicorp/go-discover), but no one seems to be paying attention to that repo, so I decided to open an issue here to bring attention to the need and hopefully get that PR integrated faster.

**Comment by pearkes** [comment]
Thanks for opening the issue here, and for the PR in go-discover @StuporHero!

I believe we owe you a further response on that PR to move this forward further. I can't speak to specific timelines we'll be able to do that by just wanted to note we're aware it is blocked on us.

That PR can serve as tracking this new feature – I'm going to close this issue to consolidate. Thanks!
