### ISSUE TITLE
List healthy nodes by service

### ISSUE THREAD

**Issue by xavierleune** [hashicorp/consul#5961]
Hi,

I'm looking for an efficient way to get all healthy nodes from a service via the http api. I'm not sure if this already exists (and I couldn't find the right query) or not (and I think it would be super useful).
Actually here's what I'm doing to filter nodes by health.

1. Get all nodes for a service with a tag via /v1/catalog/service/varnish?tag=prod
2. Get all checks not passing /v1/health/checks/varnish?tag=prod&filter=Status%21%3Dpassing
3. Filter the output of the catalog with the list from 2

#### Feature description

Add a filter on the catalog api to retrieve only healthy nodes (i.e: nodes without any "non passing" check). IE with this query: /v1/catalog/service/varnish?tag=prod&filter=Health%3D%3Dpassing

#### Use Case(s)

I think I've seen a discussion somewhere on this github where you declared that catalog and health checks where completely separated endpoints. Actually we're using consul to retrieve a list of nodes we can run queries on. We can do a lot of calls to consul, so we're trying to be the most efficient we can be (and would like not add a caching layer on our side for a health status).

In my opinion it could be a great improvement for consul to support such filtering on nodes, it's pretty aligned with the product goals.
If such feature already exists, please forgive me.

Thanks for reading,

Xavier

**Comment by mkeeler** [comment]
@xavierleune I think you are looking for [`v1/health/service/:service-name` endpoint](https://www.consul.io/api/health.html#list-nodes-for-service)

So for you I think it would be: `v1/health/service/varnish?tag=prod&passing=true`

You could alternatively use the filter query parameter for that endpoint added in 1.5.0 in which case it would look like: `v1/health/service/varnish?tag=prod&filter=<url encoded filter string>` and the filter would be `not Checks.Status != passing`
 
Why the double negative in the filter:

For lists of things such as health checks on a service, the filter language automatically maps the operation across all list elements and "matches" if the operation on *any* list element evaluates to true. So if the service instance has 3 health checks the filter `Checks.Status == passing` would actually be equivalent to `Checks[0].Status == passing or Checks[1].Status == passing or Checks[2].Status == passing` (Note that the filter language does not currently allow indexing into lists with the `Checks[0]`). While we may update the filter language to better support this sort of use case for now the filter of `not Checks.Status != passing` would work because `Checks.Status != passing` evaluates to true whenever there exists some check that is not passing, then you can negate the whole thing with the `not`.

**Comment by xavierleune** [comment]
Hi @mkeeler 

Thanks a lot for your answer, it seems I did not read the manual carefully enough ! The two queries you provided are returning the expected results. Thanks for your detailed explanations on the filter query, it will be very useful.
I think the documentation on the catalog api could mention that. If I open a pull request about that, would you consider merging it ?

**Comment by mkeeler** [comment]
We are definitely open to improving the docs to make things clearer. Filtering is very new and I/we have been trying to figure out the best way to explain all of that succinctly.

We have some high level information about the filter language itself but then each API endpoint that supports filtering has a separate table listing the valid selectors and the operations that can be performed on those. They are quite lengthy and I am not in love with the presentation.

If you open a PR we would definitely consider merging it. Before spending too much time I think it would be good to open another issue for "Improving Filtering API Docs" or something where we can discuss the best way forward to improve this. Our docs team would have some valuable input there too.
