### ISSUE TITLE
Consul service unable to start

### ISSUE THREAD

**Issue by JawadKM** [hashicorp/consul#6001]
Hi,
I am new to Hashicorp and having this issue where my consul just stops working and when I try to restart the service it fails. Below is what I get when restart the service

```
# systemctl status consul.service
● consul.service - Consul server agent
   Loaded: loaded (/etc/systemd/system/consul.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-06-20 17:02:48 EDT; 10s ago
  Process: 20054 ExecStart=/opt/forgerock/consul/consul agent -config-file=/opt/forgerock/consul/consul.json -pid-file=/opt/forgerock/consul/consul.pid (code=exited, status=1/FAILURE)
 Main PID: 20054 (code=exited, status=1/FAILURE)

Jun 20 17:02:48 server1.xxxxxx.ontario.ca systemd[1]: Unit consul.service entered failed state.
Jun 20 17:02:48 server1.xxxxxx.ontario.ca systemd[1]: consul.service failed.
```
My systemd config as below

```
### BEGIN INIT INFO
# Provides:          consul
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Consul agent
# Description:       Consul service discovery framework
### END INIT INFO

[Unit]
Description=Consul server agent
Requires=network-online.target
After=network-online.target

[Service]
User=fruser
Group=fruser
PIDFile=/opt/forgerock/consul/consul.pid
PermissionsStartOnly=true
ExecStart=/opt/forgerock/consul/consul agent -config-file=/opt/forgerock/consul/consul.json -pid-file=/opt/forgerock/consul/consul.pid
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
KillSignal=SIGTERM
Restart=on-failure
RestartSec=42s

[Install]
WantedBy=multi-user.target
```
As stated earlier I am new to the vault and do not know where to look for the logs which can tell me some more detail about the issue I am facing.

Your help in this regards will be highly appreciated.

Thanks, looking forward to hearing from you soon.

**Comment by mkeeler** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be posted to the [user forum](https://discuss.hashicorp.com/c/consul) or sent to the [consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

With all that being said, one thing I can see you may want to try would be starting consul as the `fruser` yourself with the same arguments that systemd would pass to it. The terminal output is probably telling you whats happening. Also, its odd that the systemctl command isn't outputting anything that consul would have output. You could try running something like `journalctl -xe -u consul` to look for the consul specific logs (assumes you are also using journald beside systemd). 

If you still need further help I would recommend the [HashiCorp Discuss forum](https://discuss.hashicorp.com/c/consul) first as that is where we have been moving community discussions to. There is also a Vault section on there if you need more help with that.
