### ISSUE TITLE
Memory issues in EKS

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul#6038]
For context, we're in EKS and running a Consul cluster deployed via consul-helm as the storage backend for a Hashicorp Vault.
While doing some load testing (with locust) on the Vault, I noticed that the memory usage on the Consul servers's memory usage was increasing (as expected) but then wasn't decreasing to anywhere near the original usage.

When first deployed, about 25Mi of memory was being used.
During testing of about 2000 concurrent cert signings (Vault PKI backend) over 10 minutes, some servers maxed out of memory and got restarted at 2Gi. 
I noticed that memory usage wasn't decreasing very quickly afterwards and tracked it for about 30 minutes and rechecked it the next morning. Even the next morning, memory usage had only dropped down to between 1250-1400Mi across the whole cluster of servers.

Any ideas as to the source of this memory usage even after the Vault wasn't being used or ways to debug the source of this memory usage?
If it's going to be a creeping memory leak that doesn't drop after restarts, that's worrying for the long-term.

**Comment by banks** [comment]
Hey @infa-bsurber, this is really an issue with Consul itself rather than the helm chart so I moved it here to get the proper attention.

Would you be able to confirm your Consul version and details of the workload - you mention vault is there anything else using Consul, e.g. clients registering services etc?

Do you have consul's metrics available for things like number of active RPCs (consul.rpc.{request, query}), and the raft activity especially `consul.raft.apply`. If you have `consul.http.{GET,PUT}.v1.kv` summed across all your clients that would also be useful to see the load on the servers from KV.

A few general pointers that are useful to know here:
 - Go's runtime doesn't free memory back to the OS very aggressively (or rather the OS tends not to reclaim aggressively unless it's under extreme memory pressure) which means that if a Go probelam like consul does a lot of work and uses a bunch o memory, then even after the load stops and Go GCs the objects and "frees the memory. The RSS (used memory) the OS reports will likely not drop. It is free though and Go should be able to-reuse it for future allocations before it asks for more from the OS.
 - Consul servers manage an in-memory database. If the memory growth is caused by actual writes to the state store (e.g. KV or service registrations, session creation etc) then the memory will not be freed and will come back after a restart because the state will be reloaded into memory from the snapshot. You can check this by looking at the snapshot files in the server's data dir on the persistent volume - the snapshot file size is essentially the same (or slightly lower due to fragmentation overhead in memory accounting) as the basic amount of RAM the servers will use just to store the current state. If this is high, the only way to reduce is to delete state - you may have something being stored you didn't intend like badly behaved clients creating thousands of sessions that never expire. If this is the case and you want to debug where the large state is coming from you can follow the instructions here to use a simple tool I made to dump snapshot message types/sizes: https://github.com/banks/consul-snapshot-tool

Finally, if it really does look like a "leak" (increasing all the time, returns to near zero on restart but then increases again from there. The best way to debug is via pprof heap profiles.

You need to configure `enable_debug = 1` on one of your servers (needs a restart - can be done via helm but this would add it to all servers and rolling restart all of them). Then either use go's pprof tools against it if you are familiar, or use the built in `consul debug` command to take them and share them with us to help out.

For a leak we'd need at least 2 heap profiles taken some time apart - ideally one just after restart and another later when memory has grown significantly.

Hope this helps start you off investigating, we're happy to help.

**Comment by infa-bsurber** [comment]
The snapshot size sounds reasonable as the behavior I'm seeing is that restarting the Consul servers wasn't actually resetting memory consumption.
Thanks for the good leads, I'll come back when I've got some results.

**Comment by infa-bsurber** [comment]
```
           Record Type    Count   Total Size
---------------------- -------- ------------
                   KVS   404762      412.4MB
              Register       39       18.3KB
           ACLTokenSet       10        3.9KB
 CoordinateBatchUpdate       14        2.6KB
          ACLPolicySet        4        1.7KB
             ConnectCA        1        1.5KB
ConnectCAProviderState        1        1.2KB
               Session        3         551B
                 Index       15         400B
             Autopilot        1         188B
       ConnectCAConfig        1         138B
---------------------- -------- ------------
                         TOTAL:      412.5MB
```
so, when the server restarts it should theoretically restore to 412.5MB of memory usage?

**Comment by banks** [comment]
Yep. that means you have 412MB of KV data stored which means server will
always need to restore that.

The actual steady-state memory that consumes will likely be a bit more than
412MB since there is overhead from allocation fragmentation and the indexes
we build on the KV store etc - the snapshot is just the raw data while the
actual loaded DB in memory includes secondary indexes, metadata tracking
updates and overhead from radix tree bookkeeping etc.

We generally recommend estimating RAM requirements as the actual data size
* 2-3 (https://www.consul.io/docs/install/performance.html#read-write-tuning
)

The snapshot is basically just the raw KVs so expect 2*3x that amount of
RAM needed just to load that snapshot.

Does that match roughly what you are seeing? If so then I think this is not
a "leak" in Consul but a Vault/Client behaviour to debug -- what is using
all that space.

**Comment by infa-bsurber** [comment]
Is it expected to remain at that memory consumption level of 2-3 * actual data size or is it expected to return to its steady-state value?
What we're seeing is it staying at the 2-3x amount long after testing has ended.

**Comment by banks** [comment]
It will remain there as long as the data is still present in the KV store.

It seems your testing wrote a lot of data to Vault so the memory required
to hold that data will continue to be used until it's deleted from Vault
(or aged out if its ephemeral).

If you snapshot is still 400MB then as far as Consul is concerned there is
still that much data stored in its DB and so the RAM will continue to be
used to serve that.

They key is to work out what that data is in Vault and remove it if it's
not needed. If you're not sure how to do that, it might be worth asking on
the Vault forum: https://discuss.hashicorp.com/c/vault

Hope this helps.

**Comment by infa-bsurber** [comment]
Alright, thanks for the help.

**Comment by infa-bsurber** [comment]
As a followup to this for anyone reading this later about some of my own learnings:
Vault stores some data for every cert signed by the PKI backend to enable future revocation by serial number.
You can see your full set of stored serial numbers via https://www.vaultproject.io/api/secret/pki/index.html#list-certificates.
This data should last at minimum for the TTL of the signed cert so stress testing with this backend should minimize that TTL as revocation doesn't actually remove that data (Vault has to add it to the CRL).

**Comment by banks** [comment]
Also note that if you don't need the cert meta to be preserved inside Vault
(i.e. you never need to list them or look them up later for revocation) you
can also configure the Vault role with `no_store` which makes signing a
leaf not need to store any data in Consul at all. This is great for
benchmarking too assuming you are not trying to stress test Consul writes.
