### ISSUE TITLE
When authoritative DC will down, agent API endpoint stops working

### ISSUE THREAD

**Issue by tantra35** [hashicorp/consul#6072]
#### Overview of the Issue
We have multiple consul datacenters in federation setup, so we have one authoritative DC, and we have down acl policy as "async-cache" and expect that in outages situations slave datacenters will work separately from  authoritative DC, bit this is not true, because when our authoritative DC was down, we couldn't call any agent API endpoints(https://www.consul.io/api/agent.html), for example `agent/members`(return empty list) or `agent/self` (in contrast catalog API work perfectly), also we can't register any service throw /agent/service/register API endpoint(in our case this registrations making nomad https://www.nomadproject.io/)

### Log Fragments
On client side we see follow in logs when maked for testing purposes API call `/agent/self` (we try mutiple tokens but no one works when authoritative DC was down)
```
Jul 03 19:37:25 dockerworker-2 consul.sh[8921]:     2019/07/03 19:37:25 [ERR] consul: "ACL.GetPolicy" RPC failed to server 192.168.142.201:8300: rpc error making call: No path to datacenter
Jul 03 19:37:25 dockerworker-2 consul.sh[8921]:     2019/07/03 19:37:25 [ERR] http: Request GET /v1/agent/self, error: Permission denied from=127.0.0.1:57742
Jul 03 20:21:21 dockerworker-2 consul.sh[8921]:     2019/07/03 20:21:21 [ERR] consul: "ACL.GetPolicy" RPC failed to server 192.168.142.202:8300: rpc error making call: No path to datacenter
Jul 03 20:21:21 dockerworker-2 consul.sh[8921]:     2019/07/03 20:21:21 [ERR] http: Request GET /v1/agent/self, error: Permission denied from=127.0.0.1:57960
```
Message like `No path to datacenter` expected due authoritative DC is down, but we expect that with acl replication, tokens can be resolved in slave DC, but this doesn't happens

**Comment by mkeeler** [comment]
@tantra35 prior to v1.4 consul clients when needing to authorize a request such as using one of the agent apis, they would make a cross-dc query to the authoritative dc. The catalog api is still working for you because those requests end up as RPCs to the servers and the actual authorization happens there. 

In Consul 1.4 this changed to operate like what you would be expecting. When token replication is enabled in the secondary/non-authoritative datacentets, all token resolution for that dc is provided by those servers and the clients don’t ever make direct requests to the primary dc. 

If you can confirm you were using a version before 1.4 then I can close this. If you were using 1.4, then something else is not quite right that would take more looking into.

**Comment by tantra35** [comment]
@mkeeler Thanks for you  for the detailed explanation(documentation is not full enough to understand this moment). And your absolutely right on our consul version(1.3.1) we see our problems, for check we build test stand where testing 1.5.2 and frount that with this version we doens't have any problems with agent API.

But upgrade to latest version of consul looks very dangerous, because ACL changes in 1.4.x, and in our infrastructure we use old version of vault(0.10.4)

**Comment by mkeeler** [comment]
One thing about the upgrade in ACLs for 1.4.0 is that they are almost entirely backwards compatible. 

All the old APIs are still available and anything using them should still work. Internally the replication and resolution mechanisms are all new so you can have the 1.4 failure behaviors without having to overhaul your ACL usage on day 1. 

The one place where things are not fully compatible is the v1/ACL/bootstrap endpoint. However since you already have ACLs setup you shouldn’t need to use that one anyways. 

If you have a non-production environment I would encourage testing it out there. When rewriting ACLs I attempted to make the transition from old to new as painless as possible and allow for everything users are currently doing to continue to work without modification. Hopefully testing out your usage in a ore-prod environment would give you more confidence of performing the upgrade throughout. 

Alternatively, for the agent APIs specifically, the `agent_master_token` configuration entry can be set to some random value (not a real token). In the event of an authoritative dc outage you can use that token to access the agent APIs and it won’t require remote token resolution. 

Lastly, I have wanted to write up some ACL internals documentation ever since the ACL rewrite in 1.4. It is definitely not clear exactly how these things operate to end users but it is intricately known to at least a few of the consul developers. Hopefully one of us will have the time to write that up in the not too distant future.
