### ISSUE TITLE
I am new to Consul, I have registered my service say "service_1" to a Consul server and health check is also in place. If the "service_1" goes down, I need to add a listener in my java code, where Consul notifies the listener that the "service_1" is down. I have come across watches in Consul, I see examples , where handler is a script, I don't see any example of how i can add a listener in java code to which Consul can notify that the particular service is down. Is this possible? If so, an example or steps to achieve this would be of great help.

### ISSUE THREAD

**Issue by anusha-hv** [hashicorp/consul#6096]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here if you have a question.

- Frequently asked questions: https://www.consul.io/docs/faq.html
- Consul Guides: https://www.consul.io/docs/guides/index.html
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
