### ISSUE TITLE
Use of github.com/hashicorp/consul v1.5.x or later pulls 3x the modules and slows builds

### ISSUE THREAD

**Issue by jpwhitemn** [hashicorp/consul#6222]
#### Overview of the Issue

Our project uses github.com/hashicorp/consul.  We place this module in our go.mod file.  We have been using version 1.3.1 but decided recently to upgrade to v1.5.3.  When we did so, this single change in our application caused our Jenkins build to increase from 17min to 36min on x86 platforms and from 45min to 85min on ARM platforms.  Looking further into the reasons why, we found that just with this single change to the go.mod (moving from v1.3.1 to v1.5.3), the number of modules found in go.sum jumped from 117 to 304.  We tried versions 1.5.2, 1.6.2 beta and 1.4.5 to see when the issue began.  Here are the module counts for each of these version changes:
1.6.2 - 303 modules
1.5.3 - 304 modules
1.5.2 - 304 modules
1.4.5 - 116 modules
1.3.1 - 117 modules

In checking the executable size, we did not see a large jump (only from 20.24MB to 20.40MB) so it does not appear to greatly impact the runtime artifacts - just the build.  But the build time increase is so significant that it can take several hours for our build process to complete given the micro service architecture we are using.

This ticket was created after communication with some Hashicorp team - notably Neena Pemmaraju suggested this does appear to be a result of a switch to go modules.

#### Reproduction Steps

Steps to reproduce this issue:
simply replace github.com/hashicorp/consul v1.3.1 in go.mod of a Go Lang application with one of the later versions (1.5 or later) and then see the difference in the number of modules brought in via the go.sum file

**Comment by mkeeler** [comment]
@jpwhitemn Compile times definitely have gotten slower since introducing modules on our end (which was in 1.5.0). There are several libraries Consul uses that are pretty massive for Kubernetes and Envoy integrations and while the binary size wouldn't have increased much the compiler is still going to have to compile most of that code before it can figure out much of it isn't used and remove it during the linking process. Also, its likely that it now has to download the dependencies for these pretty massive libraries as it will not be using the vendored dependencies like it would have pre-1.5.0.

The main question I have is what is your use case around having a dependency on github.com/hashicorp/consul instead of the github.com/hashicorp/consul/api module. The second one has drastically fewer dependencies and is what we recommend others use to interact with Consul. Anything outside of the api module is subject to arbitrary changes from release to release as its not something we expect to be pulled in directly. If there is some aspect that you do need that isn't in the submodule, it would be great for us to find that out so that we can make sure Consul's public facing modules meet the needs of our users.

**Comment by jpwhitemn** [comment]
resolved per Matt's suggestion.
