### ISSUE TITLE
about Installing Consul as a Service

### ISSUE THREAD

**Issue by magnificence-dream** [hashicorp/consul#6318]
install consul by command line ,it's ok, the command is as follows:

`consul agent -server -bootstrap -data-dir ./data -node=xx -bind=x.x.x.x -ui-dir ./dist -config-dir=./conf  -client=0.0.0.0  -datacenter=xxx`

now i want change it to windows server:
   my situation:
        server Installation succeeded but startup failed
  
 command:
  `sc.exe create "Consul" binPath= "C:\xxx\consul.exe agent-config-dir C:\xxx\config" start= auto`

config.json:
    
![9](https://user-images.githubusercontent.com/39826801/63016261-cab1de80-bec5-11e9-9e98-8635743bf56d.png)

i got error:

![6](https://user-images.githubusercontent.com/39826801/63017864-fb941280-bec9-11e9-8be2-79d6aa7412e4.png)

Thanks~

**Comment by i0rek** [comment]
Could you try to provide more information, like logs, consul version and so on?

**Comment by blake** [comment]
Hi @magnificence-dream, this was also reported in #6661. The command to install Consul as a Windows service was incorrect.

I have since updated the docs to reflect the proper command for [Installing Consul as a Service](https://learn.hashicorp.com/consul/datacenter-deploy/windows#installing-consul-as-a-service), so I am closing this issue. Please feel free to re-open if this does not solve your issue.
