### ISSUE TITLE
Recovering consul state after lost leader

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/consul#633]
Could someone explain what these sort of messages mean, and how to go about fixing them? 

```
2015/01/23 20:38:49 [ERR] raft: Failed to get log at index 256731: log not found
2015/01/23 20:38:49 [WARN] raft: InstallSnapshot to xxxxxxxx:8300 rejected
```

Im seeing the same message for multiple hosts, does it indicate that the cluster isnt fully recovered even though there is a leader now?

EDIT:

This is what I am seeing on the other side: 
```
2015/01/23 21:04:41 [ERR] raft: Failed to restore snapshot: failed to restore snapshot 92806-256860-1422047081715: Unrecognized msg type: [5]
```

**Comment by armon** [comment]
Looks like the followers are rejecting the data being replicated from the leader. (Likely it diverges from what they believe to be the past). This generally means something was done wrong, in a way that allowed two masters to exist for a while. (Mis-use of -bootstrap being the most likely). The simplest fix is to nuke the -data-dir on the followers and allow the leader to just replicate it all down again.

**Comment by hoffoo** [comment]
okay makes sense, I removed the directory and it seems it is trying to re cover but fails with this:

```
2015/01/23 23:02:19 [INFO] raft: Copied 431177 bytes to local snapshot
2015/01/23 23:02:19 [ERR] raft: Failed to restore snapshot: failed to restore snapshot 92806-256860-1422054139881: Unrecognized msg type: [5]
```

**Comment by ryanuber** [comment]
@hoffoo are the servers running different versions of Consul? It sounds from the logs like the leader is newer than the follower(s) being replicated to, and is attempting to replicate the `TombstoneRequestType`, which was recently introduced in Consul 0.5.0rc1. If that is the case, upgrading the other servers in the cluster might be the only way to get the followers to accept the data again, unless I am missing something. @armon what do you think?

**Comment by hoffoo** [comment]
Ahh okay, yes looks like that was the case, upgrading consul fixed it.

Thanks!

**Comment by wuub** [comment]
@armon @ryanuber doesn't this break consul's compatibility promise?

**Comment by ryanuber** [comment]
@wuub the protocol compatibility is not affected by this. The issue of not being able to apply new items from the Raft log on older versions of Consul should only come up if a partial upgrade of the server pool is performed (say, 1/3 of them), and normal operations are resumed while this inconsistency exists. There should not be problems during the upgrade process, but generally running multiple versions of Consul servers together in a cluster is not ideal.

Since this particular case involves older server nodes being unable to apply certain operations replicated to them from newer servers, we will likely need to publish a note about upgrading from pre-0.5 releases.

@armon any other thoughts on this?

**Comment by armon** [comment]
I've clarified the backwards compatibility in f53bd94. 
@wuub the short answer is kind of. The servers cannot be mixed with 0.5, but the clients can. The clients are largely where this promise matters, as it's very hard to coordinate the upgrade of thousands of nodes. We try very hard with the servers as well, but it can be extremely challenging to be forward and backward compatible in all cases. With 0.5 there is a 15 minute time window before you will have any issues, which is reasonable enough to handle a 3-5 node rolling upgrade.

**Comment by wuub** [comment]
Thanks for clarifying this. Since we are investing heavily in consul I would like to understand this better if anything similar happens to come up in the future upgrades. 

> With 0.5 there is a 15 minute time window 

1) Where does the 15 minute cut-off point comes from?
2) When agent sees an unsupported command, does it stop processing raft log or skips the entry?
2a) (assuming "stop processing" answer to the previous question) With stale reads enabled, we should expect increased number of inconsistent responses during the upgrade window, right?
3) AFAICT If we manage to upgrade followers first and current leader last, our cluster shouldn't experience any mixed-version problems*, or am I missing something? 
4) Can multiple DCs  be upgraded separately this time around**? 
4a) Do you expect that any future consul versions will require coordinated DC upgrades***? 

* - assuming no elections happen during upgrade window
** - is it safe to assume that anything KV related is local to a DC? 
*** - is it safe to assume that compatibility on API level sufficiently separates DCs?

**Comment by armon** [comment]
@wuub Let me try to clarify:

1) The 15 minutes comes from the servers periodically issuing a new `TombstoneRequest`. This is an internal detail, but it basically allows Consul to cleanup some keys in the background after a configurable TTL. The default value of the TombstoneTTL (not configurable currently) is 15 minutes: https://github.com/hashicorp/consul/blob/master/consul/config.go#L242.

Basically, 15 minutes after a 0.5.0 leader is elected, it will issue that command to followers. Older versions will append to their Raft log, but then panic when they attempt to apply it. This is by design, since we don't know if its safe to ignore a command (future compatibility), we log a message and then hard panic. This is to avoid potential state corruption given that the command is not understood.

2) As above, it will hard panic / stop processing. Stale reads will not affect this since the server will just crash.

3) Correct! The issue stems from trying to process the `TombstoneRequest` internally.

4) Yep! This command is purely internal to the cluster, and does not get issued between clusters.
4a) I highly doubt it. That would be a logistical nightmare that we would work very hard to avoid.

**Comment by wuub** [comment]
thank you @armon , everything is clear now
