### ISSUE TITLE
Reject invalid service name to prevent dns failure

### ISSUE THREAD

**Issue by Matts966** [hashicorp/consul#6335]
### Feature Description

As mentioned [here](https://github.com/hashicorp/consul/issues/3951#issuecomment-417091360), invalid characters in service names can cause failures in the dns resolution. So the validation of the name of service in config check and agent startup is helpful to prevent future errors.

Could I get feedback on this issue please?

**Comment by mkeeler** [comment]
@Matts966 We already warn for DNS and node names which are not valid DNS names. However for backwards compatibility reasons I don't think we can just reject them by default. Would you be interested in this being opt-in where you set some CLI flag (or potentially something that makes its way into raft) and then it enables the strict DNS name enforcement?

**Comment by Matts966** [comment]
Thank you for your feedback!

```
{
  "services": [{
    "name": "docker|build"
  }],
  "bind_addr": "{{GetInterfaceIP \"en0\"}}",
  "data_dir": "~/consul-data/"
}
```

In my local environment, the configuration above passed the `consul validate` successfully, but some warning is needed isn't it?

I am interested in the feature! but I could not understand the words

> (or potentially something that makes its way into raft)

Can raft be related to the DNS of the consul?

**Comment by mkeeler** [comment]
The warning must be done at a different level as a secondary pass after the main config parsing. If so we should probably move this so that `consul validate` and emit the warnings as well.

As for raft, what I meant was that in theory this should be a cluster wide setting. Not setting it on one agent would allow services to be registered when you didn't want that. So maybe we should either make Consul capable of storing these cluster wide settings in raft (similar to what we do for the autopilot config) or make sure the enforcement when opted in happens at the servers to prevent client agent misconfigurations from still allowing services with undesirable names to be registered. I will need to think through this a bit more but in general agree that at the absolute minimum we should make the existing warnings show up when running `consul validate`.

**Comment by Matts966** [comment]
I added draft PR as a solution using a flag named `verify-service-name` for I am not so familiar with `raft` and can't figure out how to verify service name (maybe the leader server should check that?).

The PR is a draft one and I am open to any feedback.

If anyone already works on it or my PR is completely in bad direction, I will give it up, so feel free to say it to me.

Thanks.

**Comment by Matts966** [comment]
I wonder if this feature is enabled by default for more security in the future major version update.
Maybe it is realized by modifying `agent/config/default.go` .

**Comment by s-christoff** [comment]
Re-opening and allowing stale bot to take its course. Apologies about this :)

**Comment by s-christoff** [comment]
Howdy -
I am going to go ahead and close this issue. If you think it should remain open, please comment back and let us know why!

Thanks!
