### ISSUE TITLE
Log Rotation configs via command line not working

### ISSUE THREAD

**Issue by sayakc5** [hashicorp/consul#6415]
Hello , 
Have couple of questions on Log rotation config provided by consul : 

1) I am trying to configure Log Rotation for a production cluster via command line argument

sudo su - $USER -c "nohup $CONSUL_PATH/consul agent -ui -config-file $CONSUL_CONFIG_FILE -log-rotate-duration 30s > $CONSUL_LOG_PATH

I have tried all possible combinations like : 
-log-rotate-duration=30s
-log-rotate-duration '30s'
-log-rotate-duration "30s"

Everytime I get an exception in the log : 
==> error parsing flags: flag provided but not defined: -log-rotate-duration
Much appreciate any help on this , I am stuck since a long time on this.

2) As per consul documentation , it provides configs like 
-log-rotate-duration , -log-rotate-max-files , -log-rotate-bytes
These all are command line arguments , are there any alternative for this which i can provide in Configuration File , I want to avoid command line arguments.

Please note i am using consul-linux-1.0.5 version for my requirement.

**Comment by i0rek** [comment]
@sayakc5 thanks for reporting! Could you verify this issues still exists with the latest version?

**Comment by sayakc5** [comment]
@i0rek Thanks for the pointer 
==> error parsing flags: flag provided but not defined: -log-rotate-duration
This error is no longer seen , but the logs are not getting rotated.

sudo su - $USER -c "nohup $CONSUL_PATH/consul agent -ui -config-file $CONSUL_CONFIG_FILE -log-rotate-duration 30s > $CONSUL_LOG_PATH 2>&1 &"

sudo su - $USER -c "nohup $CONSUL_PATH/consul agent -ui -config-file $CONSUL_CONFIG_FILE -log-rotate-bytes 1024 > $CONSUL_LOG_PATH 2>&1 &"

I see only one log file getting generated and the size is increased continuously.

**Comment by s-christoff** [comment]
Re-opening and allowing stale bot to take its course. Apologies about this :)

**Comment by rboyer** [comment]
Consul log rotation only applies if the agent is in control of the output files by use of the `-log-file` argument or `log_file` config setting. All of the logging related flags  `-log-rotate-bytes`, `-log-rotate-duration`, and `-log-rotate-max-files` only function if `-log-file` is configured, otherwise they are ignored.

If you want to have older files deleted there is a separate flag to control that called [-log-rotate-max-files](https://www.consul.io/docs/agent/options.html#_log_rotate_max_files):

```
-log-rotate-max-files - to specify the maximum number of older log file
archives to keep. Defaults to 0 (no files are ever deleted). Set to -1 to
disable rotation and discard all log files.
```

It doesn't look like you are configuring that setting, and since it defaults to zero, even if you started configuring `-log-file` it would not delete older log files unless you adjust that setting as well.

One thing I noticed when poking around the docs, all of the flags have config setting variants, but we don't actually document them all on the website which I'll open a followup PR to expose.

**Comment by rboyer** [comment]
The documentation will be updated in https://github.com/hashicorp/consul/pull/6705
