### ISSUE TITLE
How to run Consul as systemd service ?

### ISSUE THREAD

**Issue by debjitk** [hashicorp/consul#6469]
How do i run Consul as a systemd service on centos 7 ?

**Comment by blake** [comment]
Hi @debjitk, this is documented in the Consul deployment guide under [Configure systemd](https://learn.hashicorp.com/consul/datacenter-deploy/deployment-guide#configure-systemd).

After you've created the Consul service file, run `systemctl daemon-reload` so that systemd can discover the new service. Then start the service with `systemctl start consul`. Optionally enable the service to start at boot with `systemctl enable consul`.
