### ISSUE TITLE
consul and zookeeper have conflict?

### ISSUE THREAD

**Issue by mmcLine** [hashicorp/consul#6473]
consul,zookeeper ,dubbo. Can i use it together?

service is register success,but Consumers fail to find :

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commodityTypeController': Injection of @com.alibaba.dubbo.config.annotation.Reference dependencies is failed; nested exception is java.lang.IllegalStateException: Failed to check the status of the service cn.lamic.chagoi.service.CommodityTypeService. No provider available for the service cn.lamic.chagoi.service.CommodityTypeService from the url zookeeper://localhost:2181/com.alibaba.dubbo.registry.RegistryService?anyhost=true&application=order-provider&bean.name=ServiceBean:cn.lamic.chagoi.service.CommodityTypeService&check=false&default.timeout=5000&dubbo=2.0.2&generic=false&interface=cn.lamic.chagoi.service.CommodityTypeService&methods=findAllByStoreid&pid=269604&register.ip=169.254.19.230&remote.timestamp=1568160320666&side=consumer&timestamp=1568160345515 to the consumer 169.254.19.230 use dubbo version 2.6.7

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
