### ISSUE TITLE
Consul UI cuts off the address of the service if the address is long

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul#6529]
**New UI**
Consul version: `1.6.0`

**Describe the problem you're having**
If the service address is a CNAME, depending on the length of the address, UI could cut off part of the name and the port. In the screenshot below, the full address is `a07fab05ddca911e997eb02853705779-883125298.us-east-2.elb.amazonaws.com:80`, but in the UI I can only see `a07fab05ddca911e997eb02853705779-883125298`.

<img width="1674" alt="Screen Shot 2019-09-21 at 1 19 55 PM" src="https://user-images.githubusercontent.com/10640505/65447014-81b94800-ddea-11e9-9c07-f856e309a712.png">

When I click on the service address, it takes me to the service instance page, which also doesn't any address information.

<img width="1680" alt="Screen Shot 2019-09-23 at 10 20 53 AM" src="https://user-images.githubusercontent.com/10640505/65447631-d9a47e80-ddeb-11e9-8976-a42ebd633bd8.png">

**Describe the solution you'd like**
I would like to have a way see a full address of the service.

**Share inspiration**
We could show that the name of the service is cut off in the `services/:service` view by appending `...` to it, but always show a full service address on the service instance page.

**Comment by johncowen** [comment]
Hey @ishustava 👋 

Thanks for pointing this out, it's good to get some fresh eyes on it!

I think we'd probably want to continue truncating the address in some way in any listing views (if there isn't enough room). But I definitely agree we should add this to the 'detail' page.

My thinking being:

Generally I think the listing views should be a way to either get somewhere, or to find something out amongst lots of similar things.

So to explain further when I say 'get somewhere', the listing should show enough information to distinguish between one 'item' and another so you can click on it to see the full details for this 'item'. We are never going to be able to show all the information for an 'item' in a single row. So we have to be careful what we try and show there, me personally I'd rather show the minimum in order to 'get somewhere'.

When I say 'find something out amongst things' (not the best phrase I know! 😆 ) I mean for example healthchecks. It's useful to be able to see the overall state of your Consul install in one place so its handy to have this information for every service in a listing.

Looking at addresses of services, considering we distinguish services by their service names, the name gives us a way to distinguish one 'item' from another, and I can't really think of a usecase where you'd like to see all addresses of all services in order to compare or see an overall status of the addresses in relation to each other.

So really, I'd say `address` belongs on the detail page (and it's not at the moment!). It is easier to grab the addresses from the listing page also, which saves you a click. But if I was asked to say what things require the most room in these rows I'd say the service name and the checks, everything else should make room for those or just not be there at all.

We did have some ideas a while back for making it easier to get to multiple 'details' pages faster, so maybe we can discuss picking that back up again.

I'm going to mention this to the rest of the team and see what they think.

👍

**Comment by ishustava** [comment]
Thank for such a detailed explanation @johncowen 😃 🙇‍♀! This makes a lot of sense to me.

**Comment by johncowen** [comment]
Hey @ishustava 👋 

I think this is all covered now in the 1.8.0 release, so I'm going to close this.

Thanks,
