### ISSUE TITLE
watch service，how to return only the service that was added and deleted？

### ISSUE THREAD

**Issue by lddlww** [hashicorp/consul#6549]
i use watch sdk ，to listen service modify：
when i add one service ，the watch sdk return all services，how can i know the new service info？

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
