### ISSUE TITLE
Consul Server Cluster behind AWS Application Load Balancer with AWS ECS

### ISSUE THREAD

**Issue by aashitvyas** [hashicorp/consul#6560]
Hi.

We are migrating from AWS EC2 Stand alone instances to AWS ECS Containers and having some thoughts or questions as to why we use AWS Application Load balancer in front of our Consul Server Cluster (3 or 5 Nodes )

As far as I can see the setup we have, Load Balancer serves the purpose of having static DNS name to all the server nodes to hit the Consul UI.

The Static DNS name of LB is getting mapped  in route 53 and route 53 entry is getting called through Nginx via upstream http server.

The above setup gives us the access to the Consul UI as generic url like ( http://thisisexampleurl:9010 ) to external people like us to monitor the Dashboard time to time.

Other then that there is no real purpose the LB balancer serves as its Internal facing one and doesn’t really get hit by any other request as we are using the Consul for Service Discoveries.

I am curious to know what’s the best practice over here ? What are the pros and cons of using the LB in front of our Consul Server cluster other then having static DNS entry mapping ?

Please give me suggestion to some other resources or channels to post this if this is not the correct one.

Thanks.
Ash

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
