### ISSUE TITLE
Vault and Consul TLS configuration using private PKI

### ISSUE THREAD

**Issue by bmonteiro** [hashicorp/consul#6589]
Hi, It is possible to configure a Vault cluster using Consul with TLS but using a private CA so we can reuse the enterprise private PKI and do not create a separated CA just for Vault and Consul TLS.
Thx!

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
