### ISSUE TITLE
how to create the policy that allowed others can login the ui and see some key/values what i want  he see?

### ISSUE THREAD

**Issue by happywzy** [hashicorp/consul#6603]
1.when i create token include the policy,
`service_prefix "" {
  policy = "read"
  }`
this policy allow me see all the services

2.when i use the policy,
`service "consul" {
    policy = "read"
  }`
this policy allow me see  the services of "consul"

3.in the same way to the node!!!

4.but it don't work to key/values!!!!!

5. when i  use the policy,
`key_prefix "" {
  policy = "read"
  }`
it allowed the people see all the k/v

6. when i use the policy,
``key "hello" {
  policy = "read"
  }``
it not work , and i can't login the ui  in key/values!!

**Comment by happywzy** [comment]
![EA64EE9F-D251-4687-AAD9-198686A57124](https://user-images.githubusercontent.com/26290710/66465041-b13aa680-eab2-11e9-921f-b23fbbedc11d.png)
![43C45889-C887-43ff-B359-1EF0D1AE8F89](https://user-images.githubusercontent.com/26290710/66465054-b4ce2d80-eab2-11e9-98a2-0a967c1683a0.png)
![4DC56BBD-A868-4208-9788-A55CBDB0878F](https://user-images.githubusercontent.com/26290710/66465059-b7308780-eab2-11e9-9cac-8fe343e51828.png)
![A5A66F05-0836-4415-A93E-2C6FA83136CD](https://user-images.githubusercontent.com/26290710/66465069-ba2b7800-eab2-11e9-9f8f-8886032986b8.png)

**Comment by johncowen** [comment]
Hi @happywzy !

I'm guessing what you go to the KV root of the UI (`/ui/dc-name/kv`) you get a 403 error. This is probably because the user doesn't have access to KV root itself. If you go directly to `/ui/dc-name/kv/hello` by typing in that URL into your browser, I'm guessing your user will be able to see that `hello` KV.

More generally:

Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum](https://discuss.hashicorp.com/c/consul):

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
