### ISSUE TITLE
[Question] Is it possible to change RegisterOptions

### ISSUE THREAD

**Issue by marti1125** [hashicorp/consul#6612]
I get this error when try get new key/value from folder consul.watch

 [ERR] consul.watch: Watch (type: keyprefix) errored: Unexpected response code: 524, retry in 5s

Is it about Long Polling?

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
