### ISSUE TITLE
Spring Cloud service does not register with Consul

### ISSUE THREAD

**Issue by xBentu** [hashicorp/consul#6648]
I miss posted on the wrong product and not sure if this will work, but I am linking the issue I posted yesterday.

https://github.com/consul/consul/issues/3774#issue-508645444

**Comment by rboyer** [comment]
This project (`hashicorp/consul`) is for tracking issues related to the Consul Agent and CLI tool maintained by HashiCorp.

Your question appears to be a question about use of the [spring-cloud-consul](https://github.com/spring-cloud/spring-cloud-consul) Java 3rd-party library which lives elsewhere and is maintained by others. I'm closing the issue here and suggesting that you pose your question to the spring-cloud-consul project's maintainers who can better help you.
