### ISSUE TITLE
Unable to integrate nomad server into consul

### ISSUE THREAD

**Issue by mwantia** [hashicorp/consul#6670]
Hello,

I'm currently trying to deploy a new test environment to set up consul in combination with ACL.
The bootstrap for ACL was successful and I was able to add the first policy for the consul agents given the following guide: https://learn.hashicorp.com/consul/security-networking/production-acls

Unfortunately, I’m unable to implement the existing nomad server’s because they have no permission to register the services.
I’m currently unable to find any information regarding the needed configuration for the new policies that are required so that the nomad servers have to permissions to register.

I already searched the documentations for consul and nomad but couldn’t find anything about this kind of setup.

**Comment by s-christoff** [comment]
Howdy,

Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

Clarification questions that may be helpful when submitting this to the Nomad community forums:
- What does your current Consul stanza look like, and are you using the [`token` field?](https://www.nomadproject.io/docs/configuration/consul.html#token)

- [Nomad Forum](https://discuss.hashicorp.com/c/nomad)
- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
