### ISSUE TITLE
ACL Not Restricting Node From Registration

### ISSUE THREAD

**Issue by dibyajyotiron** [hashicorp/consul#6671]
#### Overview of the Issue

I have an acl token that has this following policy:
```
key_prefix "therm/" {
  policy = "write"
}
service_prefix "therm" {
	policy = "write"  
}
node_prefix "client-therm" {
  policy = "write"
}
```
In consul server, (acl.default_policy = "deny") is used.
Now, with the aforementioned node_prefix, I expect the client with that policy attached token to register node that has client-therm prefix in the name, but in reality, it can register with any node name. I want to mitigate this behaviour.
Previously, the node was registered with "client-therm" prefix, but for testing I changed the name today of the node to be the ip address and it still rejoined the serf lan, ```serf: EventMemberUpdate: IP:<x.x.x.x>```
### Consul Version 
1.6.1 in client and in server.
### Consul info for both Client and Server

**Comment by mkeeler** [comment]
Thanks for the report. We are investigating the issue and will respond more in the future.

**Comment by mkeeler** [comment]
@dibyajyotiron 

ACLs are applied at the Consul HTTP / RPC API layer.  The underlying Serf/Gossip layers are not ACL aware, and at this time we recommend using [gossip encryption](https://www.consul.io/docs/agent/encryption.html#gossip-encryption) to allow only authorized nodes with the encryption key to join the cluster and auto-register.  We will continue to investigate ways to improve our security posture but for now this is known and expected behavior.

**Comment by dibyajyotiron** [comment]
I'm using gossip encryption but I'm applying ACL at service registration to clients on node level. So that should be possible if the I've understood the docs properly. So isn't that desired?
