### ISSUE TITLE
Reload Config Entries (Connect)

### ISSUE THREAD

**Issue by Birmania** [hashicorp/consul#6703]
#### Feature Description

Currently, we can bootstrap router/resolver/splitter configuration entries on Consul Leader Election.
On new Leader Election, if config entry already exists, bootstrap file content is ignored.
It could be interesting to add a "version" attribute in the configuration file to reload configuration if version is higher or allow to reload the configuration entries from file on "Reload" CLI command.

#### Use Case(s)

In our situation, we have Consul Server built into an AWS AMI with Consul Connect configuration entries directly in the image. When we want to modify the behavior of the Consul Connect on existing services, we have to build a new image with new configuration bootstrap and modify the configuration manually on the consul cluster. (Write config for each service with CLI)
We would like to reduce the work load, only terminating each old instance of the cluster (which would be relaunched through ASG) in order to load the new version of the configuration entries.

Yours faithfully

**Comment by banks** [comment]
The bootstrapping from config file is really just a setup convenience while bootstrapping an environment but the source of truth for those entries must be in the state store once the cluster is up.

Reloading from file is problematic because then it's unclear whether the file or the content in raft is authoritative. For example if a tool has modified those via the API we don't know if the file contents is preferred or not. (I guess you understand this from the suggestion, just explaining for context for others who come across this).

One possibility we discussed was to have a separate flag in config which effectively claims the ConfigEntries defined there are authoritative. Then we'd not allow API modification for them. That or your version suggestion is feasible (although they'd not really be "bootstrap" in that case and would need to move up a level) but is quite a bit of work for something that was only meant to be a convenience mechanism during bootstrap in the first place. Managin them through server config files feels like a clunky solution to try and optimize for further because of all the issues - versioning to avoid API write conflicts, needing to keep all server config files in perfect sync otherwise it's not deterministic which is used etc.

The ideal way to manage ConfigEntries is via the API. If you want to keep them in code (a good plan!) then the best way to manage that is to use Terraform to mange them which solves all those "source of truth" and diffing and auditing etc. problems much better than server config file wrangling - we added support for ConfigEntries recently in our Terraform Provider. https://www.terraform.io/docs/providers/consul/r/config_entry.html

I suggest in your case you switch to not encoding the entries in your AMI image but supplying them at runtime using a configuration management solution or Terraform or similar. If you don't already have something like this, a simple bash script that calls `consul config write` with an on-disk file loaded from somewhere in the AMI startup will also work well.

Does this help?

**Comment by Birmania** [comment]
Hi @banks,

Thanks a lot for this complete answer which really help us, including a bit of Consul Point of View which is very interesting !

We followed your advices and get the Consul Config Entries out of Consul AMI. However, we did not used the Consul Terraform Provider as our Consul Cluster is in a private subnet which is not directly available from the hosts where we run Terraform (Waiting for this feature : https://github.com/hashicorp/terraform/issues/8367).
To update the Consul Config Entires, we created an AWS Lambda which read config entries from an S3 and apply them to Consul Cluster (using python-consul2).

Do you think that we can close this issue or you need to keep it open for a potential modification of server bootstraping behavior ?

Yours faithfully

**Comment by banks** [comment]
> To update the Consul Config Entires, we created an AWS Lambda which read config entries from an S3 and apply them to Consul Cluster (using python-consul2).

That sounds like a great solution!

> Do you think that we can close this issue or you need to keep it open for a potential modification of server bootstraping behavior ?

I'll close as we have noted the possible desire to manage them in config elsewhere but are not for now planning to do that, thanks for following up!
