### ISSUE TITLE
Concise approach to register with check and unregister

### ISSUE THREAD

**Issue by sweetodev** [hashicorp/consul#6733]
The current code I've is very verbose, can you provide a feature to register the service and check at the same, and then unregister simply removes both check and the service itself.

#### Feature Description

Here's the code.

```
let service = {name: env.CONSUL_ID, id: require('crypto').randomBytes(6).toString('hex')};
let check = {
    http: "http://" + require("os").hostname() + ":" + env.NODE_PORT + "/health",
    interval: "15s",
    name: service.name,
    id: service.id
};

let consul = require("consul")({host: env.CONSUL_HOST, port: env.CONSUL_PORT});

Promise.resolve()
    .then(function () {
        return new Promise(function (fulfilled) {

            let intervalId = setInterval(function(){

                consul.agent.service.register(service, function (error) { // service register
                    if(error) return console.log(error.toString());
                    ["exit", "SIGINT", "SIGHUP", "SIGTERM", "SIGQUIT", "SIGUSR1", "SIGUSR2"].forEach(function(value){
                        process.on(value, function(){ // exit close, SIGINT - SIGHUP ctrl+c, SIGTERM kill pid (nodemon restart)

                            consul.agent.check.deregister(check, function(error) { // check deregister
                                if (error) console.log(error.toString());
                                consul.agent.service.deregister(service, function(error) { // service deregister
                                    if (error) console.log(error.toString());
                                    process.exit(1);
                                });
                            });

                        });
                    });
                    clearInterval(intervalId);
                    fulfilled();
                });

            }, 3000);
        });
    })
    .then(function () {
        return new Promise(function (fulfilled) {
            consul.agent.check.register(check, function(error) { // check register
                if (error) console.log(error.toString());
                fulfilled();
                resolve();
            });
        });
    });
```

**Comment by blake** [comment]
Hi @sweetodev,

The Consul API supports defining checks while registering a service (https://www.consul.io/api/agent/service.html#register-service). Associated health checks are removed when the service is de-registered (https://www.consul.io/api/agent/service.html#deregister-service).

Based on your code example it looks like you're using https://github.com/silas/node-consul. The docs indicate [consul.agent.service.register](https://github.com/silas/node-consul#agent-service-register)() takes a `check` parameter, which should be what you're looking for. If that doesn't work, I recommend opening an issue in their repo to report the bug.

**Comment by sweetodev** [comment]
ok great. so I can register and provide the endpoint at the same time, and upon deregister it will remove both check and the service. Is silas/node-consul officially supported?

Another question, if multiple nodes are registered against a service, does consul load balance between them? 

I've also seen consul-template reading that data and generating routes for a reverse proxy like Nginx.

**Comment by blake** [comment]
Hi, silas/node-consul is a third-party SDK which is not officially supported by HashiCorp.

When querying the DNS interface, Consul will randomize the response values so that traffic is distributed to different nodes. The HTTP API returns all nodes for a given service. You would need to implement logic in your program to balance requests among the returned hosts.

Check out this guide, [Load Balancing with NGINX and Consul Template](https://learn.hashicorp.com/consul/integrations/nginx-consul-template), which walks through this exact use case of using consul-template to generate configs for nginx.

**Comment by sweetodev** [comment]
Thanks for the link, I'd go through it, what I'm missing is a docker based implementation which I'm unable to find any for consul-template and nginx. Let's say I've. Am I missing something here?

**server/upstream.conf.ctmpl**

```
{{range services}} {{$name := .Name}} {{$service := service .Name}}
upstream {{$name}} {
      least_conn;
      keepalive 32;
      zone upstream-{{$name}} 64k;
      {{range $service}}server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;
      {{else}}server 127.0.0.1:65535; # force a 502{{end}}
}
{{end}}
```

**Dockerfile**

FROM hashicorp/consul-template:alpine as template

FROM nginx

COPY --from=template /service/upstream.conf.ctmpl /bin/consul-template

**docker-compose**

  service:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - 8080:80

**Comment by sweetodev** [comment]
by the way why do you have to prepend `/v1` to the routes? 

if your implementation changes so is the version number of the binary and users can pick appropriate binary instead of prepending version number to the urls.

**Comment by blake** [comment]
> by the way why do you have to prepend `/v1` to the routes?
> 
> if your implementation changes so is the version number of the binary and users can pick appropriate binary instead of prepending version number to the urls.

 In multi-user environments, the person(s) maintaining the Consul cluster (i.e., the operators) and upgrading the binaries are often not the same as those who are writing code against the APIs (i.e., developers). We strive to maintain compatibility between minor version releases. The `/v1` signifies a major revision of the API (https://www.consul.io/api/index.html#version-prefix). If the API undergoes a large refactor, we would introduce a new prefix to signal to developers that the API has significantly changed & they should in turn expect that significant code changes will be required to interface with the new version.

With that said, I wanted to raise that Issues on GitHub for Consul are intended to be related to bugs or feature requests. We recommend using our other community resources for other issues instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://learn.hashicorp.com/consul)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

The forum would be the better place to continue the discussion regarding how to use consul-template in Docker.

Best regards,

Blake
