### ISSUE TITLE
Gossip

### ISSUE THREAD

**Issue by dzyand** [hashicorp/consul#6735]
How does Gossip work in SWIM?
Just for transmission？ 
And where is the relevant source code？
Thank you for your reply！

**Comment by s-christoff** [comment]
For Gossip related information check out the following:
- [Memberlist](https://github.com/hashicorp/memberlist), our implementation of SWIM
- [The SWIM paper](https://ieeexplore.ieee.org/document/1028914)
- [Armon's talk on SWIM ](https://www.youtube.com/watch?v=bkmbWsDz8LM)(I would recommend doing this one first, it's a really awesome talk)


Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
