### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by dzyand** [hashicorp/consul#6757]
How to deploy 128 Consul agents （the Lifeguard paper）are  **in a single Linux VM**？
In other words,How to make Lifeguard experiment with consul？Start an agent in a terminal，Using different ports to manually start 128 agents in 128 terminals？
Thank you for you reply！

**Comment by rboyer** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
