### ISSUE TITLE
Does every consul watch create a separate file descriptor?

### ISSUE THREAD

**Issue by kant111** [hashicorp/consul#6763]
Does every consul watch create a separate file descriptor?

How many consul watches are too many?

If I have a watch on a keyprefix does consul do something like a table scan or does it have some index?

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
