### ISSUE TITLE
Bad documentation on heroku installation

### ISSUE THREAD

**Issue by mauroprosperi** [hashicorp/consul#6766]
the seccion 6 that says;```Now, generate a secret key and save it to an ENV variable named SECRET_KEY_BASE using```

and shows this code ```  heroku config:set SECRET_KEY_BASE=`ruby -rsecurerandom -e "puts SecureRandom.hex(64)" ```

has an error on the ``` =` ``` 

should be the password ruby? then it would be ``` heroku config:set SECRET_KEY_BASE='ruby' -rsecurerandom -e "puts SecureRandom.hex(64)" ```

I saw tons of this kind of error on the documentations making it really hard to install consul, the tree of installation should  be reworked as well

**Comment by cricket007** [comment]
Seems it is missing an ending backtick, not at <code>=`</code>

Probably needs to be

```
heroku config:set SECRET_KEY_BASE=`ruby -rsecurerandom -e "puts SecureRandom.hex(64)"`
```

or 

```
heroku config:set SECRET_KEY_BASE=$(ruby -rsecurerandom -e "puts SecureRandom.hex(64)")
```

**Comment by blake** [comment]
Hi, I realized this issue is actually referencing https://docs.consulproject.org/docs/english-documentation/introduction/servers/deploying-on-heroku. This is a separate project which is not owned by HashiCorp, and is different from https://consul.io (the project for this repo).

The correct repo to file this issue is https://github.com/consul/docs, and the file you'll want to reference is https://github.com/consul/docs/blob/master/es/installation/deploying-on-heroku.md.

Hope this helps.
