### ISSUE TITLE
Register services in consul cluster

### ISSUE THREAD

**Issue by vacheli** [hashicorp/consul#6774]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here if you have a question.

- Frequently asked questions: https://www.consul.io/docs/faq.html
- Consul Guides: https://www.consul.io/docs/guides/index.html
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

Hi, I was install a consul cluster in kubernetes.
/ # consul members
Node      Address               Status  Type    Build  Protocol  DC   Segment
consul-0  192.168.119.125:8301  alive   server  1.5.3  2         dc1  <all>
consul-1  192.168.70.73:8301    alive   server  1.5.3  2         dc1  <all>
consul-2  192.168.16.118:8301   alive   server  1.5.3  2         dc1  <all>

Question1:
I register a service to consul by  /v1/agent/service/register API,but have just only data on a node,Other Node no service data.

{
    "ID": "ABC100",
    "Name": "A",
    "Tags": [
        "A100"
    ],
    "Meta": {
        "bk_host_name": "node35.ecs-95f2novalocal",
    },
    "Port": 6443,
    "Address": "192.168.1.100"
}

------------------------------------------------------------------
Question2:
I attempted to use /v1/catalog/deregister api to register a service, but appear 
" agent: Deregistered service "redis1_100"

{
  "Datacenter": "dc1",
  "Node": "consul-0",
  "Address": "192.168.119.125",
  "NodeMeta": {
    "somekey": "somevalue"
  },
  "Service": {
    "ID": "redis1_100",
    "Service": "node_other",
    "Tags": [
      "primary",
      "v1"
    ],
    "Address": "127.0.0.1",
    "Meta": {
        "redis_version": "4.0"
    },
    "Port": 9100
  }
}

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
