### ISSUE TITLE
[ERR] dns: rpc error: No cluster leader

### ISSUE THREAD

**Issue by rainkidpk** [hashicorp/consul#6783]
Hi
I have problem with consul cluster, this is my config on server1:
{
    "bootstrap_expect": 2,
    "client_addr": "0.0.0.0",
    "datacenter": "Us-Central",
    "data_dir": "/var/consul",
    "domain": "consul",
    "enable_script_checks": true,
    "dns_config": {
        "enable_truncate": true,
        "only_passing": true
    },
    "enable_syslog": true,
    "encrypt": "xxxxxxxxxxxxxxxxxx",
    "leave_on_terminate": true,
    "log_level": "INFO",
    "rejoin_after_leave": true,
    "server": true,
    "start_join": [
        "172.18.12.2xx",
        "172.18.12.1xx"
    ],
    "ui": true
}

and this is my config on server 2:
{
    "bootstrap_expect": 2,
    "client_addr": "0.0.0.0",
    "datacenter": "Us-Central",
    "data_dir": "/var/consul",
    "domain": "consul",
    "enable_script_checks": true,
    "dns_config": {
        "enable_truncate": true,
        "only_passing": true
    },
    "enable_syslog": true,
    "encrypt": "xxxxxxxxxxxxxxxxxx",
    "leave_on_terminate": true,
    "log_level": "INFO",
    "rejoin_after_leave": true,
    "server": true,
    "start_join": [
        "172.18.12.1xx",
        "172.18.12.2xx"
    ],
    "ui": true
}

when i run consul on server 1 , i receive error:
 "2019/11/13 16:56:16 [WARN]  raft: no known peers, aborting election
    2019/11/13 16:56:18 [ERR] agent: failed to sync remote state: No cluster leader
    2019/11/13 16:56:18 [ERR] dns: rpc error: No cluster leader
    2019/11/13 16:56:18 [ERR] dns: rpc error: No cluster leader
    2019/11/13 16:56:18 [ERR] dns: rpc error: No cluster leader
    2019/11/13 16:56:19 [ERR] dns: rpc error: No cluster leader"
and i run consul on server 2, i receive error form server 1:
"[ERR] memberlist: failed to receive: No installed keys could decrypt the message from=172.18.12.2xx"

i don't understand about this error?

can you help?
sorry for my english

**Comment by crhino** [comment]
Two potential ideas we have immediately.

1) Do not have 2 (or any even numbers) Consul servers, 3 is much better. Consul requires a majority quorum of all servers in order to elect a leader and make progress. By having 2 servers, if either 1 goes down, the whole cluster will go down. See [these docs](https://www.consul.io/docs/internals/consensus.html#deployment-table) for more details
2) Make sure that the value in the `encrypt` field is **the same** between all Consul agents. There are some subtle details involving the encryption key, refer to the [-encrypt](https://www.consul.io/docs/agent/options.html#_encrypt) flag documentation for more details.

For future reference, issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
