### ISSUE TITLE
Support TLS 1.3 in Go 1.13.x

### ISSUE THREAD

**Issue by zeroflaw** [hashicorp/consul#6784]
#### Feature Description

TLS 1.3 is available on an opt-out basis in Go 1.13. When Consul is updated to use the 1.13.x version of Go will the application be updated to support TLS 1.3? 

https://golang.org/pkg/crypto/tls/

#### Use Case(s)

Builtin HTTPS Health checks fail if the minimum TLS version for a service is 1.3, it would be nice not to have to use an external python script in these circumstances

**Comment by banks** [comment]
Thanks for creating the issue @zeroflaw. We'd love to support TLS 1.3 once we upgrade and I'm not aware of any reason we'd opt out of that at this point. We'll check of course there are no risks or compatibility issues present if we do.

The blocker for now though is that Go 1.13 broke some of our Go module support and tooling so that we can't actually build Consul with it just yet. It shouldn't be anything major but is the reason we've not already upgraded the Go version.

**Comment by benjarrell** [comment]
@banks Is there an issue to track Go 1.13 compatibility?

**Comment by banks** [comment]
There is now 😄 Thanks!
