### ISSUE TITLE
More strict constraints on service names/tags

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#683]
Since the DNS API will only be usable with service names which satisfy the constraints of DNS queries in general, we should probably think about how we can be more strict on service registrations to ensure that any registered service is accessible from all of our supported API's. This would be a backward-incompatible change, which makes it harder to support within the context of our compatibility promise.

See also:
https://github.com/hashicorp/consul/issues/294
https://github.com/hashicorp/consul-template/issues/187

**Comment by ryanuber** [comment]
This also reaches into constraints on service tags. It might be difficult to outright forbid dots, colons, etc in both service names and service tags.

**Comment by mitchellh** [comment]
I'm going to chime in here and say that due to backwards compatibility its probably not possible to outright reject these things. It might make more sense to simply turn it into a warning that is loud in the logs such as: `WARNING: Service name `%s` won't be discoverable via DNS due to invalid characters`. 

I'm sure there are production clusters out there where upgrading Consul would simply break things if we made it outright rejected and that would be quite scary...

**Comment by ryanuber** [comment]
Makes sense to me, rejecting would have been preferable from the beginning but not much we can do about existing clusters now.
