### ISSUE TITLE
consul watch: save command output to file

### ISSUE THREAD

**Issue by sl-ll** [hashicorp/consul#6861]
Hello, I'm trying to save a value of kv to file when it changed.
But get the next error

>  agent: watch handler '[consul kv get path/to/key/somekey > somefile]' output: Too many arguments (expected 1, got 4)

My watch configured as part of agent (if I run `consul watch -key path/to/key/somekey consul kv get path/to/key/somekey > somefile` it works fine)

>         "type": "key",
>         "key": "path/to/key/somekey",
>         "args": ["consul", "kv", "get", "path/to/key/somekey", ">", "somefile"]

If I change handler command like this, the error changes

> agent: Failed to run watch handler '[(/usr/local/bin/consul kv get path/to/key/somekey)> somefile]': exec: "path": executable file not found in $PATH

Maybe there's another way to save consul kv get output to file? 
Of course I can write dedicated shell script to make this staff, but as for me that is overhead when you already have consul command

**Comment by crhino** [comment]
Hey there.

The problem you are seeing is that the `args` array does not run the provided commands within a shell. If you prepend your `args` array with `["sh", "-c", "..."]`, like `[ "sh", "-c", "consul kv get foo/bar > /tmp/test" ]`. See [this Watches doc](https://www.consul.io/docs/agent/watches.html#executable) for more details.

For future reference, Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
