### ISSUE TITLE
Secondary CA Cert is generated twice during initialization

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#6886]
#### Overview of the Issue

During initialize of a secondary datacenters CA, it will do two rounds of CSR generation and RPCs to get it signed by the primary instead of 1.

The first is done here:
https://github.com/hashicorp/consul/blob/681767622322ae9a31b35e93bfb8d4c54a621509/agent/consul/leader_connect.go#L204

Then the `secondaryCARootWatch` routine is started and another one takes place here:

https://github.com/hashicorp/consul/blob/681767622322ae9a31b35e93bfb8d4c54a621509/agent/consul/leader_connect.go#L610

The root cause of this is that we are making no attempt to prevent certificate regeneration when the roots haven't changed. The `secondaryCARootWatch` routine starts initially with performing a non-blocking query which will return immediately with the same roots as the same RPC performed in `initializeCA`. 

This should be benign enough but maybe we want to fix it 🤷‍♂ 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Setup a primary datacenter with connect enabled.
1. Start a secondary datacenter with connect enabled.

**Comment by banks** [comment]
I think the issue is a little more subtle than described. I described it previously here after debugging for about a day: https://github.com/hashicorp/consul/issues/6771

> The root cause of this is that we are making no attempt to prevent certificate regeneration when the roots haven't changed.


Actually we do... The real issue is that our code uses the init routine in two places, in one place the "state" passed is the local state, in the replication routine it's the primary's state yet our "has it changed" check is done assuming the state is always the local state which means in replication case we are comparing the primary's keyID against the secondary's which will always fail and so cause another CA init round.
