### ISSUE TITLE
Catalog.Deregister  rpc error making call: Unknown check

### ISSUE THREAD

**Issue by celesteking** [hashicorp/consul#6947]
Got a strange error in log on client v1.6.2 when deregistering a service with a health check while supplying a token. The service and check are removed, but wtf?!

`$ curl -XPUT -H 'X-Consul-Token: xx'  http://127.0.0.1:8500/v1/agent/service/deregister/so-1-2-3-4`

```
   2019/12/13 19:11:00 [INFO] agent: Deregistered service "so-1-2-3-4"
    2019/12/13 19:11:00 [ERR] consul: "Catalog.Deregister" RPC failed to server 192.168.112.3:8300: rpc error making call: Unknown check 'service:so-1-2-3-4'
    2019/12/13 19:11:00 [INFO] agent: Deregistered check "service:so-1-2-3-4"
```

ACL for the token is:
```
service_prefix "so-" {
	policy = "write"
}
```
And the service check was:
```
# curl -H 'X-Consul-Token: xx'   http://127.0.0.1:8500/v1/agent/checks?pretty
{
    "service:so-1-2-3-4": {
        "Node": "xx",
        "CheckID": "service:so-1-2-3-4",
        "Name": "Service 'so-1-2-3-4' check",
        "Status": "passing",
        "Notes": "",
        "Output": "xx",
        "ServiceID": "so-1-2-3-4",
        "ServiceName": "so-1-2-3-4",
        "ServiceTags": [
            "xx"
        ],
        "Type": "script",
        "Definition": {},
        "CreateIndex": 0,
        "ModifyIndex": 0
    }
}
```

**Comment by crhino** [comment]
Hi @celesteking. This error is occurring because deregistering the service on the client agent will cause anti-entropy to attempt to delete both the service and associated checks from the server agent with different RPC calls. However, when anti-entropy deletes the service on the server agent, that will also delete the associated health checks. Thus, if the health check RPC deletion happens after, you will see this spurious error message. However, there is nothing going wrong within the Consul cluster.

We could definitely optimize this to not attempt to deregister health checks that have already been known to be deleted though.

**Comment by PumpkinSeed** [comment]
I have worked on a PR might be related #6619. Can I pick it up as well? I really like to work on this.

**Comment by shaqq** [comment]
@crhino Do you haven an approach that you'd recommend?

I'm new to the Consul codebase, but what I'm seeing is that the client agent itself assumes that the checks will be deleted along with the service if it's making an RPC request:

https://github.com/hashicorp/consul/blob/ca6e8662324afb33577b1266ef185e7acdf5d51f/agent/local/state.go#L1099-L1106

However, the local agent still needs to mark the checks as "deleted".

@PumpkinSeed's PR makes a few significant changes to how the agent holds state, so it might be worth holding off until their PR is in. However, it does not fix the core issue, since `SyncChanges` will still attempt to send the Catalog RPC request to deregister a check even after registering the associated service.

---

If we want to get a fix in before @PumpkinSeed's PR, a potential option is to update `SyncChanges` to filter out the CheckIds to be passed into `deleteCheck` if they appear in the services passed into `deleteService` earlier:

https://github.com/hashicorp/consul/blob/ca6e8662324afb33577b1266ef185e7acdf5d51f/agent/local/state.go#L1056-L1076

**Comment by crhino** [comment]
hi @shaqq , sorry for the wait and thanks for asking questions and doing research into this!

While I was refreshing myself on this issue, I found PR #6168 which looks to have fixed this issue already. Have you been able to reproduce this issue after this commit was added? I can do a test of this soon myself, but wondering if you already reproduced it or not?

**Comment by shaqq** [comment]
@crhino ah! yes, that indeed fixes the issue! my copy of master was old 😞

**Comment by crhino** [comment]
Thanks for the questions and enthusiasm though, let me know if there is any other issues you are interested in taking a look at!
