### ISSUE TITLE
Identify places to improve on docs INTERNALS.md

### ISSUE THREAD

**Issue by mkcp** [hashicorp/consul#7039]
As Consul has grown, [./contributing/INTERNALS.md](https://github.com/hashicorp/consul/blob/master/contributing/INTERNALS.md) there's certainly room to expand upon the various topics to expand resources for OS contributors and those onboarding to @hashicorp/consul  

A success-state for this ticket might be: identify individual tickets we'd like to improve on in INTERNALS.md or extract into independent articles with higher detail. If this ticket is still open in (throwing out an arbitrary number here) 6 months or so, and improvements have happened, then it will be safe to close out.

**Comment by mikemorris** [comment]
One thing that may be helpful is to clarify the focus of these docs - if they're intended to address implementation details someone developing Consul would need to know (directory structure, filename conventions, etc) versus architecture/protocol documentation which may be more relevant for https://www.consul.io/docs/internals/index.html with the intent of avoiding duplication of content.

**Comment by dnephin** [comment]
`contributing` has moved to https://github.com/hashicorp/consul/tree/main/docs and the `INTERNALS.md` doc was split up and moved into appropriate sections.

It now has table of contents and many sections labeled as "work in progress". The README also starts with an explanation of the purpose of the documentation. There are also more detailed documents written for a few of the sections.

There is still lots of work to do, but I believe this new structure makes it easier to contribute content. It's much more obvious now what content is missing, so we shouldn't need individual tickets for each piece. I'm going to close this issue as done since it's been over a year and we have made some progress.
