### ISSUE TITLE
IPv6 address inconsistencies

### ISSUE THREAD

**Issue by wido** [hashicorp/consul#705]
When using Consul over IPv6 there are a couple of inconsistencies

"bind_addr" has to be configured without [ and ] around the address:

"bind_addr": "2a00:f10:X:X:X"

But when joining a cluster you have to specify them:

consul join [2a00:f10:X:X]

It would be easier if this inconsistency would be resolved.

**Comment by ryanuber** [comment]
I think the reason for the difference here is that defining a bind address requires only the address, whereas doing a join might require an `<addr>:<port>` type of notation. in some cases. Since specifying `ip:port` format with IPv6 would be ambiguous without the brackets, we definitely need to keep them there for the join case. As for the bind_addr, I don't think it really makes sense to force the user to specify brackets if they are not allowed to also specify the port.

I think what we have now is the correct behavior, so I am going to close this.
