### ISSUE TITLE
Allow specifying initial state of a check

### ISSUE THREAD

**Issue by Heuriskein** [hashicorp/consul#706]
Discussion here:
https://groups.google.com/forum/#!topic/consul-tool/0VHOyA5X7js

There are times when it is useful to be able to transactionally set the initial state of a check, it would be nice if this were an additional parameter in agent/service/register and agent/check/register.

**Comment by mfischer-zd** [comment]
+1

**Comment by breedx** [comment]
+1 I have run into this when using HTTP check and registering service using `/v1/agent/service/register`.  The service will be in failed state until the HTTP interval has run its course for the first time, and the first check is done - I would like to be able to set initial state to passing like the `/v1/catalog/register` example.  The workaround is to have a low interval time, which isn't really a good workaround.

**Comment by nickwales** [comment]
+1 from my experience the opposite of what happens currently would be ideal. i.e. start in passing state unless told otherwise.

**Comment by ryanuber** [comment]
@nickwales we originally had checks register as healthy. The problem with that approach is that the service may appear healthy before its first health check has run, and then immediately fail. To err on the side of caution we flipped this so that API consumers with watches on services don't see a given service until it is confirmed healthy.

I think the best thing to do is keep the current defaults, but allow specifying an alternate initial state.

**Comment by armon** [comment]
Fixed by #859
