### ISSUE TITLE
 Improvements to `consul snapshot inspect` CLI command

### ISSUE THREAD

**Issue by ChipV223** [hashicorp/consul#7106]
#### Feature Description

Currently, the `consul snapshot inspect` CLI command outputs the snapshot size, raft index, raft term, and snapshot version of a particular snapshot file, but doesn't show counts for KV or ACL data. I noticed that @banks created a [separate inspection tool](https://github.com/banks/consul-snapshot-tool) that provides counts for this, so I believe that this tool can be integrated with the inspect command

#### Use Case(s)

For situations where users are running into memory issues with Consul, they can inspect the snapshots to see how much data Consul has stored in the catalog. The improvements to the command will be able to provide users precise data how much data(i.e, KVS entries, ACL data, etc) the cluster is processing

**Comment by banks** [comment]
This would be a nice contained smallish task that would provide a lot of value for operators!

I've not labelled it `good-first-issue` yet just because there may be some edges I've not thought about but I think this should be reasonably easy.

The biggest technical decisions to make here that can't just be copied from my tool are:
 1. How can we maintain that list of string record types in the future, making another place in `command/*` that needs updating if we add new record types is ugly and error prone. I don't think it would be too hard to do this where we define those types though so it's obvious they need updates.
 2. Output format for the table. We have precedent for more-than-two-column tables in Consul CLI so should probably try to make the output consistent with that which my tool is not.

**Comment by tpaschalis** [comment]
I'd like to pick this up if there's no objection. I'm not very familiar with consul, so it might take a few days. 

I'll read through how your tool works, and then I can start with implementing outputting the count of KVS entries. If it's deemed alright, I can do something similar for the rest of the metrics!

**Comment by mikemorris** [comment]
Done in https://github.com/hashicorp/consul/pull/8787

**Comment by mikemorris** [comment]
Initial implementation done in https://github.com/hashicorp/consul/pull/8787
