### ISSUE TITLE
Fault tolerance in service registration?

### ISSUE THREAD

**Issue by clusby** [hashicorp/consul#7285]
If I:
1. Register a service and health check on an agent (using http /agent/service/register)
2. Simulate a fault on the agent (ie kill -9)
Then the service and health check from that agent are failed|deregistered, even though the service itself is still running ok.

This matches my understanding based on the docs, eg:
https://www.consul.io/docs/agent/basics.html#lifecycle
https://www.consul.io/docs/internals/anti-entropy.html

What is the recommended approach to build in fault tolerance to our service discovery for clients?

Currently our service just registers itself on startup. Is it expected to also poll the catalog, detect it's missing and re-register itself? Is there a better approach?

I believe this is a common question - can we add a page to the FAQ describing approaches?

**Comment by i0rek** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here. This is the first time we’ve personally come across this question so it’s probably not appropriate for the FAQ right now - there are many other questions that come up way more often not in there. But if there are specific ways we can update the docs to help answer it then a specific issue for that would be welcome!

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
