### ISSUE TITLE
Service deregisters after a minute

### ISSUE THREAD

**Issue by rosmo** [hashicorp/consul#729]
Using consul 0.5.0 on 5 nodes (3 servers, 2 agents) and registering a service using the HTTP API:
```
PUT http://127.0.0.1:8500/v1/catalog/register
Content-Type: application/json
{"Datacenter":"dc1","Node":"my.node.address","Address":"10.1.187.15","Service":{"Service":"test-service","Tags":["frontend"]}}
```
After a minute or so:
```
Feb 23 17:52:16 my consul: 2015/02/23 17:52:16 [INFO] agent: Deregistered service 'test-service'
```
Member list says:
```
# consul members
Node                                       Address             Status  Type    Build     Protocol
my.node.address    10.1.187.15:8301  alive   server  0.5.0     2
my.node2.address      10.1.187.14:8301  alive   server  0.5.0  2
my.node3.address                      10.1.187.2:8301   alive   server  0.5.0  2
my.node4.address      10.1.187.11:8301  alive   server  0.5.0  2
my.node5.address  10.1.187.16:8301  alive   server  0.5.0     2
```
The node where the service add is executed is running in agent mode.

**Comment by armon** [comment]
@rosmo You want to make use of the /v1/agent/ endpoints instead of the /v1/catalog endpoints directly. What is happening is that the catalog endpoint registers with the servers, but the agent is unaware of the service. When it runs anti-entropy (roughly every minute), it notices the discrepancy and deletes the service.

**Comment by rosmo** [comment]
That solved the problem, thanks @armon.
