### ISSUE TITLE
Why CPU usage so high?

### ISSUE THREAD

**Issue by wenj1104** [hashicorp/consul#7312]
CPU usage as elow.
![image](https://user-images.githubusercontent.com/30981096/74712720-efff1b00-5261-11ea-8bbf-28c724801c85.png)

And so many error logs like below:
```
2020-02-18T07:17:18.286|ERRO|CTL|cache.getCommonPorts: Fail to parse - port=
2020-02-18T07:17:18.286|ERRO|CTL|cache.getCommonPorts: Fail to parse - port=
2020-02-18T07:17:18.286|ERRO|CTL|cache.getCommonPorts: Fail to parse - port=
2020-02-18T07:17:18.286|ERRO|CTL|cache.getCommonPorts: Fail to parse - port=
2020-02-18T07:17:18.286|ERRO|CTL|cache.getCommonPorts: Fail to parse - port=
...
```
consul version:
```
/ # consul version
Consul v1.5.1
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

Can some help me?

**Comment by wenj1104** [comment]
Did anyone meet the same issue?

**Comment by s-christoff** [comment]
Howdy @wenj1104, 

Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
