### ISSUE TITLE
AutoEncrypt for clients doesn't seem to be working

### ISSUE THREAD

**Issue by Legogris** [hashicorp/consul#7331]
I was following the docs (published only the other day) here to the T: https://learn.hashicorp.com/consul/day-2-agent-authentication/update-certificates

Configuring servers (manually copying over certs) worked fine, but auto encrypt on clients seems broken. Only the CA file is copied over and referenced, as stated in the guide.

Starting the client:

```
 ==> Starting Consul agent...
            Version: 'v1.7.0'
         Datacenter: 'dc1' (Segment: '')
             Server: false (Bootstrap: false)
        Client Addr: [X.X.X.X 127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
       Cluster Addr: X.X.X.X (LAN: 8301, WAN: 8302)
            Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: true, Auto-Encrypt-TLS: true
 ==> Log data will now stream in as it occurs:
     2020-02-21T08:18:07.719Z [WARN]  agent: "agent" token present in both the configuration and persisted token store, using the persisted token
     2020-02-21T08:18:07.721Z [ERROR] agent: Error starting agent: error="VerifyIncoming set, and no Cert/Key pair provided! AutoEncrypt only secures the connection between client and server and doesn't affect incoming connections on the client."
     2020-02-21T08:18:07.721Z [INFO]  agent: Exit code: code=1
 consul.service: Main process exited, code=exited, status=1/FAILURE

```

**Comment by i0rek** [comment]
Thank you for reporting! The guide is misleading. When using `auto_encrypt` on the clients, you cannot enable `verify_incoming`. On the client it would mean that your HTTPS endpoint would be verifying that the cert that is presented by a 3rd party is created by the auto_encrypt CA. Which is not possible since you cannot extract 3rd party certs from auto_encrypt.

Disabling `verify_incoming` on the client fixes your problem.
