### ISSUE TITLE
Unexpected response code: 500 (Failed to create boolean expression evaluator:

### ISSUE THREAD

**Issue by Megavolv** [hashicorp/consul#7338]
#### Overview of the Issue

Got error when using github.com/hashicorp/consul/api
Golang app.

(map[string]*api.AgentService) <nil>
(*errors.errorString)(0xc000013530)(Unexpected response code: 500 (Failed to create boolean expression evaluator: 1:4 (3): no match found, expected: "!=", ".", "==", "[", [ \t\r\n] or [a-zA-Z0-9_]))

#### Reproduction Steps

res, err := consul.Agent().ServicesWithFilter("foo")
No error if filter is empty

**Comment by mkeeler** [comment]
@Megavolv the string `foo` is not a valid filter. If you were trying to filter for a single service name then the correct filter would be `Service == "foo"`.

The filtering language is documented [here](https://www.consul.io/api/features/filtering.html) and that particular API client method will use [this endpoint](https://www.consul.io/api/agent/service.html#list-services). The list of fields available for filtering is documented in that section of the docs.

**Comment by pierresouchay** [comment]
@mkeeler for this kind for errors, it might be cool eventually to generate HTTP 400 instead of 500

**Comment by mkeeler** [comment]
@pierresouchay I totally agree. However since this error happens on the servers and not at the HTTP API it becomes hard to distinguish this error from any other RPC related error. Eventually it would be nice to have better typing of the errors that might come back via RPC, or potentially include extra information about the desired HTTP status code. For now though that kind of information isn't available. Its definitely something we should keep in mind though.
