### ISSUE TITLE
Service registration denied due to ACLs

### ISSUE THREAD

**Issue by lud4ik** [hashicorp/consul#734]
I use release 0.5.0
I create a token
```
curl -v -X PUT http://host:8500/v1/acl/create?token=adf4238a-882b-9ddc-4a9d-5b6758e4159e --data '{"Name": "service_name-token","Type": "client","Rules": "{\"key\":{\"service/service_name/leader\":{\"policy\":\"write\"}},\"service\": {\"service_name\":{\"policy\":\"write\"}}}"}'
```

When I register service with name service_name and id service_name-random-id I get error in log (using created token)
```
consul.catalog: Register of service 'service_name' on 'host' denied due to ACLs
```
acl_default_policy is set "deny", so rules must be whitelist.
What am I doing wrong?

**Comment by lud4ik** [comment]
Before I made requests with token parameter.
When I added acl_token to consul agent config, it started to work. Is it mandatory to specify token in agent and on making http requests?

**Comment by ryanuber** [comment]
Hi @lud4ik,
Consul 0.5 introduces service ACL's. There is an additional upgrade step you need to perform if the default policy is `deny`. Please see the [upgrade instructions for 0.5](https://consul.io/docs/upgrade-specific.html). If you still have problems just let us know!

**Comment by lud4ik** [comment]
I've read instructions.
I want to use token to register services.
But as I discribed, I create token with appropriate rules for service and only then try to register service with that token and it doesn't work.

**Comment by ryanuber** [comment]
I understand now - I think this may be an issue of the token not being passed through. I fixed a similar issue in #655. I'll take a look at this and update here.

**Comment by lud4ik** [comment]
Thanks!

**Comment by lud4ik** [comment]
Maybe reopen?

**Comment by ryanuber** [comment]
I've taken a cursory look into this. As expected, the token is not passed through. Since services and checks both are synced asynchronously to the catalog, only the locally configured agent token can be used to do the sync. Tagging as a bug, thanks!

**Comment by rockymtnlinux** [comment]
Given that you've already verified the bug, this may not be needed, but here's what I found in my testing:

1. Set acl_default_policy = deny.
2. Try to register test-service with anonymous token => fail ( expected ).
` curl -X PUT -d '{ "Name":"test-service","Port":8080 }' localhost:8500/v1/agent/service/register
2015/03/01 08:05:03 [WARN] consul.catalog: Register of service 'test-service' on 'smaug' denied due to ACLs
2015/03/01 08:05:03 [WARN] agent: Service 'test-service' registration blocked by ACLs`

3. Create test-write token with following policy:
`service "test-service" {
    policy = "write"
}`

4. Try to register test-service using test-write token:
`curl -X PUT -d '{ "Name":"test-service","Port":8080 }' localhost:8500/v1/agent/service/register?token=d0c4a74f-dc88-d7ca-d88b-30a7daa8c944
2015/03/01 08:05:25 [WARN] consul.catalog: Register of service 'test-service' on 'smaug' denied due to ACLs
2015/03/01 08:05:25 [WARN] agent: Service 'test-service' registration blocked by ACLs`

5.  Take the above policy, apply to the anonymous token, and register service the anonymous token => success.
`curl -X PUT -d '{ "Name":"test-service","Port":8080 }' localhost:8500/v1/agent/service/register
2015/03/01 08:07:11 [INFO] agent: Synced service 'test-service'`

6. Also, with the acl_default_policy set to deny, I deleted all policies from the anonymous token and the test-write token above and was still able to read the list of services.
`curl localhost:8500/v1/agent/services
{"consul":{"ID":"consul","Service":"consul","Tags":[],"Address":"","Port":8300},"test-service":{"ID":"test-service","Service":"test-service","Tags":null,"Address":"","Port":8080}}

curl localhost:8500/v1/agent/services?token=d0c4a74f-dc88-d7ca-d88b-30a7daa8c944
{"consul":{"ID":"consul","Service":"consul","Tags":[],"Address":"","Port":8300},"test-service":{"ID":"test-service","Service":"test-service","Tags":null,"Address":"","Port":8080}}`
