### ISSUE TITLE
v1/health/service ，   Is the services orderly？

### ISSUE THREAD

**Issue by FFFro** [hashicorp/consul#7361]
Is it in the order of service registration？

**Comment by pierresouchay** [comment]
I think, it is sorted by node name, but it is documented nowhere, so you should consider it random (it might change, while it is probably always the same order for a given server).

If you `near=` parameter (available for catalog/nodes and health), it might sort it according to computed round-trips to your servers, see https://www.consul.io/api/catalog.html#list-nodes, so that's predictable, but might change if estimated round trip changes
