### ISSUE TITLE
Alias check - referenced check not found behavior

### ISSUE THREAD

**Issue by oto313** [hashicorp/consul#7374]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description
Consul supports alias check which mirrors the state of a reference check. But in case the reference check does not exist the alias check is passing and the output message is "No checks found.". There could be an option for specifying behavior in such a situation. You could specify if it passes or fails.

There is already TODO in code: [alias.go](https://github.com/hashicorp/consul/blob/master/agent/checks/alias.go#L236)

#### Use Case(s)
In case you register services and checks (eg. one check and one alias check which points to the first check) and then deregister the referenced check which is used in alias check, the alias check is passing, even if the referenced check does not exist.

**Comment by pierresouchay** [comment]
@oto313 I looked a bit, it is a bit more complicated:

* A service without checks is valid and supposed to be Healthy
* The current system does not check about Service Existing

It means that:
* Consul should probably checks whether the service does exists
* if it does not, throw an error (such as "Service does not exists"), while keeping existing behavior (aka Passing if the service exists but has not health checks)

@rboyer Does it make sense (since you write the comment https://github.com/hashicorp/consul/blame/master/agent/checks/alias.go#L236 ) ?

**Comment by pierresouchay** [comment]
@oto313 Do you think my fix https://github.com/hashicorp/consul/pull/7384 make sense?
Would it fix your issue?

**Comment by pierresouchay** [comment]
Hello @danielehc,

I think this issue is not in status awaiting response since @oto313 has answered in my PR, saying it would probably fix the issue. Could a maintainer have a look at #7374?

This is a problem we also have on our side
