### ISSUE TITLE
Can I install it on raspberry pie 3B+

### ISSUE THREAD

**Issue by landonzeng** [hashicorp/consul#7408]
Can I install it on raspberry pie 3B+,
After using the command: uname - m, the system displays the following information:armv7l
Which version of file should I use

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

**Comment by mkeeler** [comment]
You should be able to use the armhf v6+ binary. If you see errors when attempting to run (I don't believe you should) then please open a new issue.

**Comment by hvindin** [comment]
I have a 12 pi 3B+ consul cluster running now with consul humming along nicely, I just grabbed these ansible playbooks:
https://github.com/dockpack/ansible-consul

And haven't need to think about it more than updating the version every now and again in a while...

**Comment by landonzeng** [comment]
Thanks！
