### ISSUE TITLE
signing up  service but not show passing immediately?

### ISSUE THREAD

**Issue by conansoft** [hashicorp/consul#7409]
When signing up for a new service(the service had online), the health check status is critical,It may take a few seconds for the display to passing,I don't know why not immediately show passing.

**Comment by pierresouchay** [comment]
This is documented: https://www.consul.io/docs/agent/checks.html#initial-health-check-status

**Comment by s-christoff** [comment]
Seems like @pierresouchay covered this one (thanks!) - but for future reference: 

Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

**Comment by conansoft** [comment]
> This is documented: https://www.consul.io/docs/agent/checks.html#initial-health-check-status

thanks
