### ISSUE TITLE
Unstable client confuses cluster

### ISSUE THREAD

**Issue by rotatingJazz** [hashicorp/consul#742]
A client running on a machine with connectivity issues was confusing the whole cluster causing leader elections and random flapping of clients/servers. Stopping the client made all the problems stop. Starting the client made the issues reappear. Reporting it for reference.

**Comment by armon** [comment]
This is a known issue. Let's leave this open as a thought ticket as to possible ways to mitigate this.

**Comment by sgargan** [comment]
Following up from https://groups.google.com/forum/#!topic/consul-tool/fk-z50J-ow4 

I went back through to see what was up with my failing client and it was being misconfigured with 0.0.0.0 as the advertise address. I re-enabled the client and the behavior mentioned starts, nodes start randomly failing with serf errors and an checks that were passing begin to fail. 

The nodes are all trying to contact the misconfigured node, (possibly are sending serf messages to themselves), this following log excerpt is illustrative of the failures

```
2015/03/23 20:21:11 [INFO] serf: EventMemberJoin: broken1.testing 0.0.0.0
2015/03/23 20:21:23 [INFO] agent: Synced check 'service:prod.supervisor'
2015/03/23 20:21:23 [INFO] serf: EventMemberFailed: broken1.testing 0.0.0.0
2015/03/23 20:21:23 [INFO] serf: EventMemberJoin: influx1.ops XXX.XX.32.143
2015/03/23 20:21:34 [INFO] memberlist: Marking auth.prod as failed, suspect timeout reached
2015/03/23 20:21:34 [INFO] serf: EventMemberFailed: auth.prod XXX.XX.1.39
2015/03/23 20:21:35 [INFO] serf: EventMemberJoin: auth.prod XXX.XX.1.39
2015/03/23 20:21:53 [INFO] serf: EventMemberJoin: broken1.testing 0.0.0.0
2015/03/23 20:22:05 [INFO] memberlist: Marking broken1.testing as failed, suspect timeout reached
2015/03/23 20:22:05 [INFO] serf: EventMemberFailed: broken1.testing 0.0.0.0
2015/03/23 20:22:11 [INFO] serf: EventMemberJoin: broken1.testing 0.0.0.0
2015/03/23 20:22:13 [INFO] agent: Synced check 'vm'
2015/03/23 20:22:14 [WARN] memberlist: Got ping for unexpected node 'broken1.testing'
2015/03/23 20:22:19 [WARN] memberlist: Got ping for unexpected node 'broken1.testing'
2015/03/23 20:22:24 [INFO] memberlist: Marking broken1.testing as failed, suspect timeout reached
2015/03/23 20:22:24 [INFO] serf: EventMemberFailed: broken1.testing 0.0.0.0
2015/03/23 20:22:30 [INFO] serf: EventMemberFailed: admin1.perf XXX.XX.5.123
2015/03/23 20:22:30 [INFO] serf: EventMemberJoin: admin1.perf XXX.XX.5.123
2015/03/23 20:22:42 [INFO] serf: EventMemberFailed: web1.stage XXX.XX.7.218
2015/03/23 20:22:43 [INFO] serf: EventMemberJoin: web1.stage XXX.XX.7.218
2015/03/23 20:22:43 [WARN] memberlist: Refuting a suspect message (from: storm1.prod)
```

Not being able to contact the misconfigured node they begin to fail which causes other nodes to fail. They eventually recover so the failures seem to ripple around the cluster. 

I understand that if all the hosts can't be contacted then a serf failure will occur, but I wouldn't expect working checks to begin failing? Possibly the 0.0.0.0 address is confusing the agents?

You say this is a known issue, can you give some details about what you think is happening and I'll try to dig into it more. Thanks.

**Comment by armon** [comment]
Ah this is a different problem. If a node is misconfigured in the sense that networking is not properly setup (UDP/TCP traffic not properly flowing) then that particular node goes through a Join/Fail cycle. In this case, it looks like the 0.0.0.0 address causes all sorts of failures. The root being that the address is not routable. I'm not sure without more investigation why this is causing other nodes to fail.

**Comment by rotatingJazz** [comment]
@armon +1 on sharing some details on the known issue. We can start throwing ideas once we have a basic understanding of what's going on :)

**Comment by whizz** [comment]
We are seeing the same problem. It happens when one server (A) has two interfaces with two IP adressess (it is in a DMZ). One for external communication, one for internal. Other cluster members are on the internal network. The consul client propagates the external IP, which the other members cannot reach. So A can reach any member in the cluster, but no other server can reach A. When A joins the cluster, it appears alive for a bit. After that, it becomes failed and soon other members start randomly reporting failures and recoveries. We are running 0.4.1. I believe it would be possible to simulate this by firewalling incoming connections but allowing outgoing, but I haven't tried.

**Comment by ashish235** [comment]
I 'm facing similar kind of issue. I 've three hosts on which I 'm running some docker containers. Each host is running a docker-consul container which forms a cluster. Now on one of the host I 'm running some containers running an application and consul agent. I 've heath checks for that application defined in the consul agent, while the health check returns "passing" state the serf health keeps flapping, which is affecting my service discovery.

Is there any workaround for this issue? A quick help will be really appreciated.

**Comment by armon** [comment]
@ashish235 It's hard to say what could be the issue with so little context, but typically there is a UDP routing issue at play. Make sure you get bi-directional routing of UDP packets. If you do rapid restarts of docker containers with fixed IPs, there is a known ARP cache issue in docker as well.

**Comment by ashish235** [comment]
Hi @armon, thanks for the reply. I don't think I 'm restarting containers rapidly. Also I had tried  "conntrack -F" for clearing the ARP cache. 

Can you provide me some pointers on where to dig the issue? 

I 've stopped the consul container on the Host where my application + consul agent was running and after that it seems the discovery is stable. 

Was it because of some NAT issue? that two containers (consul, consul agent) can't run on the same host ? My consul had all the port exposed and mapped while my consul agent only had the application port exposed and mapped. 

Kind of in middle of some confusion with the utility of consul server and consul agent.

**Comment by marc-** [comment]
Is there a way to determine such nodes and mark them is "bad", then exclude data from "bad" nodes from consideration or turn it into passive mode until it becomes stable?

**Comment by armon** [comment]
@ashish235 You would need to look at the logs to get a better idea of where to look. Especially if you crank up the verbosity to debug, they will shed more insight.

@marc- Not currently, but we likely need something like that to handle bad nodes.

**Comment by armon** [comment]
As a thought, I think one thing we can do is introduce a filter between the Serf and Consul layers. Consul can apply a simple saturating counter to fail/join events to prevent flapping nodes from causing a lot of churn.

**Comment by rotatingJazz** [comment]
@armon Sounds like a good idea! :+1: Do you think this can hit in 0.6? This issue is a roadblock for using it in production (at least, for me, I'd love to hear how others deal with it).

**Comment by slackpad** [comment]
Talked to @armon a bit today and we are going to try adding a TCP fallback for pinging peers, with a warning in the log if this actually confirms the existence of the peer. This should help the misconfigured client discover the correct state of the world and not introduce bad information into the cluster via the anti-entropy mechanism (which also uses TCP), while still being obvious to operators that there's a networking problem.

**Comment by slackpad** [comment]
The TCP ping change is in and should help with flapping in bad UDP connectivity scenarios, providing a clear log message when this occurs. This should make it into the next release of Consul.

@ashish235 please re-open this or create a new issue if your investigation leads you to think this wouldn't help what you were seeing.

@marc this should help prevent these nodes from getting marked bad in the first place since there's an alternate TCP ping mechanism, so I think we should be covered.
