### ISSUE TITLE
Recommend disabling Negative DNS Response Caching on Windows

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#743]
I ran into an problem today where a momentary flap during a service update caused one of my servers to no longer see it the service entry for 5 minutes without an `ipconfig /flushdns`. Windows respects the 0 TTL of a positive response, but if Consul returns a failure response (i.e. no available endpoints for a service definition) Windows will, by default, cache the failure for 900 seconds.

It would be worth it to recommend disabling negative DNS caching on Windows (see [KB 318803](https://support.microsoft.com/kb/318803/)). This applies to all versions of Windows __including and after__ XP despite the article being for XP.

I'd be happy to submit a PR to put it in the docs, maybe at http://www.consul.io/docs/guides/dns-cache.html but it seems like it should be a bit more obvious since this is nasty when it happens.

**Comment by ryanbreen** [comment]
We've run into this ourselves, so I definitely agree it would be good to have some language about negative caching.  I'm not sure that recommending config changes for specific platforms is the best approach since the list could get pretty unwieldy (if you're using AD-DNS as a conditional forwarder to Consul, you'll have similar issues).

Perhaps it's enough to talk about negative caching, what it is, and how to troubleshoot it.  The advice on platform-specific changes could be as simple as "check the negative cache defaults for your client operating system and any DNS forwarder on the path between the client and Consul."

**Comment by highlyunavailable** [comment]
Hmm, yes, I didn't think about forwarders. I'm using Consul as a local agent on all of my Windows servers, so it's the first point of contact for DNS for all my services. Anything else is just set as a Consul fallback resolver.

**Comment by ryanbreen** [comment]
@highlyunavailable If you want to whip up a PR, I'll be happy to review it.  Otherwise, I can take a crack at adding coverage of negative caching to dns-cache.html tomorrow.

**Comment by highlyunavailable** [comment]
Wow, it helps if I actually make the pull request to the root repo. Anyway, @ryanbreen I've made some docs on it.
