### ISSUE TITLE
Logs not present

### ISSUE THREAD

**Issue by akshatgit** [hashicorp/consul#7447]
#### Overview of the Issue

Consul agent not logging in the desired file. Added this [config](https://www.consul.io/docs/agent/options.html#log_file) for consul to log. 

Consul config:
```
{
    "advertise_addr": "x.y.a.b",
    "data_dir": "/var/consul",
    "datacenter": "dc1",
    "encrypt": "xxxxx",
    "log_file": "/var/log/consul",
    "retry_join": [
        "ip1",
        "ip2",
        "ip3"
    ],
    "server": false,
    "ui": false
}
```

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run consul with systemd service, without redirecting system out and error. 

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 2cf0a3c8
	version = 1.7.1
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 47
	max_procs = 8
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 226
	members = 21
	query_queue = 0
	query_time = 1
```

</details>

<details>
<summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 2cf0a3c8
	version = 1.7.1
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 3
	leader = false
	leader_addr = 172.19.x.y:8300
	server = true
raft:
	applied_index = 177364
	commit_index = 177364
	fsm_pending = 0
	last_contact = 79.880765ms
	last_log_index = 177364
	last_log_term = 5
	last_snapshot_index = 163894
	last_snapshot_term = 3
	latest_configuration = [{Suffrage:Voter ID:383373b5-75d1-78a7-fad2-d36f2df0ea9e Address:172.19.61.162:8300} {Suffrage:Voter ID:4e89dd31-c200-5d1a-c891-138bbb188143 Address:172.19.31.212:8300} {Suffrage:Voter ID:a96e5d29-8fa6-5b15-9596-8e773226150a Address:172.19.32.63:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 5
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 142
	max_procs = 8
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 226
	members = 21
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 158
	members = 9
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Debian 10.1

**Comment by jsosulska** [comment]
Hi @akshatgit ,

Thanks for your question! There's a bit more information that I would like to get to try and troubleshoot this issue.

1. What user is running the `consul` command?
1. For `var/log/consul` log file, what are the permissions on the file?
> Please `cd /var/log/` and run `ls -al`
1. Can you post the command and systemd configuration that is being ran, with sensitive values removed?
1. What configuration management tool, if any, are you managing the server with?
1. Is any Consul server or agent creating logs, or is this localized to a single host?

This may be a permissions issue, but we'd like to narrow down a bit more information. 
If you were able to get this working, please let us know what the resolution was.

**Comment by akshatgit** [comment]
1. Consul is running with consul user.
ps output: 
```
consul   22091  0.7  0.0 187320 64380 ?        Ssl  Mar13  44:25 /usr/local/bin/consul agent -config-dir /etc/consul
```
2. log file permissions:
```
ls -al | grep consul
-rw-r--r--  1 consul       consul             0 Mar  3 12:12 consul
```
3. Systemd file:
```
# /etc/systemd/system/consul.service
# THIS FILE IS MANAGED BY PUPPET
[Unit]
Description=Consul Agent
After=network-online.target
Wants=network-online.target

[Service]
User=consul
Group=consul
ExecStart=/usr/local/bin/consul agent \
  -config-dir /etc/consul
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
LimitNOFILE=131072

[Install]
WantedBy=multi-user.target
```
4. We use puppet for configuration management.
5. This issue is for all server/agent(s) in our cluster. 

Please let me know if anything needs modification. Thanks for helping.

**Comment by jsosulska** [comment]
Hi @akshatgit ,

Thanks for all the information.

Myself and a few other engineers are comparing the code and the documentation, and noticed that the behavior could be better documented. Currently, the way that this feature works is that Consul will look at the config file for the `log_file` entry, and use that value as the prefix of the log file defined there. This assumes that Consul has permissions to write to `/var/log`. We believe the issue is likely that the `consul` user is unable to write to `/var/log`, hence the questions above.

One potential solution is to have Puppet create and enforce a `/var/log/consul/` directory with the `consul` user and group. Then, update the `log_file` entry in the configuration file to point to `/var/log/consul/` (the directory). This should create a file, based on the [config documentation here](https://www.consul.io/docs/agent/options.html#_log_file) that fits the `consul-{timestamp}.log` format. This means that the `consul-{timestamp}.log` file will be autocreated, rather than explicitly defined.

We are looking at updating the documentation for that configuration item to explicitly call out that both the log file and the folder that stores it must have permissions for the `consul` user to write to those locations.

If this was unable to help you, can you please answer the following questions:
1. What is the permissions available for the consul user? 
2. What groups is the consul user added to? 
3. What are the permissions to write to `/var/log`?

Please let me know if there's anything else!

Best,
Jono

**Comment by akshatgit** [comment]
Hi @jsosulska 

Thanks for the detailed explanation. I think the updated documentation is explicit enough to explain the `log_file` parameter.  The issue was consul user cannot write to `/var/log` directory, hence the absence of logs. Will update my Puppet module to create a dir and config accordingly. 

Thanks,
Akshat
