### ISSUE TITLE
Pre-registration ACL verification

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#752]
Currently the only way to ensure that a service registration will appear in the catalog is to register directly with the catalog, or to check the catalog after a registration against the agent. This becomes problematic if an invalid or unauthorized token registers a service, because the agent will accept it, but Consul rejects it. The error is only exposed in the logs currently.

We can add a pre-flight RPC endpoint for services and checks to ensure that the provided token actually would allow successful registration.

**Comment by slackpad** [comment]
We pre-flight the tokens now as part of version 8 ACL support.

**Comment by DanyC97** [comment]
@slackpad so if i'm running 0.7.5-1 with ACL enabled then i'm on my own cause there are no info in the logs to suggest that services are not replicated to the catalog because they don't have the ACL in.

Would be nice if some workaround will be documented in the FAQ as i spent 2 days to understand where the problem is following activation of ACL.

**Comment by slackpad** [comment]
Hi @DanyC97 sorry you got bit by this. There should have been WARN logs in the agent when this happened, was this not the case?
