### ISSUE TITLE
Fix error formatting of `ServiceID` and `CheckID` types

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#7581]
When string formatting an error message that would container a `ServiceID` there are a few places where we are not properly formatting this struct:

https://github.com/hashicorp/consul/blob/8aec09aa8f0828f72e45cbee24b52413aa51d19e/agent/consul/acl.go#L1911

https://github.com/hashicorp/consul/blob/8aec09aa8f0828f72e45cbee24b52413aa51d19e/agent/consul/acl.go#L1966

https://github.com/hashicorp/consul/blob/8aec09aa8f0828f72e45cbee24b52413aa51d19e/agent/consul/acl.go#L1916

https://github.com/hashicorp/consul/blob/8aec09aa8f0828f72e45cbee24b52413aa51d19e/agent/acl.go#L177

There could potentially be others and it also effects the `CheckID` type as well.

Errors look like:

```
# Enterprise
Unknown service {"web:3" {"default"}}

# OSS
Unknown service {"web:3"}
```

Instead of:

```
# Enterprise
Unknown service default/web:3

# OSS
Unknown service web:3
```

There is a `String` method on both the `ServiceID` and `CheckID` types that will properly convert them to a string. In all these locations we could just invoke that method. I wonder if there is an interface we could implement so that Go's string formatting will do it for us though.

**Comment by mkeeler** [comment]
I think we could just change to using `%v` for many of these and then the standard formatting will call our `String()` methods

**Comment by dnephin** [comment]
#7583 proposed making the method receivers non-pointers to fix the problem. That would require a few changes:
* remove Init methods, which receiver a pointer receiver
* either:
  * un-embed `EnterpriseMeta` and make it a `EnterpriseMeta *EnterpriseMeta` field, or
  * change the `EnterpriseMeta` methods `Merge` and `Normalize` to operate on their args and return new copies, instead of mutating self.
* finally, making all methods non-pointer receivers.
