### ISSUE TITLE
Add count of active Client Agents

### ISSUE THREAD

**Issue by mkcp** [hashicorp/consul#7601]
#### Feature Description
Currently we can get a count of Server agents by looking at the raft peers. However, it would also be useful to have an active count of agents running as clients. 

#### Use Case(s)
This is useful for determining the shape of a Consul deployment. Currently we expect an agent on every node running.

Currently, finding the difference between `consul.serf.member_join` and `consul.serf.member_failed` gets you most of the way there, but finding the difference between these proved challenging in Datadog. Providing a straightforward count of the current number of consul agents would be ideal, so users don't have to be experts in both consul and their dashboarding system to get an accurate picture of the cluster.

**Comment by pierresouchay** [comment]
@mkcp the list of members is available at `http://localhost:8500/v1/agent/members`, you can easily count it and extract.
Here are a few examples with consul-templaterb to extract those values:
 - export as Prometheus values (`consul_members_count` with label `status`) in https://github.com/criteo/consul-templaterb/blob/master/samples/metrics.erb
 - find members VS nodes: https://github.com/criteo/consul-templaterb/blob/master/samples/find_nodes_in_catalog_but_not_in_members.json.erb (might differ if using external services of virtual nodes)

Note that it might be a very different value from nodes count since:
 - if you are using virtual nodes (for instance if you use [consul-k8s](https://github.com/hashicorp/consul-k8s), the nodes registered are not part of real Consul agents)
 - the value is more transient than nodes count - because it is what the agent is seeing at that time, the is no consistency across the cluster)
