### ISSUE TITLE
It takes too long to get service list

### ISSUE THREAD

**Issue by wangyushuai** [hashicorp/consul#7686]
#### Overview of the Issue

There are a lot of micro services in Consul, and it takes a long time to pull the service list, which causes too long when the application starts

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with  7 server nodes
2. Start my app
3. Which causes too long when the application starts

Can you give some advice？ Thanks

**Comment by jsosulska** [comment]
Hi @wangyushuai ,

Thanks for reporting this. Unfortunately, I don't have enough information to provide advice. Can you please provide the following information? Please see the additional questions at the bottom.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

Questions:
- Can you walk through your application's start up procedure? 
- How long is "too long"?
- How many services report to consul?
- Any particular reason that you opted for a 7 node cluster?
