### ISSUE TITLE
Read ACL Token by name

### ISSUE THREAD

**Issue by pratiklotia** [hashicorp/consul#7809]
### Feature Description
(on CLI)

Currently, ACL policies can be listed using 'consul acl policy list' and then accordingly, a particular policy can be read either with 'consul acl policy read -id <ID>' or 'consul acl policy read -name <Policy-Name>.

However, for ACL tokens (created directly by user or indirectly by the server for service policies): 'consul acl token list' will list the policies but there is no option to 'read' a token using the token name. One can use 'consul acl token read -id <Accessor-ID>' but not 'consul acl token read -name <Token-Name>.

It would be great to have the option to use -name as well.

#### Use Case(s)

For an administrator/operator, one cannot remember the AccessorID and therefore, has to lookup all the tokens and find the relevant ID. In contrast, the operator might remember some token names and can directly read using the name instead of listing the tokens and then finding the relevant AccessorID.

**Comment by mkeeler** [comment]
@pratiklotia One hindrance to this would be that tokens are not currently named and even if we added a `Name` field to them it could not be a mandatory/unique field (due to backwards compatibility guarantees).

One possible alternate way of being able to retrieve a token by "name" could look like:

```
> consul acl token list -selector "Description == <name> -secrets"
```

There are two things here:

1. `-selector "..."` - Many of our existing listing APIs (but not currently ACL resource listings) allow filtering using a [selector expression](https://www.consul.io/api/features/filtering.html). We could enable this for the various ACL resource listings and plumb it all the way through into the CLI.
2. `-secrets` - Today listing ACL tokens does not present the full view of a token but rather only includes some of the values. This new CLI option would cause the CLI command to fully resolve each token in the listing so that it presents all the data that a normal `consul acl token read` would.

It wouldn't be quite as straight forward as having a `-name` option to the read command but it would at least eliminate having to execute multiple commands and manually find the token.

In the meantime if it helps, Consul 1.7.3 introduced JSON format output for the ACL CLI commands so you can script up something to do the same as I had just described.

```
> consul acl token list -format json | \
     jq  -r '.[] | select(.Description == "<token name>") | .AccessorID' | \
     xargs consul acl token read -id
```

Thats pretty long and ugly but it does work. If you don't need to know the tokens secret then you could just do:

```
> consul acl token list -format json | jq -r '.[] | select(.Description == "<token name>")'
```

**Comment by pratiklotia** [comment]
@mkeeler Thank you for the quick and detailed reply. I understand the issues and workarounds you described. I think using selector should work fine.

I'm still on 1.7.2 so I will check the json format output once I get a chance to upgrade. Thank you very much.

That being said, I think I'm good with closing this issue.
