### ISSUE TITLE
[New Feature] Support Rotating Primary DC

### ISSUE THREAD

**Issue by jsosulska** [hashicorp/consul#7817]
This has been requested several times on the Discuss Forums:
Ref: 
- https://discuss.hashicorp.com/t/change-authoritative-dc-in-consul-federation/8443
- https://discuss.hashicorp.com/t/does-should-the-primary-datacenter-ever-change/6627/5
- https://discuss.hashicorp.com/t/is-it-possible-to-change-the-primary-datacenter-for-consul-clusters/6079/7

Today, rotating the primary DC is a painful, dangerous manual task.

#### Feature Description
The ability to manually promote a DC to being "primary," as well as automatically "failover" to a new authoritative DC would provide more flexibility, and avoid single points of failure. 

#### Use Case(s)
In cloud based environments, DCs may need to fail over to other regions.
Server hosts may be decommissioned and migrated to other physical hardware.
The "primary dc" may need to be isolated from a larger WAN network for incident response.
In physical DCs, a provider may fail.

**Comment by Wolfsrudel** [comment]
+1

**Comment by sgavrylenko** [comment]
+1

**Comment by jsosulska** [comment]
Thread from Discuss where someone has done this: https://discuss.hashicorp.com/t/errors-after-changing-dc/8601/4

**Comment by patricekrakow** [comment]
@jsosulska in the meantime, would you recommend to setup the primary consul datacenter across multiple availability zones, or even across multiple regions?

**Comment by jsosulska** [comment]
Hi @patricekrakow - Thanks for reaching out.

Consul defines a "datacenter"(https://www.consul.io/docs/install/glossary#datacenter) to be a networking environment that is private, low latency, and high bandwidth. This excludes communication that would traverse the public internet, but for our purposes multiple availability zones within a single EC2 region would be considered part of a single datacenter. For most Consul deployments, having an autoscaling group per AZ goes a long way for availability.

I recommend asking more specific questions about your specific use case on our [Discuss Forums](https://discuss.hashicorp.com/c/consul/29), where other community members can provide additional feedback or stories about their designs. 

Best,
Jono

**Comment by joshwolfer** [comment]
Bump +1. 

When moving infrastructure, this is a serious challenge in handling a primary DC that is no longer available.

**Comment by ches** [comment]
> Today, rotating the primary DC is a painful, dangerous manual task.
> 
> #### Feature Description
> The ability to manually promote a DC to being "primary," as well as automatically "failover" to a new authoritative DC would provide more flexibility, and avoid single points of failure.

Even if it today is a painful, dangerous, and manual task, is it documented? Sorry to cross the streams but I saw essentially this question asked but not answered on the discussion forum, with a reference to vote on this issue.

While a first-class failover mechanism—automatic or operator-induced—would be lovely, there are real-world needs to deal with this today in the absence of that feature. If ACL policies and so forth need to be frozen, dumped, and loaded manually to another cluster, so be it—automation begins with knowing what to automate!

**Comment by dekimsey** [comment]
In our use-case we are in the process of decomissioning our bare-metal datacenter which is currently the primary datacenter for Consul. What I'm looking for in the interm is a non-outage set of steps to execute to "promote" a current secondary datacenter to the primary. An automated method to publish a change to the mesh (ala gossip encryption key) would be ideal of course which I'm hoping this feature request will make happen. However, as of today, I cannot find any information on how I could manually accomplish this goal.

**Comment by Amier3** [comment]
Hey @dekimsey

Thanks for bringing this back to the forefront. We’ve discussed this internally and decided that we'd need some time before publishing a guide on zero downtime migrations for a primary datacenter ( what would be needed to "promote" the secondary DC to primary ). We've done one in the past for a large user, but after looking back at that migration plan we realized it wouldn’t translate well to a general “how-to” guide.

The main issue is that any consul migration would be highly dependent on specific configuration. Using service mesh vs not using service mesh, utilizing the KV features, or using vault as your CA provider all add nuances that make it hard to give a definitive step-by-step guide that’d work for anything but a narrow scope of configuration

There’s a couple of things we can do in tandem to address this:

1. Spend some time thinking/tinkering/testing with common configurations and figure out what works vs what doesn’t.

2. Provide a general list of considerations if you were planning on attempting a zero downtime migration to enable you to form your own migration plan confidently.

I’ll make a new issue outlining the need for investigation around this and link it in this thread so it stays in the top of the funnel.

**Comment by alsyia** [comment]
Hey @Amier3,

We are in the exact same case as @dekimsey except we can accept a downtime. Would bringing every agents and server down, changing the config, and then putting them back up work? 

This is blocking an important migration for us too!

**Comment by dekimsey** [comment]
At this point, with the runway I'm looking at, I too would accept a downtime if I could get a clear idea of the steps I'd need to take to successfully switch. That's the part that I simply don't know without a whole lot of testing/research and potentially destroying an entire testing environment (which I don't have the bandwidth for).

If anyone has done this successfully and has a quick and dirty task list, please share! I'll even take a napkin sketch written with crayons.

**Comment by thaniri** [comment]
I can easily build and tear down test Consul clusters and want to make a change in the `primary_datacenter` configuration.

Here are the results from just going ahead and trying to make the configuration change in a 2 cluster setup.

### Just doing it with a full restart:

1. Built a cluster (a) with 3 servers
2. Built a second cluster (b) with 3 servers
3. Joined them together with wan configs, and set cluster a to be the primary.
4. Added basic ACL configuration, and ran `consul acl bootstrap` in cluster a.
5. Did a rolling restart in cluster a then cluster b. No real uptime testing or feature testing.
5. Tested that the initial token was required in both clusters to run `consul operator raft list-peers -token=<token>`
6. Updated the primary datacenter configuration and the acl.tokens.master configuration in both cluster a and cluster b, then did a simultaneous restart of all consul servers in both a and b.

Result:

Complete failure. `consul operator raft list-peers -token=<token>` does not work due to ACL problems.

Attempting to revert configuration restores cluster a, but keeps cluster b broken.

Outage recovery on cluster b using peers.json does not fix.

Interestingly, when going to the web UI, both cluster a and cluster b agree on which ACLs exist.

### Just doing it with a rolling restart:

1. Built a cluster (a)
2. Built a second cluster (b)
3. Joined them together with wan configs, and set cluster a to be the primary.
4. Added basic ACL configuration, and ran `consul acl bootstrap` in cluster a.
5. Did a rolling restart in cluster a then cluster b. No real uptime testing or feature testing.
5. Tested that the initial token was required in both clusters to run `consul operator raft list-peers -token=<token>`
6. Updated the primary datacenter configuration and the acl.tokens.master configuration in both cluster a and cluster b, then did a rolling restart of all consul servers in both a and b.
6a. After (a1) is restarted, command works on (a1). After (b1) is restarted, command fails due to ACL not found on (b1) but succeeds on (a1).
6b. After (a2) is restarted, command works on (a1) and (a2). After (b2) is restarted, command succeeds on (b1) and (b2).
6c. After (a3) is restarted, command fails on all Consul servers. After (b3) is restarted, command continues to fail on all Consul servers.

Result:

Complete failure. Just like experiment 1.

### Next steps

From logs, the main errors come from ACLs and Certificate Authority. I must find a way to move the responsibility of managing the ACLs and CA to the secondary cluster before changing the `primary_datacenter` configuration. Any suggestions on what to try will be appreciated and I can report back on my results.

**Comment by david-yu** [comment]
Hi there, unfortunately rotating a primary datacenter is considered a very invasive process and thus doing so without any downtime is unlikely to be realized in the current wan federation architecture. 

We have now built a new architecture for allowing cross datacenter communication traffic through Cluster Peering in 1.13, that no longer assumes that clusters are managed by the same operator and thus enforces a primary and secondary relationship between clusters. Please read more about Cluster Peering here: https://www.consul.io/docs/connect/cluster-peering#differences-between-wan-federation-and-cluster-peering and try out the latest 1.13 release to provide us feedback as we work towards GA of cluster peering.

**Comment by dclaisse** [comment]
Hi,

Just a heads up here, even though it's not the recommended solution by Hashicorp, I was able to migrate a primary datacenter to another, including ACLs and connect CA, using builtin consul provider:

- First of all, you need to enable ACL replication so new datacenter, with a replication token and setting "enable_token_persistence" to true in your config, so secondary datacenter replicates ACL tokens and policies.
- Next, you need a small patch to allow new primary datacenter to update its root CA at startup, which is an impossible state in Consul's FSM, and cleanup old intermediate certificate. Note that this patch is applied on top of #14888 so it may not apply on HEAD.
`diff --git a/agent/consul/leader_connect_ca.go b/agent/consul/leader_connect_ca.go
index 3d40dd1..b3bb5b0 100644
--- a/agent/consul/leader_connect_ca.go
+++ b/agent/consul/leader_connect_ca.go
@@ -555,10 +555,12 @@ func (c *CAManager) primaryInitialize(provider ca.Provider, conf *structs.CAConf
 	}

 	if activeRoot != nil {
-		// This state shouldn't be possible to get into because we update the root and
-		// CA config in the same FSM operation.
+		// We are changing root CA and configuration.
+		// This means that we are changing primary datacenter.
+		// In that case, remove intermediate certs to clean up.
 		if activeRoot.ID != rootCA.ID {
-			return fmt.Errorf("stored CA root %q is not the active root (%s)", rootCA.ID, activeRoot.ID)
+			c.logger.Warn("stored CA root is not the active root, datacenter may be switching from secondary to primary. Removing old intermediate certificates.")
+			rootCA.IntermediateCerts = nil
 		}

 		// If current root in raft misses some changes from generated rootCA, persist those changes.`
- After releasing a version containing this patch, you'll need to update config of the new primary datacenter servers and restart them to make new datacenter primary. Beware, you'll have two primary datacenters at this point, so every ACL changed in old primary datacenter will be lost until it steps down to secondary.
- Then, you may change configuration of old primary datacenter and other secondary datacenters to the new one, and all should be fine, ACL source should change to new primary and intermediate connect certs should be signed by new primary.
