### ISSUE TITLE
Prevent ACL tokens from appearing in logs or monitor

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#791]

**Comment by pforman** [comment]
If possible, hashing to prevent them from appearing in cleartext in the Raft snapshots would be helpful.

It was a surprise to me to find the master ACL token readable in the snapshot while researching the effects of privilege escalation (#792).

If you feel that's a different issue or out of scope, I understand.  Just mentioning it in the context here.

**Comment by armon** [comment]
@pforman That is a bit out of context. I think that would require something along the lines of at-rest encryption.

**Comment by pforman** [comment]
No problem.  It shouldn't be an issue when #792 is fixed, because that token data would still only exist on the server nodes.  At that point, it's easier to read it from the config files than the raft snapshot.

It wouldn't necessarily require at-rest encryption if you hash the config-file-provided token at startup and then only compare the hashed versions, but that would definitely be some rework.  Feel free to ignore it or make it a separate issue if you feel it would be something useful in the future.

**Comment by tummychow** [comment]
In addition to this, it would be cool if the api package filtered tokens out of the errors that it returned to client code.

**Comment by ryanuber** [comment]
Tokens should no longer appear in the monitor or logs after ee56598.

@tummychow I'm not sure if it makes sense to do that in the API package. The client made the request, so it must already know about the token. We do plan on enhancing and unifying the response formats in a v2 api in the future, but we haven't started on that project yet.
