### ISSUE TITLE
Panic during "consul reload"

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#809]
There is a potential panic condition when "consul reload" is called under some situations. See this mailing list thread: https://groups.google.com/forum/#!topic/consul-tool/JMbZ1MRsT7I

Potentially an issue with closed file handles as well?

**Comment by imcom** [comment]
Hi Armon, thanks for you attention. Turns out, this is not Consul's bug, but still there is something worth talking about )

I have a script to deal with Keyprefix watch, what I've figured is that whenever Consul starts or reloaded, it will run through all WATCHES. In my case, the handler for keyprefix will parse all values and triggers a reload. At the beginning, I did not realize that the Keyprefix watch will return the subtree of the given Keyprefix regardless whether  the entries are modified or not, so my handler reloads Consul every time Consul gets reloaded. This triggers the `too many open files` eventually, because there are so many internal API calls flying (examined by lsof `pidof consul`), I did not have the output now, but I am pretty sure because I've seen hundred of connections to port 8400.

Instead of calling this a bug, I would admit my dumbness ) But on the other hand, if I want to skip the unchanged entries/keys under a keyprefix, will I have to record the modifyIndex by myself somewhere? Because the WATCH handler will lose status each time. Apart from using some external file/database/redis etc. I could not think of a way for persisting all the indices ...

Please kindly advise or it would be great for Consul to return only new entries and the modified ones

Thanks in advance

**Comment by armon** [comment]
@imcom Currently there is no way to have Consul send the changes only. I believe there is an open ticket for this however. For now, you do need to store that index and de-duplicate within the watcher if necessary.

**Comment by armon** [comment]
Resolved, as the issue was a reload loop.
