### ISSUE TITLE
non-voting-server Not Work

### ISSUE THREAD

**Issue by CherleX** [hashicorp/consul#8095]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I add non-voting-server to a Consul Cluster.But the non-voting-server will auto transfer to Voting-Server.

#### Reproduction Steps

Steps to reproduce this issue, eg:
1.Create a Cluster
```
docker run -d -p 8500:8500 -v /data/consul:/consul/data -e CONSUL_BIND_INTERFACE='eth0' --name=consul_server_1 consul:1.7.4 agent -server -bootstrap -ui -node=1 -client='0.0.0.0'

docker run -d -e CONSUL_BIND_INTERFACE='eth0' --name=consul_server_2 consul:1.7.4 agent -server -node=2  -join='172.17.0.2'

docker run -d -e CONSUL_BIND_INTERFACE='eth0' --name=consul_server_3 consul:1.7.4 agent -server -node=3  -join='172.17.0.2' 
```
```
$ docker exec consul_server_1 consul operator raft list-peers
Node  ID                                    Address          State     Voter  RaftProtocol
3     73537020-f59f-3f26-8cb8-2771313e4a53  172.17.0.4:8300  leader    true   3
1     0665bef6-fc11-7fcd-1456-b8e79d990b81  172.17.0.6:8300  follower  true   3
2     a70d7556-f297-0e72-5039-dd1f5dc4254c  172.17.0.3:8300  follower  true   3

```

2.Add non-voting-server Server
```
docker run -d -e CONSUL_BIND_INTERFACE='eth0' --name=consul_server_4 consul:1.7.4 agent -server -node=4  -join='172.17.0.6' -non-voting-server
```
```
$ docker exec consul_server_1 consul operator raft list-peers
Node  ID                                    Address          State     Voter  RaftProtocol
3     73537020-f59f-3f26-8cb8-2771313e4a53  172.17.0.4:8300  leader    true   3
1     0665bef6-fc11-7fcd-1456-b8e79d990b81  172.17.0.6:8300  follower  true   3
2     a70d7556-f297-0e72-5039-dd1f5dc4254c  172.17.0.3:8300  follower  true   3
4     151e0d07-0674-bc3c-e0da-eeb9a588894e  172.17.0.2:8300  follower  false  3

```

about 1min later...The Node 4 transfer to Voter.
```
$ docker exec consul_server_1 consul operator raft list-peers
Node  ID                                    Address          State     Voter  RaftProtocol
3     73537020-f59f-3f26-8cb8-2771313e4a53  172.17.0.4:8300  leader    true   3
1     0665bef6-fc11-7fcd-1456-b8e79d990b81  172.17.0.6:8300  follower  true   3
2     a70d7556-f297-0e72-5039-dd1f5dc4254c  172.17.0.3:8300  follower  true   3
4     151e0d07-0674-bc3c-e0da-eeb9a588894e  172.17.0.2:8300  follower  true   3
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
$ docker exec consul_server_4 consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = d149d7e9
        version = 1.7.4
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 172.17.0.4:8300
        server = true
raft:
        applied_index = 791
        commit_index = 791
        fsm_pending = 0
        last_contact = 36.287033ms
        last_log_index = 791
        last_log_term = 203
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:73537020-f59f-3f26-8cb8-2771313e4a53 Address:172.17.0.4:8300} {Suffrage:Voter ID:0665bef6-fc11-7fcd-1456-b8e79d990b81 Address:172.17.0.6:8300} {Suffrage:Voter ID:a70d7556-f297-0e72-5039-dd1f5dc4254c Address:172.17.0.3:8300} {Suffrage:Voter ID:151e0d07-0674-bc3c-e0da-eeb9a588894e Address:172.17.0.2:8300}]
        latest_configuration_index = 0
        num_peers = 3
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 203
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 84
        max_procs = 2
        os = linux
        version = go1.13.12
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 23
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 82
        members = 4
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 73
        members = 4
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by mkeeler** [comment]
@CherleX Non Voting servers is a Consul Enterprise feature and unavailable in the OSS version of Consul. If you look at the logs you should see some warnings that and indicating that its not going to work.

**Comment by CherleX** [comment]
@mkeeler Thanks For your answer. But my problem is that I deploy Consul in 2 AZ，when one AZ is down,How can I ensure Consul work properly?For example: consul_server_1(which is leader) and consul_server_2 deployed in AZ1，while consul_server_3 deployed in AZ2, when AZ1 is down. Does this mean the cluster is down?Is there some solution to solve the problem？

**Comment by s-christoff** [comment]
Howdy @CherleX,
Thank you so much for your question! For future reference, we ask that usage questions be posted on our [discuss form](https://discuss.hashicorp.com/c/consul), as the community there is able to provide a variety of solutions.

There are 2 sets of problems that arise from losing a single AZ. First, you lose  High Availability (HA). Ideally, your architecture could be built over 3+ AZs, so that the loss of a single AZ doesn’t mean losing HA. By only using an even number of AZ’s, you put yourself at risk of split brain situations. Is there a particular reason you are using only 2?

>Does this mean the cluster is down?Is there some solution to solve the problem？

In this case, your cluster is not down, but it is in a heavily degraded state. This is not an ideal, and you would want to scale up to at least 3 servers in your remaining AZ to get back to quorum. 


If you have Consul split in between two availability zones with an odd number of servers it will depend mostly on what availability zone the leader is in. If the leader is in the availability zone that goes down, then the other server in the over availability zone will eventually try to elect itself as leader. What I would recommend, is to have enough servers built in an autoscaling way, like AutoScaling Groups in AWS, for each availability zone so that if a zone crashes, the servers can still maintain a quorum. The minimum number of servers for a fault tolerant quorum is three. Feel free to review this [deployment table](https://www.consul.io/docs/internals/consensus.html#deployment-table) that can help with deciding how much fault tolerance you may need. 

I am going to close this issue for now - but if you have more questions feel free to start a topic on the discuss forum linked above.
