### ISSUE TITLE
Query returns service (and checks still pass) after node was terminated

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/consul#811]
Hi,

I'm running a consul cluster with 3 server nodes and several client nodes.
Some clients run consul with such json service definition:

```
{
  "service": {
    "name": "infra-haproxy-stats",
    "port": 8000,
    "check": {
      "script": "curl -o /dev/null localhost:8000",
      "interval": "60s"
    }
  }
}
```

Now if I shutdown such node, the serf check fails but the service check still passes:
![serf_failed_check_pass](http://5pi.de/screen_15_03_24_15h51m58s.png)

And most importantly, consul still returns those nodes in queries:

```
$ curl consul:8500/v1/catalog/service/infra-haproxy-stats | jq '.[]|select(.Address == "10.128.13.32")'
{
  "Node": "ip-10-128-13-32",
  "Address": "10.128.13.32",
  "ServiceID": "infra-haproxy-stats",
  "ServiceName": "infra-haproxy-stats",
  "ServiceTags": null,
  "ServiceAddress": "",
  "ServicePort": 8000
}
```

I'm not sure if the passing service check is due to design (since the check never reported 'down' although I expected it to be marked failed if there is no 'ok' in some time), but at least I expected consul to not return unhealthy nodes.

**Comment by grobie** [comment]
Do you use [leave on terminate](https://consul.io/docs/agent/options.html#leave_on_terminate)? For an intentional shut down of a node, you probably want to make sure it also leaves the cluster.

For anything health related, I believe you should use the Health API instead. https://consul.io/docs/agent/options.html#leave_on_terminate

**Comment by pearkes** [comment]
I'll note that this is a known UI issue, and expected per the Consul API. The UI should handle nodes that aren't responding to the `serfHealth` check in a special case to mark them as unreachable.

**Comment by ryanuber** [comment]
This is expected behavior. The script/interval check is run locally on the agent, so if that node goes away, the result will not be updated, which was indeed a design decision. This is where the `serfHealth` check smooths things over for you by quickly detecting the node failure and updating the catalog. As pointed out by @grobie, you will want to use the `/v1/health` endpoint to query for services in a passing state. The equivalent API call in your use case would have been `curl consul:8500/v1/health/service/infra-haproxy-stats?passing`.

**Comment by ryanuber** [comment]
Created #813 for the UI issue, let's track that separately.

**Comment by discordianfish** [comment]
Ok, got it - but is it also expected for the dns api to return unhealthy nodes? I *think* I saw that happen but will verify.

**Comment by ryanuber** [comment]
@discordianfish definitely not - the DNS interface should only return healthy results. Please do let us know if you see otherwise.
