### ISSUE TITLE
Docker Script Health Checks not displaying output in Console UI

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/consul#8161]
I filed this issue in the nomad project, but they pointed me here as a possible Consul UI bug.

Could somebody please clarify on why this behavior is happening?   We used to see the outputs but not since upgrading from 1.6.x if memory serves correctly.  Even 1.8.0 upgrade has not resolved the issue.

The issue filed below was using Consul 1.7.2 and Nomad 0.11.2 when they verified the behavior and pointed me here.

https://github.com/hashicorp/nomad/issues/8112

Thanks!

**Comment by johncowen** [comment]
Hey @idrennanvmware !

Thanks for bringing this over here! At first glance it looks as though somewhere between the config in nomad and the API response from consul the healthcheck is being changed from a `type=script` to a `type=ttl`:


```hcl
service {
  check {
    type = "script"
    name = "script.sh"
    command = "/bin/sh"
    args = ["-c", "local/script.sh"]
    interval = "5s"
    timeout = "1s"
  }
}
```

```json
  "ServiceTags": [],
  "Type": "ttl",
```

TTL checks don't have outputs so we hide the output display in the UI so it doesn't just show a blank display.

I think the problem is that this check is actually a script check (and therefore has an output) but the API response is saying its a TTL, so the UI doesn't show the output.

Anyway, thats ^ what I think the problem is, I'll check in with someone here to see if they can chase it up further.

In the meantime:


```hcl
type = "script"
name = "Zookeeper Health Check"
```

Does the API response report that this check is a TTL check even though you specified `script`?

**Comment by idrennanvmware** [comment]
@johncowen looks like you're right on the money.  It's showing as TTL from the local agent

`_nomad-check-0737dc4be895bc3f4e87a07e44a2ff29550e4edb":{
      "Node":"cps-promoter-genesis-zkp1",
      "CheckID":"_nomad-check-0737dc4be895bc3f4e87a07e44a2ff29550e4edb",
      "Name":"Zookeeper Leader or Follower Check",
      "Status":"passing",
      "Notes":"",
      "Output":"Zookeeper version: 3.6.1--104dcb3e3fb464b30c5186d229e00af9f332524b, built on 04/21/2020 15:01 GMT Latency min/avg/max: 0/0.2977/22 Received: 280055 Sent: 364850 Connections: 2 Outstanding: 0 Zxid: 0x5c00000af3 Mode: follower Node count: 198\nCurrent Mode: Mode: follower\nHEALTHY - Follower Mode: follower\n",
      "ServiceID":"_nomad-task-20c54769-af1b-3b4e-1f3b-6ef84cbaa292-zookeeper-task-zookeeper-cluster-zk",
      "ServiceName":"zookeeper-cluster",
      "ServiceTags":[
         "zookeeper"
      ],
      "Type":"ttl",
      "Definition":{

      },
      "CreateIndex":0,
      "ModifyIndex":0
   }`

**Comment by johncowen** [comment]
Hey @idrennanvmware ,

Perfect thanks for that extra info. This definitely doesn't seem to function the way we expect it to, but it doesn't seem to be a UI issue, rather an issue between Nomad and Consul API communication. I've added a bug label so that more folks can take a look at it.

Thanks for bringing this up, if you have any more info here, please feel free to add it.

**Comment by rkettelerij** [comment]
+1. Also seeing the same issue. All our script checks registered using Nomad appear to be TTL checks in Consul.

Running Consul 1.7.4 (also the case on 1.7.2)
Nomad 0.11.3 (also the case on 0.11.1)

**Comment by idrennanvmware** [comment]
Thanks @johncowen for the detailed explanation.   Appreciate how fast you all tracked that down :)
