### ISSUE TITLE
Support Linkerd2-proxy

### ISSUE THREAD

**Issue by Smithx10** [hashicorp/consul#8303]
Consul Connect should support Linkerd2-proxy

https://github.com/linkerd/linkerd2-proxy

Written in Rust, SuperFast, and doesn't depend on Bazel like Enovy.

**Comment by jkirschner-hashicorp** [comment]
Hello all,

The HashiCorp Consul team has no plans at this time to build out first class support for proxies beyond Envoy. Some reasons for this decision include:
- Consul and Envoy are both platform-agnostic, whereas linkerd2-proxy is currently focused just on Kubernetes.
- Consul takes advantage of some Envoy features which aren't currently offered in linkerd2-proxy.

However, **any proxy _can_ be extended for use with Consul Service Mesh** (Connect). If for your use case you want to use linkerd2-proxy with Consul Service Mesh (Connect) instead of Envoy, you would need to build the [documented integrations](https://www.consul.io/docs/connect/proxies/integrate). Highly performance sensitive applications can also [natively integrate with Consul Service Mesh](https://www.consul.io/docs/connect/native), though many service mesh features are not supported by native integrations.

We do appreciate you raising the suggestion and expressing your interest (👍).

Given that we have no plans at this time to pursue this, we are closing this issue. For those who followed this issue, we would be interested in hearing more about why Envoy isn't a suitable sidecar proxy for your use case.
