### ISSUE TITLE
Consul data lost happens when adding new node into existing cluster

### ISSUE THREAD

**Issue by johnzhanghua** [hashicorp/consul#8376]
#### Overview of the Issue
Version 1.8

When adding a new node into an existing cluster, the node can becomes leader, then the key values disappeared. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 3 nodes, below are the config of one node, the others are same, except ip address
```
{
    "ui": true,
    "data_dir": "/data/consul",
    "log_level": "info",
    "enable_syslog": true,
    "enable_script_checks": true,
    "leave_on_terminate": true,
    "disable_host_node_id": true,
    "server": true,
    "bind_addr": "192.168.64.152",
    "advertise_addr": "192.168.64.152",
    "client_addr": "127.0.0.1 192.168.64.152",
    "bootstrap_expect": 3,
    "retry_join": ["192.168.64.152", "192.168.64.153", "192.168.64.154"]
 }
``` 

2 Create another node with the config below
```
{
   "ui": true,
   "data_dir": "/data/consul",
   "log_level": "info",
   "enable_syslog": true,
   "enable_script_checks": true,
   "leave_on_terminate": true,
   "disable_host_node_id": true,
   "server": true,
   "bind_addr": "192.168.64.155",
   "advertise_addr": "192.168.64.155",
   "client_addr": "127.0.0.1 192.168.64.155",
   "bootstrap_expect": 1
}
```

3 On one of the cluster nodes, run 'consul kv put config/test true'

4 On the cluster nodes, join the new node into cluster; or on the new node join the cluster by
  `consul join 192.168.64.158`

5 When the new node becomes leader, the consul key disappeared.
   ```
consul operator raft list-peers
Node              ID                                    Address              State     Voter  RaftProtocol
dev5  c0760a70-159c-442d-6442-5ffd2a6907cb  192.168.64.161:8300  leader    true   3
dev2  10bb23c7-a244-ab44-c852-5a596e27a61a  192.168.64.158:8300  follower  true   3
dev4  7cda1149-9bdc-0104-c9fa-d4b4d2244c88  192.168.64.160:8300  follower  true   3
dev3  871d4c5a-d11e-63a8-1c4b-c4b561f554eb  192.168.64.159:8300  follower  true   3
```
```
 consul kv get config/test
Error! No key exists at: config/test
```

6 Wait till the consul info commit_index to be the same both on leader and follower, key still missing.

```
consul info |grep commit_index
	commit_index = 576
```

```
consul info |grep commit_index
	commit_index = 576
```
7 Stop and start the new node by 'systemctl stop/start consul', to shift leader role to other nodes, the consul key comes back.

```
consul kv get config/test
true
```

### Question?
Am I using the right way to join a server node into an existing cluster ? How can I join the existing cluster as followers ?  Also I want to do the server join by script, not manually.

**Comment by jsosulska** [comment]
Hi @johnzhanghua ,

Thank you for posting this issue. It is going to be fixed in [this PR](https://github.com/hashicorp/consul/pull/8474), which references an existing issue. As such, I will close this issue.

As for your questions, I recommend asking on our [Discuss Forum](https://discuss.hashicorp.com/c/consul/29), as community members may have different and unique recommendations! In short - Yes, you are joining servers to the cluster correctly. [`retry_join`](https://www.consul.io/docs/agent/options#retry-join) in the config will have the server instances attempt to join any of those IPs, and also supports DNS names. By setting this in the configuration, and using something like systemD to manage the process, you can bring up  Consul with a command like `consul agent -config-dir=/path/to/dir`, which seems like you're already doing.

Hope this helps!
Jono
