### ISSUE TITLE
All services added through the API are persisted

### ISSUE THREAD

**Issue by jefferai** [hashicorp/consul#851]
When any service is added through the HTTP API, it hits this piece of code in agent_endpoint.go:

```
if err := s.agent.AddService(ns, chkTypes, true); err != nil {
```

The third parameter means to persist the service across agent restarts -- it is not a parameter controlled by the client, but rather is always specified as true. I realize that this is a new feature of 0.5 from https://github.com/hashicorp/consul/pull/497. I would argue that this is exactly the opposite of what the default should be.

Some examples of the problems this has caused me:
1. Services (Docker containers) that are not up upon a machine reboot being advertised as being available, playing havoc with consul-template-written files advertising them as backends
2. Services that are available but not with the same port being advertised, causing problems with multiple backends for the service being announced but only one being valid
3. Services that are no longer available but not manually removed (for instance, due to an unexpected reboot) are announced as available

I realize that _an_ answer for this is "use health checks", but:
1. In a development environment where things come and go rapidly health checks may not be worth writing, especially since they would likely have to be different from production health checks
2. It is reasonable for the Docker container being up/down representing the granularity of a service being up/down, and I already have something managing Consul services for that (Registrator). Registrator worked perfectly with 0.4, but due to this change it is terribly broken in 0.5.

Here's my main argument: if you are using the Consul API to add a services, you can use that very same API with the very same program you initially used with the API to add the service if it's no longer there; if you absolutely care about the service being persisted, you can use a service file to achieve that effect. The best solution is for the API to gain the ability to toggle whether a service should be persisted or not, but _defaulting_ to that behavior can easily cause problems.

**Comment by ryanuber** [comment]
I could see adding a durability flag to the service and check registrations, but I definitely think persisting them is an important feature in Consul. Many use cases involve registering services against a Consul agent which are not hosted locally, and it doesn't always make sense for those to have to be in a config file somewhere because of the pain it causes for automating the registration.

The feature was also intended to guard against a Consul agent failure. If the services and checks were not persisted, it would then become the responsibility of each application to monitor its own registration in Consul.

It might make sense for persistence of API registrations to be enabled/disabled globally rather than specified in the registration calls. Reason being that it becomes harder to reason about how to register a new service or check later on (should I make this new check durable? is its associated service durable?)

I'll think more about this.

**Comment by jefferai** [comment]
"If the services and checks were not persisted, it would then become the responsibility of each application to monitor its own registration in Consul." -- or to write service files instead.

I don't think enabling/disabling globally is the right way to go. Set a default, but allow per-service configurations. I don't think it's as hard to reason about whether a service/check should be entered into the system in a durable way or not as you are suggesting. In particular, I may want all services added via, say, Registrator to be able to be non-persistent, but have any services I've manually added to be persistent.

**Comment by armon** [comment]
I think it may make sense to support a `?persist` flag to flag the persistence off on a per-service registration. Thoughts @jefferai @ryanuber?

**Comment by ryanuber** [comment]
I agree the flag on the API is the most simple. I think we just need a good way of avoiding orphaned checks. Maybe we can just clean up any orphans at consul start time.

**Comment by jefferai** [comment]
Both of your statements sound good to me.

**Comment by ryanuber** [comment]
Tagged as an enhancement, thanks @jefferai!

**Comment by m247suppport** [comment]
Hi,

My use case is a single consul agent that is used for service discovery so that prometheus so that it can scrape metrics from http endpoints . I am using the official consul image on docker hub and I add / remove services using the http api. While consul is very useful for dynamically adding services, I am finding the lack of persistence between agent reboots limiting. Unfortunately, I don't know enough about consul to be able to contribute in any meaningful way in closing this issue.

I just wanted to ask if there any other work around in regards to persistent states between agent reboots, beyond health checks (which I *believe* is not supported by every http endpoint, but then I might be missing something obvious)?

**Comment by slackpad** [comment]
We added a `deregister_critical_service_after` field to checks that seems to be working well in practice for short-lived registrations. Here's a summary of how it works from the [checks documentation](https://www.consul.io/docs/agent/checks.html):

> In Consul 0.7 and later, checks that are associated with a service may also contain an optional deregister_critical_service_after field, which is a timeout in the same Go time format as interval and ttl. If a check is in the critical state for more than this configured value, then its associated service (and all of its associated checks) will automatically be deregistered. The minimum timeout is 1 minute, and the process that reaps critical services runs every 30 seconds, so it may take slightly longer than the configured timeout to trigger the deregistration. This should generally be configured with a timeout that's much, much longer than any expected recoverable outage for the given service.

I'm going to close this out against that feature, but if folks feel strongly about persistence controls please speak up and we can reconsider.
