### ISSUE TITLE
Validation of JWT token passed through service mesh

### ISSUE THREAD

**Issue by oleksiyp** [hashicorp/consul#8556]
#### Feature Description

 - to identify originator of request it would be nice to have validation of JWT token on each hop of service mesh

#### Use Case(s)

 - services can pass token to each other and rely on it to do permission checks and other sensitive checks

### Details

 - should be relatively simple to implement
 - unlocks possibility of reliable service to service chained calls
 - offloads this functionality to service mesh
 - thus no need to put this validation check to services and distribute certificates manually

**Comment by luckymike** [comment]
We would love to see this functionality natively in Consul Service Mesh as well. 

If it helps, here are the Envoy reference docs: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter

**Comment by mirzmaster** [comment]
Came upon this issue in this community forum thread:  https://discuss.hashicorp.com/t/consul-acl-scope/31355

JWT claim-based routing is a capability which Istio offers out of the box (https://istio.io/latest/docs/tasks/security/authentication/jwt-route/) and this one gap results in having to look into other commercial gateway products in order to get JWT middleware.  The other approach suggested in the forum thread above is use of Envoy's escape hatch overrides, although those have several caveats associated.

Having Consul implement JWT claim-based auth and routing for a unified experience with Intentions would be ideal.

**Comment by david-yu** [comment]
We now JWT based authorization within the mesh available with Consul 1.16.0. Please feel free to try this out and give us feedback. Closing this issue, if you feel there are additional use cases we should cover please go ahead and file a new issue. Thank you! https://developer.hashicorp.com/consul/docs/v1.16.x/connect/intentions/jwt-authorization
