### ISSUE TITLE
Request: Create clean distinction between client and server projects

### ISSUE THREAD

**Issue by thatjames** [hashicorp/consul#8592]
#### Feature Description

The consul library is enormous, and can introduce huge latency into projects building this dependency from scratch (which is anyone using a docker image to do so)

As a client, I should be abstracted from the requirements of the server (beyond the API satisfaction). These are separate boundaries and should be treated as such.

Currently, pulling consul results in a folder with 4606 (264 Megabytes) files. Are **all** of these files really needed just to talk to a server instance? I fail to see the relevance of the Azure SDK in this context. 

Note that I am not referring to a move to go modules, I understand the pain in moving dependency management and I don't have a salient solution to this one. 

#### Use Case(s)

- Break the tight coupling between client and server
- Allow for a "lightweight" distribution, rather than a "fat dependency" tree for clients

#### Example

[nats.io](https://github.com/nats-io) demonstrates a clean split between server and client. This is the dependency tree I would expect to see

#### Replicating

I suggest docker for a clean gopath

```
docker run --rm -ti golang:latest /bin/bash
go get -v github.com/hashicorp/consul
find /go/src -name "*.go" | wc -l
du -hs /go/src
```

**Comment by thatjames** [comment]
A workaround I'm using right now is to bake the current consul lib into a base docker image for building. Given I do this to access to a private repo, I'm not too phased by this approach.

But it feels like a problem waiting to catch up to me.

**Comment by rboyer** [comment]
Thanks for the feedback!

The main repository (`github.com/hashicorp/consul`) is not intended to be itself used as a library as it contains all code required to build and operate everything that consul itself does. This repository contains within it a submodule named `github.com/hashicorp/consul/api` which is all you should need to include in your projects to be able to interact with running consul agents via the API.

```
docker run --rm -ti golang:latest /bin/bash

# make sure you are operating in go module mode, and not the deprecated GOPATH mode
mkdir demo ; cd demo ; go mod init demo

# add just the api dependency and populate your local module cache with transitives
go get -v github.com/hashicorp/consul/api

# list the transitives fetched (16)
find /go/pkg -name '*.zip' | wc -l

# size of transitives (83M)
du -hs /go/pkg
```

Aside: one thing you may not have intended in your reproduction snippet is that the `go get` was operating in GOPATH mode rather than go-modules mode since there was no `go.mod` file present and the `GO111MODULE` environment variable was left unspecified.

When I repeat my module-mode variant of your measurement on the root module it results in 155 transitive modules taking up 1010M of space, which is indeed a lot!

**Comment by thatjames** [comment]
Thank you for the feedback!

That really makes so much more sense, I tried looking for a client lib, hadn't thought of an api lib...

Happy to close this
