### ISSUE TITLE
service_id contains spaces It can be registered and added, but cannot be deleted.

### ISSUE THREAD

**Issue by lxyqwer** [hashicorp/consul#8627]
for example:
    curl -X PUT   http://xxxxxx.com/v1/agent/service/deregister/xxx  xxx

**Comment by EmilyBjartskular** [comment]
If you want spaces in service_id you need to surround the query url with quotation marks, otherwise the url is considered as two separate arguments.

`curl -X PUT "http://xxxxxx.com/v1/agent/service/deregister/xxx xxx"`

**Comment by jkirschner-hashicorp** [comment]
For an HTTP API call to work, the URL must be a valid URL. The space character ` ` is not a [valid character in a URL](https://www.urlencoder.io/learn/). Invalid characters can be included using URL encoding, which for example represents ` ` as `%20`.

To remove a service with a space, you can do:
```
curl --request PUT http://xxxxxxx/v1/agent/service/deregister/xxx%20xxx
```

Perhaps debugging things like this would be easier if an error code + error message were returned instead of HTTP code 200 with an empty body. (Similar to #9330 and #10865)

In the case of executing `curl -X PUT http://xxxxxx.com/v1/agent/service/deregister/xxx xxx`, that could have told you something like `service xxx does not exist`, which might have given a clue as to there being something wrong with the ` `.
