### ISSUE TITLE
Does consul support HCL for config files?

### ISSUE THREAD

**Issue by grantr** [hashicorp/consul#895]
HCL is supported for ACL definitions, but it doesn't seem to be supported for config files. Is this a planned feature?

**Comment by ryanuber** [comment]
@grantr eventually! We've had requests for it before so I think it makes sense to add it as long as the JSON format is preserved. The main want seems to be around adding comments to configs/service definitions etc which seems reasonable. Marking as an enhancement.

**Comment by grantr** [comment]
Yep, comments would be great. Thanks @ryanuber!

**Comment by doublerebel** [comment]
:+1:

**Comment by LordFPL** [comment]
:+1:

**Comment by bogdanov1609** [comment]
:+1:

**Comment by xxthegonzxx** [comment]
:+1:

**Comment by wsh** [comment]
:thumbsup:

**Comment by CruzanCaramele** [comment]
:+1:

**Comment by msabramo** [comment]
👍 because I want to put a comment in the config file that indicates that it is managed by Ansible -- e.g.:

```
# {{ ansible_managed }}
```

I can't do this with JSON.

I tried this:

```
"ansible_managed": "XXX",
```

but Consul doesn't like it when it sees keys that it doesn't know about:

```
==> Error decoding '/etc/consul.conf': Config has invalid keys: ansible_managed
```

so I guess if we can't have HCL in the near term, could we have some mechanism for putting keys that Consul ignores that can be used for user metadata -- e.g.: if they start with an underscore or a double underscore?

**Comment by antoineco** [comment]
I like the idea. [Nomad](https://www.nomadproject.io/docs/agent/config.html) supports HCL, so for people using both together this would allow more consistency across configurations.

**Comment by Kourkis** [comment]
👍

**Comment by v6** [comment]
// , This might make it easier on us Puppeteers and Salt Stackers.

**Comment by magiconair** [comment]
#3480 will add HCL support
