### ISSUE TITLE
Getting Started - Health checks part not working?

### ISSUE THREAD

**Issue by devinrsmith** [hashicorp/consul#897]
https://www.consul.io/intro/getting-started/checks.html

I've followed the getting started up until this point, with one server node and one client node.

The `/etc/consul.d` directory didn't exist though. I manually created it and redid the `echo` commands, but upon SIGHUP or restart the node doesn't seem to pick up the health checks.

**Comment by ryanuber** [comment]
Hey @devinrsmith,

It looks like you may have found an oversight in our getting started guide. In order to get this to work, you can pass the `-config-dir=/etc/consul.d` argument to the agent (documentation on that option is [here](https://www.consul.io/docs/agent/options.html#_config_dir). Once that is done, then using `SIGHUP` should allow Consul to reload its configuration files. If no `-config-dir` is specified, then Consul won't know where to load the files from.

We'll get this fixed up in the guide. Thanks!

**Comment by ryanuber** [comment]
Quick note: we actually *do* mention `/etc/consul.d`, but if a user follows the guide all the way through, the join page [here](https://www.consul.io/intro/getting-started/join.html) has the agents started without the option.

**Comment by devinrsmith** [comment]
Makes sense, thanks for the quick update!

**Comment by robinroestenburg** [comment]
@ryanuber: I just ran into this one as well.. it was fixed in #1127 but that commit has not made it to the website yet.

**Comment by slackpad** [comment]
Website was pushed for the 0.6.0 release.
