### ISSUE TITLE
consul command for bulk loading from config files

### ISSUE THREAD

**Issue by rhelmer** [hashicorp/consul#899]
We have a project using Consul that has a rather large set of key/value config pairs, some of which need to be customized. The easiest way we've found to do this so far is to have a set of config files (one per consul prefix) and use a simple script to bulk load these into Consul:

https://github.com/mozilla/socorro-infra/tree/master/socorro-config

This way we can keep the reference configs revision controlled and commented, and load them into Consul with a simple operation (it'd be even better if it was totally atomic e.g. PR #886 but not at all required for this to be useful)

Instead of having to provide our own bulk load script, it'd be nice if Consul supported something like:

`consul load -prefix <prefix> <config_file>`

**Comment by ryanbreen** [comment]
You might be interested in http://github.com/cimpress-mcp/git2consul.

**Comment by rhelmer** [comment]
@ryanbreen that is an interesting approach! Automatically mirroring git commits into Consul via a webhook is a very interesting idea.

**Comment by ryanbreen** [comment]
@rhelmer, yeah, I thought this might be a good fit for you because it seems our usage is pretty similar.  We have a bunch of configuration files we want to splat out onto the filesystem of remote hosts, so we use git2consul because we want to manage / version those in git and distribute them using Consul.  We then use http://github.com/cimpress-mcp/fsconsul to write them to disk on remote systems.  It makes a nice complement to git2consul.

If that seems like a good fit for you, it might make sense to close this ticket.  It's up to @armon and @ryanuber, of course, but IMHO it seems unnecessary to modify Consul itself if the constellation of tools around Consul can provide the desired functionality.

**Comment by ryanuber** [comment]
The API is definitely the best way to get things loaded into Consul's KV store. Using a script or other tooling are both viable options that I think cover this fairly well. Currently we don't have plans to add this functionality in a separate command, so I'll close this for now. Thanks for the suggestion!
