### ISSUE TITLE
Error cannot "find package github.com/hashicorp/consul/api" in GoLang

### ISSUE THREAD

**Issue by mehdihadeli** [hashicorp/consul#9057]
Hi,
in my app, I use the `github.com/hashicorp/consul/api` module but when I run my app I get the bellow error:

``` bash
main.go:18:2: cannot find package "github.com/hashicorp/consul/api" in any of:
        /usr/lib/go-1.13/src/github.com/hashicorp/consul/api (from $GOROOT)
        /home/mehdi/go/src/github.com/hashicorp/consul/api (from $GOPATH)
```
How can I resolve this problem?

**Comment by jsosulska** [comment]
Hi @mehdihadeli ,

Thank you for your question.

This would be better suited for our [Discuss forum](https://discuss.hashicorp.com/c/consul/29). Our very helpful community can often help where others can't! When posting there, please include your go.mod file so that others can see how you are importing the [API package](https://pkg.go.dev/github.com/hashicorp/consul/api@v1.7.0).

I will close this thread.
