### ISSUE TITLE
Why the manual steps and shutdown of the whole cluster on outage

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/consul#911]
The consul guide (https://www.consul.io/docs/guides/outage.html) for outages says that one has to manually remove the failed server from all `raft/peers.json` files. Why is that? Further in order to change that file one has to shutdown all server nodes, which collapses the whole cluster. I think this is not a very cluster like behaviour and would make the whole cluster unavailable. Why isn't there a command to just ignore/remove the failed server from the other servers? Or why does consul not automatically remove the failed server as it also removes failed members after some time?

In our case, we have very small clusters (5-10) and every node is a server, because we don't want the overhead of having 3 extra consul servers for a cluster of 5 nodes. Thus when one node fails, our whole cluster would need manual reconfiguration.

**Comment by kaelumania** [comment]
Am I right that the raft consensus protocol is implemented as proposed in the paper. Therefore the leader is sending a heartbeat to each other server instead of relying on the gossip mechanism?

**Comment by highlyunavailable** [comment]
If you are removing or replacing a server, you can just use consul force-leave to eject the server from the cluster (this works for clients as well to remove old clients). This should satisfy `Why isn't there a command to just ignore/remove the failed server from the other servers?`

The Outage Recovery guide is only if you've suffered a failure of "n/2+1" nodes - i.e. if you've completely lost quorum due to losing a majority of nodes. If you only need to replace 1 server at a time, you can simply bring the new server up first, shut the old server down, then force-leave it to shove it out of the cluster or perform a graceful leave on the way out. This is actually how I upgrade my Consul cluster to new versions with EC2 - new server comes up with the new version, joins the cluster as a Raft peer ("Server" in Consul parlance), then I shut down the old server and force-leave it.

The reason you need to edit the Raft peers during outage recovery is that the node set is also replicated via Raft, so if you no longer have quorum, you can't replicate the changed node set because your remaining nodes cannot gain consensus on what the Raft peer list should be, due to the consensus set including the failed majority.

**Comment by armon** [comment]
@kaelumania The explanation given by @highlyunavailable is dead on. The peers file is only ever edited during an outage, which is defined as a loss of quorum for Consul. This means a majority of servers are offline or cannot communicate. In that case, the cluster cannot safely make changes to the peer set because it is unable to coordinate. Typical operation of adding/removing servers does not require that process.

Closing the ticket, but please re-open if you have an issue!

**Comment by kaelumania** [comment]
@armon @highlyunavailable thank you very much. Can you say something about my second comment?

**Comment by highlyunavailable** [comment]
Any "server" can serve a read, but depending on how consistent you require your read to be, there may be round-trips needed to `N/2+1` members of the cluster to verify the value is current. Check out the [HTTP API](https://www.consul.io/docs/agent/http.html) docs, specifically the "Consistency Modes" section.

The short answer is: The leader is involved in "default" and "consistent" level reads though it may not directly service the read. The "consistent" mode involves N/2+1 servers, one of which must be the current leader. The "stale" consistency mode allows any server immediately service a read. In other words, yes, all non "stale" consistency mode reads will eventually talk to the leader though other servers may actually be servicing the request (that is, actually have an open TCP connection to the client).

Watches are a special case - as I understand them (and correct me if I'm wrong, @armon), the state change events are what trigger watches to complete, so the act of writing to the local state machine as part of replicating an update across the cluster will cause the server to send out the data - this is not the same as a request to the leader and a response from the leader.

**Comment by armon** [comment]
@kaelumania The explanation by @highlyunavailable is almost perfect. Watches actually aren't a special case, and are just like normal reads and even will respect the consistency modes. Raft is implemented like the paper, and the Serf/Gossip data is not used for replication.

In the "default" read mode, all reads are serviced by the leader. The "consistent" read mode forces an additional heartbeat round trip on read. The "stale" mode allows any server to service the read, and thus does load shedding from the leader.

Hope that helps!

**Comment by kaelumania** [comment]
@highlyunavailable thanks once again. If I understand you right, any server can answer a request, but internally checks the value with the leader?

@armon Does that mean that if I have 1000 nodes with each 2 watches (via `consul watch`) there are 2000 blocking queries to the leader node? Further for stale reads how is decided which server answers the request or does the client address a specific server, e.g.  when read request is send out via serf and arrives multiple servers. How is ensured, that only one server answers or is the client responsible for deduplication? How do I configure watches to use stale consistency mode?

Thanks.

**Comment by armon** [comment]
@kaelumania That is correct, there would be 2K blocking queries. A client can't pick the server that answers, instead a random server is always selected under the hood. The requests are not sent via Serf, the client uses a dedicated TCP connection for RPC requests so you only ever get one response, no need to handle de-duplication

Blocking queries take the "?stale" flag to enable that mode, I'm not actually sure this is exposed for watches however. I'll make a ticket for it!

**Comment by kaelumania** [comment]
@armon thanks, it might be useful to add an article to the consul documentation about which parts use serf and which parts use serf etc.
