### ISSUE TITLE
[Streaming] Order of results in /health is modified when streaming is enabled for cached queries

### ISSUE THREAD

**Issue by PHBourquin** [hashicorp/consul#9239]
#### Overview of the Issue

While testing streaming on Consul 1.9.0-beta2, we encountered the following issue:

When streaming is enabled, results on /health endpoint are not sorted in a deterministic way

#### Reproduction Steps

Steps to reproduce this issue, eg:

Register 100 instances for a service
Run ` curl '127.0.0.1:8500/v1/health/service/my-fake-service?pretty&cached' | jq '.[].Node.Node' -r | head`

##### With streaming disabled

The results are sorted the same way as any non cached query:

```
$ curl '127.0.0.1:8500/v1/health/service/my-fake-service?pretty&cached' | jq '.[].Node.Node' -r | head
agent-1
agent-10
agent-100
agent-1000
agent-10000
agent-10001
agent-10002
agent-10003
```

##### With streaming enabled

The results are not sorted the same way for cached queries:

```
$ curl '127.0.0.1:8500/v1/health/service/my-fake-service?pretty&cached' | jq '.[].Node.Node' -r | head
agent-813
agent-11431
agent-12555
agent-2092
agent-7112
agent-8042
agent-1093
agent-17152
agent-18740
agent-763
```

### Consul info for both Client and Server

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease = beta2
        revision = db08bdc1
        version = 1.9.0
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 66
        max_procs = 2
        os = linux
        version = go1.14.9
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 15
        members = 6
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

Linux

**Comment by pierresouchay** [comment]
While the semantics is identical, it breaks assumptions on HTTP's client side about ordering of responses

**Comment by dnephin** [comment]
Thank you for this report! I went looking to see how we sort these results when streaming is disabled. The only explicit sort I found was [`sortNodesByDistanceFrom`](https://github.com/hashicorp/consul/blob/master/agent/consul/health_endpoint.go#L244) which I believe uses the [`near` query parameter](https://www.consul.io/api-docs/health#near). Are you using  that query parameter?

When that is not set, it appears to be doing a stable sort, so I guess it is returning the order in which they are stored in memdb.

We don't have access to the coordinates to perform a distance sort. I guess we need to ensure that the old non-streaming cache is used if the `near` query parameter is set.

I think we have a couple options for sort order with streaming:
1. [lexicographical order](https://en.wikipedia.org/wiki/Lexicographic_order) ascending, using the node name
2. numerical ascending order, using the `Node.RaftIndex.CreateIndex`

I believe the second option should be roughly the same as the previous sort order of results. Does that sound right to you?

**Comment by dnephin** [comment]
Also, it would be great to learn more about the use case that requires ordering, so that we can make the right decision about what the order should be. Are you interested in a specific order, or just that it is consistent with the non-streaming result?

**Comment by pierresouchay** [comment]
Hello @dnephin ,

> Thank you for this report! I went looking to see how we sort these results when streaming is disabled. The only explicit sort I found was sortNodesByDistanceFrom which I believe uses the near query parameter. Are you using that query parameter?

I did look the same way, and while we don't use that much `near`, some applications are relying on the order being stable (for instance some LB systems might use a subset of records to select only a few nodes).

I completely understand that the order with near might be hard to achieve (since we don't have the coordinates ion the context, but I think having at least a constant order (if the order could be the same as in `memdb`, that would be an extra bonus, but we could live without this) would reduce significantly the possibility of breaking something).

For now, the order is not stable at all (changes at every update). About the possible orders:
 * lexical order should be fine (but it should sort probably both node.name, node.id and service ID for multiple identical services on a given node). It also sounds what is currently doing memdb (see below)
 * Using indexes: might be fine as well, but I wonder if some tools that do sync third-party systems (for instance Nomad, Hadoop Mesos or k8s sync systems) might be deleting/creating systems all the time (for instance @ltagliamonte-dd is working in his company in those kind of designs), so this looks like a more disruptive approach to me.

### Test about lexical order:

```
curl http://localhost:8500/v1/health/service/consul-agent-http | jq '.[]|(.Node.Node + .Service.ID)' > default_order.txt
sort default_order.txt > lexical_order.txt
diff default_order.txt lexical_order.txt
```
=> gives not result, so I think it is exactly the order of memdb by default, sounds like a great choice!

### About ?near
While not implementing `near` for us should not be an issue, it might be documented somewhere that `near` is not working for cached queries with streaming enabled
