### ISSUE TITLE
Consul cannot elect leader when one node is down

### ISSUE THREAD

**Issue by pmkpa** [hashicorp/consul#9253]
Consul 1.4.0-dev
There is a scenario that consul cannot elect leader. We have 3 consul one per node. We are using daemonset in yaml.
When we shutdown VM  where consul has elected leader , election is restarted as expected to elect new leader but fails due to time out. Election keeps restarting and keeps failing. 

I have noticed that this happens only when dnsPolicy is None. When i change dnsPolicy to ClusterFirst issue is not reproduced.

I keep getting these logs in consul: 
{"process":"consul_server","time":"2020-11-15T02:54:32.500043000Z","service":"consul","output":"    2020/11/15 03:54:32 [INFO] raft: Node at 10.254.194.24:8300 [Candidate] entering Candidate state in term 67588"}
{"process":"consul_server","time":"2020-11-15T02:54:32.595380000Z","service":"consul","output":"2020/11/15 03:54:32 [WARN] raft: Unable to get address for server id 9e84e3b9-5780-cc95-eeb0-e0d7b4e97862, using fallback address 10.254.17.9:8300: Could not find address for server id 9e84e3b9-5780-cc95-eeb0-e0d7b4e97862"}
{"process":"consul_server","time":"2020-11-15T02:54:32.946249000Z","service":"consul","output":"    2020/11/15 03:54:32 [ERR] raft: Failed to make RequestVote RPC to {Voter 9e84e3b9-5780-cc95-eeb0-e0d7b4e97862 10.254.17.9:8300}: dial tcp 10.254.194.24:0->10.254.17.9:8300: i/o timeout"}
{"process":"consul_server","time":"2020-11-15T02:54:38.698132000Z","service":"consul","output":"    2020/11/15 03:54:38 [WARN] raft: Election timeout reached, restarting election"}
{"process":"consul_server","time":"2020-11-15T02:54:38.698132000Z","service":"consul","output":"    2020/11/15 03:54:38 [INFO] raft: Node at 10.254.194.24:8300 [Candidate] entering Candidate state in term 67589"}
{"process":"consul_server","time":"2020-11-15T02:54:38.779858000Z","service":"consul","output":"2020/11/15 03:54:38 [WARN] raft: Unable to get address for server id 9e84e3b9-5780-cc95-eeb0-e0d7b4e97862, using fallback address 10.254.17.9:8300: Could not find address for server id 9e84e3b9-5780-cc95-eeb0-e0d7b4e97862"}
{"process":"consul_server","time":"2020-11-15T02:54:40.133690000Z","service":"consul","output":"    2020/11/15 03:54:40 [ERR] agent: Coordinate update error: No cluster leader"}
{"process":"consul_server","time":"2020-11-15T02:54:42.595626000Z","service":"consul","output":"    2020/11/15 03:54:42 [ERR] raft: Failed to make RequestVote RPC to {Voter 9e84e3b9-5780-cc95-eeb0-e0d7b4e97862 10.254.17.9:8300}: dial tcp 10.254.194.24:0->10.254.17.9:8300: i/o timeout"}
{"process":"consul_server","time":"2020-11-15T02:54:46.941858000Z","service":"consul","output":"    2020/11/15 03:54:46 [WARN] raft: Election timeout reached, restarting election"}

**Comment by jsosulska** [comment]
Hi @pmkpa 

This is for a substantially older build of Consul. I also noticed you mentioned "YAML" which makes me think you are trying to run this in Kubernetes. I don't believe Consul had a fully functioning helm chart until 1.7, so that also may be a factor.

The latest release that just went G.A. is 1.9 as of today. 1.4 doesn't have many of the great new features that Consul provides. If you are not running this on Kubernetes, and are required to run Consul 1.4, I recommend getting the [latest binary](https://releases.hashicorp.com/consul/) for 1.4.5. However, understand that because of the age of the release, there is not going to be any additional changes made. 

For the latest Consul binary: [1.9](https://releases.hashicorp.com/consul/1.9.0/)
For the latest Consul Helm Chart: [v.0.26.0](https://github.com/hashicorp/consul-helm/tree/v0.26.0)

I hope this helps. I will be closing the issue in the meantime due to this being a particularly old version.
