### ISSUE TITLE
Stopped GCP nodes (Compute engines), showing up as healthy on consul

### ISSUE THREAD

**Issue by anmol1vw13** [hashicorp/consul#9355]
Consul Version Used: 1.4.0

Stopped GCP nodes still show up as healthy. 
For example, for one of the nodes, the **Service Check** fails and it should, since the ping fails but the **Serf Health Status passes** and I am not able to find a logical explanation for this.
![image](https://user-images.githubusercontent.com/13599208/101631582-93682900-3a4a-11eb-9f51-812d4fe802d5.png)
While for one of the other nodes belonging to the same service, which has been stopped as well, both the **service check** and **serf health status** pass.
![image](https://user-images.githubusercontent.com/13599208/101631673-bbf02300-3a4a-11eb-98fe-c8b66c965a3c.png)
When I check consul members though, both of them are shown to be in **left** state which is contradicting what's showing up on the UI. Need some direction to digest this :')
![image](https://user-images.githubusercontent.com/13599208/101632096-649e8280-3a4b-11eb-9e10-6a0b254ba420.png)

**Comment by anmol1vw13** [comment]
@jsosulska Can you please have a look at this?

**Comment by anmol1vw13** [comment]
@jsosulska Any leads on this? Do you need anything from me?

**Comment by jsosulska** [comment]
Hi @anmol1vw13 

Sorry for the delay in responses. Thank you for the follow up! 

As I'm looking this over, nothing is readily apparent as to why you're running into this. Can you please provide some replication steps? Maybe include some client/server configs with the sensitive bits removed/replaced so I can spin this up on my own. A copy of the service definition would also help, so I can understand a bit about what check you are using.

Thanks again for your patience!

**Comment by johncowen** [comment]
Hi @anmol1vw13 👋 

Would it be possible for you to look at the HTTP responses to those pages you are showing and seeing if the HTTP response matches up with the UI? Then we can figure out if this is an issue frontend or backend.

If you open up the WebInspector in your browser and look in the Network panel you should be able to see responses for:

```js
/v1/internal/ui/node/g-lambda-temporiser-app-b-01
// and
/v1/internal/ui/node/g-lambda-temporiser-app-b-02
```
Both responses will have a `Checks` property if you can find the healthchecks in there and see if the `Status` values match up with the UI then that would be a first step to getting to the bottom of what the issue is.

Thanks

**Comment by jkirschner-hashicorp** [comment]
Hi @anmol1vw13,

We don't have enough information at this time to take any further action and haven't heard any updates in a few months, so I'm closing this for now.

If you are still experiencing this issue, please reopen and provide some of the additional information requested by @jsosulska and @johncowen.

Thanks!
