### ISSUE TITLE
Unable to deregister service if multiple nodes available

### ISSUE THREAD

**Issue by frankiedrake** [hashicorp/consul#9415]
We have consul with multiple nodes in our environment.
I'm using `spring-cloud-starter-consul-discovery` do register my app instances as a services. And I faced a problem when deregistering services. I'm getting an error:
```
Unknown service {"<service-name>" {}}
```
I tried to repeat the same request with a `curl` and got the same error. 
Command I execute:
```
curl -v -X PUT -H 'X-Consul-Token: ***' https://consul-host/v1/agent/service/deregister/<service-name>
```

What I noticed is that repeating the request multiple times results in success service deregistration.
I guess that what happens is some round-robin behavior, and each time the request is falling in a different node.
I don't know if this is an expected behavior, but maybe it's possible to find some workaround for this issue.
What I need is to deregister my service automatically when stopping/rebooting the application.

**Comment by jkirschner-hashicorp** [comment]
Hi @frankiedrake ,

My apologies for the delayed response. I'm unfamiliar with the [spring-cloud-consul Github project](https://github.com/spring-cloud/spring-cloud-consul). It may make sense to post there to understand why service deregistrations through spring-cloud-consul aren't working.

---

However, I can speak to why the `curl` command you issued may not have worked: you may have used a service _name_ rather than a service _id_ in the call. The [deregister endpoint](https://www.consul.io/api-docs/agent/service#deregister-service) requires a service _id_.

This is a very easy mistake to make. We should make it easier to avoid, or detect/fix, this mistake. I'm tracking such improvements in #10861.
