### ISSUE TITLE
Ingress service and Consul DNS

### ISSUE THREAD

**Issue by pvyaka01** [hashicorp/consul#9479]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
Unable to call ingress service using \<service\>.ingress.consul

A paragraph or two about the issue you're experiencing.
When we setup ingress service, unless we know the host and listen port, we cannot call the service using \<service\>.ingress.consul:\<listen_port\>

This limits our ability to setup multiple ingress services and also requires hard-coding the service end points. Consul DNS returns the port we use to start envoy instead of ingress listening port.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create envoy ingress.hcl with something like:
Kind = "ingress-gateway"
Name = "web-ingress"

Listeners = [
  {
    Port = 8080
    Protocol = "http"
    Services = [
      {
        Name = "web",
        Hosts = ["*"]
      }
    ]
  }
]

2. Start ingress envoy on the first node **node1:**
consul connect envoy -gateway=ingress -register -service web-ingress -admin-bind="0.0.0.0:19000" -admin-access-log-path=/var/log/envoy/envoy_admin.log -address '{{ GetInterfaceIP "eth0" }}:8888'

3. Start ingress envoy on a second node **node2:**
consul connect envoy -gateway=ingress -register -service web-ingress -admin-bind="0.0.0.0:19000" -admin-access-log-path=/var/log/envoy/envoy_admin.log -address '{{ GetInterfaceIP "eth0" }}:8887'

4. How do we call ingress service now? The only way seems to be **http://\<node1\>:8080/ or http://\<node2\>:8080/**
What happens when ingress on node1 or node2 is down? There's no HA. Am I calling this the wrong way?
dig @127.0.0.1 -p 8600 web.ingress.consul SRV
web.ingress.consul. 0   IN      SRV     1 1 8888 \<node1\>
web.ingress.consul. 0   IN      SRV     1 1 8887 \<node2\>

a. dig command returns port as 8888 or 8887
b. Ingress is listening on port 8080

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 2
        check_ttls = 0
        checks = 12
        services = 9
build:
        prerelease =
        revision = a417fe51
        version = 1.9.0
consul:
        acl = disabled
        known_servers = 1
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 126
        max_procs = 2
        os = linux
        version = go1.15.5
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 8277
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 68518
        members = 24
        query_queue = 0
        query_time = 99


```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 2
        check_ttls = 0
        checks = 7
        services = 6
build:
        prerelease =
        revision = a417fe51
        version = 1.9.0
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = x.x.x.x:8300
        server = true
raft:
        applied_index = 2010823
        commit_index = 2010823
        fsm_pending = 0
        last_contact = 0
        last_log_index = 2010823
        last_log_term = 8288
        last_snapshot_index = 2000854
        last_snapshot_term = 8287
        latest_configuration = [{Suffrage:Voter ID:e5bcd96a-9c66-a8f4-bb43-8a722a14d623 Address:x.x.x.x:8300}]
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 8288
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 632
        max_procs = 4
        os = linux
        version = go1.15.5
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 8277
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 68518
        members = 24
        query_queue = 0
        query_time = 99
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 1
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.
Red Hat Enterprise Linux Server release 7.8 (Maipo)

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by DerekStrickland** [comment]
Hi and thanks for using Consul!  I'm really sorry to hear that you are having issues. I'd like to ask a few questions to better understand your situation.

- What is your use case?
- Are you using Consul on Virtual Machines or in Kubernetes?
- Are you trying to configure service to service communication **inside** the mesh or allow for **external** traffic to reach services hosted inside the mesh?
- Are you trying to make make calls between 2 different federated Consul datacenters?

I am unsure why you would be using <service>.ingress.consul to call your ingress gateway service since that URL would only resolve **inside** the service mesh, but I can try to help by providing some information about different type of connection scenarios in Consul in general.

- [Service Mesh](https://learn.hashicorp.com/tutorials/consul/get-started-service-networking?in=consul/getting-started) within a single datacenter, can be configured to allow services to interact within the same datacenter using DNS resolution or proxy configuration - if you want to call your web service for instance you don't need to call it using web.ingress.consul, you could just use `web.service.consul` or you could register and upstream with your proxy
- [Mesh Gateways](https://learn.hashicorp.com/tutorials/consul/service-mesh-gateways) allow services in different Consul datacenters to communicate across the WAN. If you add a mesh gateway, and a little extra configuration to your proxies, or segments in your Consul urls, you can call services hosted in different datacenters.
- [Ingress Gateways](https://learn.hashicorp.com/tutorials/consul/service-mesh-ingress-gateways) allow external traffic to access services running inside the mesh - in this scenario, I don't think your client would use web.ingress.consul because that DNS name has no meaning outside the service mesh. I think you would need to point **external** DNS to the exposed ingress gateway by IP/Port. If you are using Kubernetes this would likely be your LoadBalancer for instance. For VMs, you shouldn't need two ingress gateways.  The diagram and details at [this page](https://www.consul.io/docs/connect/gateways/ingress-gateway) should help you visualize how the Ingress Gateway actually acts as a _single, externally available front_, for however many instances of the service you are running inside the service mesh.

If this information doesn't help you resolve your situation, please post some details about your use case as well as some details about the client that is trying to reach the service. With more information about your use case we might be able help more.

**Comment by pvyaka01** [comment]
Thanks Derek for responding. Consul is on VMs, not Kubernetes. Yes, external traffic to reach services hosted inside the mesh. Perhaps I'm a bit confused. We've three node cluster (three masters). I'm starting envoy using this command:
"consul connect envoy -gateway=ingress -register -service ingress-service \
   -address '{{ GetInterfaceIP "eth0" }}:8888'"

Should I start this on master node or a specific agent node? What happens when that envoy process dies? The dig command sees one server as explained in the tutorial or two if I start envoy on multiple nodes as it should.

**Comment by pvyaka01** [comment]
Sorry...think it was confusion on my part. Looks like I need to start envoy on each of the downstream nodes. Let me check my setup again.

**Comment by pvyaka01** [comment]
Figured out need to start ingress on the nodes that are receiving traffic. Think it's working as expected
