### ISSUE TITLE
Adding a service w IP different from localhost / consul 0.4.1

### ISSUE THREAD

**Issue by dynnamitt** [hashicorp/consul#950]
When adding a service w IP different from localhost, like this

    {
        "service": {
                "id" : "redis-master",
                "name": "redis",
                "tags": ["redis","db"],
                "Address" : "10.133.172.216",
                "port": 6379
        }
    }

It always REWRITES address to whatever localhost / private_ip points at...
I'm using version 0.41 and just one consul instance (... -server -bootstrap-expect 1 -bind=0.0.0.0 )

Is this to be expected.. will 0.5 work different?

Maybe IPs in "Address" values need a running consul agent to be accepted, but if so PLEASE document this better here https://www.consul.io/docs/agent/services.html

**Comment by dynnamitt** [comment]
Rephrased issue:
Cannot register service address outside of consul cluster in version 0.4.1

**Comment by highlyunavailable** [comment]
The ability to use service-specific addresses was added in 0.5.0, it is not present in 0.4.1.

https://github.com/hashicorp/consul/blob/master/CHANGELOG.md

* Support for service specific IP addresses. This allows the service to advertise an address that is different from the agent. [GH-229] [GH-570]

Also, the docs are for the current version (0.5.1).

One oddity in Consul configs: any parameter that isn't a "known" one is silently ignored since it's being deserialized to a dictionary but then that parameter is never looked at.

**Comment by dynnamitt** [comment]
Thx
