### ISSUE TITLE
arm64/armv7 DEB/RPM repo support

### ISSUE THREAD

**Issue by dkowis** [hashicorp/consul#9542]
Found this, would like to bring it to greater attention, if at all possible:
https://discuss.hashicorp.com/t/apt-repo-with-arm64/19418

#### Feature Description

Have the DEB/RPM support more than just x86_64. I've got several aarch64 boxes now, and it'd be nice to use on rpis as well.

#### Use Case(s)

I've got rpi's and pine64's managed with chef, and it would be super helpful to have debian packages to install consul with.

**Comment by neurostream** [comment]
Thanks for opening this.  With an increasing count of aarch64 developer workstations and interest in ARM compute both in cloud and IoT, this would be awesome.

I've always made great and thankful use of the different raw binary build outputs they've always already provided.  Our build chain is pretty air-gapped with only a couple of early entry points to induct external (3rd party ) artifacts; and _there is a preference for pulling new ones in through packaging_ repos schemes integrated with distributions we use.

For now, we have a custom external artifact import job that scrapes releases.hashicorp.com for aarch64 updates, which triggers our own rpm packaging. So, just as we've enjoyed having the official the x86_64/amd64 packages since 2020, we'd also just as much rather use official Hashicorp Linux repos for aarch64/arm64 as well.

**Comment by blake** [comment]
32-bit and 64-bit ARM packages are now available in the Linux package repositories. Support for these architectures was added by PR #11417.

Use the following command to add the repo to your APT sources for Ubuntu/Debian.

### Debian
**32-bit**
```shell-session
$ sudo apt-add-repository "deb [arch=armhf] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
```

**64-bit**
```shell-session
$ sudo apt-add-repository "deb [arch=arm64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
```

## CentOS/RHEL

```shell-session
$ sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
```
