### ISSUE TITLE
Feature Request: Show node maintence mode in `consul members`

### ISSUE THREAD

**Issue by nicholascapo** [hashicorp/consul#957]
It would be nice if I could see the maintenance status in the output of consul members.

For example:

```
Node           Address              Status   Type    Build     Protocol
Node1          10.240.180.110:8301  left     client  0.5.1dev  2
Node2          10.240.102.146:8301  alive    server  0.5.1dev  2
Node3          10.240.83.117:8301   maint    server  0.5.1dev  2
Node4          10.240.168.242:8301  alive    server  0.5.1dev  2
Node4          10.240.168.142:8301  failed   server  0.5.1dev  2
```

**Comment by ryanuber** [comment]
I agree it would be nice to be able to see the nodes in maintenance mode from a bird's-eye view like this. I don't think it should overload the status though, since that information is still useful to know even during a maintenance. Maybe we should instead extend the output of the `maint` command in list mode, or add an additional switch to print maintenances within the cluster. Marking as an enhancement, thanks!

**Comment by nicholascapo** [comment]
Sure. An additional column would be fine. It would also be nice if the
maint command would list other nodes that are in maint mode, other than
just itself.

Thanks.

**Comment by adilbaig** [comment]
Has this been added to consul. This is one thing we need the web interface for, and it would be much nicer if we can just see it from `consul members`

**Comment by slackpad** [comment]
Hi, this never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves.

A tricky bit here is that this combines information from Consul's catalog with the `consul members` information, which is all local in the Serf instance. This means that we'd need to RPC for the maintenance status which makes `consul members` much more complicated.
