### ISSUE TITLE
Continuously writing same values to API causes nodes to intermittently appear

### ISSUE THREAD

**Issue by looprock** [hashicorp/consul#963]
I testing with a project that wrote the same data to the consul API service endpoint every 5 seconds. Whenever I would do this, I would see those nodes disappear and reappear from files created by consul-template. 

The code used to create the scenario is here: 
https://github.com/looprock/dockingstation/commit/c83087044e5847339d91d1e85e3623f0309cbc3e

Sample payload data:
{'port': 32776, 'tags': ['looprock', 'v0-1'], 'name': u'versiontest-service-v0-1', 'check': {u'interval': u'10s', u'http': u'http://localhost:32776', u'timeout': u'1s'}}

**Comment by ryanuber** [comment]
Hi @looprock,

Could you provide some debug logs from Consul? It would be helpful to know what is going on from that perspective. Nodes which are considered unhealthy (1 or more failing node-level checks) would be dropped from the output, so that part is intended behavior.

Any logs, especially with the `-log-level=debug` verbosity option, would help a ton.

**Comment by ryanuber** [comment]
Hey @looprock,

Were you able to resolve this? If you are still having trouble, providing some logs would definitely help us figure out what's going on here. Thanks!

**Comment by looprock** [comment]
Sorry I was unable to reproduce this after stopping consul on the servers, clearing out state, and restarting. Not sure what was going on.
