### ISSUE TITLE
[DNS][Streaming] DNS service queries do not filter with tags anymore when streaming is enabled

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#9695]
### Overview of the Issue

When streaming is enabled, on Consul 1.9.x, the DNS queries do not filter on tags anymore.

#### In 1.9.x branch, start agent with streamig enabled:

```
$ consul agent -dev -hcl 'rpc{enable_streaming=true}' -hcl use_streaming_backend=true -hcl 'dns_config{ allow_stale=true, max_stale="3h", use_cache=true, "cache_max_age"="3h"}'

# Query on non-existing tag
$ dig @localhost -p 8600 wrongtag.consul.service.consul +short
127.0.0.1
$
```
=> There should be no result, because wrongtag does not exists.

#### Without streaming
```
$ consul agent -dev -hcl 'dns_config{ allow_stale=true, max_stale="3h", use_cache=true, "cache_max_age"="3h"}'

# Query on non-existing tag
dig @localhost -p 8600 wrongtag.consul.service.consul +short
$
```
=> Expected => not results => correct

**Comment by pierresouchay** [comment]
This bug is actually worse, it also happens on health:

The URL: http://localhost:8500/v1/health/service/consul?tag=wrongtag&index=13&wait=5s

is returning data, while removing index=13 does not return any result (expected)

**Comment by banks** [comment]
Thanks Pierre. That's an important one to get fixed before the feature is GA!

I think this should be implemented the same way that general filtering works - basically on agent cache side. I guess we missed the case of tags rather than the more general filter expressions. I _think_ fixing it in one place will make DNS work again as well.

CC @dnephin.

**Comment by pierresouchay** [comment]
Meta filtering seems to work however:
```
curl -fs --get "localhost:8500/v1/health/service/consul?index=13&wait=5s&" --data-urlencode 'filter=Service.Meta.non_voter == "true"'
[]
```
=> ok

also:
```
curl -fs --get "localhost:8500/v1/health/service/consul?index=13&wait=5s&" --data-urlencode 'filter=Service.Meta.non_voter == "false"'
[
    {
...
    }
]
```
=> works

So, seems to apply only on tag filtering

**Comment by dnephin** [comment]
Thank you for the bug report!

I believe `tag` , `node-meta`, and `near` query params do not work because they were previously implemented on the server side.

We should be able to implement `tag`, and `node-meta` filtering pretty easily in the client using bexpr filter, but `near` will likely not be possible, so we'll need to handle that using blocking queries.
