### ISSUE TITLE
Question about using DNS for start_join

### ISSUE THREAD

**Issue by MrMMorris** [hashicorp/consul#972]
So I have this config:
```
{
  "start_join": [
    "consul.service.consul"
],
  "disable_remote_exec": true,
  "domain": "consul.",
  "data_dir": "/opt/consul/data",
  "log_level": "INFO",
  "node_name": "csm-tv-prod-1",
  "server": false,
  "client_addr": "0.0.0.0",
  "bind_addr": "0.0.0.0",
  "datacenter": "ec2",
  "rejoin_after_leave": true,
  "leave_on_terminate": true
}
```

Originally, I had the private IPs of the cluster for start_join, but I had recently set up DNS so I thought I would use the service DNS name. **This is not supposed to be possible, correct?**

I quickly realized that the client would need to join the cluster in order for the DNS to resolve, but the DNS can't resolve until it has joined the cluster...

**Comment by highlyunavailable** [comment]
You are correct, that's not possible. You can use DNS, but you can't use Consul's DNS provider with start_join since as you correctly stated, Consul isn't joined yet..

I have a Salt state that does something like this:
```
{% set server_list = [] %}
{% for server_id, server in salt['boto_ec2.get_instances']({'tag:role':'consul'}, region=salt['grains.get']('ec2_region')).iteritems() %}
{% if 'ip_address' in server %}
{% do server_list.append(server['ip_address']) %}
{% endif %}
{% endfor %}

{% if server_list %}
Ensure Consul has servers to join to:
  file.managed:
    - name: {{ [paths['config_path'], 'join.json']|join(path_sep) }}
    - source: salt://consul/files/definition.json.jinja
    - template: jinja
    - context:
        definition:
          start_join: {{server_list|json}}
    - listen_in:
      - service: Ensure Consul service is started
{% endif %}
```

What it's saying is "Get all EC2 instances in my current region that are tagged "role"="consul" and populate their IPs into an array, which then gets written to `join.json` in the config directory". This state runs every boot and populates all 3 servers per region into the join.json file. If the server membership changes while the server is up, it's fine because the normal gossip changes will inform it, so it really only needs to know on boot.

**Comment by MrMMorris** [comment]
@highlyunavailable thanks for the tip!
