### ISSUE TITLE
Pages in Consul becomes unavailable. 

### ISSUE THREAD

**Issue by ashish235** [hashicorp/consul#990]
I 've a setup with 4 nodes ( 3 consul servers + 1 Consul client). Now if the 1-2 server goes down and I bring them up and make it join the cluster this happens. The client also fluctuates (joins and leaves the cluster). Not sure if ARP issue or anything else. 
  
Below is the error I get on the UI on clicking on the Key/value link. 

"HTTP error code from Consul: 500 Internal Server Error

This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.

Otherwise, please report any unexpected issues on the GitHub page."

**Comment by armon** [comment]
@ashish235 Check the log files on the Consul servers or whatever machine is hosting the UI. My guess is that you have lost quorum / leadership due to the servers failing. This means there is no leader node in the cluster and requests cannot be serviced.

**Comment by ashish235** [comment]
@armon yeah, it was a quorum issue which I could see from the logs. But I don't get this my one node (consul server) was always up, so in that case it should have elected itself as a leader and other nodes should join it later. This was my understanding but I think I am missing something here. But  can you confirm that if only one server is running it can be elected as a leader.

I think I need to find some way to find the new leader and join it instead of joining a failing server.

**Comment by ashish235** [comment]
While bootstrapping I didn't mention the number of servers to expect. So if my consul servers are running but the link between them goes down, we can have a possibility of split brain.

**Comment by highlyunavailable** [comment]
In a 3-server cluster, 1 server being up isn't enough. Check out the "quorum" section of the [Consensus Protocol](https://www.consul.io/docs/internals/consensus.html) docs - in a 3-server cluster, you'd need 2 servers to be up to have a quorum and if you lose more than 1, you're now in an outage state and have to follow the [outage recovery process](https://www.consul.io/docs/guides/outage.html). So to answer your question:

> But can you confirm that if only one server is running it can be elected as a leader.

The answer is no, you MUST have quorum (n/2+1 servers able to process requests) to elect a leader.

`-bootstrap-expect` is _only_ used in a pristine cluster state - if any servers have formed a cluster, you're out of bootstrap mode and into normal quorum. This means that once you have bootstrapped, once you lose quorum, no server will "self-elect" and it also cannot have a split brain since quorum prevents split-brain (that is, the "small" side of the split will always fail due to not being able to reach consensus).

**Comment by ashish235** [comment]
Hi @highlyunavailable, cool Thanks for the awesome response. My queries are answered.
