### ISSUE TITLE
Please consider changing to Apache, BSD, MIT or other permissive non-copyleft license

### ISSUE THREAD

**Issue by tigrannajaryan** [hashicorp/consul#9944]
#### Feature Description

This repository uses MPL-2.0 weak copyleft license. I wonder if you would consider re-licensing the source code using a permissive non-copyleft license such as Apache License 2.0?

#### Use Case(s)

We want to use https://github.com/hashicorp/consul as a dependency in [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector), a CNCF sandbox project. Unfortunately, CNCF [does not](https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist) generally approve usage of MPL-licensed libraries, which creates barriers for adopting this repository as a dependency in any Apache-licensed CNCF project.

I believe the same restriction applies to other Hashicorp libraries that are currently licensed as MPL-2.0.

Moving to Apache License 2.0 would remove this barrier and help increase the adoption of Hashicopr's open-source code even more.

Thank you for considering.

**Comment by jsosulska** [comment]
Hi @tigrannajaryan

Thanks for opening this request. Hashcorp uses the MPL license across all our open source projects, so a change like this extends far beyond Consul. Historically, the CNCF has worked with us to get [exceptions](https://github.com/cncf/foundation/blob/master/license-exceptions/cncf-exceptions-2019-11-01.json), and this could be extended to Consul for Open-Telemetry, or [other HashiCorp tools](https://github.com/cncf/foundation/issues/138). Feel free to add your use-cases and requests to that issue so that it gains more visibility :)
Looking forward to seeing how the Open Telemetry stack evolves over time!

Best,
Jono

**Comment by tigrannajaryan** [comment]
Thanks for the answer @jsosulska, I will work on adding an exception :-)
