### ISSUE TITLE
Debian Arm7l doesn't work 

### ISSUE THREAD

**Issue by gingi99** [hashicorp/consul#999]
I downloaded 32 bit ver.

```
probe@server1:~$ ls
0.5.2_linux_386.zip
```

```
probe@server1:~$ ls -la /usr/local/bin/consul
-rwxr-xr-x 1 probe probe 14763649 2015-05-19 06:34 /usr/local/bin/consul
```

```
probe@server1:~$ uname -a
Linux server1 3.0.6 #2 SMP Mon Jun 17 14:35:19 JST 2013 armv7l GNU/Linux
```

```
probe@server1:~$ consul -h
bash: /usr/local/bin/consul: cannot execute binary file
```

I don't know why consul doesn't work.

**Comment by ryanuber** [comment]
Hi @gingi99, the problem is that the compiled binary you downloaded was not built for your CPU architecture. We don't currently offer pre-compiled versions for ARM, but we will starting with Consul 0.6. In the meantime, you can compile Consul yourself following the directions [here](https://github.com/hashicorp/consul#developing-consul). Hope that helps!
