### ISSUE TITLE
Duplicate events received on Consul agents wherein same event is received multiple times on a single agent.

### ISSUE THREAD

**Issue by ckalotra** [hashicorp/consul#9997]
#### Overview of the Issue

We are observing that when we raise events even on a cluster where there are only 2 agents connected, duplicate events are received.
Same event is received multiple times. We ae currently trying to handle this by filtering out duplicate events in application code.
Is there any other configuration in Consul which can help us in removing this from Consul end itself.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 2 client nodes and 3 server nodes
2. Raise events from one of agents.
3. Same events are received multiple times on different agents.

### Consul info for both Client and Server

<details>
      <summary>Client info</summary>
    
             agent:
                check_monitors = 0
                check_ttls = 0
                checks = 0
                services = 0
        build:
                prerelease =
                revision = 9be6dfc3
                version = 1.6.1
        consul:
                acl = disabled
                known_servers = 3
                server = false
        runtime:
                arch = amd64
                cpu_count = 16
                goroutines = 68
                max_procs = 16
                os = linux
                version = go1.12.1
        serf_lan:
                coordinate_resets = 0
                encrypted = true
                event_queue = 0
                event_time = 7698039
                failed = 15
                health_score = 0
                intent_queue = 0
                left = 0
                member_time = 1625347
                members = 332
                query_queue = 0
                query_time = 8

</details>

<details>
      <summary>Server Info</summary>
          agent:
            check_monitors = 0
            check_ttls = 0
            checks = 0
            services = 0
        build:
                prerelease =
                revision = 9be6dfc3
                version = 1.6.1
        consul:
                acl = disabled
                bootstrap = false
                known_datacenters = 1
                leader = true
                leader_addr = x.x.x.x:8300
                server = true
        raft:
                applied_index = 4507694
                commit_index = 4507694
                fsm_pending = 0
                last_contact = 0
                last_log_index = 4507694
                last_log_term = 7842
                last_snapshot_index = 4492253
                last_snapshot_term = 7842
                latest_configuration = [{Suffrage:Voter ID:08e2e01a-ef68-98b8-3562-fd180b7eebb4 Address:x.x.x.x:8300} {Suffrage:Voter ID:df2a07c0-4fff-960a-33b5-f95a0c1bd1ec Address:x.x.x.x:8300} {Suffrage:Voter ID:beeab0ba-be1f-6b9e-362c-01ff860617a7 Address:x.x.x.x:8300}]
                latest_configuration_index = 2141027
                num_peers = 2
                protocol_version = 3
                protocol_version_max = 3
                protocol_version_min = 0
                snapshot_version_max = 1
                snapshot_version_min = 0
                state = Leader
                term = 7842
        runtime:
                arch = amd64
                cpu_count = 4
                goroutines = 3265
                max_procs = 4
                os = linux
                version = go1.12.1
        serf_lan:
                coordinate_resets = 0
                encrypted = true
                event_queue = 149
                event_time = 7697139
                failed = 29
                health_score = 7
                intent_queue = 0
                left = 0
                member_time = 1625348
                members = 343
                query_queue = 0
                query_time = 8
        serf_wan:
                coordinate_resets = 0
                encrypted = true
                event_queue = 0
                event_time = 1
                failed = 0
                health_score = 0
                intent_queue = 0
                left = 0
                member_time = 253
                members = 3
                query_queue = 0
                query_time = 1

</details>

**Comment by jsosulska** [comment]
Hi @ckalotra 

Welcome to the HashiCorp Consul Repo! 😃  I'm going to respond here, but this response also extends to #9996. 

The behavior you've described with Consul Events is expected. Consul's [event](https://www.consul.io/commands/event#consul-event) system will make a best-effort to deliver the event, but there is no guaranteed delivery. Event data is purely peer-to-peer over gossip. This means it is not persisted and does not have a total ordering. In practice, this means you cannot rely on the order of message delivery, or the number of messages received. An advantage however is that events can still be used even in the absence of server nodes or during an outage.

[Serf](https://www.serf.io/docs/internals/gossip.html) powers the event system, and uses UDP. This can lead to many, one, or no messages being received. If you want a deep dive on some of Consul's internal communication methods, I recommend checking out [Everybody Talks: Gossip, Serf, memberlist, Raft, and SWIM in HashiCorp Consul](https://www.hashicorp.com/resources/everybody-talks-gossip-serf-memberlist-raft-swim-hashicorp-consul). 

Based on both the opened issues, it sounds like the solution you are looking for is an event queue system with ordering for your application, rather than the features of Consul's weakly consistent event system. Trying to make the event system into a fault tolerant queueing system is not something that Consul is intent on doing.

Thanks for submitting these issues though! I learned a lot while digging into the eventing system itself 😄
